export const landscapeMeta = {
  reviewedAt: "2026-08-27",
  status: "research_registry",
  scope:
    "A maintained source landscape, not a claim that every technically reachable dataset may be redistributed or sold.",
};

export const connectedCoverage = [
  {
    id: "tushare-quicksync",
    provider: "Tushare via QuickSync",
    market: "CN",
    family: "china-markets",
    contractCount: 190,
    activeCount: 135,
    pausedCount: 55,
    unit: "interfaces",
    collection: "configured",
    evidence: "provider-native registry",
    note: {
      zh: "190 个标准化运行合同；135 个配置为 active。active 不等于每个接口都已连续稳定采集。",
      en: "190 normalized runtime contracts; 135 are configured active. Active does not mean every interface has continuous healthy collection.",
    },
  },
  {
    id: "binance-public",
    provider: "Binance public market data",
    market: "CRYPTO",
    family: "crypto",
    contractCount: 6,
    activeCount: 6,
    pausedCount: 0,
    unit: "families",
    collection: "observed",
    evidence: "isolated crypto registry + historical receipt report",
    note: {
      zh: "6 类数据覆盖固定 40 个 USDT 标的，共 240 个 dataset 对象；不把 240 个对象误称为 240 个上游接口。",
      en: "Six data families cover a fixed 40-symbol USDT universe, yielding 240 dataset objects—not 240 upstream APIs.",
    },
  },
  {
    id: "firecrawl-news",
    provider: "Firecrawl",
    market: "CN / GLOBAL",
    family: "news-events",
    contractCount: 2,
    activeCount: 1,
    pausedCount: 1,
    unit: "pipelines",
    collection: "configured",
    evidence: "provider-native registry",
    note: {
      zh: "境内与全球新闻页面采集各 1 条；全球合同配置为 active，境内页面仍暂停。来源许可与页面条款仍按站点逐项审核。",
      en: "One domestic and one global news-page pipeline; the global contract is configured active and the domestic page remains paused. Source licensing stays a per-site review.",
    },
  },
];
export const collectionHistory = [
  {
    date: "2026-08-27",
    provider: "Tushare / QuickSync",
    status: "registry_snapshot",
    title: { zh: "运行注册表覆盖 190 个接口", en: "Runtime registry covers 190 interfaces" },
    detail: {
      zh: "133 active、57 paused。该记录证明合同与配置状态，不替代当日 receipt 和认证 API 回读。",
      en: "133 active and 57 paused. This proves contract/config state, not same-day receipts or authenticated API readback.",
    },
  },
  {
    date: "2026-08-23",
    provider: "Binance",
    status: "observed",
    title: { zh: "固定 40 个标的首轮采集 40/40 成功", en: "First fixed-universe collection completed 40/40" },
    detail: {
      zh: "这是一次历史运行记录，不代表今天仍连续健康，也不扩大固定标的范围。",
      en: "A historical runtime observation; it does not prove continuous health today or expand the fixed universe.",
    },
  },
  {
    date: "2026-08-23",
    provider: "TradingDatas A-share plane",
    status: "api_readback",
    title: { zh: "认证 Catalog 历史回读成功", en: "Authenticated Catalog historical readback succeeded" },
    detail: {
      zh: "该记录证明当时 API 路径可读；每个 dataset 的 freshness、quality 与 receipt 仍需独立判断。",
      en: "This proved the API path at that time; freshness, quality, and receipts remain dataset-level decisions.",
    },
  },
];

export const sourceCandidates = [
  {
    id: "sse-market-data",
    name: "Shanghai Stock Exchange",
    region: "China",
    family: "china-markets",
    materials: "L1/L2, end-of-day, tick, order book, indices, options",
    access: "licensed_feed",
    rights: "license_required",
    stage: "rights_review",
    phase: "P1",
    officialUrl: "https://english.sse.com.cn/markets/dataservice/products/",
  },
  {
    id: "szse-market-data",
    name: "Shenzhen Stock Exchange / SSIC",
    region: "China",
    family: "china-markets",
    materials: "L1/L2, delayed, end-of-day, order and trade depth",
    access: "licensed_feed",
    rights: "license_required",
    stage: "rights_review",
    phase: "P1",
    officialUrl: "https://investor.szse.cn/English/services/dataServices/index.html",
  },
  {
    id: "bse",
    name: "Beijing Stock Exchange",
    region: "China",
    family: "china-markets",
    materials: "listings, disclosures, market statistics, market data",
    access: "files_or_feed",
    rights: "review_required",
    stage: "source_review",
    phase: "P1",
    officialUrl: "https://www.bse.cn/",
  },
  {
    id: "hkex",
    name: "Hong Kong Exchanges and Clearing",
    region: "Hong Kong",
    family: "global-markets",
    materials: "securities, derivatives, issuer news, L1/L2/FullTick",
    access: "licensed_feed",
    rights: "license_required",
    stage: "rights_review",
    phase: "P2",
    officialUrl: "https://www.hkex.com.hk/Services/Market-Data-Services/Data-Licensing?sc_lang=en",
  },
  {
    id: "cffex",
    name: "China Financial Futures Exchange",
    region: "China",
    family: "derivatives",
    materials: "index futures, bond futures, options, reference and statistics",
    access: "files_or_feed",
    rights: "review_required",
    stage: "source_review",
    phase: "P1",
    officialUrl: "http://www.cffex.com.cn/",
  },
  {
    id: "cn-commodity-exchanges",
    name: "SHFE · DCE · CZCE · GFEX",
    region: "China",
    family: "derivatives",
    materials: "commodity futures/options, warehouses, positions, settlement",
    access: "files_or_feed",
    rights: "review_required",
    stage: "source_review",
    phase: "P1",
    officialUrl: "https://www.shfe.com.cn/",
  },
  {
    id: "cninfo",
    name: "CNInfo",
    region: "China",
    family: "company-regulatory",
    materials: "listed-company announcements and disclosure documents",
    access: "web_or_files",
    rights: "review_required",
    stage: "source_review",
    phase: "P1",
    officialUrl: "https://www.cninfo.com.cn/",
  },
  {
    id: "csi",
    name: "China Securities Index Company",
    region: "China",
    family: "funds-indices",
    materials: "index methodologies, constituents, weights and reference",
    access: "files_or_license",
    rights: "license_required",
    stage: "rights_review",
    phase: "P1",
    officialUrl: "https://www.csindex.com.cn/",
  },
  {
    id: "nbs",
    name: "National Bureau of Statistics of China",
    region: "China",
    family: "macro-rates",
    materials: "national, regional and sector macroeconomic statistics",
    access: "web_database",
    rights: "review_required",
    stage: "technical_review",
    phase: "P1",
    officialUrl: "https://data.stats.gov.cn/",
  },
  {
    id: "pbc-safe-customs",
    name: "PBOC · SAFE · China Customs",
    region: "China",
    family: "macro-rates",
    materials: "money, rates, FX, balance of payments and trade statistics",
    access: "files_or_web",
    rights: "review_required",
    stage: "source_review",
    phase: "P1",
    officialUrl: "http://www.pbc.gov.cn/",
  },
  {
    id: "sec-edgar",
    name: "SEC EDGAR Data APIs",
    region: "United States",
    family: "company-regulatory",
    materials: "filings, submissions, XBRL company facts and frames",
    access: "public_rest",
    rights: "public_terms",
    stage: "technical_review",
    phase: "P2",
    officialUrl: "https://www.sec.gov/about/developer-resources",
  },
  {
    id: "fred-alfred",
    name: "FRED / ALFRED",
    region: "United States / Global",
    family: "macro-rates",
    materials: "macro series, releases, vintages and revisions",
    access: "api_key_rest",
    rights: "series_specific",
    stage: "technical_review",
    phase: "P2",
    officialUrl: "https://fred.stlouisfed.org/docs/api/fred/overview.html",
  },
  {
    id: "world-bank",
    name: "World Bank Indicators / SDMX",
    region: "Global",
    family: "macro-rates",
    materials: "country indicators, development statistics and metadata",
    access: "public_rest_sdmx",
    rights: "public_terms",
    stage: "technical_review",
    phase: "P2",
    officialUrl: "https://datahelpdesk.worldbank.org/knowledgebase/topics/125589-developer-information",
  },
  {
    id: "imf",
    name: "IMF Data / SDMX",
    region: "Global",
    family: "macro-rates",
    materials: "financial, fiscal, external-sector and economic statistics",
    access: "sdmx",
    rights: "public_terms",
    stage: "source_review",
    phase: "P2",
    officialUrl: "https://www.imf.org/en/Data",
  },
  {
    id: "oecd",
    name: "OECD Data Explorer",
    region: "Global",
    family: "macro-rates",
    materials: "economic, policy, labor, industry and country statistics",
    access: "sdmx",
    rights: "public_terms",
    stage: "source_review",
    phase: "P2",
    officialUrl: "https://data-explorer.oecd.org/",
  },
  {
    id: "ecb",
    name: "ECB Data Portal",
    region: "Europe",
    family: "macro-rates",
    materials: "rates, FX, monetary, banking and revision history",
    access: "public_sdmx",
    rights: "public_terms",
    stage: "technical_review",
    phase: "P2",
    officialUrl: "https://data.ecb.europa.eu/help/api/overview",
  },
  {
    id: "companies-house",
    name: "UK Companies House",
    region: "United Kingdom",
    family: "company-regulatory",
    materials: "company register, officers, filings and insolvency records",
    access: "api_key_rest",
    rights: "public_terms",
    stage: "technical_review",
    phase: "P2",
    officialUrl: "https://developer.company-information.service.gov.uk/",
  },
  {
    id: "nasdaq-data-link",
    name: "Nasdaq Data Link",
    region: "Global",
    family: "global-markets",
    materials: "market, reference, fundamentals and vendor datasets",
    access: "commercial_api",
    rights: "dataset_specific",
    stage: "commercial_review",
    phase: "P3",
    officialUrl: "https://docs.data.nasdaq.com/",
  },
  {
    id: "coinbase",
    name: "Coinbase Exchange",
    region: "Crypto",
    family: "crypto",
    materials: "spot market data through REST, WebSocket and FIX",
    access: "public_market_api",
    rights: "terms_review",
    stage: "technical_review",
    phase: "P3",
    officialUrl: "https://docs.cdp.coinbase.com/exchange/introduction/welcome",
  },
  {
    id: "kraken",
    name: "Kraken",
    region: "Crypto",
    family: "crypto",
    materials: "spot, derivatives, L2/L3 and historical market data",
    access: "public_market_api",
    rights: "terms_review",
    stage: "technical_review",
    phase: "P3",
    officialUrl: "https://docs.kraken.com/exchange/guides/rest/introduction",
  },
  {
    id: "okx",
    name: "OKX",
    region: "Crypto",
    family: "crypto",
    materials: "spot, swaps, futures, options, books, trades and candles",
    access: "public_market_api",
    rights: "terms_review",
    stage: "technical_review",
    phase: "P3",
    officialUrl: "https://www.okx.com/docs-v5/en/",
  },
  {
    id: "deribit",
    name: "Deribit",
    region: "Crypto",
    family: "crypto",
    materials: "options, futures, perpetuals and market microstructure",
    access: "public_market_api",
    rights: "terms_review",
    stage: "technical_review",
    phase: "P3",
    officialUrl: "https://docs.deribit.com/",
  },
  {
    id: "coingecko",
    name: "CoinGecko",
    region: "Crypto / Global",
    family: "crypto",
    materials: "aggregated coins, exchanges, categories and on-chain DEX data",
    access: "demo_or_commercial_api",
    rights: "plan_specific",
    stage: "commercial_review",
    phase: "P3",
    officialUrl: "https://docs.coingecko.com/",
  },
  {
    id: "defillama",
    name: "DefiLlama",
    region: "On-chain",
    family: "crypto",
    materials: "TVL, stablecoins, DEX volume, fees, yields and open interest",
    access: "free_and_pro_api",
    rights: "terms_review",
    stage: "technical_review",
    phase: "P3",
    officialUrl: "https://api-docs.defillama.com/",
  },
  {
    id: "gdelt",
    name: "GDELT",
    region: "Global",
    family: "news-events",
    materials: "global news search, events, entities, geography and coverage",
    access: "public_api_or_bulk",
    rights: "source_sensitive",
    stage: "rights_review",
    phase: "P4",
    officialUrl: "https://blog.gdeltproject.org/gdelt-doc-2-0-api-debuts/",
  },
  {
    id: "common-crawl",
    name: "Common Crawl",
    region: "Global",
    family: "web-attention",
    materials: "web archives, URL index, page text and link observations",
    access: "open_bulk_and_index",
    rights: "page_level_review",
    stage: "rights_review",
    phase: "P4",
    officialUrl: "https://index.commoncrawl.org/",
  },
  {
    id: "physical-world",
    name: "AIS · satellite · mobility vendors",
    region: "Global",
    family: "physical-world",
    materials: "shipping, ports, imagery, facilities, footfall and supply-chain proxies",
    access: "commercial_vendor",
    rights: "license_required",
    stage: "discovery",
    phase: "P4",
    officialUrl: "https://gdeltcloud.com/data",
  },
];

export const roadmapPhases = [
  {
    id: "P0",
    horizon: { zh: "现在", en: "Now" },
    title: { zh: "把现有运行面公开讲清楚", en: "Make the existing runtime legible" },
    gates: ["registry identity", "receipt-bound state", "authenticated catalog/query", "rights boundary"],
  },
  {
    id: "P1",
    horizon: { zh: "优先", en: "Priority" },
    title: { zh: "补齐境内市场、衍生品、披露与宏观", en: "Complete China market, derivatives, disclosure, and macro coverage" },
    gates: ["official source", "redistribution permission", "schema + cadence", "bounded canary"],
  },
  {
    id: "P2",
    horizon: { zh: "第二阶段", en: "Second wave" },
    title: { zh: "开放型全球基本面与宏观数据", en: "Open global fundamentals and macro" },
    gates: ["public API terms", "revision/vintage model", "entity mapping", "receipt readback"],
  },
  {
    id: "P3",
    horizon: { zh: "第三阶段", en: "Third wave" },
    title: { zh: "全球行情与多交易所加密数据", en: "Global market and multi-venue crypto" },
    gates: ["vendor economics", "market-data licence", "historical depth", "isolated runtime"],
  },
  {
    id: "P4",
    horizon: { zh: "探索", en: "Exploration" },
    title: { zh: "新闻、Web 与实体世界另类数据", en: "News, web, and physical-world alternative data" },
    gates: ["source rights", "privacy review", "coverage bias", "separate add-on entitlement"],
  },
];
