import { preparationTutorialExpansion } from "./preparationTutorialExpansion.js";
const bilingual = (zh, en) => ({ zh, en });
const step = (zh, en, bodyZh, bodyEn) => ({ title: bilingual(zh, en), body: bilingual(bodyZh, bodyEn) });

export const preparationTutorials = {
  "adjusted-price-series": {
    title: bilingual("构建复权价格序列", "Build an adjusted price series"),
    summary: bilingual("保留原始价格，明确复权锚点，验证公司行动造成的机械跳变。", "Keep raw prices, choose an adjustment anchor and check mechanical corporate-action jumps."),
    goal: bilingual("得到一张同时包含原始收盘价、因子、锚点与复权收盘价的表；不计算策略收益。", "Produce a table of raw closes, factors, the anchor and adjusted closes; do not calculate strategy returns."),
    datasetIds: ["cn.equity.daily", "cn.dataset.adj_factor"],
    fields: [bilingual("证券标识 + 交易日期：唯一连接键", "Security ID + trading date: unique join key"), bilingual("close：未复权价格；保留币种", "close: unadjusted price; retain currency"), bilingual("adj_factor：同来源、同版本的正数因子", "adj_factor: positive factors from one source/version"), bilingual("anchor_date：固定的归一化日期", "anchor_date: fixed normalization date")],
    steps: [
      step("1. 先冻结价格定义", "1. Freeze the price definition", "确认输入是未复权价格，而不是已经复权的价格。Tushare日线说明中，close与除权后的pre_close具有不同含义；不要拿两者混算。保留供应商字段、币种和版本，先按证券、交易日查重。", "Confirm that inputs are unadjusted, not previously adjusted. Tushare's daily specification distinguishes close from the ex-rights reference pre_close; do not mix them. Retain source fields, currency and version, and check uniqueness by security and trading date."),
      step("2. 按同一交易日连接因子", "2. Join factors on the same date", "以证券标识和交易日期精确连接价格与因子。缺失因子、重复键、非正价格或非正因子应停止计算，不能默认填1。停牌日没有成交记录并不等于价格为零；需要另存交易日历与缺失原因。", "Join on the exact security and trading date. Missing factors, duplicate keys and non-positive prices or factors must stop the calculation, not default to one. No trade during a suspension does not mean a zero price; retain a calendar and missingness reasons separately."),
      step("3. 声明归一化锚点", "3. Declare the normalization anchor", "在采用乘法复权因子的前提下，示例用 adjusted_close = close × factor / anchor_factor。固定末日作为锚点时，末日复权价等于原价。更换锚点会改变整条序列的数值尺度，因此应把锚点写进结果，而不是只写“前复权”。", "For multiplicative adjustment factors, the example uses adjusted_close = close × factor / anchor_factor. With the final date as anchor, its adjusted close equals its raw close. Changing the anchor rescales the series, so retain the actual date rather than only a label such as forward-adjusted."),
      step("4. 检查跳变与单位", "4. Check jumps and units", "示例中的虚构股票从100变为50，同时因子从1变为2；归一化后两日均为50。这里只说明二拆一的机械调整，不代表真实公司行动。不要给成交量、成交额直接乘同一价格因子；它们需要各自的定义。", "In the synthetic two-for-one split, price changes from 100 to 50 and the factor from 1 to 2; both adjusted observations are 50. This is arithmetic, not an observed corporate action. Do not apply the price factor blindly to volume or traded value."),
    ],
    expected: bilingual("输出3行，adjustedClose依次为50、50、51；原始close仍为100、50、51。锚点价格不变，原始数据不被覆盖。", "Three rows: adjustedClose is 50, 50, 51; raw close remains 100, 50, 51. The anchor price is unchanged and inputs are not overwritten."),
    pitfalls: [bilingual("重复复权会制造错误跳变；已复权输入必须拒绝。", "Applying adjustment twice creates false changes; reject already adjusted inputs."), bilingual("最新因子版本并不证明历史时点可得；回看研究要冻结因子快照。", "The latest factor version is not proof of historical availability; freeze factor snapshots."), bilingual("复权价格不自动等于含税费、现金分红再投资的总收益序列。", "Adjusted prices are not automatically total returns with taxes, fees and dividend reinvestment.")],
    sources: [{ label: bilingual("Tushare：复权因子字段", "Tushare: adjustment-factor fields"), url: "https://tushare.pro/document/2?doc_id=28" }, { label: bilingual("Tushare：日线价格口径", "Tushare: daily-price conventions"), url: "https://tushare.pro/document/2?doc_id=27" }],
    research: ["Common risk factors in the returns on stocks and bonds", "Modeling and Forecasting Realized Volatility"],
  },
  "pit-fundamentals-panel": {
    title: bilingual("构建时点一致财务面板", "Build a point-in-time fundamentals panel"),
    summary: bilingual("同一报告期的多个版本，按当时实际可得的信息选择，而不是使用今天的最新值。", "Select report versions available at a historical cutoff, not today's latest restatement."),
    goal: bilingual("对每个公司、报告期、指标和单位，保留截止时点可用的最新披露版本，以及来源和可得时间。", "For each entity, period, metric and unit, retain the latest disclosed version available at the cutoff, with provenance and availability time."),
    datasetIds: ["cn.dataset.income", "cn.dataset.cashflow", "cn.dataset.balancesheet"],
    fields: [bilingual("entity / period / metric / unit：分组键", "entity / period / metric / unit: grouping key"), bilingual("version：不可覆盖的披露版本标识", "version: immutable filing-version identifier"), bilingual("publishedAt：带时区的披露时间", "publishedAt: timezone-aware disclosure time"), bilingual("firstSeenAt：本数据链首次观察时间", "firstSeenAt: first observation in your data chain")],
    steps: [
      step("1. 区分四种时间", "1. Distinguish four clocks", "报告期末描述经济期间；披露时间描述发布；首次观察描述你的系统何时拿到数据；研究截止时间描述可使用的信息边界。示例使用 max(publishedAt, firstSeenAt) 作为本数据链的可得时点，不把后来补采的文件假装成当时已持有。", "Period-end describes the economic period; publication time describes release; first-seen time describes your acquisition; the cutoff bounds the information set. The example uses max(publishedAt, firstSeenAt) for availability in your data chain, avoiding fictional historical possession of later-backfilled records."),
      step("2. 保留版本，而不是覆盖", "2. Preserve versions rather than overwrite", "把公司、报告期、指标、单位和版本作为记录身份。示例中同一报告期先披露100，后来修订为105。两条都保留；同版本不同内容应隔离核对。实际数据还要区分合并与母公司口径、累计与单季、会计准则及币种。", "Retain entity, period, metric, unit and version as record identity. The synthetic report first says 100 and later revises to 105; keep both. Quarantine conflicting versions. Real inputs additionally require consolidation scope, cumulative versus standalone periods, accounting standards and currency."),
      step("3. 先过滤可得性，再选版本", "3. Filter availability before selection", "先排除可得时间晚于截止时点的记录，再从每组中选择披露时间最新的版本。若披露顺序相同但版本不同，示例拒绝猜测。不能先对全库取最新版本，再用报告期末判断是否属于过去。", "Exclude records available after the cutoff before choosing the latest publication in each group. The example refuses to guess between different versions with ambiguous publication order. Selecting the database's latest version first and filtering by period-end afterward leaks future information."),
      step("4. 检查尚未披露与修订", "4. Check unreleased and revised cases", "把截止时间放到首次披露之前，应没有结果；放到两次披露之间，应得到100；放到修订可得之后，应得到105。若来源只有日期，没有可信发布时间，不能自动补成当天零点；应明确采用保守的下一交易日约定或标记待核对。", "A cutoff before first disclosure returns nothing; between disclosures it returns 100; after the revision becomes available it returns 105. Date-only sources must not silently become midnight timestamps. Use an explicitly conservative next-session convention or require review."),
    ],
    expected: bilingual("示例截止2025-03-31，输出v1与数值100，排除4月的v2。此结果只验证示例规则，不证明供应商提供完整历史版本。", "At the synthetic 2025-03-31 cutoff, return v1 and 100, excluding April's v2. This verifies the example rule, not completeness of vendor revision history."),
    pitfalls: [bilingual("缺少历史版本或可信披露时间时，不能仅靠程序制造PIT数据。", "Code cannot manufacture point-in-time evidence when historical versions or release times are missing."), bilingual("示例函数在每个报告期内选版本，不负责选择最新报告期或计算TTM。", "The function chooses versions within each period; it does not select the latest period or compute TTM."), bilingual("缺失记录不是0；真实可得性与许可须独立确认。", "Missing records are not zero; actual availability and licensing require separate confirmation.")],
    sources: [{ label: bilingual("Tushare：财务数据入口", "Tushare: financial-statement data"), url: "https://tushare.pro/document/2?doc_id=16" }, { label: bilingual("Dechow与Dichev：应计估计误差", "Dechow & Dichev: accrual estimation errors"), url: "https://papers.ssrn.com/sol3/papers.cfm?abstract_id=277231" }],
    research: ["Do Stock Prices Fully Reflect Information in Accruals and Cash Flows about Future Earnings?", "The Quality of Accruals and Earnings: The Role of Accrual Estimation Errors"],
  },
  "company-event-timeline": {
    title: bilingual("准备公司事件时间线", "Prepare a company-event timeline"),
    summary: bilingual("保留事件、修订与信息时间，把记录映射到明确的交易日约定。", "Preserve events, revisions and information clocks, then map them using an explicit session convention."),
    goal: bilingual("输出去重后的事件版本、可信可得时间、下一完整交易日与待核对原因，不计算异常收益。", "Output deduplicated event versions, defensible availability times, the next full session and review flags, without abnormal-return calculations."),
    datasetIds: ["cn.dataset.anns_d", "cn.market.trade_calendar"],
    fields: [bilingual("id + version：事件身份，修订不能合并掉", "id + version: event identity; keep amendments"), bilingual("publishedAt / firstSeenAt：两个带时区的时间", "publishedAt / firstSeenAt: two timezone-aware timestamps"), bilingual("sessionOpens：特定交易所的已核对开盘日历", "sessionOpens: a checked calendar for one exchange"), bilingual("原始URL、文件摘要与实体映射：真实样本另行保留", "Source URL, document hash and entity mapping: retain separately for real inputs")],
    steps: [
      step("1. 冻结事件定义", "1. Freeze the event definition", "公告、媒体报道和公司行动生效日是不同对象。先声明本次研究使用哪一种，并保留原始链接、文件内容摘要、公司识别和修订关系。相同内容被转载，不应该自动变成多个独立事件。", "An announcement, a news report and a corporate action's effective date are different objects. Define which one you need, preserving source links, content hashes, company mapping and revisions. Syndicated copies must not automatically become independent events."),
      step("2. 明确可得时点", "2. Establish availability", "示例取发布时间和首次观察时间的较晚者。只有日期的记录进入needs_review，不猜测盘前还是盘后。时间戳必须带时区；不能把UTC与上海本地时间直接按字符串排序。", "The example takes the later of publication and first observation. Date-only records become needs_review rather than guessed pre- or post-market releases. Require timezone-aware timestamps; do not sort UTC and Shanghai local times as raw strings."),
      step("3. 采用保守的日频映射", "3. Use a conservative daily mapping", "本教程选择可得时点之后第一个开盘的完整交易日。周五盘后公告映射到日历中的下一个交易日；盘中公告也进入下一完整交易日。这是明确的日频约定，不是交易所规则，也不适用于直接分析公告后的分钟反应。", "Choose the first session opening strictly after availability. A Friday after-close release maps to the next listed session; an intraday release also maps to the next full session. This is a declared daily convention, not an exchange rule or a method for immediate intraday reactions."),
      step("4. 保留无法对齐的记录", "4. Keep unresolved records visible", "完全相同的事件版本只保留一条，冲突版本停止处理。超出日历覆盖范围的事件标记outside_calendar，补足日历后再映射，不自动猜下一个工作日。待核对记录与已对齐记录分开，避免缺失时间被悄悄掩盖。", "Keep one exact duplicate; conflicting versions stop processing. Events beyond calendar coverage become outside_calendar and wait for a longer calendar, rather than guessing the next weekday. Keep unresolved records distinct so missing timing is not hidden."),
    ],
    expected: bilingual("3条虚构输入去重后为2条：DEMO-A映射到2025-01-06开盘；DEMO-B只有日期，保留为needs_review且无交易日。", "Three synthetic inputs become two records: DEMO-A maps to the 2025-01-06 open; date-only DEMO-B remains needs_review with no session."),
    pitfalls: [bilingual("不能用工作日日历替代交易所假期、停市和证券停牌状态。", "Weekdays do not replace exchange holidays, closures or security-specific suspensions."), bilingual("首次抓取时间只是本数据链的证据，不证明全市场首次获知。", "First capture is evidence for your data chain, not the entire market's first knowledge."), bilingual("对齐事件不构成因果识别；并发事件与样本偏差仍需后续研究。", "Event alignment does not establish causality; confounding events and selection remain research questions.")],
    sources: [{ label: bilingual("MacKinlay：事件研究方法", "MacKinlay: event-study methods"), url: "https://www.jstor.org/stable/2729691" }, { label: bilingual("Tushare：证券身份与上市状态", "Tushare: security identity and listing status"), url: "https://tushare.pro/document/2?doc_id=25" }],
    research: ["Event Studies in Economics and Finance", "Giving Content to Investor Sentiment: The Role of Media in the Stock Market"],
  },
  ...preparationTutorialExpansion,
};
