const bi = (zh, en) => ({ zh, en });
const step = (zh, en, bodyZh, bodyEn) => ({ title: bi(zh, en), body: bi(bodyZh, bodyEn) });
const spotDocs = "https://developers.binance.com/docs/binance-spot-api-docs/rest-api/market-data-endpoints";
const oiDocs = "https://developers.binance.com/docs/derivatives/usds-margined-futures/market-data/rest-api/Open-Interest-Statistics";

export const preparationTutorialExpansion = {
  "minute-bar-gaps": {
    title: bi("检查分钟行情缺口", "Audit minute-bar gaps"),
    summary: bi("把应有时间网格与实际观测分开，保留缺失，不用补零制造完整性。", "Separate expected time slots from observations; preserve gaps instead of filling them with zeros."),
    goal: bi("得到一张有明确区间边界、实际价格和缺失标记的表。这里只审查时间覆盖，不计算波动率或补造行情。", "Produce interval boundaries, observed closes and missingness flags. This audits time coverage; it neither estimates volatility nor fabricates bars."),
    datasetIds: ["cn.dataset.stk_mins", "cn.market.trade_calendar"],
    fields: [bi("单一证券、场所与频率的输入批次；先分组再运行", "One security, venue and frequency per batch; partition before running"), bi("openTime：UTC整秒时间；close：原始价格", "openTime: UTC whole-second timestamp; close: raw price"), bi("expectedOpens：经核对的区间起点，不包含休市时段", "expectedOpens: checked interval starts, excluding closed sessions"), bi("intervalMinutes：统一频率；所有预期区间都已经结束", "intervalMinutes: fixed frequency; all expected intervals must have ended")],
    steps: [
      step("1. 冻结时间含义", "1. Freeze timestamp semantics", "先核对供应商的时间戳表示开盘还是收盘，再转成示例要求的UTC整秒格式。示例把区间写成左闭右开，endExclusive不是供应商原始close_time的替代字段。真实分钟数据的原始时区、边界含义与字段应另行保留，不能只改列名就当作完成映射。", "Check whether vendor timestamps label interval starts or ends, then normalize explicitly to UTC whole seconds. The example uses half-open intervals; endExclusive does not replace the vendor's raw close_time. Preserve original timezone and boundary semantics rather than merely renaming a column."),
      step("2. 独立准备预期网格", "2. Prepare an independent grid", "根据交易所日历和会话规则提供expectedOpens，只放已经结束且应当观察的区间。午休、假期或闭市不应该算缺口；停牌需要额外状态，交易日历本身不够。不要从已有行情反推应有网格，否则缺失的区间会在检查之前就消失。", "Supply expectedOpens from the relevant calendar and session rules, including only finished intervals expected to be observed. Lunch breaks, holidays and closures are not gaps; suspensions need additional security-level status. Deriving the grid from available bars would hide missing intervals before the audit."),
      step("3. 精确连接并拒绝冲突", "3. Join exactly and reject conflicts", "按区间起点连接，重复时间、重叠网格、网格外观测和无效价格直接拒绝。预期网格可以有休市间隔，但单个区间不能重叠。函数不猜测最近一分钟，也不把两个不同证券的同一时间合并，因此必须事先按证券和场所分批。", "Join on exact starts; reject duplicate bars, overlapping grid intervals, off-grid observations and invalid prices. Gaps between sessions are allowed, overlapping intervals are not. The function does not guess a nearest minute or combine securities, so partition by instrument and venue first."),
      step("4. 保留缺失，再解释原因", "4. Preserve gaps before explaining them", "虚构网格有三个5分钟区间，中间一条没有观测，输出missing和null。这里不能判断是停牌、无交易还是采集失败；应结合原始回执与市场状态另查。后续计算收益前，必须选择并说明跨缺口处理，不能把null换成0或上一条价格后隐瞒处理。", "The synthetic grid contains three five-minute intervals with the middle observation absent; output is missing with a null close. That does not identify suspension, no trading or acquisition failure. Check receipts and market state separately, and disclose any treatment before computing returns across gaps."),
    ],
    expected: bi("输出3行：observed、missing、observed；收盘价100、null、102。原始两行不被修改。", "Three rows: observed, missing, observed; closes are 100, null, 102. The two source rows remain unchanged."),
    pitfalls: [bi("不检查尚未结束的K线；缺少成交不自动等于采集失败。", "Do not audit unfinished candles; no trade is not automatically an ingestion failure."), bi("日历只描述市场开放，不能证明证券没有停牌。", "An exchange calendar does not establish a security's suspension status."), bi("样本不执行插值、补零或向前填充。", "The example performs no interpolation, zero filling or forward filling.")],
    sources: [{ label: bi("Tushare：股票历史分钟", "Tushare: historical stock minutes"), url: "https://tushare.pro/document/2?doc_id=370" }, { label: bi("Andersen等：已实现波动的构造", "Andersen et al.: realized-volatility construction"), url: "https://users.ssc.wisc.edu/~behansen/718/Anderson2003.pdf" }],
    research: ["Modeling and Forecasting Realized Volatility", "Intraday Information Efficiency on the Chinese Equity Market"],
  },
  "document-version-ledger": {
    title: bi("保留文档修订与去重台账", "Keep a document revision ledger"),
    summary: bi("去掉重复抓取，但留下真正修订、原始身份和当时可得的证据。", "Remove duplicate captures while retaining revisions, source identities and availability evidence."),
    goal: bi("输出截止时点内的全部已观察版本，并区分首次观察、内容变更与内容未变。不识别情绪，也不自动判断新闻真伪。", "Retain all observed versions within a cutoff, distinguishing first observation, changed content and unchanged content. No sentiment or truth classification is performed."),
    datasetIds: ["cn.dataset.anns_d", "cn.news.flash"],
    fields: [bi("publisher + documentId + version：来源内版本身份", "publisher + documentId + version: source-scoped version identity"), bi("contentHash：同一种字节/文本规范下的SHA-256", "contentHash: SHA-256 under a fixed byte/text convention"), bi("publishedAt / firstSeenAt：UTC整秒时间", "publishedAt / firstSeenAt: UTC whole-second timestamps"), bi("cutoff：本数据链可用信息的截止时间", "cutoff: information cutoff for this data chain")],
    steps: [
      step("1. 先定义文档与版本", "1. Define document and version identity", "文档身份应在发布方范围内稳定，修订号也必须可追溯。标题相同不证明是同一文件；不同发布方即使内容一样，也保留各自身份。示例不做转载聚类或实体识别，真实公告中的URL、公司代码与原始文件还需要作为独立来源证据保存。", "Use a stable document identity within each publisher and a traceable version. Matching titles do not prove document identity; identical content at different publishers retains separate identities. Syndication clustering and entity recognition are outside the example. Retain real URLs, company IDs and source files separately."),
      step("2. 冻结内容哈希口径", "2. Freeze the hashing convention", "实际哈希必须来自固定口径的原始字节或规范化文本，并记录算法与解析版本。两者不能混用，否则PDF元数据变化或解析器更新也可能看似内容修订。示例里的64位字符串只是虚构标识，函数不下载文件、不计算真实哈希，也不替代来源完整性验证。", "Hash a consistently defined byte stream or normalized text, recording the algorithm and parser version. Mixing conventions can make metadata or parser changes resemble revisions. The sample's 64-character strings are synthetic placeholders; the function neither downloads files nor validates actual source integrity."),
      step("3. 先查冲突，再限定可得性", "3. Check conflicts before availability", "完全相同的版本重复输入只保留一次；同一版本出现不同哈希或时间证据则停止。按发布时间与首次观察时间的较晚者筛选截止时点，不能把后来抓到的文件倒填成过去已持有。只有日期的来源不能直接补零点，需要外部核对或保守规则。", "Collapse exact repeats, but reject conflicting hashes or time evidence for the same version. Filter by the later of publication and first observation, so later acquisitions are not fictional historical holdings. Date-only sources need external review or a disclosed conservative rule, not silently assigned midnight."),
      step("4. 保留每次变化的轨迹", "4. Keep the change trail", "对每份文档按可得时间排列版本，并与上一次可得版本比较哈希：标记首次观察、内容变化或内容未变。相同可得时间的不同版本拒绝猜顺序。内容变化不表示哪版更真实，也不自动代表负面消息；需要回到原文理解具体修订。", "Order each document's versions by availability and compare hashes with the preceding available version. Mark first observation, changed content or unchanged content; reject ambiguous equal-time revisions. A changed hash neither identifies the truer version nor implies adverse news. Interpret the actual edit separately."),
    ],
    expected: bi("4条输入去重后留下3个版本：v1首次观察，v2内容变化，v3内容未变；不覆盖旧版本。", "Four inputs become three versions: v1 first observation, v2 changed content, v3 unchanged content. Older versions are not overwritten."),
    pitfalls: [bi("版本台账需要自己保留的历史证据，最新API结果无法自动补出它。", "A revision ledger needs retained historical evidence; a latest-only API cannot manufacture it."), bi("相同哈希不等于相同版权、发布方或文件身份。", "Equal hashes do not imply equal rights, publishers or document identities."), bi("真实许可与全文获取范围需单独核对。", "Real licensing and full-text access require separate checks.")],
    sources: [{ label: bi("Tushare：公告字段与原文链接", "Tushare: announcement fields and source links"), url: "https://tushare.pro/document/2?doc_id=176" }, { label: bi("Loughran与McDonald：解析范围", "Loughran & McDonald: parsing boundaries"), url: "https://www.uts.edu.au/globalassets/sites/default/files/adg_cons2015_loughran-mcdonald-je-2011.pdf" }],
    research: ["When Is a Liability Not a Liability? Textual Analysis, Dictionaries, and 10-Ks", "Lazy Prices"],
  },
  "crypto-observation-alignment": {
    title: bi("对齐现货区间与持仓量观测", "Align spot intervals and open-interest observations"),
    summary: bi("先核对市场、时间与单位，再做有时效上限的向后连接，不借用未来记录。", "Check markets, clocks and units before a bounded backward join that excludes future information."),
    goal: bi("给已结束的5分钟现货区间附上当时可得且未过期的持仓量；缺失或过旧时保留空值，不推导资金费率或交易信号。", "Attach available, recent open-interest observations to finished five-minute spot intervals. Preserve nulls for missing or stale data; infer no funding rate or trading signal."),
    datasetIds: ["crypto.spot.binance.btcusdt.5m", "crypto.perp.binance.btcusdt.open_interest"],
    fields: [bi("输入仅覆盖同一场所的一组已明确映射的现货/永续合约", "One explicitly mapped spot/perpetual pair at one venue per input batch"), bi("openTime / endExclusive / close：已结束的5分钟现货区间", "openTime / endExclusive / close: completed five-minute spot intervals"), bi("observedAt / firstSeenAt / value / unit：持仓量观测与可得证据", "observedAt / firstSeenAt / value / unit: open-interest observation and availability"), bi("maxAgeSeconds与expectedUnit：冻结的时效和单位合同", "maxAgeSeconds and expectedUnit: fixed age and unit contract")],
    steps: [
      step("1. 不把同名标的当成同一产品", "1. Do not equate similarly named products", "先固定交易场所、现货对、永续合约、基础资产与计价币，再将单一匹配组传给函数。示例借用BTC单位表达方式，但所有数值虚构。持仓量数量与持仓量名义价值是不同字段，不能因为同属加密数据就用USDT金额代替BTC数量。", "Freeze venue, spot pair, perpetual contract, base asset and quote asset before passing one mapped pair to the function. BTC is a teaching unit; all values are synthetic. Open-interest quantity and notional value are different fields, so a USDT amount must not silently replace a BTC quantity."),
      step("2. 把时钟映射写清楚", "2. Make clock mapping explicit", "示例采用UTC整秒，现货区间左闭右开，决策时点为区间结束边界。原始毫秒时间需要显式转换并保留原值。持仓量的观察时间描述统计时点，首次观察时间描述本系统何时拿到它；不能仅按统计时间把后来取得的数据放回过去。", "Normalize explicitly to UTC whole seconds, retaining raw timestamps. Spot intervals are half-open, with the decision time at their end boundary. Open-interest observation time identifies the measurement; first-seen time identifies acquisition. A later-acquired record cannot become historically available just because its measurement is earlier."),
      step("3. 向后连接并限制年龄", "3. Join backward with an age limit", "只考虑统计时点与首次观察时点均不晚于区间结束的记录，再选统计时点最新的一条。示例允许边界时刻已经可得的观测，并将最大年龄设为300秒，这是教学约定而非交易所承诺。超过上限标记stale，空值不做向前填充；没有候选则明确保留缺失。", "Choose the newest measurement whose observation and first-seen times are both no later than the interval end. Boundary-time availability is allowed. The 300-second maximum age is a teaching convention, not an exchange guarantee. Older candidates become stale with null values; absent candidates remain explicitly missing."),
      step("4. 检查迟到和单位冲突", "4. Test late arrivals and unit conflicts", "第一个区间中的持仓量直到区间结束后才观察到，因此不能使用；第二个区间可连接，第三个区间的观测过旧。重复统计时点、错误单位和非5分钟区间会被拒绝。即使连接成功，也只说明满足示例时间规则，不说明价格和持仓量有因果关系。", "The first interval cannot use an observation acquired after its end; the second aligns and the third has stale information. Duplicate observation times, unit mismatches and non-five-minute intervals are rejected. Successful alignment validates only this timing convention, not a causal relation between price and open interest."),
    ],
    expected: bi("三个区间依次为no_available_observation、aligned、stale，持仓量分别为null、12、null。", "The three intervals are no_available_observation, aligned and stale; open interest is null, 12 and null."),
    pitfalls: [bi("持仓量是存量，不是成交量；不要跨区间求和。", "Open interest is a stock, not traded volume; do not sum it across intervals."), bi("资金费率、溢价指数和持仓量不能互相代替。", "Funding rates, premium indices and open interest are not interchangeable."), bi("目录合同不证明当前数据可得；网络、权限、历史窗口与首次观察证据仍需核对。", "A catalog contract does not establish current availability; check network, grants, coverage and first-observation evidence separately.")],
    sources: [{ label: bi("Binance：现货K线时间字段", "Binance: spot candle timestamps"), url: spotDocs }, { label: bi("Binance：持仓量统计字段", "Binance: open-interest statistics"), url: oiDocs }],
    research: ["Trading and Arbitrage in Cryptocurrency Markets", "Tokenomics: Dynamic Adoption and Valuation"],
  },
};
