// Original bilingual commentary; evidenceScope records the specific pages inspected.
const bi = (zh, en) => ({ zh, en });
const guide = (url, edition, evidenceScope, limits, related, rows) => ({
  reviewedAt: "2026-08-31", evidenceUrl: url, evidenceScope, limits, related,
  sections: rows.map(([location, zh, en, bodyZh, bodyEn]) => ({
    title: bi(zh, en), body: bi(bodyZh, bodyEn),
    reference: { url, label: bi(`${edition.zh} · ${location}`, `${edition.en} · ${location}`) },
  })),
});

export const researchSixtyGuides = {
  "Regularization and Variable Selection via the Elastic Net": guide(
    "https://hastie.su.domains/Papers/elasticnet.pdf",
    bi("2004年8月修订稿", "August 2004 revision"),
    "Author-hosted manuscript dated December 2003, revised August 2004: pp. 1–11, sections 1–3.2 read for standardization, penalty definitions, grouping and corrected versus naive estimators. Page 10 visually checked. The 2005 journal identity is retained; application tables and financial prediction were not replicated.",
    bi("导读依据2004年修订稿，正式期刊引用不变。弹性网是一种估计方法，不保证金融预测有效；参数名称、损失函数缩放和原文的重缩放定义需分别核对。", "This guide uses the 2004 revision, separately from the journal citation. Elastic net does not guarantee useful financial forecasts. Parameter names, loss scaling and the original rescaling definition must be checked separately."), {}, [
      ["§1", "预测精度与变量选择是两个目标", "Prediction and variable selection are distinct goals",
        "Zou与Hastie从预测误差和模型简洁性两方面讨论回归。Lasso能够产生零系数，但面对强相关变量或变量多于观测的情形会有局限；弹性网尝试在稀疏选择中保留相关变量的信息，不是宣称所有数据都优于其他方法。",
        "Zou and Hastie consider predictive error and parsimony separately. Lasso produces zero coefficients but can struggle with correlated predictors or more predictors than observations. Elastic net seeks sparse selection while retaining information shared by correlated variables; it is not universally superior."],
      ["§2.1", "标准化属于模型定义", "Standardization belongs to the model definition",
        "文中先将响应变量中心化，并令每个预测变量均值为零、平方和为一。惩罚施加在系数上，因此改变变量单位会改变惩罚的相对作用。编辑建议记录训练期的中心与尺度，应用到后续样本时不能重新借用未来数据估计。",
        "The manuscript centers the response and gives each predictor zero mean and unit sum of squares. Since penalties act on coefficients, measurement units affect their relative influence. Editorial application: retain training-period centers and scales rather than estimating preprocessing from future observations."],
      ["§2.1", "两个惩罚，不要只对照参数名", "Two penalties, not just a familiar parameter name",
        "最初的目标函数把残差平方和、L1惩罚与平方L2惩罚相加。该稿用两个惩罚系数定义混合比例，比例为一对应岭回归、为零对应Lasso。软件中的同名参数未必沿用这个方向，应对照目标函数而不是直接复制数字。",
        "The initial objective combines residual sum of squares, an L1 penalty and a squared L2 penalty. Its mixing convention assigns one to ridge and zero to lasso. A software parameter with the same name need not follow that convention; compare objective functions rather than copying values."],
      ["§2.3–2.4", "相关变量的成组效应", "Correlated variables can move together",
        "平方L2部分使目标更严格地凸化，并鼓励高度相关变量取得相近的系数。这里的成组效应来自变量之间的相关结构，不要求事先给出行业或特征分组；它也不等于研究者已经识别出具有经济含义的独立因素。",
        "The squared L2 component strengthens convexity and encourages highly correlated predictors to receive similar coefficients. This grouping effect arises from their correlation, without a predefined sector or feature group. It does not establish that the selected variables are independent economic mechanisms."],
      ["§3.1–3.2 · p. 10", "原文区分朴素估计与修正估计", "The original paper distinguishes naive and corrected estimates",
        "作者指出两个惩罚可能带来双重收缩，并将修正估计写成朴素估计的重缩放：乘以一加L2惩罚系数。这个关系依赖该稿的标准化与目标函数定义。阅读复现代码时，应先确认实现的是哪一种估计，不能额外重复修正。",
        "The authors identify double shrinkage and rescale the naive estimate by one plus the L2 penalty coefficient. That relation depends on the manuscript's normalization and objective. Before interpreting replication code, establish which estimator it implements; do not apply the correction twice."],
      ["§1; §3.2", "方法有效不等于样本外收益有效", "An estimator is not evidence of an investable forecast",
        "这篇文章讨论统计估计与变量选择，而不是为某个金融因子组合提供收益承诺。编辑建议将调参、变量筛选、预处理和最终评价分开，并保留按时间划分的未用样本；相关变量被一同保留，也不构成因果识别。",
        "The article studies estimation and selection, not promised returns from a financial signal. Editorial application: separate tuning, feature selection, preprocessing and final evaluation, with untouched chronological observations. Retaining correlated variables together also does not identify causation."],
    ]),
  "Discretion versus Policy Rules in Practice": guide(
    "https://web.stanford.edu/~johntayl/Papers/Discretion.PDF",
    bi("1993年期刊版", "1993 journal article"),
    "Author-hosted scanned journal article: printed pp. 196–199 and 202 visually read for responsive rules, judgment, measurement, durability and equation (1). Later historical simulations were not independently checked. The illustrative coefficients are not a present-day policy prescription.",
    bi("这是一篇1993年的政策规则讨论。文中的美国历史示例不是当前政策立场，也不是其他经济体的推荐利率；趋势产出、通胀口径和当时可得信息会改变解释。", "This 1993 discussion uses a historical US illustration. It is neither current policy guidance nor a recommended rate for other economies. Trend output, inflation definitions and information available at the time affect interpretation."), {}, [
      ["pp. 196–197", "规则可以随经济变化作出反应", "A rule can respond to the economy",
        "Taylor首先澄清，规则并不等于固定不变的政策工具。利率可以按通胀和实际活动变化而调整，关键是反应具有可理解、相对稳定的结构。因此，利率发生变化不能单独证明决策是随意的，也不能把固定增速规则当作唯一形式。",
        "Taylor distinguishes systematic policy from an unchanging instrument. Interest rates may respond to inflation and activity through an understandable, reasonably stable relation. A rate change alone does not establish discretion, and constant-growth rules are not the only form of systematic policy."],
      ["pp. 197–198", "有判断，不代表每次重新发明政策", "Judgment need not mean starting over each time",
        "季度模型无法处理所有短期冲击，潜在产出也不能直接观测。作者因而允许在执行中使用判断，同时反对把每次决定都视为完全独立的问题。讨论规则时，需要区分长期反应方式与短期特殊情形下的操作调整。",
        "Quarterly models cannot cover every short-lived disruption, and potential output is not directly observed. The paper therefore allows judgment in implementation without treating every decision as a wholly new problem. Distinguish the durable response pattern from operations under unusual conditions."],
      ["p. 199", "设计、过渡与日常执行分开", "Separate design, transition and daily implementation",
        "选用怎样的规则、怎样从原有制度过渡、日常怎样操作，是作者提出的三个不同问题。即使一种规则在模型比较中表现良好，也不能跳过制度过渡与实际执行；只展示一个目标利率数字，会把这些层次隐藏起来。",
        "The article separates choosing a rule, moving toward it and operating it day to day. Good performance in a model comparison does not settle transition or implementation. Displaying a single implied interest rate conceals these separate institutional and operational questions."],
      ["p. 202 · equation (1)", "公式里的通胀与产出都有明确口径", "Inflation and output in the illustration have precise meanings",
        "示例写作r＝p＋0.5y＋0.5(p－2)＋2，其中p是过去四个季度的通胀率，y是实际GDP相对趋势GDP的百分比偏离。y不是GDP增长率；把环比通胀或同比产出增速直接代入，会改变原式所回答的问题。",
        "The illustration is r = p + 0.5y + 0.5(p − 2) + 2. Here p measures inflation over the previous four quarters and y is the percentage deviation of real GDP from trend. The output gap is not GDP growth, and quarterly inflation is not the same input."],
      ["p. 202", "常数不是对所有时期的估计", "The constants are not universal estimates",
        "当通胀处于示例中的2%目标、产出等于趋势时，公式给出的名义利率为4%。这个结果包含文中对实际均衡利率的示例性设定。它便于讨论政策反应，却不说明当前或任何国家的均衡利率都应取同一数值。",
        "At the illustrative 2 percent inflation target and trend output, the formula gives a 4 percent nominal rate. This incorporates an assumed equilibrium real rate. It makes the response mechanism easy to discuss but does not estimate the appropriate equilibrium rate for every country or period."],
      ["pp. 197–198; p. 202", "事后拟合与当时可操作性不同", "Historical fit differs from real-time feasibility",
        "文章讨论了规则与历史政策路径的接近程度，也指出测量与特殊事件带来的困难。编辑建议保留每次公布的GDP、通胀与趋势估计版本，再讨论当时能否计算该规则；用今天修订后的数据画出的拟合线，不是实时决策记录。",
        "The discussion relates a rule to past policy while recognizing measurement problems and unusual events. Editorial application: retain release vintages of GDP, inflation and trend estimates. A fitted line calculated from today's revised data is not a record of what policymakers could compute then."],
    ]),
  "Forecasting Using Principal Components From a Large Number of Predictors": guide(
    "https://www.princeton.edu/~mwatson/papers/Stock_Watson_JASA_2002.pdf",
    bi("2002年JASA期刊版", "2002 JASA article"),
    "Author-hosted final JASA article, printed pp. 1167–1170: sections 1–3 read for two-stage forecasting, approximate factor assumptions, normalization, estimation, joint asymptotics and bounded loading drift. Printed p. 1169 visually checked. Monte Carlo tables and appendix proofs not reproduced; not substituted with the related JBES article.",
    bi("本文的结论依赖近似因子模型及误差、样本维度和载荷变化条件。渐近性质不保证有限样本预测改善，统计主成分也不自动具有确定的经济含义。", "Results depend on approximate-factor assumptions, error conditions, sample dimensions and bounded loading changes. Asymptotic properties do not guarantee better finite-sample forecasts, and principal components do not automatically have unique economic interpretations."), {}, [
      ["§1", "先压缩预测变量，再估计预测关系", "Compress predictors, then estimate the forecast relation",
        "Stock与Watson处理的是预测变量很多、观测期可能相对较少的问题。第一步从预测变量提取少数共同成分，第二步用这些估计因子及其他观测变量预测目标序列。压缩共同变化与预测目标，是两个不同的估计环节。",
        "Stock and Watson study many predictors relative to the available dates. The first step extracts a few common components; the second regresses the forecast target on estimated factors and other observed variables. Summarizing co-movement and predicting the target are distinct estimation tasks."],
      ["§2.1", "近似因子模型允许有限的残差相关", "Approximate factors allow bounded residual dependence",
        "模型不要求所有变量在扣除共同因子后完全独立，允许残差存在时间相关与较弱的横截面相关。但“允许相关”不是不受限制：相关程度和矩条件仍受约束。把大量重复指标加入面板，不能自动当作同等数量的新信息。",
        "Residuals need not become independent after removing common factors: serial and weak cross-sectional dependence are allowed. These are bounded conditions, not unrestricted correlation. Editorial interpretation: adding many duplicate indicators does not create an equal number of independent information sources."],
      ["§2.1", "因子的正负号不等于经济方向", "A factor's sign is not an economic direction by itself",
        "因子与载荷可以同时变换而保持观测关系不变，论文通过标准化约束识别它们，仍需处理正负号差异。不同运行结果中第一主成分翻转符号，不一定表示经济机制反转；比较之前应同时检查载荷、排序与标准化方式。",
        "Factors and loadings can be transformed together without changing the observed relation. Normalizations identify them subject to sign choices. A component changing sign between runs need not mean an economic reversal; compare loadings, ordering and normalization before interpreting the movement."],
      ["§2.2 · p. 1169", "矩阵方向可以改变，预测空间不变", "Different matrix directions can represent the same space",
        "估计可从变量之间的矩阵求特征向量，也可以在变量数量超过观测期时改用观测期之间的较小矩阵。作者说明两者产生相同的列空间，适合按计算规模选择。计算形式等价，不代表可以随意更改变量缩放或样本。",
        "Components can be computed from the predictor-by-predictor matrix or, when predictors outnumber dates, from the smaller date-by-date matrix. The resulting column spaces are equivalent for forecasting. That computational choice does not license arbitrary changes to scaling or sample membership."],
      ["§2.3", "理论同时需要变量与时间维度增长", "The theory needs both dimensions to grow",
        "因子和预测的一致性结果以变量数量N与观测期T同时增大为背景。它比较可行预测与能够看到真实因子的不可行预测之间的差异，不是承诺小样本误差为零。只有增加更多指标、却不增加时间信息，不能直接援引完整结论。",
        "Consistency is established as both the number of predictors N and dates T increase. The forecast result concerns convergence toward an infeasible forecast using true factors, not zero finite-sample error. Increasing indicators alone does not reproduce the full asymptotic setting."],
      ["§3", "对小幅漂移稳健，不等于抵御所有断裂", "Small loading drift is not arbitrary structural change",
        "第3节允许因子载荷随时间变化，但漂移不能太大，也不能在大量变量间高度同步。这个条件有助于理解方法的适用边界：一次广泛制度变化并不会因为模型用了主成分就被自动消化。编辑建议将结构变化检查与预测评价分开保留。",
        "Section 3 permits loading drift only when it is sufficiently small and weakly dependent across series. A broad regime change is not automatically handled by using principal components. Editorial application: retain structural-change diagnostics separately from the reported forecasting comparison."],
    ]),
  "The Probability of Backtest Overfitting": guide(
    "https://www.davidhbailey.com/dhbpapers/backtest-prob.pdf",
    bi("2015年2月作者稿", "February 2015 author manuscript"),
    "Author-hosted February 27 2015 manuscript: pp. 1–12 and p. 23 read for repeated trials, rank-based PBO, selection versus estimation, CSCV matrix/splits and limitations. Page 11 visually checked. Simulation results and estimator calibration were not independently reproduced.",
    bi("PBO评价给定候选集合和划分方法下的选择过拟合，不是某个策略未来亏损的概率。本文不提供交易策略、收益承诺或生产回测验证。", "PBO evaluates selection overfitting for a specified candidate set and partition scheme. It is not a strategy's probability of future loss. This guide provides neither a trading strategy nor a return promise or production backtest validation."), {}, [
      ["§1 · pp. 3–5", "一次显著，不等于多次尝试后仍显著", "One significant result is not a multiple-trial assessment",
        "论文从同一批历史数据上反复尝试参数和模型的问题出发。最终展示的最好结果可能只是众多试验中的幸运样本；如果只保留获胜者，就看不到选择过程带来的偏差。试过多少配置、哪些被舍弃，都是研究证据的一部分。",
        "Repeatedly testing configurations on the same history can produce a lucky winner. Reporting that winner alone conceals selection bias. The number and identity of attempted configurations, including discarded ones, are part of the evidence needed to assess the research process."],
      ["§2.1 · pp. 9–10", "PBO比较排名，不直接预测亏损", "PBO compares rankings, not future losses",
        "作者关注样本内表现最好的配置，在样本外是否落到所有候选配置的中位数以下。这个事件是相对排名事件：它可能发生在所有配置都盈利或都亏损的情况下。把PBO直接解释成未来亏损率，会把两个不同问题混为一谈。",
        "The event concerns whether the in-sample winner ranks below the median of candidates out of sample. It is relative: this can happen when every candidate gains or when every candidate loses. PBO must not be relabeled as the probability of a future financial loss."],
      ["§2.1 · p. 10", "选择配置与拟合模型分开", "Separate selecting configurations from fitting models",
        "该框架中的样本内数据，是用于在多个配置之间选出获胜者的数据，不一定是每个模型最初估计参数的训练期。论文因此能够只利用各配置的表现序列进行比较。编辑建议分别记录模型训练、配置选择和最终评价的时间范围。",
        "In-sample here means the observations used to select among configurations, not necessarily each underlying model's estimation period. This enables comparison using performance series. Editorial application: record model fitting, configuration selection and final evaluation as separate time windows."],
      ["§2.2 · p. 11", "输入矩阵必须同一时点可比", "Performance columns must share comparable timestamps",
        "CSCV把每个尝试配置放在一列、同步观测放在一行。不同频率的结果要先对齐到共同索引，评价指标也要能在子样本计算。把某些配置缺失的日期静默删掉，或把缺失当作零表现，会改变用于比较的样本。",
        "CSCV places configurations in columns and synchronized observations in rows. Different frequencies require a common index, and the evaluation statistic must be meaningful on subsamples. Editorial caution: silently dropping missing dates or treating missing performance as zero changes the comparison."],
      ["§2.2 · pp. 11–12", "对称划分是诊断，不是时间前进模拟", "Symmetric partitions are a diagnostic, not a walk-forward replay",
        "方法将时间行分成偶数个区块，组合其中一半进行选择，再用互补的一半检查排名。组合会交换样本内外的角色，因此不等于每次只用过去预测未来。编辑建议把这种选择稳定性诊断与严格按时间前进的评价分别报告。",
        "The method partitions rows into an even number of blocks, selects on combinations of half and evaluates ranks on the complement. Roles are exchanged, so this is not a past-only walk-forward replay. Editorial application: report this selection diagnostic separately from chronological evaluation."],
      ["§5.1 · p. 23", "划分粒度与依赖结构限制结论", "Partition size and dependence limit interpretation",
        "作者明确说明，对称划分不是适合所有情形的办法；强自相关在过细分块时可能被掩盖。相同权重也是一种设定，而不是从数据自动证明的真理。报告PBO时应一并保留候选集合、区块数量、指标和适用范围。",
        "The authors note that symmetry is not suitable for every application and fine partitions may obscure strong autocorrelation. Equal weighting is also a design choice. A PBO report should retain the candidate set, block count, performance metric and the limits under which it was calculated."],
    ]),
  "Size and Value in China": guide(
    "https://finance.wharton.upenn.edu/~stambaug/size_value_china_appendix_2_rev.pdf",
    bi("作者在线附录", "Author-hosted online appendix"),
    "Author-hosted seven-page appendix: B.1 variable construction and B.2 WIND data dictionary read in full, with focus on share denominators, earnings/book equity, volatility windows, turnover and release fields. Main article empirical results and shell-value interpretation were not inspected in this pass. Printed p. 5 visually checked.",
    bi("本篇聚焦作者附录的变量构造，不代替正文关于中国规模与价值效应的实证论证。WIND字段与当前平台字段不能直接等同，复权和披露时点仍需独立核对。", "This guide focuses on variable construction in the author's appendix, not the main article's empirical explanation of size and value in China. WIND items are not automatically equivalent to platform fields; adjustment and disclosure timing require separate checks."), { recipes: ["pit-fundamentals-panel", "adjusted-price-series"] }, [
      ["Appendix B.1", "同一篇研究也可能使用不同股本分母", "Share-count definitions differ even within one study",
        "附录中的规模变量使用收盘价乘以A股总股数，而盈利价格比和账面市值比的市值分母使用总股数。两种股本范围并不总是相同。先写清分母，再讨论变量之间的关系，不能因为都叫市值就用一个字段覆盖全部定义。",
        "Size uses the closing price times total A-shares, while the market-value denominator for earnings-to-price and book-to-market uses total shares. These scopes need not coincide. Define the denominator explicitly rather than applying one market-cap field to every variable."],
      ["Appendix B.1; B.2", "盈利口径包含非经常性项目处理", "The earnings measure treats nonrecurring items explicitly",
        "附录优先使用扣除非经常性损益后的净利润，并在数据字典中说明该字段缺失时的替代处理。这个选择会影响盈利价格比与公司排序。复用时应保留原字段是否缺失和替代来源，不能只留下一个最终盈利数字。",
        "The appendix prioritizes profit excluding nonrecurring gains and losses and documents a fallback when that item is missing. This affects earnings-to-price and firm rankings. Preserve the missing-item flag and substitute source rather than retaining only the final earnings value."],
      ["Appendix B.1; B.2", "账面权益先对齐合并范围", "Align the scope of book equity",
        "账面市值比使用不含少数股东权益的股东权益，附录同时列出报告期和公告日期字段。报告期告诉我们会计量属于何时，公告日才帮助判断外部可得性。编辑建议区分两者，不把期末报表视为期末当天已经公开。",
        "Book-to-market uses shareholders' equity excluding minority interests. The dictionary also lists reporting periods and announcement dates. The former dates the accounting measure; the latter helps establish availability. Editorial application: do not assume quarter-end figures were public at quarter end."],
      ["Appendix B.1", "波动率与最大单日收益不同", "Volatility differs from the largest daily return",
        "作者把过去20个交易日收益的标准差与同一窗口的最大单日收益分别作为变量。它们一个衡量分散程度，一个记录极端正收益，不能互换。编辑建议在交易日历上构造窗口，并说明缺失、停牌和收益复权的处理。",
        "The appendix distinguishes the standard deviation of returns over 20 trading days from the maximum daily return in that window. Dispersion and an extreme positive observation are different measures. Editorial application: specify the trading calendar, missing days, suspensions and adjustment convention."],
      ["Appendix B.1", "异常换手率还需要长期基准", "Abnormal turnover needs a longer-run baseline",
        "附录将日换手率定义为成交量相对股数的比例，并用短期20日均值与较长期250日均值比较。短期均值、长期均值和二者的比值各有含义。不能直接拿成交额增速替代，也不能省去股本口径与成交量单位的核对。",
        "Daily turnover relates volume to shares, and the abnormal measure compares a 20-day average with a 250-day average. The short average, baseline and ratio are separate objects. Turnover-value growth is not a substitute; share scope and volume units must also match."],
      ["Appendix B.2 · pp. 5–6", "相似字段名不证明跨供应商等价", "Similar field names do not establish provider equivalence",
        "数据字典特别区分WIND终端取得的含分红再投资、已处理拆股收益，与底层数据库中的另一收益字段。这个差异说明供应商内部也可能存在口径变化。关联教程只帮助准备复权与时点对齐，不能声称已复现作者的完整输入。",
        "The dictionary distinguishes terminal returns adjusted for splits and dividend reinvestment from a database return item not adjusted for splits. Even one provider may expose different definitions. The linked tutorials prepare price adjustment and as-of alignment, not the author's complete input dataset."],
    ]),
  "Presidential Address: Discount Rates": guide(
    "https://www.nber.org/system/files/working_papers/w16972/w16972.pdf",
    bi("2011年4月NBER版", "April 2011 NBER edition"),
    "NBER Working Paper 16972, Discount Rates, April 2011: cover, abstract, introduction and sections I–II.B opening, PDF pp. 1–6, read for expected-return variation, dividend-price ratios, present-value decomposition and time-series versus cross-sectional questions. PDF p. 5 visually checked. No claim extends beyond the abstract and inspected pages; journal tables and empirical decompositions not reproduced.",
    bi("导读使用2011年NBER工作论文，保留期刊文章引用。预期收益随时间变化与可执行的样本外预测不是同一命题，现值关系也不能单独识别经济机制。", "This guide uses the 2011 NBER paper, separately from the journal citation. Time-varying expected returns and feasible out-of-sample forecasting are different claims. A present-value relation alone does not identify an economic mechanism."), {}, [
      ["§I; §II.A–B", "价格变化不只来自现金流消息", "Price variation need not come only from cash-flow news",
        "Cochrane以折现率变化重新组织资产定价中的若干问题。价格相对现金流发生变化，可以关联到未来现金流预期，也可以关联到要求收益的变化。这个框架帮助区分解释方向，但不意味着每次价格下跌都已经找到了唯一原因。",
        "Cochrane organizes several asset-pricing questions around changing discount rates. Prices relative to cash flows can reflect expected cash-flow changes or changes in required returns. This distinction frames explanations; it does not identify a unique cause for every observed price decline."],
      ["§II.A", "股息价格比不是单纯的低价标签", "Dividend–price ratios are not simply cheapness labels",
        "文章从股息价格比与后续收益、股息增长的关系展开。D/P与P/D互为倒数，却不能在回归和图示中不加说明地交换。编辑建议明确使用水平、对数还是增长率，并保留股息累计窗口与价格日期，避免仅凭指标名称做比较。",
        "The discussion relates dividend–price ratios to subsequent returns and dividend growth. D/P and P/D are reciprocals, not interchangeable regression labels. Editorial application: specify levels, logs or growth rates, along with the dividend accumulation window and price date."],
      ["§II.A", "短期解释度小，不表示预期收益不变化", "Low short-horizon fit need not mean constant expected returns",
        "短期实际收益包含大量未预期的变化，因而回归解释度可以很小。作者提醒，预测回归中的低解释度与经济上重要的预期收益变化可以同时存在。这不是忽略统计不确定性的理由，更不能把低解释度改说成强预测能力。",
        "Realized short-horizon returns contain substantial unexpected variation, so a regression can have low fit despite economically meaningful changes in expected returns. This distinction does not eliminate statistical uncertainty or turn weak forecasting evidence into a strong predictive claim."],
      ["§II.B · present-value relation", "有限期限分解还保留终值", "A finite-horizon decomposition retains a terminal term",
        "现值关系将当前估值比与未来收益、未来股息增长及期末估值比联系起来。有限期限下，终值项不能凭方便直接删除。只有另加相应的长期条件，才可讨论无限期限表达；恒等关系本身不是一个已估计的因果模型。",
        "The present-value relation connects today's valuation ratio to future returns, dividend growth and a terminal valuation ratio. The terminal term remains at a finite horizon. Removing it requires additional long-run conditions; the identity is not itself an estimated causal model."],
      ["§II.B", "估值比变化与价格变化分开", "Valuation-ratio variation differs from price variation",
        "关于股息价格比的分解，不应直接改写成所有股票价格涨跌都来自折现率。比率同时涉及分子与分母，而短期价格消息和长期估值差异又是不同对象。编辑建议在引用结论时，保留原文分析的变量及其时间尺度。",
        "A decomposition of dividend–price ratios should not become a claim that all price changes are discount-rate news. Ratios involve two quantities, and short-run price news differs from long-run valuation differences. Editorial application: preserve both the variable and horizon when citing a result."],
      ["§I; §II.A–B", "时间序列与横截面回答不同问题", "Time-series and cross-sectional questions differ",
        "同一市场的预期收益为何随时间变化，与不同资产为何要求不同收益，是两个问题。文章把它们放在共同的折现率视角下讨论，但证据与模型并不相同。编辑建议再与样本外预测研究对读，区分经济解释、统计估计和真实可用信息。",
        "Why expected returns vary over time differs from why assets command different returns. The address connects both through discount rates without making their evidence identical. Editorial application: read alongside out-of-sample prediction studies to separate economic explanation, estimation and feasible information."],
    ]),
  "A Comprehensive Look at The Empirical Performance of Equity Premium Prediction": guide(
    "https://www.nber.org/system/files/working_papers/w10483/w10483.pdf",
    bi("2004年5月NBER版", "May 2004 NBER edition"),
    "NBER Working Paper 10483, May 2004: cover, introduction and section 2, PDF pp. 1–7, read for historical-mean benchmarking, recursive availability, reused samples, equity-premium inputs and DP versus DY. PDF p. 4 visually checked. This early edition is not a verification of the 2008 journal tables or current forecasting performance.",
    bi("依据2004年工作论文阅读预测评价方法，正式期刊引用不变。历史样本中的预测困难不能外推成任何市场、任何时期都不存在可预测性。", "This guide uses the 2004 working paper to explain forecast evaluation, separately from the journal citation. Difficulty predicting a historical sample does not prove that every market and period is unpredictable."), { recipes: ["adjusted-price-series"] }, [
      ["§1", "解释历史与提前预测分开", "Explaining history differs from forecasting ahead",
        "Goyal与Welch比较多种文献中的权益溢价预测变量，重点追问模型在当时可用的信息下能否胜过简单基准。用全样本估计出的关系能够描述过去，并不说明每个历史时点都能得到同样的参数或预测。",
        "Goyal and Welch compare published equity-premium predictors against a simple benchmark using information available at the forecast date. A relation fitted to the full history may describe the past without being a forecast that could have been produced at each date."],
      ["§1", "历史均值也必须只用当时的历史", "The historical mean must also be available at the time",
        "基准不是研究结束后才算出的全样本平均值，而是随着预测时点推进、利用此前数据得到的历史均值。模型和基准必须在相同信息范围下比较。编辑建议同时保存两个预测序列，不能只报告模型自身的样本内拟合优度。",
        "The benchmark is the mean available from prior observations at each forecast date, not the final full-sample average. Model and benchmark must share the same information boundary. Editorial application: retain both forecast sequences rather than reporting only the model's in-sample fit."],
      ["§1", "借用过的测试期不再完全陌生", "A previously studied test period is not wholly unseen",
        "文章指出，即使计算过程称为样本外评价，研究者仍可能已经知道某段历史的表现，或根据既有研究选择变量。这个问题不靠重新切一次数据就自动消失。编辑建议保留变量选择、修改和评价的记录，不把形式上的留出样本说成全新证据。",
        "A computational out-of-sample exercise may still use a period familiar to researchers or variables chosen through earlier studies. Repartitioning alone cannot undo that prior knowledge. Editorial application: retain the history of selection and revisions instead of calling every holdout entirely new evidence."],
      ["§2", "权益溢价需要股票与无风险两端", "An equity premium needs both equity and risk-free inputs",
        "权益溢价由股票收益与对应期间的无风险收益共同构成。价格收益、含分红收益及不同期限利率并不等价；数据源和历史替代序列会影响可比性。下方复权教程只处理价格准备，不提供本文完整的股息、利率或早期历史输入。",
        "An equity premium combines equity returns with a corresponding risk-free return. Price returns, dividend-inclusive returns and yields of different maturities are not interchangeable. The linked tutorial prepares adjusted prices only, not the paper's full dividend, interest-rate or early-history inputs."],
      ["§2", "D/P与D/Y标签背后是不同价格日期", "DP and DY use different price dates",
        "工作论文区分股息价格比DP与股息收益率DY：两者采用的价格日期不同，一个对应当前价格，另一个使用滞后价格。名称相近不代表预测信息相同。编辑建议将公式、滞后期与发布时间直接写入变量合同，而不是仅保存缩写。",
        "The working paper distinguishes DP from DY through the date of the price denominator: current versus lagged price. Similar labels do not imply identical predictive information. Editorial application: preserve the formula, lag and availability date rather than storing an acronym alone."],
      ["§1–2", "结论跟着样本、期限与版本走", "Conclusions travel with the sample, horizon and edition",
        "初始训练窗口、预测期限、变量定义和样本终点都会影响评价。这份早期稿与后来的期刊版不能仅凭标题相近就混用数值。编辑建议引用具体版本，并将历史发现与新的市场测试分开，避免把一次负面结果写成普遍的不可能定理。",
        "Training windows, horizons, variable definitions and sample endpoints affect the comparison. Numerical results from this early manuscript should not be silently merged with the later journal article. Editorial application: name the edition and distinguish historical findings from tests in a new market."],
    ]),
  "Flash Boys 2.0: Frontrunning in Decentralized Exchanges, Miner Extractable Value, and Consensus Instability": guide(
    "https://arxiv.org/pdf/1904.05234v1",
    bi("2019年arXiv初稿", "2019 arXiv v1"),
    "arXiv 1904.05234v1, April 10 2019, titled Frontrunning, Transaction Reordering, and Consensus Instability in Decentralized Exchanges: PDF pp. 1–4 read for market/consensus interaction, gas units, custody distinctions and the pure-revenue subset. Page 4 visually checked. Later conference results and current Ethereum mechanics not verified.",
    bi("导读依据2019年初稿，保留后续会议论文引用。历史以太坊的费用与共识环境不代表当前机制；本文用于理解交易排序和测量边界，不提供抢跑操作或收益承诺。", "This guide uses the 2019 first draft, separately from the later conference citation. Its historical Ethereum fee and consensus setting is not current-mechanism evidence. The focus is ordering and measurement, not instructions for frontrunning or promised returns."), {}, [
      ["§I", "不托管资产，不代表排序公平", "Noncustodial settlement does not ensure fair ordering",
        "Daian等人把去中心化交易所中的竞争与底层交易排序联系起来。用户保有资产控制权，只说明某些托管依赖被改变，并不保证交易按所有人都认为公平的顺序执行。研究市场设计时，托管、报价、排序和结算需要分别讨论。",
        "Daian and colleagues connect competition on decentralized exchanges to transaction ordering below them. Retaining control of assets changes custody dependencies, not necessarily execution fairness. Custody, quotations, ordering and settlement are separate dimensions of market design."],
      ["§I; §II", "应用层激励可能影响共识层", "Application incentives can reach the consensus layer",
        "文章关注的不只是某个交易者多支付了多少费用，还包括排序产生的经济激励是否改变区块生产者的行为。交易应用和共识协议不能总被视作互不影响的两层。但具体风险仍依赖当时机制，不能由历史讨论直接推断当前网络状态。",
        "The argument goes beyond fees paid by an individual trader to incentives that ordering opportunities create for block producers. Applications and consensus are not always economically independent. The specific risk still depends on the mechanism studied, not an inference about today's network."],
      ["§II.A–B", "Gas用量、单价与总费用分开", "Separate gas used, gas price and total fees",
        "初稿区分计算消耗的Gas单位、每单位愿付价格及由此形成的费用。Gas上限则约束执行预算，不等于最后实际使用量。比较历史交易成本时，应同时保留数量、价格和计价资产；一个叫Gas的字段不足以重建成本。",
        "The draft separates computational gas units, the price per unit and the resulting fee. A gas limit caps the execution budget rather than reporting actual usage. Historical cost comparisons need quantities, prices and denomination; a single field called gas is insufficient."],
      ["§II.C–E", "交易所设计包含多个集中化环节", "Exchange designs contain distinct coordination points",
        "论文讨论的去中心化交易场所仍可能在订单传播、匹配或界面等部分依赖特定运营者，而资金结算交给链上合约。不同设计暴露的机会和观测数据不相同。不能只按DEX标签合并所有场所，再解释为同一种市场结构。",
        "Exchanges in the discussion can rely on particular operators for order dissemination, matching or interfaces while settling through contracts. Designs expose different opportunities and observable data. Pooling venues under a DEX label does not make their market structures equivalent."],
      ["§III.A", "原子执行改变失败模式，不消除成本", "Atomic execution changes failure modes, not all costs",
        "多笔交换可以放入一次合约交易，使部分步骤失败时整体回退。这与跨场所分开执行、只有一条腿成功的风险不同。编辑解读中仍应把交易资产流入与网络费用分开；原子性不是零成本或无条件净利润的同义词。",
        "Several swaps can execute inside one contract transaction and revert together if a step fails, unlike separately executed legs. Editorial interpretation: keep traded-asset proceeds separate from network fees. Atomicity changes execution failure modes; it does not imply zero cost or unconditional net profit."],
      ["§III.A · p. 4", "可识别子集不是全部MEV", "An identifiable subset is not all MEV",
        "作者明确聚焦可从单次原子交易辨认的纯收入机会，并把更复杂或不确定的机器人行为留在范围之外。这个取样有助于测量，却不能代表全部排序收益。链上成交记录也不能自动替代未上链订单、被替换请求和传播过程的完整历史。",
        "The measurement focuses on identifiable pure-revenue opportunities within atomic transactions and excludes more complex or nondeterministic bot behavior. This tractable subset is not all ordering value. Editorial caution: settled chain records alone do not reconstruct every pending, replaced or disseminated request."],
    ]),
  "Why DeFi Lending? Evidence from Aave V2": guide(
    "https://www.bis.org/publications/working-paper-1183-why-defi-lending-evidence-aave-v2.pdf",
    bi("2024年7月BIS版", "July 2024 BIS edition"),
    "BIS Working Paper 1183, downloaded edition with July 2024 cover: PDF pp. 1–5 and 7–10 read for motivations, Ethereum V2 sample, deposit/borrow transactions, daily aggregation, governance dummies and financial reference series. Page 9 visually checked. Regression tables, identification and raw transactions not replicated.",
    bi("研究样本是以太坊上的Aave V2历史活动，不能代表所有链、协议版本或当前用户。借贷与治理动机通过观测变量讨论，不等于识别了每个地址的真实目的。", "The sample concerns historical Aave V2 activity on Ethereum, not every chain, version or current user. Observable variables inform lending and governance interpretations; they do not reveal each address's true intent."), {}, [
      ["§1–2", "先限定协议、链与历史窗口", "Fix the protocol, chain and historical window",
        "文章研究以太坊主市场Aave V2在2020年12月至2022年7月中旬的交易。这个窗口早于后续若干协议与网络变化。把结果写成所有DeFi用户的长期行为规律，会同时扩大链、版本和时间范围，超出原样本支持。",
        "The study examines Aave V2's Ethereum main market from December 2020 to mid-July 2022. The window precedes later protocol and network changes. Presenting the findings as a permanent rule for all DeFi users expands the chain, version and time scope beyond the sample."],
      ["§1; §2", "提供资金与借入资产是不同选择", "Supplying funds and borrowing assets are distinct decisions",
        "作者分别讨论存入资金和借入代币的动机，包括收益机会、杠杆需求与治理相关活动。两侧面对的资产、成本和约束不同。即使发生在同一个地址，也不能把一次存入与一次借入视作同一经济行为或自动归为相同动机。",
        "The paper considers supply and borrowing motives separately, including yields, leverage and governance-related activity. The two sides face different assets, costs and constraints. Even for one address, a deposit and a borrow are not the same economic decision or evidence of an identical motive."],
      ["§2 · figure 3", "笔数、金额和未偿余额不同", "Counts, transaction amounts and outstanding balances differ",
        "图3分别按交易笔数和换算为美元的交易金额展示代币分布，因此同一代币在两种图中的份额可能不同。这些是期间发生的交易，不是某一天的未偿余额或锁仓量。比较协议规模前，应先说明衡量的是流量还是存量。",
        "Figure 3 separates transaction counts from USD transaction amounts, so a token's shares can differ across panels. These are flows during a period, not a day's outstanding balance or total value locked. Define flow versus stock before comparing protocol scale."],
      ["§2 · p. 10", "日借款需求保留用户与资产维度", "Daily borrowing retains user and reserve identities",
        "论文把某一天同一用户、同一储备资产的借款交易加总为借款需求。合并到协议总量会丢掉用户和代币间差异；以地址数替代借款金额，也会变成另一个指标。编辑建议保留聚合键、代币单位、换算价格和日期边界。",
        "Borrowing demand sums transactions for a user and reserve asset within a day. Protocol totals discard user and token differences, while address counts measure something else. Editorial application: preserve aggregation keys, token units, conversion prices and day boundaries."],
      ["§2 · p. 10", "治理标记是代理变量，不是动机证明", "Governance indicators are proxies, not proof of intent",
        "作者区分赋予投票权的治理代币，并利用Snapshot中的投票日历标记投票期间。这让治理活动与借款之间的关系可以被研究，但并不直接说明每一笔借款都是为投票而发生。其他共同变化或地址用途仍可能影响解释。",
        "Governance tokens are flagged by voting rights, and voting periods are identified using Snapshot calendars. This supports studying a relation between governance activity and borrowing. It does not establish that every loan was taken to vote; other co-movements and address uses remain relevant."],
      ["§2 · pp. 9–10", "市场参照不是单一交易所的替身", "Market reference series are not a single-venue substitute",
        "文中ETH永续资金费率是七家交易所的简单平均，传统国债利率在非交易日沿用最近交易日数值。两种对齐规则都影响解释。仅有Binance序列不能声称取得了论文输入，资金费率本身也不是Aave借款利率或链上借贷活动。",
        "The ETH funding reference averages seven exchanges, while Treasury yields carry the latest trading-day value across closures. Both alignment rules matter. A Binance series alone is not the paper's input, and perpetual funding is neither the Aave borrowing rate nor on-chain lending activity."],
    ]),
  "Decentralized Finance: On Blockchain- and Smart Contract-Based Financial Markets": guide(
    "https://www.stlouisfed.org/-/media/project/frbstl/stlouisfed/publications/review/pdfs/2021/04/15/decentralized-finance-on-blockchain-and-smart-contract-based-financial-markets.pdf",
    bi("2021年Review期刊版", "2021 Review article"),
    "St. Louis Fed Review article: printed pp. 153–157 and 167–170 read for the five-layer framework, TVL, token representation, composability and execution/admin-key risks. Printed p. 155 visually checked. Protocol examples are historical; current deployments, security and legal entitlements were not audited.",
    bi("这篇2021年综述提供分层阅读框架，不是当前协议安全评级。公开代码、确定性执行与审计都不能消除全部风险，代币记录也不能单独证明链下权利。", "This 2021 survey offers a layered reading framework, not a current protocol safety rating. Public code, deterministic execution and audits do not remove every risk; token records alone do not establish off-chain rights."), {}, [
      ["§1", "先问指标量到了什么", "Start with what a metric measures",
        "Schär用锁在合约中的资产说明DeFi的扩展，同时讨论其金融活动形式。锁仓量反映特定口径的资产存量，并不是交易次数、成交额或代币市值。编辑建议在比较规模时同时保留估值价格、资产范围和跨协议重复计算的处理。",
        "Schär introduces DeFi partly through assets locked in contracts. Total value locked is a stock under a chosen definition, not transaction count, trading volume or token market capitalization. Editorial application: retain valuation prices, asset scope and treatment of cross-protocol double counting."],
      ["§2 · five-layer framework", "五层框架帮助定位依赖", "Five layers help locate dependencies",
        "文章区分结算层、资产层、协议层、应用层和聚合层。读者看到的界面只是其中一层，背后可能组合多个协议与资产。分层的价值在于追问每一步依赖谁，而不是把一个易用界面直接等同于整个金融基础设施。",
        "The framework separates settlement, asset, protocol, application and aggregation layers. A visible interface is only one layer and may combine several protocols and assets. The framework helps trace dependencies instead of equating a convenient interface with the full financial infrastructure."],
      ["§2 · five-layer framework", "上层透明不能修复底层缺陷", "Upper-layer transparency cannot repair lower-layer failure",
        "各层建立在更低层的可用性与安全之上，因此一个应用即使交互清楚，也仍依赖结算与资产合约正确工作。编辑建议阅读产品说明时分开核对界面、协议规则和底层资产，而不是以一个可访问网页证明整条链路可靠。",
        "Higher layers depend on lower-layer availability and security. A clear interface still relies on settlement and asset contracts functioning correctly. Editorial application: assess the interface, protocol rules and underlying assets separately; a reachable website does not establish end-to-end reliability."],
      ["§2.1", "代币表示与链下资产权利分开", "Token representation differs from off-chain entitlement",
        "代币可以记录账本中的控制关系，也可以被用来表示外部资产。后一种情形仍需要理解发行者、保管与兑现安排，不能只看链上余额。编辑解读中，应把合约能够执行的规则与链下需要履行的承诺分别列出。",
        "A token can record ledger control or represent an external asset. The latter still requires understanding issuers, custody and redemption arrangements. Editorial interpretation: distinguish rules enforceable by the contract from obligations that must be fulfilled outside the chain."],
      ["§3.1 · p. 169", "可组合性也意味着共享依赖", "Composability also creates shared dependencies",
        "共同结算环境让不同协议能够组合出新的服务，减少重复建设。与此同时，组合服务会继承所用协议和外部数据的依赖。编辑建议画清资金与信息所经过的组件；多个不同品牌并不一定意味着底层风险已经分散。",
        "A shared settlement environment allows protocols to combine into new services. Combinations also inherit dependencies on constituent protocols and external information. Editorial application: trace the components carrying funds and information; several brands need not imply diversified underlying risk."],
      ["§3.2 · p. 170", "确定执行不等于安全执行", "Deterministic execution is not safe execution",
        "综述分别讨论代码错误、被破坏的前端、管理密钥和治理权集中等风险。确定性可以让同一规则重复执行，也可能让错误规则同样可靠地执行。审计、多签与时间锁可以缓解部分风险，但不应被读作绝对安全或当前部署已获验证。",
        "The survey distinguishes coding errors, compromised interfaces, admin keys and concentrated governance. Determinism can execute a flawed rule reliably too. Audits, multisignatures and timelocks mitigate some risks; they are not proof of absolute safety or verification of a current deployment."],
    ]),
};
