// Per-record curation of the 150 summary-only records at the v11 baseline.
// Empty selections are deliberate: no suitable maintained material is asserted.
// Navigation scope only; not a new full-text review or an original-sample match.
export const researchSummaryMaterials = {
  "Returns to Buying Winners and Selling Losers: Implications for Stock Market Efficiency": {"recipes":["adjusted-price-series"]},
  "Optimal Execution of Portfolio Transactions": {},
  "Price Momentum and Trading Volume": {"recipes":["adjusted-price-series"]},
  "Media Coverage and the Cross-section of Stock Returns": {"recipes":["document-version-ledger"]},
  "CSI 300 Index Methodology": {},
  "SSE Statistical Yearbook": {},
  "Findings Regarding the Market Events of May 6, 2010": {},
  "Staff Report on Equity and Options Market Structure Conditions in Early 2021": {},
  "Why DeFi Lending? Evidence from Aave V2": {},
  "Form 13F: Official Filing Guidance and EDGAR Data Access": {"recipes":["document-version-ledger"]},
  "Binance USDⓈ-M Futures Market Data: Funding Rate and Open Interest": {"datasets":["crypto-binance-derivatives"]},
  "A Comprehensive Look at The Empirical Performance of Equity Premium Prediction": {"recipes":["adjusted-price-series"]},
  "The Valuation of Risk Assets and the Selection of Risky Investments in Stock Portfolios and Capital Budgets": {},
  "An Intertemporal Capital Asset Pricing Model": {},
  "The Arbitrage Theory of Capital Asset Pricing": {},
  "Risk, Return, and Equilibrium: Empirical Tests": {"recipes":["adjusted-price-series"]},
  "The Equity Premium: A Puzzle": {},
  "Asset Prices in an Exchange Economy": {},
  "Habit Formation: A Resolution of the Equity Premium Puzzle": {},
  "By Force of Habit: A Consumption-Based Explanation of Aggregate Stock Market Behavior": {},
  "Risks for the Long Run: A Potential Resolution of Asset Pricing Puzzles": {},
  "Dissecting Anomalies with a Five-Factor Model": {"recipes":["pit-fundamentals-panel","adjusted-price-series"]},
  "Digesting Anomalies: An Investment Approach": {"recipes":["pit-fundamentals-panel","adjusted-price-series"]},
  "… and the Cross-Section of Expected Returns": {},
  "Value and Momentum Everywhere": {},
  "Time Series Momentum": {},
  "Betting Against Beta": {},
  "Idiosyncratic Risk and the Cross-Section of Expected Stock Returns": {"recipes":["adjusted-price-series"]},
  "Expected Stock Returns and Volatility": {"recipes":["adjusted-price-series"]},
  "The Cross-Section of Volatility and Expected Returns": {"recipes":["adjusted-price-series"]},
  "Tests of Asset Pricing with Time-Varying Expected Risk Premiums and Market Betas": {"recipes":["adjusted-price-series"]},
  "The Dividend-Price Ratio and Expectations of Future Dividends and Discount Factors": {"recipes":["adjusted-price-series"]},
  "Do Stock Prices Move Too Much to be Justified by Subsequent Changes in Dividends?": {"recipes":["adjusted-price-series"]},
  "Stock Prices, Earnings, and Expected Dividends": {"recipes":["adjusted-price-series"]},
  "On the Estimation of Beta-Pricing Models": {"recipes":["adjusted-price-series"]},
  "Presidential Address: Discount Rates": {},
  "Size and Value in China": {"recipes":["pit-fundamentals-panel","adjusted-price-series"]},
  "Bid, Ask and Transaction Prices in a Specialist Market with Heterogeneously Informed Traders": {},
  "One Security, Many Markets: Determining the Contributions to Price Discovery": {},
  "Asset Pricing and the Bid-Ask Spread": {},
  "Liquidity Risk and Expected Stock Returns": {"datasets":["cn-equity-daily"]},
  "Trading Volume and Serial Correlation in Stock Returns": {"datasets":["cn-equity-daily"]},
  "Limit Order Book as a Market for Liquidity": {},
  "Hawkes Processes in Finance": {},
  "The Long Memory of the Efficient Market": {},
  "An Analysis of Changes in Specialist Inventories and Quotations": {},
  "Why Do Security Prices Change? A Transaction-Level Analysis of NYSE Stocks": {},
  "High-Frequency Trading and Price Discovery": {},
  "Does Algorithmic Trading Improve Liquidity?": {},
  "The High-Frequency Trading Arms Race: Frequent Batch Auctions as a Market Design Response": {},
  "The Flash Crash: High-Frequency Trading in an Electronic Market": {},
  "High Frequency Trading and the New Market Makers": {},
  "Market Microstructure: A Survey": {},
  "Commonality in Liquidity": {},
  "Market Liquidity and Trading Activity": {},
  "Order Imbalance and Individual Stock Returns: Theory and Evidence": {},
  "A New Estimate of Transaction Costs": {"recipes":["adjusted-price-series"]},
  "Autoregressive Conditional Heteroscedasticity with Estimates of the Variance of United Kingdom Inflation": {},
  "Generalized Autoregressive Conditional Heteroskedasticity": {},
  "A Heteroskedasticity-Consistent Covariance Matrix Estimator and a Direct Test for Heteroskedasticity": {},
  "Robust Inference With Multiway Clustering": {},
  "The Adjustment of Stock Prices to New Information": {"recipes":["company-event-timeline","adjusted-price-series"]},
  "A Reality Check for Data Snooping": {},
  "A Test for Superior Predictive Ability": {},
  "Comparing Predictive Accuracy": {},
  "The Probability of Backtest Overfitting": {},
  "The Deflated Sharpe Ratio: Correcting for Selection Bias, Backtest Overfitting, and Non-Normality": {},
  "False Discoveries in Mutual Fund Performance: Measuring Luck in Estimated Alphas": {},
  "Controlling the False Discovery Rate: A Practical and Powerful Approach to Multiple Testing": {},
  "The Stationary Bootstrap": {},
  "An Introduction to the Bootstrap": {},
  "Regularization and Variable Selection via the Elastic Net": {},
  "Greedy Function Approximation: A Gradient Boosting Machine": {},
  "Empirical Asset Pricing via Machine Learning": {"recipes":["pit-fundamentals-panel","adjusted-price-series"]},
  "Autoencoder Asset Pricing Models": {"recipes":["pit-fundamentals-panel","adjusted-price-series"]},
  "Deep Learning in Asset Pricing": {"recipes":["pit-fundamentals-panel","adjusted-price-series"]},
  "Characteristics Are Covariances: A Unified Model of Risk and Return": {"recipes":["pit-fundamentals-panel","adjusted-price-series"]},
  "A Simple Approximate Long-Memory Model of Realized Volatility": {"recipes":["minute-bar-gaps"]},
  "Realized Kernels in Practice: Trades and Quotes": {},
  "Microstructure Noise in the Continuous Case: The Pre-Averaging Approach": {},
  "Earnings Management During Import Relief Investigations": {"recipes":["pit-fundamentals-panel"]},
  "The Detection of Earnings Manipulation": {"recipes":["pit-fundamentals-panel"]},
  "Financial Ratios and the Probabilistic Prediction of Bankruptcy": {"recipes":["pit-fundamentals-panel"]},
  "The Dark Side of Outside Directors: Do They Quit When They Are Most Needed?": {},
  "Investor Protection and Corporate Governance": {},
  "Law and Finance": {},
  "Corporate Ownership Around the World": {},
  "The Separation of Ownership and Control in East Asian Corporations": {},
  "Agency Costs of Free Cash Flow, Corporate Finance, and Takeovers": {},
  "The Capital Structure Puzzle": {},
  "Corporate Financing and Investment Decisions When Firms Have Information That Investors Do Not Have": {},
  "Toward an Implied Cost of Capital": {},
  "PE Ratios, PEG Ratios, and Estimating the Implied Expected Rate of Return on Equity Capital": {},
  "Information Asymmetry, Corporate Disclosure, and the Capital Markets: A Review of the Empirical Disclosure Literature": {},
  "Disclosure, Liquidity, and the Cost of Capital": {},
  "International Differences in the Cost of Equity Capital: Do Legal Institutions and Securities Regulation Matter?": {},
  "The Cost of Capital, Corporation Finance and the Theory of Investment": {},
  "More Than Words: Quantifying Language to Measure Firms' Fundamentals": {"recipes":["document-version-ledger"]},
  "Textual Analysis in Accounting and Finance: A Survey": {"recipes":["document-version-ledger"]},
  "The Price of Political Uncertainty: Theory and Evidence from the Option Market": {},
  "In Search of Attention": {},
  "The Sum of All FEARS Investor Sentiment and Asset Prices": {},
  "All That Glitters: The Effect of Attention and News on the Buying Behavior of Individual and Institutional Investors": {},
  "Peer Pressure: Social Interaction and the Disposition Effect": {},
  "Wisdom of Crowds: The Value of Stock Opinions Transmitted Through Social Media": {"recipes":["document-version-ledger"]},
  "Investor Sentiment in the Stock Market": {},
  "The Stock Market's Reaction to Unemployment News: Why Bad News Is Usually Good for Stocks": {},
  "What Moves Stock Prices?": {},
  "The Impact of Public Information on the Stock Market": {"recipes":["document-version-ledger"]},
  "The Information Content of Forward-Looking Statements in Corporate Filings—A Naïve Bayesian Machine Learning Approach": {"recipes":["document-version-ledger"]},
  "Annual Report Readability, Current Earnings, and Earnings Persistence": {"recipes":["document-version-ledger"]},
  "Common Factors Affecting Bond Returns": {"datasets":["cn-yield-curve"]},
  "The Macroeconomy and the Yield Curve: A Dynamic Latent Factor Approach": {"datasets":["cn-yield-curve"]},
  "Business Cycles in a Small Open Economy": {},
  "The Forward Premium Puzzle: Different Tales from Developed and Emerging Economies": {},
  "Common Risk Factors in Currency Markets": {},
  "Carry": {},
  "Discretion versus Policy Rules in Practice": {},
  "Monetary Policy Shocks: What Have We Learned and to What End?": {},
  "Measuring the Effects of Monetary Policy: A Factor-Augmented Vector Autoregressive (FAVAR) Approach": {},
  "The Macroeconomic Impact of Financial and Uncertainty Shocks": {},
  "Credit Spreads and Business Cycle Fluctuations": {},
  "Financial Intermediation and Credit Policy in Business Cycle Analysis": {},
  "The Leverage Cycle": {},
  "SRISK: A Conditional Capital Shortfall Measure of Systemic Risk": {"recipes":["pit-fundamentals-panel","adjusted-price-series"]},
  "Forecasting Using Principal Components From a Large Number of Predictors": {},
  "Law, Finance, and Economic Growth in China": {},
  "Short-Sales Constraints and Price Discovery: Evidence from the Hong Kong Market": {},
  "Differences of Opinion, Short-Sales Constraints, and Market Crashes": {},
  "Speculative Trading and Stock Prices: Evidence from Chinese A-B Share Premia": {},
  "How Does Government Ownership Affect Firm Performance? Evidence from China’s Privatization Experience": {"recipes":["pit-fundamentals-panel"]},
  "Politically Connected CEOs, Corporate Governance, and Post-IPO Performance of China's Newly Partially Privatized Firms": {},
  "The Effects of Political Connections and State Ownership on Corporate Litigation in China": {},
  "Asset Growth and the Cross-Section of Stock Returns": {"recipes":["pit-fundamentals-panel","adjusted-price-series"]},
  "The Investment CAPM": {},
  "Stock Market Liberalization, Economic Reform, and Emerging Market Equity Prices": {},
  "Does Financial Liberalization Spur Growth?": {},
  "Retail and Institutional Investor Trading Behaviors: Evidence from China": {},
  "The Economics of Cryptocurrencies—Bitcoin and Beyond": {},
  "Common Risk Factors in Cryptocurrency": {},
  "Is Bitcoin Really Un-Tethered?": {},
  "Some Simple Economics of the Blockchain": {},
  "Blockchain Economics": {},
  "SoK: Research Perspectives and Challenges for Bitcoin and Cryptocurrencies": {},
  "Decentralized Finance: On Blockchain- and Smart Contract-Based Financial Markets": {},
  "Taming Wildcat Stablecoins": {},
  "An Empirical Study of DeFi Liquidations: Incentives, Risks, and Instabilities": {},
  "Flash Boys 2.0: Frontrunning in Decentralized Exchanges, Miner Extractable Value, and Consensus Instability": {},
  "SoK: Decentralized Finance (DeFi)": {},
  "Cryptocurrency Pump-and-Dump Schemes": {},
};
