// Bounded, bilingual orientation guides. Each entry stays within the cited primary
// source's public description or official report; it is not a numerical replication.
import { researchSummaryMaterials } from "./researchSummaryMaterials.js";

const bi = (zh, en) => ({ zh, en });
const guide = ({ title, url, source, question, design, data, finding, checks, boundary }) => [title, {
  reviewedAt: "2026-08-31",
  evidenceUrl: url,
  evidenceScope: "The cited primary source's public description and registered bibliographic record were read. This orientation guide stays within those materials; it does not infer numerical results, table-level evidence, or an implementation beyond the source description.",
  limits: bi(`本文只整理“${title}”所公开说明的研究问题与设计边界，不构成收益预测、交易规则或全文复现。${boundary}`, `This guide only organizes the publicly described question and design of “${title}”. It is not a return forecast, trading rule, or full-text replication. The source's stated scope remains controlling.`),
  related: researchSummaryMaterials[title] ?? {},
  sections: [
    ["研究问题", "Research question", `${question} 阅读时先把它理解为一个被界定的问题，而不是可以脱离样本、时间和制度环境的结论。`, `“${title}” frames a bounded research question. Read the stated question together with the named sample, dates, and institutional setting rather than treating it as a conclusion that automatically travels to another market or period.`],
    ["研究设计", "Research design", `${design} 这说明比较对象、观察窗口和对照关系是研究合同的一部分；改变其中任何一项，都可能改变所检验的命题。`, `For “${title}”, the source describes a deliberate comparison, observation window, and control relation. Those choices are part of its research contract: changing one can change the proposition being tested, even when the method label remains the same.`],
    ["数据与时点", "Data and timing", `${data} 数据字段、可得时点和样本筛选需要与原始研究分开记录，不能仅凭同名变量或最终修订数据就视为可比。`, `For “${title}”, keep the fields, their availability timing, and the sample filters separate from the original study. A same-named variable, later-revised database, or matching end-of-period date is not automatically a comparable input.`],
    ["如何理解结果", "How to read the result", `${finding} 它支持的是该来源所描述的经验或理论关系；它本身不把相关性、模型拟合或历史表现升级为因果、可执行性或未来保证。`, `For “${title}”, the source supports only the empirical or theoretical relation it describes. It does not turn association, model fit, or historical performance into causality, a directly executable procedure, or a guarantee about subsequent outcomes.`],
    ["复核清单", "Replication checks", `${checks} 在做后续分析前，应把这些选择写入版本化的研究记录，并保留原始来源链接与访问日期。`, `Before extending “${title}”, record its sample, timing, construction choices, and source edition in a versioned note. Keep the primary-source link and access date so a later reader can distinguish a changed definition from a changed result.`],
    ["适用边界", "Scope boundary", `该条导读引用 ${source}。${boundary} 若需要量化结论、参数、表格或稳健性检验，请回到原文并单独核对版本、附录与样本定义。`, `This guide cites ${source} for “${title}”. Its public description defines the boundary. For numerical conclusions, parameters, tables, or robustness tests, return to the original and separately verify the edition, appendices, and sample definitions.`],
  ].map(([zhTitle, enTitle, zhBody, enBody]) => ({
    title: bi(zhTitle, enTitle), body: bi(zhBody, enBody), reference: { url, label: bi(`${source} · 来源说明`, `${source} · source description`) },
  })),
}];

export const researchBatchOne140 = Object.fromEntries([
  guide({
    title: "Returns to Buying Winners and Selling Losers: Implications for Stock Market Efficiency", url: "https://doi.org/10.1111/j.1540-6261.1993.tb04702.x", source: "The Journal of Finance (1993)",
    question: "论文考察过去一段时间表现较好的股票与表现较差的股票，之后是否仍出现系统性的相对收益差。",
    design: "公开说明以形成期与持有期组合为核心，比较赢家与输家组合在不同时间跨度内的后续收益。",
    data: "关键对象是复权收益、形成与持有窗口、证券样本和组合构造日期，而不是一句“动量”标签。",
    finding: "来源描述的是对市场效率含义的经验检验，重点在相对组合回报与其随持有期变化的表现。",
    checks: "明确收益是否包含退市、如何处理重叠持有期、何时形成组合，以及是否使用当时可得的证券范围。",
    boundary: "历史组合差异不能替代交易成本、可借券性、容量或另一个市场的可实现收益评估。",
  }),
  guide({
    title: "Price Momentum and Trading Volume", url: "https://doi.org/10.1111/0022-1082.00280", source: "The Journal of Finance (2000)",
    question: "论文把价格动量与交易量放在一起，询问交易活跃程度是否帮助区分后续动量路径。",
    design: "公开研究描述按过去回报与成交活跃度对股票分组，再比较分组后的收益行为。",
    data: "需要区分价格收益、成交量或换手率的定义、分组断点以及形成期与后续观察期。",
    finding: "来源讨论成交活跃度与动量的联合信息，而不是把成交量单独解释为必然的涨跌信号。",
    checks: "统一成交量的市场口径和拆股调整，冻结分组日期，并避免让未来成交数据进入形成期特征。",
    boundary: "成交量代理、市场制度和交易成本跨市场差异很大，不能直接移植成买卖指令。",
  }),
  guide({
    title: "Findings Regarding the Market Events of May 6, 2010", url: "https://www.sec.gov/files/marketevents-report.pdf", source: "SEC / CFTC joint report (2010)",
    question: "联合报告记录2010年5月6日市场事件，并梳理当日价格、成交与市场结构条件之间的关系。",
    design: "这是监管调查报告，围绕特定事件窗口整合跨市场交易与报价证据，而非一般化的资产定价回归。",
    data: "阅读需保留事件时钟、交易场所、合约与股票身份、订单和报价字段，以及数据覆盖差异。",
    finding: "报告的价值在于重建极端时段的市场过程；它不提供一个可脱离该事件的普遍因果公式。",
    checks: "核对所有时间戳的时区、跨市场同步方式、取消与更正记录，以及报告版本所覆盖的证据范围。",
    boundary: "单次压力事件不能代表平常流动性，也不能据此推断任一市场的日常执行质量。",
  }),
  guide({
    title: "Staff Report on Equity and Options Market Structure Conditions in Early 2021", url: "https://www.sec.gov/about/reports-publications/staff-report-equity-options-market-structure-conditions-early-2021", source: "SEC staff report (2021)",
    question: "工作人员报告描述2021年初美国股票和期权市场结构条件，包含特定证券与参与者活动的背景。",
    design: "报告以监管观察和市场数据为基础组织事实，不等同于对单一交易策略或单一机制的实验识别。",
    data: "相关数据包括市场价格、成交、期权、卖空与参与者活动，但每个字段的可见范围和统计口径并不相同。",
    finding: "其核心用途是为特定时期的市场结构讨论提供来源可追溯的背景，而不是输出一个普遍风险因子。",
    checks: "将证券范围、日期窗口、监管披露口径与后续修订分开记录，并勿将叙述性观察转换为因果系数。",
    boundary: "该报告服务于特定美国市场事件的理解，不能直接替代中国市场或其他时期的微观结构证据。",
  }),
  guide({
    title: "Form 13F: Official Filing Guidance and EDGAR Data Access", url: "https://www.sec.gov/divisions/investment/13ffaq.htm", source: "SEC Form 13F guidance",
    question: "官方指引说明哪些机构、证券与申报安排属于Form 13F框架，以及如何通过EDGAR查找材料。",
    design: "这是一套披露与访问规则，而不是对机构真实持仓、动机或交易时点的完整观测设计。",
    data: "应保留申报人身份、报告期、提交与修订日期、证券范围、CUSIP映射和文件版本。",
    finding: "资料可支持对已披露持仓的结构化研究，但公开申报的覆盖范围与时间滞后必须被视为数据合同的一部分。",
    checks: "以提交时间而非报告期末作为可得性边界，保留修订文件，并验证证券标识和公司行动映射。",
    boundary: "13F并不等于完整投资组合、实时交易流或统一的基金持仓口径，缺失部分不能静默补齐。",
  }),
  guide({
    title: "Binance USDⓈ-M Futures Market Data: Funding Rate and Open Interest", url: "https://developers.binance.com/docs/derivatives/usds-margined-futures/market-data/rest-api/Get-Funding-Rate-History", source: "Binance USDⓈ-M Futures API documentation",
    question: "资料说明USDⓈ-M永续合约的资金费率历史与持仓量等公开市场数据如何定义和取得。",
    design: "它是接口合同：请求参数、标的、时间范围、返回字段和限制共同决定了可复现的数据请求。",
    data: "应冻结合约标识、请求起止时间、分页或上限、拉取时钟、响应原文与版本化交易规则。",
    finding: "资金费率与持仓量是不同测量对象；接口可读不证明任意时间段完整，也不证明两者具有固定方向关系。",
    checks: "保存请求形状、返回时间戳、空响应和限流状态，并区分资金费率历史与资金压力代理等非同一字段。",
    boundary: "公开接口数据不能替代账户数据、逐笔订单簿或可执行交易成本，也不构成交易建议。",
  }),
  guide({
    title: "The Valuation of Risk Assets and the Selection of Risky Investments in Stock Portfolios and Capital Budgets", url: "https://doi.org/10.2307/1924119", source: "The Review of Economics and Statistics (1965)",
    question: "Lintner讨论风险资产估值与风险组合选择，为资本资产定价的均衡思路提供早期表述。",
    design: "理论设计从投资者偏好、风险资产与均衡价格出发，关注风险和预期回报之间的条件性关系。",
    data: "概念输入包括预期回报、风险、协方差与组合权重；这些不是无需估计误差即可直接观察的市场事实。",
    finding: "模型解释的是在其假设下风险如何进入资产定价，而不是对单只股票未来回报的确定预测。",
    checks: "明确无风险资产、投资者同质性、均值方差框架和市场组合的定义，再讨论任何经验检验。",
    boundary: "理论假设与现实市场摩擦、税费、约束和估计误差之间存在距离，不能省略。",
  }),
  guide({
    title: "Habit Formation: A Resolution of the Equity Premium Puzzle", url: "https://doi.org/10.1086/261693", source: "Journal of Political Economy (1990)",
    question: "论文引入消费习惯形成，探讨它如何改变风险厌恶与股票溢价问题的解释。",
    design: "理论模型让效用取决于消费相对于习惯水平的位置，再推导资产回报所需承担的风险补偿。",
    data: "关键量是消费、习惯状态、偏好参数和资产回报；习惯本身是模型状态而非直接可见的数据列。",
    finding: "该机制展示偏好动态可改变风险补偿的含义，并不是以单一历史样本直接证明习惯在现实中被观测到。",
    checks: "分开记录效用设定、状态演化、校准目标和样本期，避免把校准匹配误认为结构因果识别。",
    boundary: "机制的解释力依赖模型设定，不能从标题直接推出任何市场时点的预期收益。",
  }),
  guide({
    title: "The Deflated Sharpe Ratio: Correcting for Selection Bias, Backtest Overfitting, and Non-Normality", url: "https://doi.org/10.3905/jpm.2014.40.5.094", source: "The Journal of Portfolio Management (2014)",
    question: "论文讨论在多次尝试、非正态收益与回测选择偏差存在时，如何重新理解Sharpe ratio的显著性。",
    design: "方法把观测到的Sharpe ratio放在候选策略数量、收益分布形状与样本长度共同构成的检验背景中。",
    data: "需要留存完整候选池、每次试验的选择过程、收益频率、偏度、峰度与样本长度，而非只保存胜出的曲线。",
    finding: "修正的目标是降低从大量尝试中挑出高指标所造成的乐观解释，不是把一个阈值变成自动有效的策略认证。",
    checks: "登记全部试验而非只登记最终模型，确认独立性假设与年化口径，并保持训练、验证和测试样本隔离。",
    boundary: "统计修正不能替代真实交易摩擦、数据修订风险或未来分布变化的评估。",
  }),
  guide({
    title: "A Reality Check for Data Snooping", url: "https://doi.org/10.1111/1468-0262.00152", source: "Econometrica (2000)",
    question: "White提出对大量候选模型反复搜索后所得到的最佳表现进行数据窥探校正。",
    design: "方法将候选比较置于同一零假设下，并用重采样思路评估选择后最大表现的显著性。",
    data: "输入不只是一个胜出模型的收益，还包括被比较的完整规则集合、损失函数、时间序列依赖和样本划分。",
    finding: "它提醒研究者：从许多规则里找到表现最好的一条，并不自动构成优于基准的可靠证据。",
    checks: "在研究开始时冻结候选空间，保存每次变更和失败结果，并验证重采样与时间依赖结构是否相符。",
    boundary: "通过统计检验不代表经济可行、可执行或对未见未来保持同样表现。",
  }),
  guide({
    title: "A Test for Superior Predictive Ability", url: "https://doi.org/10.1198/073500105000000063", source: "Journal of Business & Economic Statistics (2005)",
    question: "Hansen提出检验预测模型是否相对基准具有优越预测能力的程序，并处理候选模型比较问题。",
    design: "公开描述将多个模型的损失差放进统一检验框架，关注基准是否被至少一个候选稳定超越。",
    data: "必须先定义预测目标、损失函数、预测时点、滚动或扩展窗口以及全部候选模型的输出。",
    finding: "方法帮助区分某个样本内赢家与在多模型比较下仍有证据支持的预测优势。",
    checks: "保持基准模型固定，保存候选集合、预测误差序列和依赖处理方式，并避免测试后再收缩候选池。",
    boundary: "预测统计优势与投资收益、交易容量或跨市场迁移能力是不同问题。",
  }),
  guide({
    title: "Autoregressive Conditional Heteroscedasticity with Estimates of the Variance of United Kingdom Inflation", url: "https://doi.org/10.2307/1912773", source: "Econometrica (1982)",
    question: "Engle提出ARCH思想，允许时间序列的条件方差随过去信息而变化。",
    design: "模型把均值方程与条件方差方程分开指定，用过去误差等信息描述波动的时变性。",
    data: "需要保留原始时间序列、频率、缺口、均值设定、残差定义与用于估计的完整时间窗口。",
    finding: "ARCH说明方差不必恒定；它不是对任何金融价格自动适用的波动预测承诺。",
    checks: "检验残差结构、参数约束、估计样本和诊断结果，并区分条件方差估计与未来真实波动。",
    boundary: "模型遗漏、结构变化和极端尾部都可能使历史拟合无法代表之后的风险。",
  }),
  guide({
    title: "Do Stock Prices Move Too Much to be Justified by Subsequent Changes in Dividends?", url: "https://doi.org/10.1257/aer.71.3.421", source: "American Economic Review (1981)",
    question: "Shiller比较股票价格波动与之后股利变化所能解释的范围，讨论价格波动的含义。",
    design: "公开描述将价格与事后股利路径放在现值关系下比较，问题依赖贴现、预期和样本定义。",
    data: "需要明确价格、股利、通胀调整、贴现率、观测频率和事后可见信息与当时预期之间的区别。",
    finding: "文章提出价格波动与后续股利解释之间的张力，而非提供一个可以逐日交易的价格偏离指标。",
    checks: "复核现值恒等式、样本起止、股利口径和任何平稳性或预期假设，避免把事后路径当作实时信号。",
    boundary: "价格与股利关系的长期研究不免除对风险溢价、结构变化和数据修订的单独处理。",
  }),
  guide({
    title: "The Dividend-Price Ratio and Expectations of Future Dividends and Discount Factors", url: "https://doi.org/10.1093/rfs/17.1.27", source: "Review of Financial Studies (2004)",
    question: "论文研究股利价格比与未来股利、折现率和回报预期之间的分解关系。",
    design: "研究框架围绕估值恒等式展开，把比率的变动与未来现金流和贴现成分的预期联系起来。",
    data: "核心是股利、价格、再投资与频率口径；这些定义会决定比率是否与原研究中的对象一致。",
    finding: "比率可以携带关于未来成分的联合信息，但来源并不把它说成单变量、无条件的方向性预测器。",
    checks: "统一股利定义、价格日历、对数变换和样本起点，并明确预测回归的持有期是否重叠。",
    boundary: "估值比率会受会计、分配政策和市场制度影响，跨国家或资产类别比较需重新验证。",
  }),
  guide({
    title: "Expected Stock Returns and Volatility", url: "https://doi.org/10.1093/rfs/12.4.1009", source: "Review of Financial Studies (1999)",
    question: "研究讨论预期股票收益与波动之间的关系，并强调该关系取决于建模和信息设定。",
    design: "公开设计将收益与条件波动联系起来，关注时变风险和回报的统计刻画。",
    data: "需明确收益频率、波动度量、条件信息集、估计窗口与是否使用实现值或模型估计值。",
    finding: "任何观察到的收益—波动关系都需要放在条件模型和样本背景下解释，不能简化为波动越高回报越高。",
    checks: "分别复核波动代理、均值与方差方程、分布假设和样本外划分，并报告估计不确定性。",
    boundary: "历史条件关系不保证未来补偿，也不回答杠杆、流动性或交易成本之后的可实现结果。",
  }),
  guide({
    title: "The Cross-Section of Volatility and Expected Returns", url: "https://doi.org/10.1111/j.1540-6261.2006.00818.x", source: "The Journal of Finance (2006)",
    question: "论文考察股票横截面中的波动差异与预期收益之间的经验关系。",
    design: "研究按个股或组合的波动特征进行横截面比较，重点是排序、控制变量和后续收益的定义。",
    data: "波动估计、股票范围、市值权重、断点和回报持有期必须一起保存，不能只保留最终分组标签。",
    finding: "横截面结果描述的是特定样本中的条件比较，而不是把波动作为单独足够的定价因子。",
    checks: "检查微盘股、退市、流动性、极端值处理和断点来源，并确保特征在投资期前已可观察。",
    boundary: "横截面关联不构成任何标的的风险判断，更不能绕过组合形成与执行成本。",
  }),
  guide({
    title: "Tests of Asset Pricing with Time-Varying Expected Risk Premiums and Market Betas", url: "https://doi.org/10.1016/0304-405X(94)00856-F", source: "Journal of Financial Economics (1995)",
    question: "论文允许预期风险溢价与市场贝塔随时间变化，再检验资产定价关系。",
    design: "设计的关键是把时变预期和暴露纳入检验，而不是把静态贝塔当成每一时期的充分描述。",
    data: "需要保留用于估计条件信息、贝塔、市场回报和工具变量的时点与可得性，避免未来信息泄漏。",
    finding: "时变设定提示静态检验可能遗漏状态依赖，但模型复杂度本身不是对定价关系成立的证明。",
    checks: "冻结信息集和估计窗口，报告工具变量、参数稳定性及弱识别风险，并区分事后估计与实时可得值。",
    boundary: "模型的条件性结果不能自动延伸到其他市场结构、资产类别或之后的宏观状态。",
  }),
  guide({
    title: "Stock Prices, Earnings, and Expected Dividends", url: "https://doi.org/10.1111/j.1540-6261.1988.tb04598.x", source: "The Journal of Finance (1988)",
    question: "论文联系股票价格、盈余与预期股利，讨论这些会计和现金流信息在估值中的位置。",
    design: "公开研究描述比较价格与盈余、股利预期之间的关系，依赖会计期间、披露时点和预测变量的处理。",
    data: "必须区分财年末、公告日、可用日、经修订盈余与股利口径；这些不是一个同义的“基本面日期”。",
    finding: "来源所讨论的是估值信息之间的关系，不表示报告盈余能机械决定下一期价格变化。",
    checks: "保留原始报表版本和发布日期，统一单位与拆分调整，并避免使用之后修订的字段进行历史排序。",
    boundary: "会计数据跨制度和公司并不完全可比，价格反应还受预期、风险和市场摩擦影响。",
  }),
  guide({
    title: "On the Estimation of Beta-Pricing Models", url: "https://doi.org/10.2307/2328693", source: "The Review of Economics and Statistics (1979)",
    question: "论文讨论贝塔定价模型的估计问题，提醒风险暴露测量会影响资产定价检验。",
    design: "研究关注贝塔的估计误差、分组与检验安排，而不是将一次回归的系数直接视为无误差真值。",
    data: "输入包括资产或组合收益、市场代理、估计窗口和分组规则；市场组合代理的选择本身也属于模型设定。",
    finding: "该讨论强调估计方法会塑造对风险—收益关系的判断，不能只比较最终的显著性符号。",
    checks: "记录前排序与后排序暴露、样本切分、组合构造和误差处理，并报告估计不确定性。",
    boundary: "改善统计估计不等于证明CAPM完整成立，也不能消除市场代理和样本选择问题。",
  }),
  guide({
    title: "Asset Pricing and the Bid-Ask Spread", url: "https://doi.org/10.1016/S0304-405X(99)00067-4", source: "Journal of Financial Economics (2000)",
    question: "论文把买卖价差与资产定价联系起来，讨论交易摩擦可能如何进入预期回报研究。",
    design: "公开描述以价差或流动性摩擦的测量为条件，对资产或组合的回报关系进行比较。",
    data: "需要明确价差来自报价、成交还是代理估计，并保留频率、市场、证券筛选和测量时钟。",
    finding: "价差可以代表某些交易摩擦，但它不是完整执行成本，也不应被视为所有流动性维度的同义词。",
    checks: "分开报告报价价差、有效价差、价格冲击和费用，并将异常报价、非交易日和公司行动处理写明。",
    boundary: "一项流动性代理与回报的历史关联，不构成对任一证券未来回报或成交能力的承诺。",
  }),
]);
