// Original editorial prose. Reading scopes identify the inspected edition, not replication.
const bi = (zh, en) => ({ zh, en });
const guide = (url, edition, evidenceScope, limits, related, rows) => ({
  reviewedAt: "2026-08-31", evidenceUrl: url, evidenceScope, limits, related,
  sections: rows.map(([location, zh, en, bodyZh, bodyEn]) => ({
    title: bi(zh, en), body: bi(bodyZh, bodyEn),
    reference: { url, label: bi(`${edition.zh} · ${location}`, `${edition.en} · ${location}`) },
  })),
});

export const researchFiftyGuides = {
  "CoVaR": guide(
    "https://www.newyorkfed.org/medialibrary/media/research/staff_reports/sr348.pdf",
    bi("2014年9月工作论文", "September 2014 staff report"),
    "NY Fed Staff Report 348, September 2014 revision: introduction and sections 3.1–3.5 read for the definition, conditioning direction, sign convention and non-causal interpretation; printed p. 7 visually checked. Final journal tables and empirical replication not checked.",
    bi("导读依据2014年9月工作论文，保留正式期刊的引用身份。尾部联动包含共同暴露，不能解释为某家机构造成了系统损失，也不是监管资本或投资建议。", "This guide uses the September 2014 staff report, separately from the final journal citation. Tail dependence includes common exposures; it does not identify losses caused by a firm or prescribe regulatory capital or investments."),
    { recipes: ["adjusted-price-series"] }, [
      ["§1", "单家机构风险与系统联动分开", "Separate standalone risk from systemic dependence",
        "Adrian与Brunnermeier从单家机构的VaR出发，追问它处于困境时，整个金融系统的损失分布怎样变化。一家机构自身波动很大，未必与其他机构共同承压；多家小机构也可能因共同暴露而同时陷入困境。",
        "Adrian and Brunnermeier move from standalone VaR to the system's loss distribution when one institution is distressed. Large individual volatility need not imply strong system dependence, while several small firms may share the same exposure."],
      ["§3.1", "差值需要一个正常状态基准", "The difference needs a median-state baseline",
        "工作论文将困境状态下的系统CoVaR与该机构处于中位数状态时的系统CoVaR相减，得到ΔCoVaR。只报告困境条件下的一个分位数，会遗漏比较基准，也不能自动叫作风险贡献的变化。",
        "Delta CoVaR subtracts system CoVaR conditional on an institution's median state from system CoVaR conditional on its distress state. Reporting only the distressed conditional quantile omits the baseline and is not the same statistic."],
      ["§3.1", "条件事件与正负号都是定义", "Conditioning and signs belong to the definition",
        "第3.1节按损失定义分位数，并在ΔCoVaR公式中把机构损失固定在自身VaR或中位数。固定在阈值与落入整个尾部不是同一条件；若改用收益而非损失，分位方向和正负号也必须一并说明。",
        "Section 3.1 uses loss quantiles and evaluates the delta formula at the institution's VaR and median. Equality at a threshold is not conditioning on the entire tail. Switching from losses to returns also requires explicit quantile and sign conventions."],
      ["§3.4", "交换条件，问题就变了", "Reversing the conditioning changes the question",
        "系统在某家机构困境下的风险，与某家机构在系统危机下的风险，方向相反。作者把后一种称为Exposure-CoVaR。两者都研究尾部关系，却不能作为同一个指标互换，也不能仅靠相关系数的对称性混淆。",
        "System risk conditional on a firm's distress differs from firm risk conditional on system distress. The latter is called Exposure-CoVaR. These directional questions are not interchangeable simply because ordinary correlation is symmetric."],
      ["§1; §3.3", "共同暴露不等于因果传染", "Common exposure is not causal contagion",
        "共同宏观冲击、相似持仓和机构之间的反馈，都可能形成尾部共同变化。作者明确将ΔCoVaR定位为简约统计工具，而不是因果分摊。要回答某家机构究竟导致多少额外损失，需要额外的模型或识别依据。",
        "Shared macro shocks, similar positions and feedback can all generate tail co-movement. The authors describe a reduced-form statistical tool, not a causal allocation. Identifying losses caused by a particular institution requires additional assumptions or identification."],
      ["§1; §3.1", "先固定样本与收益口径", "Fix the sample and return definition first",
        "文中使用上市金融机构的周频股票收益，并区分百分比指标与乘入规模后的金额指标。编辑建议先保留机构身份、退市与合并处理、收益窗口及权重。下方复权教程只帮助准备价格，不提供系统组合、金融机构样本或CoVaR估计。",
        "The report uses weekly equity returns for listed financial institutions and distinguishes percentage measures from size-scaled amounts. Editorial application: retain identities, merger and delisting rules, windows and weights. The linked adjustment tutorial prepares prices only, not the system portfolio, institution sample or CoVaR estimator."],
    ]),
  "Liquidity and Leverage": guide(
    "https://www.newyorkfed.org/medialibrary/media/research/staff_reports/sr328.pdf",
    bi("2010年12月工作论文", "December 2010 staff report"),
    "NY Fed Staff Report 328, December 2010 revision: introduction and printed pp. 4–12 read for passive versus active leverage, balance-sheet examples and sample choice. Printed p. 8 visually checked. Later forecasting tables not independently verified.",
    bi("依据2010年12月工作论文阅读历史美国金融机构，正式期刊引用不变。资产负债表扩张、市场成交活跃与货币供应不是同一流动性概念，不能据此推断当前机构状态。", "The December 2010 report concerns historical US intermediaries, separately from the journal citation. Balance-sheet expansion, market trading activity and money supply are different liquidity concepts; the study does not establish current institutional conditions."),
    { recipes: ["pit-fundamentals-panel"] }, [
      ["§1–2", "杠杆先明确分子分母", "Define leverage through assets and equity",
        "作者用总资产相对权益的比例观察杠杆。当资产按市值计价而债务暂时不变，资产升值会增加权益，使这个比率下降。这种被动变化与机构随后主动借款、买入或缩减资产，是两个需要分开的过程。",
        "The paper examines leverage as assets relative to equity. With marked-to-market assets and approximately unchanged debt, appreciation increases equity and lowers leverage. That passive arithmetic is separate from subsequent borrowing, purchases or balance-sheet contraction."],
      ["§2 · p. 8", "价格上升为何反而引出借款", "Why a price rise can induce borrowing",
        "原文示例从资产100、债务90、权益10开始。资产升到101后，权益变成11；若仍以十倍杠杆为目标，就要增加9单位债务并买入资产，使资产达到110。这是解释机制的算例，不是实际银行的目标建议。",
        "The illustration starts with assets of 100, debt of 90 and equity of 10. Assets rising to 101 leave equity of 11. Restoring tenfold leverage requires borrowing and buying 9 more units, bringing assets to 110. This is a mechanism illustration, not a recommended target."],
      ["§2 · pp. 9–10", "出售与价格下跌可能相互强化", "Sales and falling prices can reinforce each other",
        "反方向上，资产损失压缩权益并抬高杠杆，恢复目标可能要求出售资产偿债。若大量出售又压低市场价格，其他持有者的资产负债表也会走弱。反馈是否发生仍取决于市场流动性和机构行为，不能只凭会计恒等式断言。",
        "Losses compress equity and raise leverage, potentially prompting sales to repay debt. If selling depresses prices, other holders' balance sheets weaken too. The feedback depends on market liquidity and institutional responses, not on the accounting identity alone."],
      ["§2 · pp. 4–7", "不同部门不能混成一条规律", "Do not pool different sectors into one rule",
        "论文依次比较家庭、非金融企业、商业银行和证券交易商的资产与杠杆变化，发现它们的行为模式不同。证券交易商的顺周期关系不能直接外推给家庭或全部公司，汇总前应保留部门分类和计价口径。",
        "The paper contrasts households, nonfinancial firms, commercial banks and securities dealers. Their asset–leverage patterns differ. Dealer procyclicality should not be assigned to every sector; preserve sector classifications and valuation conventions before aggregation."],
      ["§3.1 · pp. 10–12", "样本是独立投行，不是所有银行", "Standalone investment banks are a specific sample",
        "作者选择当时五家独立美国投行，并从10-K与10-Q取得季度资产负债表。回购融资、逆回购资产、交易资产和权益各有角色；不能用一家普通公司的负债率或交易量替代这些项目，也不能忽略样本起始时间不同。",
        "Five then-standalone US investment banks are studied using quarterly 10-K and 10-Q balance sheets. Repos, reverse repos, trading assets and equity have distinct roles. Ordinary corporate debt ratios or trading volume cannot replace these items, and sample starting dates differ."],
      ["§1; §3.1", "观察日期与公开日期分开保存", "Separate balance-sheet dates from availability",
        "季度末的资产负债表不是在该日就一定可供外部研究者使用。编辑建议同时保存报告期、披露日期、修订版本和机构合并变化。关联的时点一致教程只说明披露对齐，不代表平台已经提供原文的投行回购数据。",
        "A quarter-end balance sheet need not have been publicly available on that date. Editorial application: retain reporting period, release date, revisions and changes in entity scope. The as-of tutorial addresses disclosure alignment, not availability of the paper's investment-bank repo data."],
    ]),
  "Text as Data": guide(
    "https://web.stanford.edu/~gentzkow/research/text-as-data.pdf",
    bi("2019年期刊版", "2019 journal article"),
    "Author-hosted JEL article: section 2 and opening of section 3, printed pp. 537–541, read for document units, filtering, n-grams, search-interface limits and dictionary methods. Printed p. 537 visually checked. Not an audit of all methods/applications in the survey.",
    bi("这是2019年的方法综述。文本表示会损失信息，词典和清洗规则依赖语境；文中的英文例子不能直接成为中文金融文本的有效性证明。", "This is a 2019 methods survey. Text representations discard information, and dictionaries and preprocessing depend on context. English examples do not validate a Chinese financial-text implementation."),
    { recipes: ["document-version-ledger"] }, [
      ["§2.1", "先决定一篇文档是什么", "Choose the document unit before the model",
        "一篇新闻、一天的新闻集合和一家公司一年的发言，可以成为不同的文档单位。作者强调单位应服务于研究对象；聚合方式改变可保留的依赖关系，也改变统计样本数，不能仅为了文件方便而随意切分。",
        "An article, a day's news or a speaker-year can each define a document unit. Aggregation should match the research attribute. It changes both the dependence retained and the number of observations, so file convenience alone is not a sufficient reason for choosing it."],
      ["§2.2", "清洗不是无损操作", "Cleaning is not information-free",
        "删去数字、标点、常见词和罕见词，可以降低维度，却也可能删掉事件日期、否定含义或领域专有信息。作者举例说明别人眼中的停用词可能正是研究对象。应保留原文，并记录每一步过滤规则及其版本。",
        "Removing numbers, punctuation, common words and rare terms reduces dimensionality but may remove dates or domain-specific meaning. The survey stresses that one study's stop words may be another's object of interest. Preserve raw text and version each filtering decision."],
      ["§2.2", "词频与文档频率不是同一件事", "Term counts differ from document prevalence",
        "词在某篇文章出现多少次，与它出现在多少篇文章中，是两个维度。TF-IDF同时利用局部词频和语料中的文档频率；因此更换语料集合，即使单篇文本不变，其权重也可能改变。权重不是词语经济重要性的直接度量。",
        "A word's count within a document differs from the number of documents containing it. TF-IDF combines local frequency with corpus-wide prevalence. Changing the corpus may change weights even for unchanged text; a weight is not a direct measure of economic importance."],
      ["§2.3", "词袋丢掉顺序，词组保留局部依赖", "Bags of words lose order; phrases retain local context",
        "词袋只统计词语次数，不保存完整语序；二元或三元词组能保留部分相邻关系，但特征空间会快速增长。选择更长词组不自动带来更好的经济解释，应比较新增信息、稀疏程度和计算代价，而非只追求表示更复杂。",
        "Bag-of-words counts ignore order. Bigrams and trigrams retain some adjacent relationships at the cost of rapidly increasing dimensionality. Longer phrases do not automatically improve interpretation; assess the extra information, sparsity and computational cost."],
      ["§2.5", "搜索命中数不等于拿到了语料", "Search counts are not access to the corpus",
        "如果只能通过检索界面获取命中文章数，就未必能枚举全部词汇、计算文档频率或重新切分文章。作者区分这种访问方式与直接持有原始文本。保存查询条件很重要，但不能因此声称已重建完整语料。",
        "A search interface may return match counts without allowing vocabulary enumeration, document-frequency calculation or new document boundaries. The authors distinguish this from raw-text access. Preserving queries is useful but does not establish reconstruction of the corpus."],
      ["§3 · pp. 540–541", "词典分数与训练得到的模型分开", "Distinguish dictionary rules from fitted models",
        "预先指定词典和计数规则，可以把文本变成分数，但这个步骤本身未必包含统计估计。编辑建议保留词典版本、文本版本及发布时间，再讨论分数是否对应目标概念。文档版本教程帮助保存这些材料，不替代词典有效性检验。",
        "A predefined dictionary and counting rule can produce scores without fitting a statistical model. Editorial application: retain dictionary and text versions with publication times before asking whether the score measures the intended concept. The document-ledger tutorial preserves materials, not dictionary validity."],
    ]),
  "Measuring Geopolitical Risk": guide(
    "https://www.federalreserve.gov/econres/ifdp/files/ifdp1222r1.pdf",
    bi("2022年3月IFDP版", "March 2022 IFDP edition"),
    "Federal Reserve IFDP 1222r1 March 2022 cover, manuscript dated November 15 2021: section I.A–I.E read for definition, newspaper corpus, paired/proximity queries and frequency/components. Printed p. 5 visually checked. Later causal/firm regressions and current index releases not audited.",
    bi("导读使用封面为2022年3月、正文日期为2021年11月的IFDP版本。新闻覆盖既受事件影响，也受媒体关注影响；指数不是冲突概率，历史文本规则不能自动代表当前数据版本。", "The IFDP cover is dated March 2022 and the manuscript November 2021. Coverage reflects both events and media attention. The index is not a conflict probability, and historical text rules do not certify current releases."),
    { recipes: ["document-version-ledger"] }, [
      ["§I.A", "风险包括威胁，也包括已经发生的事件", "Risk here includes threats and realized events",
        "Caldara与Iacoviello将战争、恐怖活动及国际紧张局势的威胁、发生和升级纳入定义。这里的“风险”并非只指未来不确定性；在用它解释经济变化前，先要明确自己研究的是威胁预期还是实际冲击。",
        "Caldara and Iacoviello include threats, realizations and escalation of wars, terrorism and international tensions. Risk is not restricted to future uncertainty. An application should distinguish anticipation of threats from the consequences of events already occurring."],
      ["§I.B", "命中数必须带着分母看", "Keep the denominator with the hit count",
        "指数以涉及地缘事件的文章占全部刊发文章的比例为基础，而不是简单汇总关键词次数。报纸总发文量变化，会影响同样命中数量的含义。保存命中文章数的同时，必须保留分母、报纸身份和月份。",
        "The index is based on relevant articles as a share of all published articles, not raw keyword totals. Changes in publishing volume alter the meaning of identical hit counts. Preserve the denominator, newspaper identity and month alongside the relevant-article count."],
      ["§I.B; §I.D", "近期与历史序列使用不同报纸范围", "Recent and historical series use different coverage",
        "文中的近期序列从1985年开始，使用十家英文报纸；从1900年开始的历史序列使用三家报纸。它们在重叠期间相近，不代表原始样本相同。跨期连接时应保留系列身份，避免把覆盖变化误读成风险变化。",
        "The recent series begins in 1985 with ten English-language newspapers; the historical series begins in 1900 with three. Similarity during the overlap does not make the corpora identical. Preserve series identity when interpreting changes across coverage regimes."],
      ["§I.B", "词语组合和距离决定命中含义", "Word combinations and proximity define a match",
        "查询分成八类，组合主题词与威胁或行动词，多数类别还要求词语相距足够近。排除词帮助剔除电影、体育等误报。只搜索一个“战争”关键词，会改变测量对象；中文应用还需要另行设计词组和人工核对。",
        "Eight categories combine topic terms with threat or act terms, often requiring proximity. Exclusions reduce false positives such as films or sports. A single war keyword changes the measure; a Chinese application requires its own phrase design and manual validation."],
      ["§I.C; §I.E", "频率和分项回答不同问题", "Frequency and components answer different questions",
        "日频序列能定位短暂事件，月频序列则混合事件强度与持续时间。威胁分项和行动分项进一步拆开不同内容。一次短促尖峰与持续高位不能只用单日最高值比较，也不应把总指数当成纯粹的威胁指标。",
        "Daily values locate short episodes while monthly values combine intensity and persistence. Threat and act components separate different content. A short spike and sustained coverage are not equivalent, and the headline index should not be relabelled as threats alone."],
      ["§I.B–I.D", "媒体覆盖是一层测量，不是事件全集", "Media coverage is a measurement layer",
        "作者指出，一些缓慢展开且事后才被认识的事件可能不被指数充分捕捉。编辑建议保留检索版本、报纸覆盖和发布日期，不把未命中等同于没有风险。关联教程只展示文档版本记录，平台新闻入口不等于这套历史报纸语料。",
        "The paper notes that slowly unfolding events recognized mainly in hindsight may be missed. Editorial application: retain query versions, coverage and publication dates; no match does not mean no risk. The linked ledger demonstrates version records, not possession of this historical newspaper corpus."],
    ]),
  "Random Forests": guide(
    "https://www.stat.berkeley.edu/users/breiman/randomforest2001.pdf",
    bi("2001年1月作者稿", "January 2001 author manuscript"),
    "Berkeley author manuscript, January 2001: sections 1–4 and 10 read for tree voting, strength/correlation, bootstrap/OOB construction and permutation importance. Printed p. 8 visually checked. Journal citation retained; benchmark results and current software implementations not reproduced.",
    bi("导读依据2001年1月作者稿，正式期刊引用不变。树数增加时的收敛并不消除数据泄漏、重复调参或市场变化；算法重要性不是因果解释，本文也不是金融预测效果证明。", "The guide uses the January 2001 author manuscript, separately from the journal citation. Convergence as trees increase does not remove leakage, repeated tuning or distribution shifts. Variable importance is not causality, and this is not evidence of financial predictive performance."),
    {}, [
      ["§1.1", "随机化的是建树过程", "Randomize tree construction, then aggregate",
        "Breiman把森林定义为一组依赖随机向量的树分类器，每棵树对类别投票。随机化可以来自样本抽取或特征选择；最终输出来自多棵树的组合，而不是挑出训练表现最好的一棵树，也不是随机给出类别。",
        "Breiman defines a forest as tree classifiers built using random vectors, with each tree voting for a class. Randomness may enter sample or feature selection. The output aggregates trees rather than selecting the best training tree or choosing classes at random."],
      ["§2.1–2.2", "树强不强与彼此像不像同时重要", "Strength and dependence matter together",
        "论文用单棵分类器的强度与树之间的相关性解释泛化误差上界。若所有树重复相同错误，增加数量帮助有限；随机选择特征旨在降低依赖，同时保留分类能力。上界是理解机制的工具，并非每个数据集的精确误差公式。",
        "A generalization-error bound combines classifier strength and dependence between trees. Repeating the same errors limits the benefit of more trees. Random feature selection seeks diversity while retaining useful predictions; the bound is not an exact error formula for every dataset."],
      ["§3.1; §4", "自助抽样与节点特征抽取分开", "Separate bootstrap sampling from node feature selection",
        "作者实验中，每棵树的训练样本有放回抽取，同时在节点分裂时随机选择一组输入特征，树不剪枝。这是两种不同的随机化。记录随机种子之外，还需要说明抽样单位、特征数量与建树设置，才能解释复现差异。",
        "The experiments draw each training sample with replacement and randomly select candidate inputs at split nodes, growing unpruned trees. These are distinct sources of randomness. A seed alone is insufficient: record sampling units, feature counts and tree settings."],
      ["§3.1", "袋外预测只使用没见过该行的树", "Out-of-bag predictions exclude trees trained on that row",
        "一行数据的袋外预测，只聚合训练样本没有包含它的那些树的投票，再与真实标签比较。这不是拿全部树对训练集预测。因为每行的可用树集合不同，也应明确森林规模以及袋外误差的计算方式。",
        "For a row, out-of-bag prediction aggregates only trees whose bootstrap samples excluded it, then compares the result with its label. This differs from applying all trees to the training set. Each row uses a different subset of trees, so the aggregation convention matters."],
      ["§10", "打乱变量后变差，不等于因果作用", "Permutation importance is not a causal effect",
        "原文通过打乱袋外样本某个变量，观察误分类率变化来讨论重要性。相关变量可能携带相似信息，因此单独打乱的重要性与加入变量后的增量价值不同。这个诊断衡量模型依赖，不代表改变现实中的变量会造成对应结果。",
        "The manuscript permutes an input in out-of-bag rows and measures the change in misclassification. Correlated inputs can carry overlapping information, so permutation importance differs from incremental value after another variable is included. Model reliance is not an intervention's causal effect."],
      ["§2.1; §3.1", "袋外不等于时间外", "Out-of-bag is not out-of-time",
        "编辑应用边界：随机留出的行可能与训练行共享公司、日期或重叠的结果窗口。原文的袋外机制并未自动保证金融研究的时间隔离。用于带时间的数据时，还应保留标签可用日、分组和按先后顺序划分的独立测试。",
        "Editorial application: randomly held-out rows may share firms, dates or overlapping outcome windows with training rows. The paper's out-of-bag mechanism does not automatically provide temporal separation. Time-indexed work also needs label availability, grouping and an independent chronological test."],
    ]),
  "The Chinese Warrants Bubble": guide(
    "https://www.princeton.edu/~wxiong/papers/warrant.pdf",
    bi("2011年期刊版", "2011 journal article"),
    "Author-hosted AER journal article: introduction and section I, printed pp. 2723–2728, read for finite maturity, valuation bounds and historical trading rules; p. 2727 visually checked. Later panel/momentum tables not reproduced; no current-rule verification implied.",
    bi("论文研究2005—2008年的中国认沽权证，涉及特定历史制度和到期条款。不能把其规则当成当前股票或期权规则，也不能从活跃成交直接判定今天某个资产存在泡沫。", "The paper concerns Chinese put warrants in 2005–2008 under specific historical rules and expiry terms. Those rules are not current stock or option rules, and heavy trading alone does not diagnose a present-day bubble."),
    {}, [
      ["pp. 2723–2724", "有限到期日让估值问题更清楚", "Finite maturity sharpens the valuation question",
        "Xiong与Yu研究一批深度价外的认沽权证。与无限期存在的股票不同，权证有明确到期日和行权条款，标的股票价格又可公开观察。这些特征帮助约束基础价值，但不意味着任何衍生品的合理价值都能轻易确定。",
        "Xiong and Yu study deeply out-of-the-money put warrants. Unlike indefinitely lived shares, these instruments have specified expiry and exercise terms, with observable underlying stock prices. These features constrain valuation without making every derivative's fundamental value obvious."],
      ["p. 2724", "模型估值与制度上界互相对照", "Compare model values with institutional bounds",
        "作者不只依赖Black-Scholes估值，还用当时标的价格跌幅限制与行权价构造更少依赖模型的上界。不同方法共同帮助识别异常定价。若换了合约、行权比例或价格限制，必须重新推导边界，不能直接移用原文阈值。",
        "The authors supplement Black–Scholes values with bounds using historical stock-price limits and strike prices. Different approaches strengthen the valuation comparison. New contracts, exercise ratios or trading limits require re-deriving the bounds rather than copying thresholds."],
      ["p. 2727", "权证与股票的交易制度不同", "Warrants and stocks had different trading rules",
        "研究时期的权证允许T+0回转交易，而股票适用T+1；两者交易成本和价格限制也不同。比较换手率时必须带上这些制度差异，否则可能把交易机会更多造成的活跃，完全解释为投资者观点或信息的变化。",
        "During the study, warrants allowed T+0 resale while stocks used T+1; costs and price limits also differed. Turnover comparisons need these institutional details. More frequent trading opportunities should not be attributed entirely to changing beliefs or information."],
      ["pp. 2725, 2728", "价格偏离不意味着套利可执行", "A price deviation does not establish executable arbitrage",
        "论文将卖空约束与异质信念共同纳入解释。即便投资者认为价格过高，也未必能卖空获利；买方则可能期待转卖给后来更乐观的人。理解这种机制需保留可交易性约束，而不是只展示价格与估值之间的差额。",
        "The explanation combines short-sale constraints with heterogeneous beliefs. An investor who sees overvaluation may be unable to short it, while a buyer may anticipate resale to a more optimistic participant. A price–value gap alone omits the constraints on trading it."],
      ["pp. 2723–2725", "最后交易日与行权结束不是同一天", "Last trading and exercise expiry are different dates",
        "原文指出权证最后交易日之后仍有行权期间。交易剩余时间与行权剩余时间因此不是同一个字段。整理历史材料时，应分别保存最后交易日、行权窗口、行权价与比例，避免把最后成交价误当成到期支付。",
        "The article distinguishes the last trading day from the subsequent exercise period. Time left to trade is not time left to exercise. Preserve both dates, the strike and exercise ratio; the final market price is not the contract's terminal payoff."],
      ["pp. 2724–2726", "高换手是证据的一部分，不是独立判据", "High turnover is evidence, not a standalone test",
        "作者把高换手、波动、有限期限和价值边界放在一起分析，而不是仅凭成交热度定义泡沫。编辑建议同时保存权证和标的行情、流通数量及合约变化；普通A股日线不足以提供这些材料，成交量还需要配合当时可交易数量解释。",
        "The analysis combines turnover and volatility with finite maturity and valuation bounds. Editorial application: retain warrant and underlying prices, float and contract changes. Ordinary A-share daily bars do not supply that evidence, and volume needs the contemporaneous tradable quantity as context."],
    ]),
  "DeFi Risks and the Decentralisation Illusion": guide(
    "https://www.bis.org/publications/defi-risks-and-decentralisation-illusion",
    bi("2021年12月BIS专题", "December 2021 BIS feature"),
    "Official BIS December 6 2021 HTML feature: overview, building blocks, decentralisation illusion and vulnerabilities/spillover sections read. Chart values, Box A and current protocol or regulatory conditions not independently audited. Institutional analysis, not empirical replication.",
    bi("这是2021年BIS专题对当时DeFi结构的分析，不是当前协议排名、安全审计或监管结论。中心化交易所的资金费率和持仓量，不能替代链上抵押、治理和稳定币储备材料。", "This 2021 BIS feature analyzes the ecosystem of its time, not current protocol rankings, security or regulation. Centralized-exchange funding rates and open interest cannot substitute for on-chain collateral, governance and stablecoin reserve evidence."),
    {}, [
      ["Overview", "自动执行不等于没有中介职能", "Automation does not remove intermediation functions",
        "Aramonte、Huang与Schrimpf区分由智能合约执行的DeFi与依赖平台内部记录的CeFi。两者都可能提供交易或借贷，但记录位置、治理与交易执行方式不同。把所有加密活动合成一个指标，会掩盖这些关键差异。",
        "Aramonte, Huang and Schrimpf distinguish smart-contract DeFi from CeFi based on intermediaries' private records. Both can support trading or lending, but records, governance and execution differ. A single aggregate crypto indicator hides these distinctions."],
      ["Building blocks", "稳定币会把链上与链下连接起来", "Stablecoins link on-chain and off-chain arrangements",
        "专题把稳定币视为不同平台之间转移资金的重要工具，但区分链下管理储备与链上抵押机制。合约运行在链上，并不证明它依赖的资产、赎回安排或管理权也完全在链上；研究必须沿着这些依赖继续核对。",
        "Stablecoins facilitate transfers across platforms, but off-chain reserve management differs from on-chain collateral. A contract running on-chain does not establish that its backing assets, redemption arrangements or control are entirely on-chain. Follow those dependencies when evaluating the structure."],
      ["Decentralisation illusion", "代码无法预先写完所有治理选择", "Code cannot pre-specify every governance decision",
        "作者用算法不完备解释治理需求：新业务、升级和未预见情况仍需有人作决定。治理代币的投票权与实际持有集中度因此重要，不能只凭“去中心化”的标签判断谁能改变协议，或把地址数量等同于独立决策者数量。",
        "Algorithm incompleteness motivates governance: upgrades, new activities and unforeseen contingencies still require decisions. Voting rights and ownership concentration matter. A decentralized label does not identify who can change a protocol, and address counts do not count independent decision makers."],
      ["Vulnerabilities · Leverage", "超额抵押也可能形成杠杆链", "Overcollateralization can coexist with leverage chains",
        "即使单笔借款有超额抵押，借出的资金仍可能被用于另一笔抵押和借款，扩大整体暴露。抵押物下跌触发减仓，又可能加重价格下跌。只看某一个仓位的抵押率，会遗漏跨协议的重复使用和共同价格风险。",
        "A loan can be overcollateralized while its proceeds support further collateral and borrowing elsewhere. Falling collateral prices may prompt deleveraging that adds selling pressure. One position's collateral ratio misses reuse across protocols and common price exposure."],
      ["Vulnerabilities · Liquidity mismatches", "储备风险与赎回承诺要一起看", "Read reserve risk alongside redemption promises",
        "稳定币储备可能面临市场价格风险或变现困难，而持有人希望按面值退出。信任下降时，先赎回者优势可能促成挤兑。不同储备设计的脆弱性不相同，不能因为价格暂时稳定，就认为赎回权、流动性和偿付能力都已得到证明。",
        "Reserve assets may be volatile or hard to liquidate while holders expect par redemption. Declining trust can create incentives to exit first. Designs differ, and a temporarily stable market price does not prove redemption rights, liquidity or solvency."],
      ["Vulnerabilities · Spillovers", "研究应追踪依赖，而不只追踪币价", "Trace dependencies, not only token prices",
        "专题关注抵押链、稳定币资金连接和共同融资如何传播压力。编辑建议保存协议与版本、抵押资产、清算条件、储备披露及时间戳。交易所行情不能描述这些关系；相同代币价格也不意味着不同协议面对相同的清算与赎回约束。",
        "The feature examines collateral chains, stablecoin connections and funding links as transmission channels. Editorial application: preserve protocols and versions, collateral, liquidation terms, reserve disclosures and timestamps. Exchange prices cannot describe these relationships; identical token prices do not imply identical liquidation or redemption constraints."],
    ]),
};
