// Editorial comparisons, not inferred citations, agreement, or evidence rankings.
const pair = (left, right, zh, en) => ({ left, right, reason: { zh, en } });
export const researchConnections = [
  pair("A Simple Approximate Long-Memory Model of Realized Volatility", "Generalized Autoregressive Conditional Heteroskedasticity",
    "对照两种持续性表达：HAR使用不同期限的已实现波动率，GARCH递推潜在条件方差；先统一单位，再谈模型比较。",
    "Compare persistence through horizon-averaged realized volatility in HAR and recursive conditional variance in GARCH. Reconcile units before comparing models."),
  pair("A Simple Approximate Long-Memory Model of Realized Volatility", "Modeling and Forecasting Realized Volatility",
    "一篇提供多期限预测结构，另一篇建立已实现波动率的测量与预测背景；测量可靠与预测有效需要分别判断。",
    "Connect HAR's horizon structure with the measurement and forecasting of realized volatility. Reliable measurement and useful prediction are separate questions."),
  pair("A Heteroskedasticity-Consistent Covariance Matrix Estimator and a Direct Test for Heteroskedasticity", "A Simple, Positive Semi-Definite, Heteroskedasticity and Autocorrelation Consistent Covariance Matrix",
    "从独立观测下的异方差，扩展到时间相关；White协方差与HAC处理的误差结构不同，不能互换名称。",
    "Compare heteroskedasticity under independent observations with serial dependence. White covariance and HAC address different error structures."),
  pair("A Heteroskedasticity-Consistent Covariance Matrix Estimator and a Direct Test for Heteroskedasticity", "Robust Inference With Multiway Clustering",
    "比较逐个观测的稳健协方差与共享簇的协方差；增加聚类改变依赖假设，不会修复内生性。",
    "Compare observation-level robustness with shared-cluster covariance. Clustering changes dependence assumptions; it does not repair endogeneity."),
  pair("Robust Inference With Multiway Clustering", "Estimating Standard Errors in Finance Panel Data Sets: Comparing Approaches",
    "用金融面板中的公司与时间依赖理解双向聚类公式；大量记录与足够多的独立簇不是同一条件。",
    "Connect the two-way formula to firm and time dependence in finance panels. Many rows are not the same as many independent clusters."),
  pair("Comparing Predictive Accuracy", "Forecasting Using Principal Components From a Large Number of Predictors",
    "因子方法产生预测，损失差检验比较预测；能提取共同信息不等于已经证明样本外误差更小。",
    "Factor methods produce forecasts; loss-difference tests compare them. Extracting common information does not itself establish lower out-of-sample error."),
  pair("Comparing Predictive Accuracy", "The Probability of Backtest Overfitting",
    "区分两个固定预测的损失比较与多次尝试后挑选赢家；单次比较的显著性不能覆盖整个选择过程。",
    "Distinguish comparing two fixed forecasts from choosing a winner after many trials. Significance in one comparison does not assess the full selection process."),
  pair("Controlling the False Discovery Rate: A Practical and Powerful Approach to Multiple Testing", "The Probability of Backtest Overfitting",
    "FDR控制错误拒绝比例的期望，PBO研究被选赢家的样本外相对排名；两者不是同一种错误概率。",
    "FDR concerns the expected false-rejection proportion; PBO concerns a selected winner's out-of-sample rank. They are not the same error probability."),
  pair("Controlling the False Discovery Rate: A Practical and Powerful Approach to Multiple Testing", "Replicating Anomalies",
    "把多重检验的统计问题与变量、样本、权重的复现问题分开；调整p值不能弥补定义或数据不一致。",
    "Separate multiplicity from replication choices about variables, samples and weights. Adjusting p-values does not repair inconsistent definitions or data."),
  pair("Liquidity Risk and Expected Stock Returns", "Illiquidity and Stock Returns: Cross-Section and Time-Series Effects",
    "比较个股流动性水平与收益对市场流动性冲击的暴露；都讨论流动性，但指标和定价问题并不相同。",
    "Compare a stock's illiquidity level with return exposure to market-wide liquidity shocks. The measurements and pricing questions differ."),
  pair("One Security, Many Markets: Determining the Contributions to Price Discovery", "Measuring the Information Content of Stock Trades",
    "从交易携带的信息转到不同市场对共同价格的贡献；信息份额不是成交量份额，也不是永久价格影响本身。",
    "Connect information in trades with venue contributions to a common price. Information shares are neither volume shares nor permanent price impact itself."),
  pair("Does Algorithmic Trading Improve Liquidity?", "The Price Impact of Order Book Events",
    "比较算法活动的消息代理与订单簿事件的不平衡；前者的制度识别不能代替后者逐事件的数据定义。",
    "Compare a message-based proxy for algorithmic activity with order-book event imbalance. Institutional identification does not replace event-level measurement."),
  pair("The Equity Premium: A Puzzle", "Presidential Address: Discount Rates",
    "一篇追问平均股票溢价与无风险收益，另一篇梳理预期收益的变化；长期平均难题与时变折现率证据需要分开。",
    "One examines average equity and risk-free returns; the other surveys changing expected returns. A long-run average puzzle differs from time-varying discount-rate evidence."),
  pair("Time Series Momentum", "Returns to Buying Winners and Selling Losers: Implications for Stock Market Efficiency",
    "对照自身过去收益与同伴相对排名两种动量定义；期货合约和股票样本、收益基准及持有期也不相同。",
    "Compare own-past returns with peer-relative rankings. Futures and equity samples, return benchmarks and holding horizons also differ."),
  pair("Time Series Momentum", "Robust Inference With Multiway Clustering",
    "多合约研究共享同一市场时点，聚类论文帮助追问有效独立信息有多少；这里的联系是推断方法，不是收益验证。",
    "Multi-contract studies share market dates. Clustering helps question how much independent information exists; this is a link about inference, not return validation."),
  pair("Law, Finance, and Economic Growth in China", "Investor Protection and Corporate Governance",
    "对照跨国投资者保护框架与中国不同部门的关系融资证据；公开资本市场、非上市融资和企业增长不能直接等同。",
    "Compare cross-country protection with relationship finance across Chinese sectors. Public markets, unlisted financing and corporate growth are different outcomes."),
  pair("Law, Finance, and Economic Growth in China", "The Real Value of China's Stock Market",
    "一篇比较不同部门的融资与治理，另一篇研究股票价格的信息含量；上市公司价格不能代表所有企业融资。",
    "Compare sector-level finance and governance with information in stock prices. Listed-company prices do not represent every firm's access to finance."),
  pair("Investor Protection and Corporate Governance", "Corporate Governance and Equity Prices",
    "跨国法律保护与美国公司治理条款是不同分析层级；不要把国家制度差异直接解释成单家公司的估值效应。",
    "Cross-country legal protection and US firm-level governance provisions operate at different levels. Country differences do not directly identify one firm's valuation effect."),
  pair("The Capital Structure Puzzle", "Information Asymmetry, Corporate Disclosure, and the Capital Markets: A Review of the Empirical Disclosure Literature",
    "融资顺序讨论信息差如何影响证券发行，披露综述讨论信息如何传递；披露更多不自动消除融资中的选择偏差。",
    "Pecking order concerns information-sensitive issuance; disclosure research concerns communication. More disclosure does not automatically eliminate selection in financing."),
  pair("Information Asymmetry, Corporate Disclosure, and the Capital Markets: A Review of the Empirical Disclosure Literature", "Lazy Prices",
    "用披露动机与测量误差框架阅读文件变化研究；文本发生变化、信息增加与投资者已经理解，是三个不同问题。",
    "Use disclosure incentives and measurement limits to read document-change evidence. Changed text, more information and investor understanding are distinct questions."),
  pair("All That Glitters: The Effect of Attention and News on the Buying Behavior of Individual and Institutional Investors", "In Search of Attention",
    "对照新闻、成交与极端收益代理和主动搜索指标；关注不是情绪方向，两篇的投资者与数据覆盖也不同。",
    "Compare news, volume and extreme-return proxies with active search. Attention is not sentiment direction, and investor and data coverage differ."),
  pair("All That Glitters: The Effect of Attention and News on the Buying Behavior of Individual and Institutional Investors", "Lazy Prices",
    "比较什么进入投资者视野与企业文件变化怎样被处理；容易吸引注意的事件，不一定等于信息已经被充分理解。",
    "Compare what enters investors' consideration with how filing changes are processed. An attention-grabbing event does not establish that its information is understood."),
  pair("In Search of Attention", "Giving Content to Investor Sentiment: The Role of Media in the Stock Market",
    "搜索频率测主动信息需求，媒体语气测语言特征；即使两者相关，也不能把关注度直接解释为乐观或悲观。",
    "Search frequency measures active information demand; media tone measures language. Correlation does not turn attention into optimism or pessimism."),
  pair("Measuring the Effects of Monetary Policy: A Factor-Augmented Vector Autoregressive (FAVAR) Approach", "Forecasting Using Principal Components From a Large Number of Predictors",
    "两篇都压缩大量指标，但预测与结构冲击识别目的不同；提取因子之后，政策解释仍需要额外假设。",
    "Both compress many indicators, but forecasting differs from structural-shock identification. Policy interpretation still requires assumptions after factor extraction."),
  pair("Measuring the Effects of Monetary Policy: A Factor-Augmented Vector Autoregressive (FAVAR) Approach", "Discretion versus Policy Rules in Practice",
    "对照政策意外变化的响应与系统性利率反应规则；一条脉冲响应不能直接回答更换整套政策规则的后果。",
    "Compare responses to policy innovations with systematic interest-rate rules. An impulse response does not directly reveal the consequences of replacing an entire rule."),
  pair("Credit Spreads and Business Cycle Fluctuations", "Bond Risk Premia",
    "企业信用利差的模型残差与国债持有期超额收益不是同一种溢价；现金流基准、风险来源和预测对象均需区分。",
    "A corporate-spread residual differs from a Treasury holding-period excess return. Cash-flow benchmarks, risk sources and forecast targets must be distinguished."),
  pair("Credit Spreads and Business Cycle Fluctuations", "Robust Inference With Multiway Clustering",
    "信用利差模型面对同一企业多只债券与共同时间冲击；双向聚类有助于理解推断，却不证明残差是纯风险偏好。",
    "Bond-spread models share issuers and dates. Two-way clustering helps interpret inference but does not establish that the residual is pure risk appetite."),
  pair("Some Simple Economics of the Blockchain", "Bitcoin: Economics, Technology, and Governance",
    "用具体协议背景理解验证与网络组织成本；记录共识、链外事实真实性和治理责任仍然是不同层次。",
    "Connect protocol context with verification and network-organization costs. Ledger consensus, truthful offline facts and governance responsibility remain distinct layers."),
  pair("Some Simple Economics of the Blockchain", "DeFi Risks and the Decentralisation Illusion",
    "对照降低中介控制的经济设想与实际治理集中风险；去中心化架构不会自动消除协调、输入或控制权问题。",
    "Compare the economic case for reducing intermediary control with governance concentration risks. Decentralized architecture does not automatically remove coordination or control problems."),
];

export function comparisonReadings(paper, catalog, excludedIds = []) {
  const excluded = new Set([paper.id, ...excludedIds]);
  return researchConnections.flatMap(({ left, right, reason }) => {
    const title = paper.title === left ? right : paper.title === right ? left : null;
    const target = title && catalog.find(item => item.title === title);
    if (!target || excluded.has(target.id)) return [];
    excluded.add(target.id);
    return [{ paper: target, reason }];
  }).slice(0, 3);
}
