// Original commentary on the specified passages, not translations or replication claims.
const bi = (zh, en) => ({ zh, en });
const guide = (url, edition, evidenceScope, limits, rows) => ({
  reviewedAt: "2026-08-31", evidenceUrl: url, evidenceScope, limits, related: {},
  sections: rows.map(([location, zh, en, bodyZh, bodyEn]) => ({
    title: bi(zh, en), body: bi(bodyZh, bodyEn),
    reference: { url, label: bi(`${edition.zh} · ${location}`, `${edition.en} · ${location}`) },
  })),
});

export const researchSeventyGuides = {
  "A Simple Approximate Long-Memory Model of Realized Volatility": guide(
    "https://statmath.wu.ac.at/%7Ehauser/LVs/FinEtricsQF/References/Corsi2009JFinEtrics_LMmodelRealizedVola.pdf", bi("2009年期刊版", "2009 journal article"),
    "Journal article pp. 174–181, introduction and sections 2.1–2.3 inspected for the approximate-memory claim, square-root convention, aggregation and restricted autoregression. Empirical forecast tables and simulation code not replicated.",
    bi("HAR在有限尺度上模拟持续性，并不具有真正的渐近长记忆。本文使用的RV是平方收益和的平方根；不能与方差或对数方差模型直接混用。", "HAR approximates persistence over finite scales, without true asymptotic long memory. Here RV is the square root of summed squared returns, not variance or log variance."), [
      ["§1", "看起来持续，不一定是真正长记忆", "Persistent appearance is not true long memory",
        "Corsi提出一个有限维、易估计的模型，说明多个不同时间尺度的短记忆成分也能形成很缓慢的相关衰减。标题中的“近似”很重要：有限样本中观察到持续性，不能单凭这一点认定生成过程具有真正的渐近长记忆。",
        "Corsi shows how a few short-memory components operating at different horizons can mimic slowly decaying dependence. The word approximate matters: persistence observed over a finite sample does not establish genuine asymptotic long memory."],
      ["§2.1 · equation (3)", "先辨认RV的单位", "Identify the units of RV first",
        "这篇论文将一天内平方对数收益加总后开平方，称为已实现波动率；积分方差则是另一个量。相同缩写在其他文章中可能代表方差。对照模型、数据字段或误差指标时，必须先确认有没有开平方及年化处理。",
        "The paper calls the square root of summed intraday squared log returns realized volatility. Integrated variance is a different quantity. The same abbreviation can mean variance elsewhere, so transformations and annualization must be reconciled before comparing models."],
      ["§2.1 · equation (4)", "周成分是日波动率的平均", "The weekly component averages daily volatility",
        "文中的周成分取最近五个日波动率的平均，较长成分采用相应窗口的平均。它不是先累加五天平方收益再开平方，两种运算次序不能交换。作者明确指出这种聚合定义是为了便于解释受约束的自回归模型。",
        "The weekly component averages the latest five daily volatility observations. It is not the square root of five days of summed squared returns. These operations are not interchangeable; the averaging convention supports the restricted-autoregression interpretation."],
      ["§2.2", "不同期限是建模动机，不是账户识别", "Different horizons motivate the model, not investor identification",
        "模型用日、周、月三个期限描述参与者反应速度的差异，并借此解释波动在不同尺度之间的联系。但这些成分是统计构造，不是观测到的散户、基金或养老账户。估计出某个期限系数，不能反推出具体投资者的行为。",
        "Daily, weekly and monthly horizons motivate heterogeneous responses across participants. These components are statistical constructs, not observed retail, fund or pension accounts. A fitted horizon coefficient does not identify the behavior of a particular investor group."],
      ["§2.3 · equation (8)", "用少数系数约束一串滞后", "A few coefficients restrict many lags",
        "日、周、月成分同时进入下一期波动率回归，相当于对较长自回归中的滞后权重施加阶梯形限制。简洁来自这些限制，而不是没有使用历史信息。各成分共享部分日期，因此也不能把它们看成三个互相独立的实验。",
        "Regressing next-period volatility on daily, weekly and monthly components imposes step-shaped restrictions on a longer autoregression. Parsimony comes from those restrictions. The components share dates and must not be interpreted as three independent experiments."],
      ["§2.3 · footnote 10", "可观测波动率仍含测量误差", "Observed volatility still contains measurement error",
        "从潜在波动率转到已实现波动率的推导保留了测量误差。原文特别提醒，一致性本身不足以推出有限样本误差均值为零。高频数据的噪声处理和采样间隔因此仍然重要，模型结构简单并不会自动消除这些测量问题。",
        "The link from latent to realized volatility retains measurement error. The paper cautions that consistency alone does not imply a zero-mean finite-sample error. Sampling intervals and microstructure treatment remain important even when the forecasting equation is simple."],
    ]),
  "Generalized Autoregressive Conditional Heteroskedasticity": guide(
    "https://public.econ.duke.edu/~boller/Published_Papers/joe_86.pdf", bi("1986年期刊版", "1986 journal article"),
    "Author-hosted final article pp. 307–311 read for motivation, equations 1–8, Theorem 1 and higher-moment restrictions. Printed pp. 309–310 visually checked against imperfect PDF extraction. Likelihood proofs and inflation results not reproduced.",
    bi("GARCH描述条件方差，不预测价格方向。有限方差的平稳条件、严格平稳和高阶矩存在是不同问题，不能用同一个参数和阈值概括。", "GARCH models conditional variance, not price direction. Finite-variance stationarity, strict stationarity and existence of higher moments are distinct questions."), [
      ["§1–2", "让过去的方差参与今天的方差", "Past variance enters today's variance",
        "Bollerslev在ARCH的历史误差平方之外加入滞后条件方差，使持续性可以用较少参数表达。这里的条件方差依赖过去信息而变化；无条件方差则概括整个过程。两者并不要求每天相等，也不应被当成同一个数据字段。",
        "Bollerslev adds lagged conditional variance to ARCH's lagged squared innovations, allowing persistence with fewer parameters. Conditional variance changes with past information; unconditional variance summarizes the process. They are not interchangeable daily measurements."],
      ["§2 · equations (1)–(3)", "均值模型与方差模型各回答一个问题", "Mean and variance models answer different questions",
        "论文先定义条件均值为零的创新，再将它放入线性回归的误差项。方差方程描述创新的大小如何变化，并不决定回归均值的正负。即使方差预测准确，也不能据此宣称下一期价格上涨，或认定均值模型没有遗漏信息。",
        "The paper defines zero-conditional-mean innovations and then embeds them in a regression. The variance equation describes their changing magnitude, not the sign of the conditional mean. Accurate variance forecasts do not establish directional predictability or a correctly specified mean."],
      ["§2 · equation (2)", "阶数要对照原文定义", "Check which lags each order denotes",
        "原文以q表示误差平方的滞后阶数，以p表示条件方差的滞后阶数，并对常数与系数设置非负约束。不同软件可能采用不同参数命名。比较估计结果时，应先写清实际方程，而不是仅凭GARCH括号中的两个数字判断相同。",
        "In the original notation q counts squared-innovation lags and p counts conditional-variance lags, with positivity restrictions on the coefficients. Software naming can differ. Compare the actual equation rather than assuming two identically displayed orders specify the same model."],
      ["§2 · Theorem 1", "有限方差的条件不只是数值稳定", "Finite variance is more than numerical stability",
        "在文中设定下，两个滞后多项式的系数和小于一对应广义平稳及有限无条件方差。常数除以一减这个系数和，给出无条件方差。优化程序成功结束不能代替这一条件；靠近边界时，长期方差也会对参数变化很敏感。",
        "Under the stated model, the combined lag-coefficient sum below one gives wide-sense stationarity and finite unconditional variance. The latter divides the constant by one minus that sum. Optimizer convergence does not verify this property, especially near the boundary."],
      ["§2 · equations (4)–(7)", "简洁递推可以包含很长的历史", "A short recursion can retain a long history",
        "作者将方差递推改写为历史创新平方的无限滞后形式，也讨论平方过程的ARMA表示。因此，只有一阶条件方差滞后不意味着只记住昨天。它以受约束的权重传递过去冲击，但这种持续性不能自动等同于真正的长记忆过程。",
        "The recursion can be expanded into an infinite distributed lag of squared innovations, with a related ARMA representation for the squared process. One variance lag therefore does not mean only yesterday matters. This constrained persistence is not automatically true long memory."],
      ["§3 · Theorem 2", "二阶矩存在，不保证更高阶矩存在", "A second moment does not guarantee higher moments",
        "GARCH(1,1)的讨论进一步为不同阶矩给出额外条件。一个过程可以有有限方差，却没有研究者希望使用的更高阶矩。读到峰度、极端值或渐近检验时，需要核对相应矩条件，不能仅检查两个系数相加是否小于一。",
        "The GARCH(1,1) discussion places additional restrictions on higher moments. Finite variance alone does not guarantee the moments needed for kurtosis or a particular asymptotic test. Checking only the sum of two coefficients is insufficient for those uses."],
    ]),
  "A Heteroskedasticity-Consistent Covariance Matrix Estimator and a Direct Test for Heteroskedasticity": guide(
    "https://crooker.faculty.unlv.edu/econ441/econ_papers/White-Heteroskedasticity-Correction-1980.pdf", bi("1980年期刊版", "1980 journal article"),
    "Original journal scan, printed pp. 818–822 inspected for independent observations, orthogonality, residual-based covariance, asymptotic inference and the opening of the direct-test section. Appendix proofs and later finite-sample refinements not reviewed.",
    bi("异方差稳健标准误不能修复内生性、遗漏变量或序列相关。本文的独立观测与矩条件仍然重要，渐近推断也不等于小样本精确检验。", "Heteroskedasticity-robust standard errors do not repair endogeneity, omitted variables or serial dependence. Independence and moment conditions still matter, and asymptotic inference is not finite-sample exact."), [
      ["§2 · Assumption 1", "允许方差不同，仍要求观测独立", "Different variances do not remove independence requirements",
        "White允许观测不是同分布，但开头仍明确要求观测向量相互独立，并对解释变量与误差施加正交条件。这扩大了通常同方差模型的范围，却没有把任意时间相关或同组相关都包含进来；金融面板往往需要进一步处理依赖。",
        "White allows observations to be non-identically distributed, while retaining independence and regressor-error orthogonality. This broadens homoskedastic regression without covering arbitrary serial or within-group dependence. Financial panels often require additional treatment of dependence."],
      ["§2 · Lemmas 1–2", "系数一致性和标准误正确性分开", "Coefficient consistency and valid standard errors are separate",
        "论文先在条件下建立OLS系数的一致性，再讨论系数估计量的分布与协方差。异方差可能使常规标准误失真，却不必然使OLS系数失去一致性。反过来，换一个稳健协方差公式也不能让本来内生的解释变量变得外生。",
        "The paper establishes OLS consistency before deriving its distribution and covariance. Heteroskedasticity can invalidate conventional standard errors without making coefficients inconsistent. Conversely, replacing a covariance formula cannot make an endogenous regressor exogenous."],
      ["§2 · p. 820", "不必分别估出每个观测的真实方差", "Individual error variances need not be estimated separately",
        "关键是估计解释变量与误差平方构成的平均矩，而不是为每个观测估计一个独立的方差参数。论文用OLS残差平方代替不可观测的误差平方。这个构造依赖大样本条件，不是在声称一个残差就准确测出了该观测的风险。",
        "The key object is an average regressor-weighted error moment, not a separate variance parameter for every observation. Squared OLS residuals replace unobserved squared errors. This is an asymptotic construction, not a claim that one residual accurately measures individual risk."],
      ["§2 · Theorem 1", "三明治中间部分承担异方差信息", "The sandwich middle carries heteroskedasticity information",
        "协方差估计保留设计矩阵的两侧逆矩阵，中间改用残差平方加权的解释变量乘积。回归系数本身不因此改变，但置信区间和检验可能变化。稳健标准误也不是必然更大，其大小取决于误差变异与解释变量之间的实际关系。",
        "The covariance estimator keeps inverse design matrices on both sides and uses residual-weighted regressor products in the middle. Coefficients remain unchanged, while intervals and tests may change. Robust standard errors need not be larger; their size depends on the variance pattern."],
      ["§2 · pp. 820–821", "渐近正态不等于精确的小样本分布", "Asymptotic normality is not an exact small-sample law",
        "定理给出的推断建立在矩有界、矩阵可逆和样本增长等条件上，使用渐近正态或卡方结果。不能把软件显示的t样式统计量理解为自动具有经典小样本t分布。样本少或少数高杠杆观测主导时，近似误差尤其值得单独检查。",
        "Inference relies on moment bounds, nonsingular matrices and growing samples, yielding asymptotic normal or chi-squared results. A t-shaped statistic in software does not automatically have the classical exact t distribution. Small or highly leveraged samples warrant separate scrutiny."],
      ["§3 · pp. 821–822", "检验协方差设定，不是给模型颁发合格证", "A covariance diagnostic is not a certificate for the model",
        "直接检验的出发点是比较两种对相关矩的估计是否一致，从而识别常规协方差公式可能失效的情形。即使没有拒绝，也不证明均值模型、因果解释或所有误差假设都成立。诊断回答的范围比整篇研究是否可信要窄得多。",
        "The direct-test discussion compares moment estimates to diagnose failure of the conventional covariance formula. Non-rejection does not validate the mean model, causal interpretation or every error assumption. A covariance diagnostic answers a narrower question than overall research credibility."],
    ]),
  "Robust Inference With Multiway Clustering": guide(
    "https://cameron.econ.ucdavis.edu/research/CGM_twoway_ALL_13may2008.pdf", bi("2008年5月作者稿", "May 2008 author manuscript"),
    "Author manuscript pp. 1–10 read for non-nested dependence, two-way inclusion-exclusion, small-sample corrections and extension to multiple dimensions. The 2011 journal identity remains unchanged. Simulations and appendix proofs not reproduced.",
    bi("导读采用2008年作者稿。多维聚类不是允许所有观测任意相关；各维簇数、簇间依赖与有限样本协方差问题都影响推断。", "This guide uses the 2008 manuscript. Multiway clustering does not permit arbitrary dependence everywhere; cluster counts, between-cluster dependence and finite-sample covariance problems affect inference."), [
      ["§1", "公司相关与日期相关可能同时存在", "Firm and date dependence can coexist",
        "同一公司的多个日期可能共享未观测因素，同一天的不同公司也可能受到共同冲击。只按公司聚类会漏掉后一类联系，只按日期聚类又会漏掉前一类。论文针对这种彼此交叉而非完全嵌套的相关结构建立协方差估计。",
        "A firm's observations can share persistent influences, while different firms share shocks on the same date. Clustering only by firm misses the latter; clustering only by date misses the former. The paper addresses these crossed, non-nested dependence structures."],
      ["§1", "嵌套分组不必重复加一层", "Nested groups need not be counted twice",
        "作者区分交叉聚类与嵌套聚类：如果较小的簇完全属于较大的簇，在适当条件下按较大层级聚类即可。家庭属于州和公司跨越日期是不同结构。选择聚类维度应从观测如何共享冲击出发，而不是机械增加标准误选项。",
        "The paper distinguishes crossed from nested clustering. When smaller clusters are entirely contained within larger ones, clustering at the larger level can suffice under the relevant assumptions. Household-within-state and firm-by-date structures therefore require different reasoning."],
      ["§2.2 · equation (2.12)", "不共享任何簇的观测仍有限制", "Observations sharing no cluster remain restricted",
        "双向设定允许只要共享任一聚类维度的观测之间存在相关，却对两个维度都不共享的误差施加不相关条件。若不同公司、不同日期仍受持续共同冲击影响，这个条件可能失败。多维这个名字并不代表已经处理一切依赖。",
        "The two-way setup allows correlation when observations share either cluster dimension, but restricts errors sharing neither. Persistent common shocks across different firms and dates can violate that condition. Multiway does not mean that all possible dependence has been handled."],
      ["§2.2 · equations (2.14)–(2.15)", "两项相加，再减去交集", "Add both dimensions, subtract their intersection",
        "双向估计把第一维和第二维的聚类协方差相加，再减去两维交集的聚类协方差，避免重复计算共享两维的观测对。交集是公司与日期等标签的联合组合，不是任选一维。三个组成部分必须基于同一回归与同一有效样本。",
        "The two-way estimator adds covariance estimates clustered on each dimension, then subtracts clustering on their intersection to avoid double counting. The intersection consists of joint labels. All three components must refer to the same regression and effective sample."],
      ["§1; §2.2", "关键是簇数，不只是记录数", "Cluster counts matter, not just row counts",
        "理论要求各维的簇数增长，双向情形尤其关注较小的那个簇数。很多公司但只有少数年份，并不会因为总记录数很大就自动获得可靠推断。论文讨论有限样本修正，但这些修正不能把少数独立簇变成大量独立信息。",
        "The theory requires cluster counts to grow along each dimension, especially the smaller count in the two-way case. Many firms over very few years do not automatically provide reliable inference. Finite-sample adjustments cannot create independent information that is absent."],
      ["§2.2–2.3 · pp. 9–10", "多维修正也可能产生异常协方差", "Multiway correction can still produce problematic covariance",
        "由于包含减法，有限样本估计可能出现负的方差项；作者明确讨论这一问题。扩展到三维时，需要按交集层级交替加减，而不是只把三张矩阵相加。发现异常结果应检查簇结构与样本条件，不能静默取绝对值掩盖。",
        "Subtraction can produce negative variance estimates in finite samples, a problem explicitly discussed in the manuscript. Three dimensions require alternating inclusion-exclusion terms. Problematic results call for inspecting cluster structure and sample conditions, not silently taking absolute values."],
    ]),
  "Comparing Predictive Accuracy": guide(
    "https://www.ssc.wisc.edu/~bhansen/718/DieboldMariano1995.pdf", bi("1995年期刊版", "1995 journal article"),
    "Scanned journal pp. 254–255 visually read, including sections 1.1–1.3: loss-difference null, long-run variance, horizon-related dependence and the different sign-test null. OCR was insufficient; simulation tables and application not reviewed.",
    bi("检验针对两个预测序列在指定损失函数下的平均表现。未拒绝不等于等效，单次比较也不校正反复筛选；损失差的平稳性与相关结构仍需成立。", "The test compares two forecast sequences under a specified loss. Non-rejection is not equivalence, and one comparison does not correct repeated selection. Assumptions on loss-difference stationarity and dependence still apply."), [
      ["p. 254", "先定义什么叫预测得好", "Define what a good forecast means",
        "Diebold与Mariano允许损失函数不局限于平方误差，也不要求对正负误差对称。比较必须先确定预测对象、评价日期与损失含义。用绝对误差和平方误差得到不同排序并不矛盾，它们对大误差的权重本来就不同。",
        "Diebold and Mariano allow losses beyond squared error, including asymmetric losses. The forecast target, evaluation dates and meaning of loss must be specified first. Rankings under absolute and squared error can differ because they weight large mistakes differently."],
      ["p. 254 · §1.1", "检验对象是逐期损失差", "The object is a sequence of loss differences",
        "每个日期先计算两个预测的损失，再相减形成损失差序列。原假设是这个序列的总体均值为零，不是两个模型系数相同，也不是每一天都表现相同。损失相减的方向决定统计量正负，解释时必须与定义一致。",
        "For each date, subtract one forecast's loss from the other's. The null concerns a zero population mean of that difference, not identical model coefficients or identical performance every day. The subtraction convention determines the statistic's sign and interpretation."],
      ["§1.1", "平均差的误差要考虑时间相关", "Uncertainty in the average must account for dependence",
        "即使两种预测针对同一目标，其误差也可能同期相关，损失差还可能跨期相关。论文用包含自协方差的长期方差刻画平均损失差的不确定性。直接把逐期差值当作独立样本，可能低估或误估检验所需的标准误。",
        "Forecast errors can be contemporaneously correlated, and their loss differences can also be serially dependent. The long-run variance includes autocovariances when measuring uncertainty in the mean difference. Treating every date as independent can misstate the standard error."],
      ["§1.1 · p. 254", "预测期限不自动决定正确带宽", "The horizon does not automatically determine a valid bandwidth",
        "原文把k步最优预测误差至多具有k减一阶依赖作为有用基准，同时提醒实际应用可能违背它。核函数和截断滞后影响长期方差估计。不能仅凭预测期限就无条件截断所有相关，尤其当模型误设或信息更新不规则时。",
        "The paper treats dependence through k minus one lags for optimal k-step errors as a useful benchmark, not a universal fact. Kernel and truncation choices affect long-run variance estimation. Misspecification or irregular information updates can invalidate a purely horizon-based choice."],
      ["§1.2–1.3", "符号检验的零假设略有不同", "The sign test has a different null",
        "论文也讨论符号和符号秩检验，其中符号检验针对损失差的中位数为零。中位数差与均值差并非通常相同，甚至损失差的中位数也不等于两个损失中位数之差。只有增加相应分布条件，才能把这些检验解释为同一个问题。",
        "The sign test concerns the median of the loss difference, not generally its mean or the difference between two medians. The paper discusses conditions such as symmetry that connect these interpretations. Choosing another test can therefore change the question being answered."],
      ["§1.1–1.3", "一次比较不能证明普遍优越", "One comparison does not establish universal superiority",
        "渐近检验需要损失差满足平稳和短记忆等条件，有限样本检验也各有前提。编辑解读：一个评价窗口中的拒绝，只支持该样本设计与损失下的差异；未拒绝可能是证据不足，反复尝试很多预测后挑选赢家还引入另一个选择问题。",
        "The asymptotic result needs stationary, short-memory loss differences; finite-sample alternatives have their own assumptions. Editorial interpretation: rejection concerns the specified evaluation design. Non-rejection may reflect limited evidence, while selecting a winner after many trials creates another problem."],
    ]),
  "Controlling the False Discovery Rate: A Practical and Powerful Approach to Multiple Testing": guide(
    "https://www.dcscience.net/Benjamini-Hochberg-1995-FDR.pdf", bi("1995年期刊版", "1995 journal article"),
    "Original JRSS B article pp. 290–293 inspected for FDR versus FWER, the zero-rejection convention, predefined hypotheses, the step-up procedure and Theorem 1 independence conditions. Simulation tables and appendix proof not reproduced.",
    bi("FDR控制的是错误发现比例的期望，不是每次实验的错误比例保证，也不是单个发现为假的概率。1995年定理不能直接推广到任意相关的检验。", "FDR controls an expected false-discovery proportion, not a guarantee for each experiment or a posterior probability for one finding. The 1995 theorem does not cover arbitrary dependence."), [
      ["§2.1", "把错误放在所有发现中衡量", "Measure errors among the discoveries",
        "Benjamini与Hochberg将错误拒绝的数量除以全部拒绝的数量，并对这个随机比例取期望。如果没有任何拒绝，比例定义为零。分母不是全部检验数，因此FDR与每个检验的错误率是不同指标，不能仅因都写成百分比就混用。",
        "The authors take the expected proportion of false rejections among all rejections, defining the proportion as zero when none are rejected. The denominator is not the number of tests. FDR and per-test error rates remain different quantities even when both are percentages."],
      ["§2.1", "与至少错一次的概率不同", "It differs from the probability of any error",
        "家族错误率关注是否至少出现一次错误拒绝，FDR则关注错误在发现中所占的比例。全部原假设都为真时，两者一致；存在真实效应时，FDR通常允许更宽松的筛选。是否接受这种取舍，应由研究的决策后果决定。",
        "Familywise error concerns whether any false rejection occurs; FDR concerns the proportion among discoveries. They coincide when every null is true. When real effects exist, FDR can support less stringent screening, but the consequences of errors determine whether that tradeoff is suitable."],
      ["§2.3", "期望比例不是每批结果的保证", "An expected proportion is not a guarantee for each batch",
        "论文明确区分随机比例、比例的期望以及两个期望之比。FDR控制并不意味着某一次筛选中错误发现必然少于指定百分比，也不为每个入选结论分配一个可信概率。解读结果时，应保留这种重复实验层面的含义。",
        "The paper separates the random proportion, its expectation and ratios of expectations. FDR control does not guarantee that every realized batch stays below the target proportion, nor assign a credibility probability to each selected result. Its meaning is across repeated experiments."],
      ["§3.1 · procedure (1)", "排序后寻找最后一个满足条件的位置", "Find the last qualifying ordered p-value",
        "程序把m个p值从小到大排列，找到满足p值不超过i乘目标水平再除以m的最大位置k，并拒绝排序前k个假设。如果没有位置满足条件，就不拒绝任何假设。这里是逐步向上的整体规则，不是每个p值都与同一门槛比较。",
        "Order m p-values and find the largest rank k whose p-value is at most k times the target level divided by m; reject through that rank. If none qualifies, reject none. This step-up rule differs from applying one identical threshold to every test."],
      ["§3.1 · Theorem 1", "依赖结构决定定理能否使用", "Dependence determines whether the theorem applies",
        "原始定理在独立检验统计量的条件下给出控制结果，并进一步说明证明所需的独立性范围。金融研究中重叠样本与相似变量容易导致检验相关。不能因为软件能够运行BH程序，就推断任意相关结构下都得到原文保证。",
        "The original theorem establishes control under independence and clarifies the independence needed by its proof. Overlapping financial samples and similar predictors often create dependent tests. Software successfully running the BH procedure does not establish the guarantee under arbitrary dependence."],
      ["§2; §2.2", "检验家族要包括实际尝试的问题", "The testing family must reflect the questions actually tried",
        "文中把待检验的假设视为事先已知，并把筛选后的确认研究视为重要使用情境。编辑建议：记录所有尝试而不只记录最终入选者，否则m不再描述真实选择空间。控制多重检验也不替代新样本验证、经济解释或数据质量检查。",
        "The framework treats the hypotheses as specified in advance and discusses screening before confirmation. Editorial application: record attempted hypotheses, not only selected ones, so m represents the testing family. Multiplicity control does not replace new-sample validation or sound measurement."],
    ]),
  "Liquidity Risk and Expected Stock Returns": guide(
    "https://rodneywhitecenter.wharton.upenn.edu/wp-content/uploads/2014/03/0121.pdf", bi("2001年工作稿", "2001 working paper"),
    "Wharton-hosted working paper printed pp. 1–4, introduction and section 2.1 read for systematic liquidity risk, daily return reversals, signed dollar volume and sample exclusions. Journal citation retained separately; final-version return estimates not inferred from this draft.",
    bi("导读采用2001年稿，讨论市场流动性冲击的暴露，不等同于个股流动性差。日成交量签名只是订单流代理，不能替代真实主动买卖记录。", "This guide uses the 2001 draft and studies exposure to market liquidity shocks, not merely an illiquid stock. Signed daily volume proxies order flow; it is not observed trade direction."), [
      ["§1", "自身难交易与市场变差时一起跌不同", "Own illiquidity differs from exposure to market liquidity",
        "这篇研究问的是股票收益对全市场流动性变化的敏感度，是否与预期收益有关。一只股票平时成交困难，与它在整个市场流动性恶化时表现较差，是两件事。前者是自身交易特征，后者是收益对共同状态变化的暴露。",
        "The paper asks whether expected returns relate to sensitivity to market-wide liquidity changes. Being difficult to trade normally differs from performing poorly when market liquidity deteriorates. The former is a trading characteristic; the latter is exposure to a common state variable."],
      ["§1; §2.1", "用成交后的反向价格变化刻画一种流动性", "Use subsequent reversals to capture one dimension of liquidity",
        "作者关注成交压力造成的暂时价格变化：某方向的成交量越大，随后越容易出现反向收益，可能意味着提供流动性需要更大的价格补偿。这只刻画流动性的一个维度，不等于同时测量报价宽度、深度和完成大额交易所需时间。",
        "The measure focuses on temporary price pressure: stronger subsequent reversals after directional volume can indicate greater compensation for supplying liquidity. It captures one dimension, not quoted spreads, depth and the time needed to complete a large trade simultaneously."],
      ["§2.1 · equation (1)", "成交量符号来自超额收益", "Volume is signed using market-adjusted returns",
        "月内回归把下一日相对市场的收益作为被解释变量，并加入当日收益及带符号的美元成交量。符号取自当日股票相对市场的收益，而非逐笔成交的主动方向。把普通收益、超额收益或真实订单流混换，会改变指标定义。",
        "Within each month, next-day market-adjusted returns are regressed on current returns and signed dollar volume. The sign comes from the stock's return relative to the market, not observed trade initiation. Substituting raw returns or actual order flow changes the definition."],
      ["§2.1 · p. 4", "样本筛选与成交额单位会改变估计", "Filters and volume units affect the estimate",
        "工作稿要求月内有足够连续观测，并设置股价区间，成交额以百万美元计量。样本还区分不同交易所的成交量统计方式。不同货币单位、停牌处理或数据缺口会影响系数大小，不能直接把数值搬到另一市场作横向排名。",
        "The draft requires sufficient consecutive observations, applies price filters and measures volume in millions of dollars. It also distinguishes exchange volume conventions. Currency units, suspensions and missing observations affect coefficients, preventing mechanical comparisons across markets."],
      ["§1 · pp. 1–2", "市场指标与流动性beta有两层估计", "The market measure and liquidity beta are separate estimates",
        "研究先从股票层面的测量构造市场流动性，再研究收益对其创新的敏感度。个股的反转系数不是最终的流动性beta，后者也不是个股流动性本身的波动率。阅读相关实证时，应识别每个变量来自哪一层估计。",
        "The study first constructs market liquidity from stock-level measurements, then studies return sensitivity to its innovations. A stock's reversal coefficient is not its liquidity beta, and that beta is not the volatility of its own liquidity. Track each estimation layer separately."],
      ["§1; §2.1", "历史定价证据不等于现成因子数据", "Historical pricing evidence is not a ready-made factor dataset",
        "工作稿中的定价结论依赖特定美国样本、市场基准和流动性构造。编辑解读：只有日收益和成交额，还不足以声称已经复制原文因子或风险溢价。版本差异、跨股票聚合与后续暴露估计都需要单独核对。",
        "The draft's pricing evidence depends on its US sample, market benchmark and liquidity construction. Editorial interpretation: daily returns and volume alone do not establish replication of the factor or premium. Version differences, aggregation and subsequent exposure estimation remain separate tasks."],
    ]),
  "One Security, Many Markets: Determining the Contributions to Price Discovery": guide(
    "https://www.bauer.uh.edu/rsusmel/phd/hasbrouck95.pdf", bi("1995年期刊版", "1995 journal article"),
    "Journal scan printed pp. 1176–1179 and 1182–1183 read for the common efficient price, cointegration, lead-lag misspecification and information-share bounds. Historical venue shares and empirical estimation were not reproduced.",
    bi("信息份额分解的是共同价格创新的方差，不是成交量份额。共同趋势、采样频率和同期相关影响解释；相关创新下通常应报告界限而非唯一排名。", "Information shares allocate common-price innovation variance, not trading volume. Common trends, sampling and contemporaneous correlation matter; correlated innovations generally require bounds rather than a unique ranking."), [
      ["pp. 1176–1177", "先说明为什么这些价格属于同一对象", "Explain why the prices represent one economic object",
        "Hasbrouck将同一证券理解得较宽，可以包含经套利关系转换后可比较的相关价格。但共同经济对象是模型前提，不是看到相关性就成立。现货、期货或不同场所报价需要先处理单位、合约与转换关系，再讨论共同价格。",
        "Hasbrouck allows economically linked prices, including transformed derivative prices, to represent one security. That shared object is a modeling premise, not a consequence of high correlation alone. Units, contracts and conversion relationships must be reconciled before imposing a common price."],
      ["§I", "价格可以各自游走，差异却有限", "Prices can wander while their difference remains bounded",
        "协整描述各价格可能非平稳，但某些价格差组合仍然平稳。论文用一个市场先变、另一个延迟反应的例子解释共同趋势与暂时偏离。共同趋势并不要求所有报价每秒一致，也不意味着每次偏离都能无成本套利。",
        "Cointegration allows individual prices to be nonstationary while a combination of their differences remains stationary. A delayed-response example separates a common trend from temporary deviations. This does not require identical quotes every second or costless arbitrage whenever prices differ."],
      ["§I · pp. 1178–1179", "只回归收益的领先滞后可能遗漏约束", "Return lead-lag regressions can omit the long-run constraint",
        "作者展示，忽略协整关系的有限滞后收益回归可能看起来系数合理，却误描绘信息传递所需时间。误差修正表示把价格偏离与短期变化放在同一个框架中。一个漂亮的领先滞后图并不足以证明某市场真正贡献了新信息。",
        "A finite-lag return regression that ignores cointegration can look well behaved while misrepresenting transmission delays. Error correction combines price discrepancies and short-run changes. An appealing lead-lag chart alone does not establish which market contributes new information."],
      ["§III · p. 1182", "信息份额的分母是共同创新方差", "The denominator is common innovation variance",
        "信息份额衡量某市场创新对共同随机游走价格创新方差的贡献比例。成交额更大、报价更多或先成交，都不直接等于这一统计量更大。它回答的是特定模型中永久价格变化的来源，而不是哪个市场整体最好或最容易交易。",
        "An information share measures a market innovation's contribution to the variance of the common random-walk innovation. Larger turnover, more quotes or earlier trades do not directly determine it. It concerns permanent price variation within a model, not overall venue quality."],
      ["§III · p. 1183", "同时变化会使唯一分解变困难", "Simultaneous changes complicate unique attribution",
        "当不同市场创新同期相关时，方差不能简单独立相加。论文通过改变Cholesky分解中的排序，为各市场计算信息份额的上界与下界。排序会影响归属，因此只挑一个顺序给出精确百分比，可能隐藏识别上的不确定性。",
        "Contemporaneously correlated innovations prevent a simple independent variance allocation. Reordering the Cholesky factorization yields upper and lower information-share bounds. Reporting one precise percentage from a chosen ordering can conceal this identification uncertainty."],
      ["§III · p. 1183", "更细采样有帮助，但不能消除全部相关", "Finer sampling helps but does not eliminate correlation",
        "较粗时间间隔可能把先后发生的报价更新合并为同一时点变化。作者因而使用很细的采样，但也明确说缩短间隔不能彻底消除同期相关。时间戳精度、市场时钟和同步方式，应与信息份额结果一起解释，不能只保留最终排名。",
        "Coarse intervals can collapse sequential quote updates into apparently simultaneous changes. The paper uses fine sampling but notes that shorter intervals do not eliminate contemporaneous correlation. Timestamp precision and synchronization belong alongside the reported shares, not behind a simple ranking."],
    ]),
  "Does Algorithmic Trading Improve Liquidity?": guide(
    "https://faculty.haas.berkeley.edu/hender/Algo.pdf", bi("2011年期刊版", "2011 journal article"),
    "Author-hosted final article printed pp. 3–8 read for competing mechanisms, NYSE autoquote instrument, balanced sample, normalized message-traffic proxy and liquidity definitions. Instrument validity and all empirical tables were not independently replicated.",
    bi("研究基于2001–2005年NYSE及自动报价制度变化。消息流量是算法活动代理，不是算法账户数量；大盘股的结果不能直接推广到所有证券或今日市场。", "The study concerns NYSE trading in 2001–2005 and autoquote introduction. Message traffic proxies algorithmic activity, not account counts; large-stock findings do not automatically generalize to every security or today's markets."), [
      ["pp. 3–4", "算法可能供给流动性，也可能消耗它", "Algorithms can supply or demand liquidity",
        "作者没有预先把算法等同于更好市场。算法可能降低提供报价的成本，也可能更快利用过时报价，使流动性提供者承担更大风险。因此，技术使用增加与价差下降同时发生，不足以单独说明是哪一种机制起作用。",
        "Algorithms may lower quoting costs or exploit stale quotes more effectively, increasing the risk faced by liquidity suppliers. The paper therefore considers competing mechanisms. Technology adoption and narrowing spreads occurring together do not by themselves identify which mechanism operates."],
      ["§II.A", "电子消息不等于直接识别算法", "Electronic messages do not directly identify algorithms",
        "研究无法逐笔知道订单是否由计算机生成，于是用电子提交、撤单和成交报告的消息流量构造代理。这个代理也会随着同一算法更频繁撤单而变化，不只是反映采用算法的参与者增加。消息数量不能被读成算法用户数量。",
        "The study cannot directly label every order as algorithm-generated, so it uses submissions, cancellations and trade reports. The proxy can rise when existing algorithms cancel more frequently, not only when more participants adopt them. Message counts are not algorithm-user counts."],
      ["§II.A–B", "活动强度与流动性结果分开测量", "Measure activity intensity separately from liquidity outcomes",
        "消息指标按成交额归一，目的是避免把总体交易增长全当成算法增强。流动性则用报价价差、有效价差、已实现价差与价格影响等不同指标衡量。这些结果涉及不同时间基准，不能把一个更窄的报价价差解释为所有成本都下降。",
        "Message activity is normalized by trading volume to distinguish intensity from general market growth. Liquidity outcomes include quoted, effective and realized spreads and price impact. Their reference times differ; narrower quoted spreads do not imply that every cost measure declines."],
      ["p. 3", "利用分批自动报价，而非仅比较前后趋势", "Use staggered autoquote introduction, not just parallel trends",
        "NYSE在不同股票上分批引入自动报价，为作者提供算法活动变化的工具变量。识别依赖这个制度事件及相关假设，不是简单把几年间的算法增长与流动性改善相连。编辑解读：制度变化还可能有其他影响，因此需要回到原文检验识别论证。",
        "Staggered NYSE autoquote introduction supplies an instrument for algorithmic activity. Identification depends on that institutional event and its assumptions, not merely co-moving trends. Editorial interpretation: other effects of the change make the paper's identification argument essential to assess."],
      ["§II · pp. 5–6", "平衡面板便于比较，也带来样本边界", "A balanced panel aids comparison but limits the sample",
        "样本保留整个研究期持续存在的股票，以减少样本组成变化；作者也指出这可能引入存续偏差。研究还限制股价范围，并对极端观测处理。阅读时间趋势时，应同时看到这些选择，不能把结果视为所有进入与退出公司的完整经历。",
        "Stocks present throughout the study form a balanced panel, reducing composition changes but potentially introducing survivorship effects. Price filters and treatment of extremes also shape the sample. Reported trends are not a complete history of every entering or disappearing company."],
      ["pp. 3–4", "交易成本改善与供给者收入可以并存", "Lower trading costs and supplier revenues can move differently",
        "论文报告大盘股流动性改善，同时讨论流动性提供者暂时获得更多收益的现象。更低有效价差不必意味着供给者竞争已完全消除租金。对小盘股没有显著结果也可能与工具变量较弱有关，不能据此证明算法在小盘股上完全无影响。",
        "The paper discusses improved large-stock liquidity alongside temporarily higher supplier revenues. Lower effective spreads need not imply that competition has eliminated rents. Insignificant small-stock findings may also reflect a weaker instrument, rather than proof of no effect."],
    ]),
  "The Equity Premium: A Puzzle": guide(
    "https://academicwebpages.com/preview/mehra/pdf/The%20Equity%20Premium%20A%20Puzzle.pdf", bi("1985年期刊版", "1985 journal article"),
    "Original journal PDF introduction and printed pp. 150–151, 154 inspected for the historical question, representative-agent exchange economy, marginal-utility pricing and consumption calibration. Numerical equilibrium solutions and alternative-model claims not independently reproduced.",
    bi("这是一项针对特定偏好与交换经济模型的历史定量检验，不是未来股票溢价预测。结论同时涉及股票和无风险收益，不能仅用单一收益均值解释。", "This is a historical quantitative exercise for a specified exchange economy and preferences, not a forecast of future equity premia. It jointly concerns equity and risk-free returns."), [
      ["§1", "难题是能否同时解释两种收益", "The puzzle is explaining two returns together",
        "Mehra与Prescott比较美国长期股票收益与短期近乎无风险债务收益，问标准模型能否同时产生这种差距和较低无风险利率。它不是简单问股票是否比债券波动大，也不是看到历史溢价就断言未来必定获得同样补偿。",
        "Mehra and Prescott ask whether a standard model can jointly explain the historical equity premium and low risk-free return. The question goes beyond whether stocks fluctuate more than bills. A historical premium is not a promise of the same compensation in the future."],
      ["§3 · p. 150", "代表性家庭与交换经济限定了问题", "The representative household and exchange economy delimit the question",
        "模型采用代表性家庭、不可储存的消费品与随机禀赋增长，股票索取这项产出的支付。这样的结构便于推导均衡价格，但并不包含所有真实家庭的收入、借贷限制与资产配置差异。对该模型的困难不能直接写成对所有经济理论的否定。",
        "A representative household values consumption in an exchange economy with stochastic endowment growth, and equity claims the output. This tractable structure does not contain every household's income or borrowing constraints. Its difficulty is not a rejection of all economic models."],
      ["§3 · equation (2)", "风险厌恶与跨期替代在这里相联系", "Risk aversion and intertemporal substitution are linked here",
        "原文使用时间可分的恒定相对风险厌恶效用。效用曲率既影响对风险的厌恶，也影响不同时期消费之间的权衡。提高曲率来解释股票溢价，同时会影响模型中的无风险利率；不能只调整一个收益结果而忽略另一个结果。",
        "Time-separable constant-relative-risk-aversion utility links attitudes toward risk and consumption across dates. Increasing curvature to explain the equity premium also changes the implied risk-free rate. One return cannot be adjusted in isolation from the other within this specification."],
      ["§3 · equation (5)", "支付发生在哪种消费状态更重要", "The consumption state of a payoff matters",
        "资产支付通过未来与当前边际效用的比率折现，因而支付与消费状态的共同变化进入定价。单独列出资产自身标准差不能完整表达这里的风险。相同大小的支付，若出现在消费更稀缺的状态，对家庭的价值会不同。",
        "Payoffs are discounted using the ratio of future to current marginal utility, making their co-movement with consumption relevant. Standalone return volatility does not fully describe risk in this model. A payoff is valued differently when it arrives in a consumption-scarce state."],
      ["§4 · p. 154", "校准消费过程，再考察模型能产生什么", "Calibrate consumption, then examine the model's implications",
        "论文用两状态增长过程匹配历史人均消费增长的均值、波动和一阶相关，再研究偏好参数下的收益。作者将其描述为定量理论练习，而不是为了找出最佳参数估计。理解这个顺序，有助于区分模型限制与统计拟合优劣。",
        "A two-state growth process matches historical consumption-growth moments before the authors examine implied returns across preference parameters. This is a quantitative theoretical exercise, not simply a search for best-fitting estimates. The distinction separates model restrictions from statistical fit."],
      ["§1; §3–4", "保留历史样本与模型边界", "Keep the historical and model boundaries visible",
        "这篇文章的重要性在于明确提出一组模型与历史事实之间的张力，而不是提供今天的合理股票回报率。编辑解读：比较后续习惯形成、长期风险或市场摩擦研究时，应先看改变了哪个假设，再看是否同时解释原来的两个收益对象。",
        "The contribution identifies tension between a model class and historical observations, not today's appropriate equity return. Editorial reading: when comparing later work on habits, long-run risk or frictions, ask which assumption changes and whether both original return objects are explained."],
    ]),
};
