// Bounded source-reading evidence is maintained here, never rendered as article prose.
const guide = (url, year, evidenceScope, limits, rows) => ({
  reviewedAt: "2026-08-30", evidenceUrl: url, evidenceScope, limits,
  sections: rows.map(([pages, zh, en, bodyZh, bodyEn]) => ({
    title: { zh, en }, body: { zh: bodyZh, en: bodyEn },
    reference: { url, label: { zh: `原文定位：${year}年期刊版，第${pages}页`, en: `Source: ${year} journal article, pp. ${pages}` } },
  })),
});

export const researchCorporateGuides = {
  "Detecting Earnings Management": guide(
    "https://doi.org/10.2308/tar-9505096112", 1995,
    "1995 journal scan at http://sseriga.free.fr/course/uploads/FA%20-%20PM/Dechow_et_al_1995.pdf: pp. 193–198 extracted; pp. 199–201 visually read for modified Jones and experimental design. The public locator uses the canonical DOI because the scanned copy is HTTP-only. Later result tables were not independently re-estimated; no full-text redistribution.",
    { zh: "异常应计是模型估计量，不是违规认定。本文比较的是特定样本与模拟条件下的检验表现；业绩、收入确认和模型误差都可能影响推断。", en: "Abnormal accruals are model estimates, not findings of misconduct. Test performance depends on the sampled firms and simulated mechanisms; performance, revenue recognition and measurement error affect inference." },
    [
      ["193–195", "先问模型能识别什么", "Start with what the test can identify",
        "论文比较多种应计模型的检验表现，而不是给每家公司贴上操纵标签。检验既可能把没有发生的系统性管理误判为存在，也可能漏掉真实变化。阅读结果时，应同时关注误报与检出能力，不能把一次显著性检验当成独立的事实认定。",
        "The paper compares accrual-based tests, not company misconduct labels. A test may reject a true null or miss an actual intervention. Its rejection rate and detection power answer different questions; statistical significance alone does not establish the underlying conduct."],
      ["195–198", "残差里不只有管理裁量", "A residual contains more than discretion",
        "可操纵应计无法直接观察，需要从总应计中估计正常部分。如果遗漏的经营因素与研究事件相关，剩余项也会带上这种相关性。反过来，过强的控制可能吸收本来想寻找的变化。因此残差大小必须结合模型设定理解，而不是直接解释为操纵金额。",
        "Discretionary accruals are unobserved. Estimating normal accruals leaves measurement error alongside the intended component. Omitted operating factors correlated with an event can bias inference, while controls may absorb the intervention being studied. The residual is not a directly observed manipulation amount."],
      ["198–199", "修正发生在事件期的收入变量", "The modification changes event-period revenue",
        "原Jones模型用收入变化和固定资产等变量解释正常应计。修正版在事件期从收入变化中扣除应收账款变化，两项均按上期总资产缩放。参数仍从原Jones估计期模型取得；不要把这一版本默认为每个年度都重新估计的行业横截面模型。",
        "The original Jones model uses revenue changes and property, plant and equipment. Its modified version subtracts the change in receivables from event-period revenue changes, both scaled by lagged assets. Parameters still come from the original estimation-period model, not an automatically substituted annual industry cross-section."],
      ["199", "赊销假设需要单独审视", "Examine the credit-sales assumption",
        "这一修正针对收入确认裁量被原模型当成正常收入变化吸收的问题，但隐含假设是事件期赊销变化来自盈余管理。实际企业也可能因客户结构、收款周期或业务增长增加应收款。理解假设的强度，比机械套用“修正后更准确”更重要。",
        "The adjustment targets revenue discretion absorbed as normal activity by the original model. It assumes event-period credit-sales changes arise from earnings management. Ordinary changes in customers, collections or growth may also affect receivables, so the assumption needs scrutiny rather than a blanket claim of improved accuracy."],
      ["200–201", "不同样本检验不同问题", "Different samples test different weaknesses",
        "作者区分随机公司年度、极端业绩样本、人工加入应计变化的样本和监管执法样本。随机抽样主要考察一般情况下的检验设定，极端业绩揭示混淆风险；人工样本的解释依赖操纵方式与转回时点，执法样本也不是所有企业的随机代表。",
        "Random firm-years, extreme-performance samples, injected accrual changes and enforcement cases serve different purposes. Random sampling probes general specification; extreme performance probes confounding. Simulation depends on the intervention and reversal timing, while enforcement cases are not a random cross-section of all firms."],
      ["193–195, 201", "把显著性放回经营背景", "Return significance to its operating context",
        "论文提醒研究者，较小幅度的管理可能难以检出，极端业绩下的拒绝率也可能偏离名义水平。实务阅读应先核对经营变化、事件选择与可比期间，再理解异常应计。未检出不能证明没有管理，检出也不能单凭模型断言是谁、为何改变了报表。",
        "Modest interventions may be difficult to detect, and rejection rates can behave differently under extreme performance. Interpret estimates alongside operating changes, event selection and comparable periods. Failure to reject does not establish absence, and rejection does not by itself identify an actor or motive."],
    ]),
  "Earnings, Book Values, and Dividends in Equity Valuation": guide(
    "https://users.metu.edu.tr/mugan/Ohlson%201995%20earnings%20bv%20div%20in%20eq%20valuation.pdf", 1995,
    "METU-hosted scan of the 1995 Contemporary Accounting Research article. Printed pp. 664–668 visually inspected for the valuation overview, clean surplus, residual-income identity, terminal condition and information dynamics. Publisher abstract checked for identity, with no claim beyond that abstract and the inspected pages. Later proofs and empirical application were not verified.",
    { zh: "这是在净盈余关系、折现与信息动态假设下建立的理论基准，不是由当期财报直接得出的目标价。剩余收益中的“异常”也不表示会计操纵。", en: "This is a theoretical benchmark with clean-surplus, discounting and information-dynamics assumptions, not a target price read directly from current statements. Abnormal earnings here do not mean accounting manipulation." },
    [
      ["664–666", "盈利与账面价值各自提供什么", "What earnings and book value contribute",
        "Ohlson把当期盈利、账面权益和股息放入同一估值框架。盈利是期间流量，账面权益是某一时点的存量，不能只凭它们和价格都有关就随意相加。模型通过明确的会计关系与未来预期，说明这几项变量为什么能够共同进入价值表达式。",
        "Ohlson connects earnings, book equity and dividends in one valuation framework. Earnings are a period flow and book equity a dated stock; their association with prices does not justify arbitrary addition. Accounting restrictions and expectations explain how they enter the same expression."],
      ["666", "净盈余关系不是只减现金股息", "Clean surplus uses net distributions",
        "期末账面权益等于期初账面权益加当期盈利，再减去净分配。这里的股息已经扣除股东投入，因此可以为负。阅读真实报表时，应先核对权益变动的范围；若有绕过损益的项目，不能默认为原模型的净盈余关系自然成立。",
        "Closing book equity equals opening book equity plus earnings less net distributions. Dividends are net of capital contributions and may be negative. Applying the relation requires reconciling the scope of equity movements; items bypassing earnings cannot simply be ignored."],
      ["667", "剩余收益先扣期初资本占用", "Residual earnings charge beginning capital",
        "异常或剩余收益，是当期盈利扣除期初账面权益所对应的资本占用成本。使用期末权益会把同一期盈利与分配混入基数。在这一语境中，“异常”指超过基准资本回报的部分，不是应计模型中的异常残差，更不是不当会计行为的同义词。",
        "Residual or abnormal earnings subtract a capital charge on beginning book equity from period earnings. Using closing equity mixes current earnings and distributions into the base. Here abnormal means above the capital-return benchmark, not an accrual-model residual or evidence of improper accounting."],
      ["667", "账面价值加的是未来预期的现值", "Book value adds discounted expectations",
        "在净盈余关系与终端条件成立时，股权价值可写为当前账面权益加未来预期剩余收益的现值。终端条件要求遥远未来的折现账面价值趋于零。这种等价转换没有消除预测任务，也不允许直接用后来实现的盈利替代当时能够形成的预期。",
        "Under clean surplus and a vanishing discounted terminal book value, equity value equals current book equity plus discounted expected residual earnings. The identity reorganizes valuation; it does not remove forecasting or permit later realized earnings to stand in for expectations available at the valuation date."],
      ["664, 668", "报表之外的信息并未消失", "Information beyond the statements remains",
        "模型允许尚未反映在当期盈利中的其他信息影响未来剩余收益，并用特定动态方程描述其演变。该变量不是随意加入的神秘分数；它与持续性参数一起约束预测路径。若将其设为零，应明确这是一项简化，而不是证明财报已包含全部信息。",
        "Other information can affect future residual earnings before appearing in current accounting numbers. Specified dynamics and persistence parameters constrain its role. Setting that information to zero is a simplifying restriction, not evidence that financial statements already contain everything relevant."],
      ["664–666, 668", "理论基准与估计工作分开", "Separate the benchmark from estimation",
        "这里先以风险中性、共同预期及固定利率结构建立模型，信息持续性参数也被视为已知。实际比较企业仍要处理盈利预测、资本成本、会计口径和可得时点。套入当期数字得到一个结果，并不等于这些假设已经被样本支持。",
        "The initial model uses risk neutrality, shared beliefs, a fixed interest-rate structure and known persistence parameters. Empirical comparison still needs forecasts, discount rates, consistent accounting and information dates. Substituting current figures does not validate those assumptions."],
    ]),
  "Financial Ratios, Discriminant Analysis and the Prediction of Corporate Bankruptcy": guide(
    "https://calctopia.com/papers/Altman1968.pdf", 1968,
    "Matching 1968 Journal of Finance scan: printed pp. 592–596 read for discriminant construction, sample selection and five ratios; p. 594 visually checked. Printed pp. 602 and 609 read for loss-making comparison firms and sample limits. Publisher identity confirmed; model outputs were not replicated.",
    { zh: "原研究以特定时期、可取得完整资料的制造业企业为样本。判别分数不是经过校准的破产概率，也不能不经重新检验直接套用到当代A股、金融企业或其他行业。", en: "The original sample covers manufacturers with sufficient historical data. A discriminant score is not a calibrated bankruptcy probability and cannot be transferred to present-day A-shares, financial firms or other sectors without validation." },
    [
      ["592–594", "联合比较而不是逐项贴标签", "Compare a profile rather than isolated ratios",
        "Altman用多变量判别分析，将若干财务比率组合为区分两类企业的分数。重点在变量共同提供的信息，不是某个比率单独超过阈值就决定企业状况。一个单独区分能力较弱的变量，放入组合后仍可能有用，因此逐项排名不等于模型选择。",
        "Altman combines financial ratios to distinguish two predefined groups. The information in their joint profile matters, not a universal threshold on each ratio. A weak standalone discriminator may contribute when combined with other variables, so individual rankings do not reproduce model selection."],
      ["593", "先看样本如何组成", "Begin with the sampling design",
        "初始样本包含33家破产制造企业与33家非破产制造企业，后者按行业与规模进行配对选择。这样的研究设计有助于比较两类特征，却不等于现实市场中两类企业各占一半。阅读任何分类结果前，必须区分样本配比与总体发生率。",
        "The initial sample pairs 33 bankrupt manufacturers with 33 non-bankrupt manufacturers selected by industry and size. This supports comparison but does not imply equal prevalence in the market. Sample composition and population incidence must be distinguished before interpreting classification results."],
      ["594–595", "五个比率衡量不同维度", "Five ratios represent different dimensions",
        "模型包含营运资本、留存收益、息税前利润分别相对总资产的比率，以及股权市值相对债务账面价值、销售额相对总资产的比率。留存收益反映累计历史，并非当年利润；股权项使用市值而非账面权益。更换字段口径就已经改变了输入。",
        "Inputs cover working capital, retained earnings and EBIT relative to assets, market equity relative to book debt, and sales relative to assets. Retained earnings are cumulative, not annual income. The equity input uses market value, not book equity; substituting fields changes the model inputs."],
      ["594–596", "系数大小不能直接解释重要性", "Coefficient size is not variable importance",
        "作者从候选比率中反复比较组合，并明确不声称得到全局最优函数。不同输入的计量单位与波动大小不同，直接比较系数绝对值会误导。阅读或移植公式时，需要同时保留原始单位、尺度与完整变量组合，而不是挑出最大的系数。",
        "The variable set emerged from comparisons among alternatives, without a claim of global optimality. Different units and variability make raw coefficient magnitudes misleading. Reading or transferring the equation requires its input scales and full variable profile, not selection of the largest coefficient."],
      ["593, 602", "经营亏损不等于破产事件", "An operating loss is not a bankruptcy event",
        "论文另外考察出现亏损但未破产的制造企业，提醒读者经营困难和法律上的破产不是同一标签。会计期间、报表取得时间与破产日期也不是同一时点。分类研究必须明确预测对象以及信息领先期，不能事后挑选最接近事件的一份资料冒充实时判断。",
        "A separate comparison considers loss-making manufacturers that did not fail. Operating difficulty and bankruptcy are different labels. Reporting periods, information availability and event dates also differ; a classification study needs an explicit target and lead time rather than a hindsight-selected statement."],
      ["592–593, 609", "判别分数不能读成概率", "A discriminant score is not a probability",
        "Z在原文中是将变量压缩到一维的判别指标，不能把数值直接读成百分比风险。原样本的行业、规模和资料可得性也限制了外推。用于新的企业群体之前，应重新审视事件标签、样本分布和会计可比性，而不是只检查公式能否算出结果。",
        "Z is a one-dimensional discriminant index, not a percentage risk. Industry, size and data availability limit the original sample's reach. A new population requires reassessment of event definitions, sample distributions and accounting comparability, beyond checking that the equation can be computed."],
    ]),
};
