// The final twenty catalog identities promoted from summary-only orientations to
// source-bounded bilingual reader guides. These are not replications or signals.
import { researchSummaryMaterials } from "./researchSummaryMaterials.js";

const bi = (zh, en) => ({ zh, en });
const guide = ({ title, url, source, question, design, data, finding, checks, boundary, english = researchBatchFour200English[title] }) => [title, {
  reviewedAt: "2026-09-02",
  evidenceUrl: url,
  evidenceScope: "The cited primary source's public description and registered bibliographic record were reviewed. This orientation stays within those materials; it does not infer unreported estimates, table-level results, causality, or an implementation beyond that stated scope.",
  limits: bi(`本文只整理“${title}”公开说明的研究对象、设计与适用边界，不构成收益预测、交易规则或全文复现。${boundary}`, `This guide only organizes the publicly described question and design of “${title}”. It is not a return forecast, trading rule, or full-text replication. The source's stated scope remains controlling.`),
  related: researchSummaryMaterials[title] ?? {},
  sections: [
    ["研究问题", "Research question", `${question} 阅读时应将其放回原始样本、时点和制度环境中理解，不能把问题本身当作跨市场结论。`, `${english.question} Read it as a bounded question, not as a conclusion that automatically travels beyond its sample, dates, or institutional setting.`],
    ["研究设计", "Research design", `${design} 比较对象、观察窗口和对照关系共同构成研究合同；改变其中任一选择，可能改变所检验的命题。`, `${english.design} The comparison, observation window, and control relation are part of the research contract; changing one can change the proposition being tested.`],
    ["数据与时点", "Data and timing", `${data} 字段定义、可得时点和样本筛选必须与原研究分开记录，不能因变量同名或使用最新修订值便视为可比。`, `${english.data} Keep fields, availability timing, and sample filters separate from the original study: a same-named variable or later-revised database is not automatically comparable.`],
    ["如何理解结果", "How to read the result", `${finding} 它只支持来源描述的经验或理论关系，不能把相关性、模型拟合或历史表现升级为因果、可执行性或未来保证。`, `${english.finding} This remains the empirical or theoretical relation described by the source; it does not turn association, fit, or historical performance into causality, an executable procedure, or a future guarantee.`],
    ["复核清单", "Replication checks", `${checks} 开展后续分析前，应将这些选择写入版本化研究记录，并保留原始来源链接与访问日期。`, `${english.checks} Before extending the analysis, record these choices in a versioned note and retain the primary-source link and access date.`],
    ["适用边界", "Scope boundary", `该条导读引用 ${source}。${boundary} 如需数值结论、参数、表格或稳健性检验，请回到原文并单独核对版本、附录与样本定义。`, `This guide cites ${source}. ${english.boundary} For numerical conclusions, parameters, tables, or robustness tests, return to the original and separately verify the edition, appendices, and sample definitions.`],
  ].map(([zhTitle, enTitle, zhBody, enBody]) => ({ title: bi(zhTitle, enTitle), body: bi(zhBody, enBody), reference: { url, label: bi(`${source} · 来源说明`, `${source} · source description`) } })),
}];

export const researchBatchFour200English = {
  "SSE Statistical Yearbook": {
    question: "The Shanghai Stock Exchange yearbook is an official annual reference for the exchange's market overview, price indices, trading, listed companies, members, investors, and major events.",
    design: "It is a compiled statistical publication, not a causal study or a point-in-time market-data feed; the selected volume and its definitions determine the comparison.",
    data: "Use the chosen volume's tables, coverage year, classification definitions, publication date, units, revisions, and market-segment scope rather than combining values across editions without a crosswalk.",
    finding: "The archive supports a structured descriptive reference to exchange statistics, not a claim about a security, a current market state, or the causal effect of any market change.",
    checks: "Record the volume and coverage year; preserve table title, unit, segment, and footnotes; separate annual aggregate figures from daily data; and retain publication and access dates.",
    boundary: "Annual exchange statistics cannot replace security-level, intraday, or real-time records, and a later volume can revise definitions or coverage used by an earlier one.",
  },
  "Digesting Anomalies: An Investment Approach": {
    question: "The article examines whether a q-factor model built around market, size, investment, and profitability factors summarizes a broad cross-section of reported return anomalies.",
    design: "It compares factor-model performance across a large anomaly inventory, so factor definitions, portfolio construction, test sample, and benchmark models are part of the experiment.",
    data: "A comparable exercise needs point-in-time security returns, market equity, investment and profitability measures, delisting treatment, factor construction rules, portfolio breakpoints, and dated sample eligibility.",
    finding: "Its public abstract reports that the q-factor model accounts for many, but not all, anomalies in its examined set; it is not proof that every named anomaly disappears or is investable after costs.",
    checks: "Freeze the anomaly definitions and publication set; retain accounting availability dates and exits; reproduce factor and breakpoint rules; and report benchmarks, costs, and multiple-testing choices separately.",
    boundary: "A historical model comparison is not a live factor recommendation, a guarantee of expected returns, or permission to use later accounting revisions in an earlier information set.",
  },
  "… and the Cross-Section of Expected Returns": {
    question: "The article asks how a large history of proposed factors and repeated tests should change the statistical hurdle for claims about the cross-section of expected returns.",
    design: "It assembles a historical factor-publication inventory and applies a multiple-testing framework, making the inventory, dependence assumptions, and threshold construction material to the result.",
    data: "Inputs include a dated record of tested factors and papers, test statistics, factor definitions, publication timing, and explicit assumptions about dependence and unobserved research attempts.",
    finding: "The paper motivates a higher evidentiary hurdle in a data-mined setting; it does not turn any single t-statistic into a universal acceptance or rejection rule.",
    checks: "Pre-specify the factor family and hypothesis count; preserve chronological discovery and validation splits; record all tried specifications; and distinguish discovery evidence from confirmatory evidence.",
    boundary: "Its historical survey and multiple-testing assumptions do not certify a new signal, resolve economic relevance, or substitute for out-of-sample and implementation review.",
  },
  "Idiosyncratic Risk and the Cross-Section of Expected Stock Returns": {
    question: "The article studies whether expected returns relate to idiosyncratic risk after distinguishing predictable conditional volatility from a simple realized-volatility proxy.",
    design: "It estimates firm-level volatility within an asset-pricing framework and compares return relations across volatility measures, so the factor model, forecast specification, and holding window matter.",
    data: "A comparable analysis needs cleaned daily returns, risk-free and factor series, security identifiers, delistings, trading-status flags, volatility-estimation windows, and dated universe rules.",
    finding: "The source investigates how the chosen measure of idiosyncratic risk changes the cross-sectional relation; it does not establish that raw volatility is a universal priced factor.",
    checks: "State the factor model and volatility forecast; keep stale prices and infrequent trading visible; preserve rebalancing and return horizons; and test sensitivity to sample and microcap filters.",
    boundary: "Model-dependent volatility estimates and the paper's market period cannot be converted into a current risk score, a causal claim, or an investable prediction for another venue.",
  },
  "False Discoveries in Mutual Fund Performance: Measuring Luck in Estimated Alphas": {
    question: "The article asks how to separate apparent mutual-fund alpha caused by estimation luck from skill, zero-alpha performance, and unskilled performance when many funds are tested together.",
    design: "It applies false-discovery control to a broad fund sample while allowing dependence across estimated alphas, so the fund universe, benchmark model, and survival treatment are central.",
    data: "Inputs include gross and net fund returns, expenses, factor returns, fund identifiers, entry and exit dates, share-class treatment, benchmark specification, and a historically complete dead-fund record.",
    finding: "The method changes how significant alphas are interpreted in a multiple-fund population; it does not identify a particular live manager as skilled without reproducing the full design.",
    checks: "Include closed and merged funds; declare fee treatment and benchmark factors; preserve fund inception and liquidation dates; specify the testing family; and separate estimation from later validation.",
    boundary: "Historical fund classifications are neither product recommendations nor forward performance forecasts, and omitting dead funds can materially alter the inference.",
  },
  "An Introduction to the Bootstrap": {
    question: "The book explains bootstrap and related resampling methods for assessing sampling variation, bias, coverage, and other measures of statistical accuracy.",
    design: "It is a methodological reference: resamples are drawn according to a specified data-generating or sampling scheme, not a substitute for defining the estimator and dependence structure.",
    data: "A use case needs the original observations, sampling unit, estimator, resampling scheme, seed, number of resamples, handling of dependence, and any chronological or cluster boundaries.",
    finding: "Bootstrap output describes uncertainty under its resampling assumptions; it does not validate a model, remove selection bias, or make dependent financial observations independent.",
    checks: "Declare the sampling unit and estimand; preserve random seed and resample count; choose block or cluster structure where needed; and keep training, validation, and test periods separate.",
    boundary: "Resampling cannot recover information absent from the original sample or justify causal and predictive claims beyond the stated sampling design.",
  },
  "Greedy Function Approximation: A Gradient Boosting Machine": {
    question: "The paper frames function approximation as stagewise optimization and develops gradient-boosting procedures for regression and classification under specified loss functions.",
    design: "It builds an additive function through sequential loss-reducing updates, with weak learner, loss, stopping rule, and validation procedure defining the model rather than the word 'boosting' alone.",
    data: "Inputs require an outcome, feature definitions available at prediction time, training and held-out observations, loss function, weak-learner settings, regularization or stopping choices, and a chronological split when data are time ordered.",
    finding: "The article supplies an optimization and model-building framework; it does not show that a flexible model has economic meaning, stable performance, or a tradable edge in a financial application.",
    checks: "Freeze target timing and feature availability; use validation not test data for tuning; record tree, learning-rate, and iteration settings; evaluate calibration and drift; and retain all candidate specifications.",
    boundary: "A generic predictive algorithm cannot substitute for causal identification, point-in-time data controls, or an execution and risk assessment.",
  },
  "Autoencoder Asset Pricing Models": {
    question: "The article studies an autoencoder framework for modeling conditional factor exposures and common components in a large panel of asset returns and characteristics.",
    design: "It combines nonlinear representation learning with an asset-pricing structure, so the latent dimension, training objective, sample split, factor interpretation, and conditioning information are part of the design.",
    data: "A faithful extension needs a point-in-time returns-and-characteristics panel, universe membership and delistings, factor or test-asset definitions, missing-data treatment, macro conditioning variables, and chronological validation periods.",
    finding: "The source presents a way to estimate latent conditional pricing structure; it does not make latent features observable economic factors or guarantee out-of-sample returns.",
    checks: "Preserve feature vintages and scaling; avoid cross-sectional and temporal leakage; freeze architecture and tuning choices before the final test; report missingness and survivorship; and compare to stated benchmarks.",
    boundary: "A learned representation is model- and sample-dependent, not a live signal, causal mechanism, or replacement for data-lineage and implementation review.",
  },
  "Deep Learning in Asset Pricing": {
    question: "The article estimates an individual-stock asset-pricing model that uses deep neural networks, conditioning information, macroeconomic states, and an economic no-arbitrage criterion.",
    design: "It uses an adversarial construction of informative test assets with flexible conditional functions, so model objective, architecture, economic restriction, and temporal evaluation must be read together.",
    data: "Inputs include historical individual-stock returns, point-in-time firm characteristics, macroeconomic series with release timing, universe membership, training and validation periods, and benchmark-model definitions.",
    finding: "The source reports model comparisons under its stated evaluation design; it does not establish that a neural-network score is an investable forecast or a universally valid pricing kernel.",
    checks: "Lock feature availability and release lags; keep the test period untouched during tuning; record architecture, seed, objective, and benchmarks; audit delistings and missing data; and report sensitivity to regime changes.",
    boundary: "Economic restrictions and historical fit do not remove model risk, data leakage, transaction costs, or the need for independent replication before any financial use.",
  },
  "Characteristics Are Covariances: A Unified Model of Risk and Return": {
    question: "The article develops a framework in which firm characteristics help model time-varying factor exposures and the conditional covariance structure underlying risk and return.",
    design: "It links characteristic panels to latent factor structure, making the characteristic definitions, normalization, factor dimension, covariance estimator, and time variation part of the model contract.",
    data: "A comparable study needs point-in-time returns, dated firm characteristics, market and factor data, universe membership, delisting history, normalization rules, and train-validation-test chronology.",
    finding: "The paper provides a unified risk-and-return modeling perspective; it does not say that an observed characteristic has a standalone causal premium or is a portable signal.",
    checks: "Document characteristic lags and transformations; preserve missing and delisting rules; fix factor dimension before final testing; distinguish in-sample fit from validation; and compare against explicit benchmark models.",
    boundary: "Conditional covariances inferred by one model and sample are not observable truths or current investment recommendations.",
  },
  "Realized Kernels in Practice: Trades and Quotes": {
    question: "The article explains practical use of realized kernels to estimate daily volatility from high-frequency trade or quote observations when market microstructure effects are present.",
    design: "It compares trade- and quote-based estimates for the same stocks and discusses challenging local trends, making observation type, cleaning, sampling, kernel, and session rules essential.",
    data: "Inputs require timestamped trades or quotes, price and quote fields, exchange-session calendars, security identifiers, sampling and synchronization rules, correction flags, and stated kernel choices.",
    finding: "The source shows how realized-kernel estimates can be implemented on high-frequency observations; it does not make any five-minute bar an equivalent substitute for the underlying trade or quote record.",
    checks: "Separate trades from quotes; retain exchange and receive clocks; define session and auction treatment; document outlier and correction rules; choose kernel and bandwidth before results; and inspect local price trends.",
    boundary: "The method estimates historical variation under its data and noise assumptions, not an executable volatility forecast or a measure of all liquidity and execution costs.",
  },
  "Microstructure Noise in the Continuous Case: The Pre-Averaging Approach": {
    question: "The article develops pre-averaging methods for estimating volatility-related quantities when high-frequency observations are contaminated by microstructure noise.",
    design: "It is a continuous-time statistical framework that locally averages observations before estimation, with noise assumptions, sampling scheme, window choice, and asymptotics defining applicability.",
    data: "A comparable implementation needs ordered high-frequency prices, timestamps, market-session rules, correction and outlier flags, sampling intervals, pre-averaging windows, and explicit noise and jump assumptions.",
    finding: "The paper supplies a noise-robust estimation approach under stated conditions; it does not prove that every observed price irregularity is noise or that a chosen window is universally optimal.",
    checks: "State the observation clock and market hours; preserve raw versus corrected records; document window and sampling choices; check dependence and jumps; and evaluate finite-sample sensitivity separately from asymptotic claims.",
    boundary: "Continuous-time assumptions and high-frequency inputs cannot be silently replaced by coarse bars, and the estimator is not a trading rule or real-time risk guarantee.",
  },
  "The Cost of Capital, Corporation Finance and the Theory of Investment": {
    question: "The article establishes benchmark propositions about financing structure, cost of capital, and investment under restrictive capital-market assumptions.",
    design: "It is theoretical benchmark analysis: the propositions depend on the assumptions about taxes, transaction costs, information, contracting, and capital-market completeness rather than on a firm-level predictive sample.",
    data: "An empirical extension would need dated financing instruments and terms, taxes, issuance and distress costs, ownership and information frictions, investment opportunities, and a clearly stated counterfactual.",
    finding: "The framework clarifies what follows under its assumptions and why later frictions matter; it does not determine an individual company's optimal capital structure or current cost of capital.",
    checks: "List every maintained assumption; define cash-flow claims and tax treatment; separate book from market leverage; preserve announcement timing; and state the counterfactual before interpreting an observed financing choice.",
    boundary: "A benchmark theorem is not a corporate-finance recommendation, valuation output, or proof that real-world frictions are immaterial.",
  },
  "The Impact of Public Information on the Stock Market": {
    question: "The article studies the relation between the daily number of publicly reported news announcements and aggregate market activity, including trading volume and returns.",
    design: "It relates a dated news-count measure to aggregate market variables while controlling for calendar effects, news importance proxies, scheduled macro announcements, and selected noninformation activity.",
    data: "Inputs include the original news-source universe and timestamps, article classification, aggregate market returns and volume, trading calendar, control events, publication timing, and treatment of duplicated or syndicated stories.",
    finding: "The source documents a bounded association and emphasizes the difficulty of linking activity and volatility to observed information; it does not say that raw news volume measures information quality or causes a tradeable move.",
    checks: "Retain source coverage and first-seen time; distinguish firm and market news; deduplicate syndication; align publication and market clocks; predefine control events; and test calendar and selection sensitivity.",
    boundary: "A historical news database and aggregate-market setting cannot validate current sentiment labels, redistribution rights, or a real-time trading rule.",
  },
  "The Information Content of Forward-Looking Statements in Corporate Filings—A Naïve Bayesian Machine Learning Approach": {
    question: "The article examines forward-looking statements in MD&A sections of 10-K and 10-Q filings using a Naïve Bayesian classification approach and relates measured tone to later fundamentals.",
    design: "It defines a filing-text corpus, classification procedure, tone measure, and accounting outcomes; text selection, label construction, filing time, and controls are integral to the result.",
    data: "Inputs require versioned filing text, filing and amendment timestamps, MD&A boundaries, sentence or document labels, firm identifiers, accounting outcomes, returns where used, and an auditable vocabulary or classifier version.",
    finding: "The source finds information in its defined forward-looking tone measure under the paper's design; it does not validate generic dictionaries, infer managerial intent, or certify a particular filing's outlook.",
    checks: "Use the filing available at the analysis date; preserve amendments and document sections; record preprocessing and vocabulary; separate labels from training; test entity mapping; and keep accounting outcome timing explicit.",
    boundary: "Text-derived measures are proxies subject to selection, language, and timing error; they are not legal advice, investment advice, or a substitute for reading the underlying filing.",
  },
  "Common Factors Affecting Bond Returns": {
    question: "The article studies common movements in yield-curve changes, commonly described through level, slope, and curvature patterns in interest-rate data.",
    design: "It uses a factor decomposition of rate changes across maturities, so the curve construction, instrument set, maturity mapping, sampling frequency, and factor-extraction convention define the comparison.",
    data: "Inputs need dated yields or prices across identified maturities, instrument and quote conventions, curve-construction rules, calendars, missing-quote treatment, currency and market scope, and factor normalization.",
    finding: "The source describes common components of historical bond-return variation; it does not make a factor label a forecast, a complete risk model, or a statement about current yield movements.",
    checks: "Record instrument eligibility and maturity buckets; preserve yield convention and currency; align observation times; document interpolation and missing-data rules; fix factor sign and scale; and separate rate moves from total returns.",
    boundary: "A historical factor decomposition cannot replace security-level pricing, credit analysis, duration conventions, or a current allocation recommendation.",
  },
  "Business Cycles in a Small Open Economy": {
    question: "The article develops a dynamic small-open-economy model intended to match key empirical regularities of macroeconomic fluctuations, including trade-balance behavior.",
    design: "It compares model implications with aggregate cyclical moments, so preference specification, external environment, calibration, accounting identities, and country measurement choices are part of the analysis.",
    data: "An empirical counterpart needs dated national accounts, output, consumption, investment, trade balance, prices, world interest rates, population and seasonal-adjustment conventions, plus data-vintage and revision records.",
    finding: "The paper provides a modeled explanation for selected open-economy regularities; it does not identify a live shock, forecast a country's cycle, or establish one policy effect.",
    checks: "Preserve national-account vintages and release dates; state country and currency definitions; document detrending and seasonal adjustment; list calibrated parameters; and distinguish model moments from observed causal estimates.",
    boundary: "A stylized small-open-economy model is not a current macro forecast, policy prescription, or substitute for country-specific institutional analysis.",
  },
  "The Forward Premium Puzzle: Different Tales from Developed and Emerging Economies": {
    question: "The article compares the relation between forward premia, exchange-rate changes, and interest differentials across developed and emerging economy groups.",
    design: "It estimates foreign-exchange relations across country classifications, so currency universe, forward-contract maturity, quote convention, sample window, and developed-versus-emerging grouping are core design choices.",
    data: "Inputs include synchronized spot and forward exchange rates, interest differentials, currencies and quote direction, maturity dates, holiday calendars, capital-control or regime information, and country classifications fixed as of the study period.",
    finding: "The source documents differences in a historical cross-country FX setting; it does not establish uncovered-interest-parity causality, a carry strategy, or an expected currency return for a current market.",
    checks: "Freeze currency and country membership; state bid, ask, or midpoint convention; match contract maturities and calendars; retain regime changes; account for transaction costs; and avoid using later classifications.",
    boundary: "FX market structure, convertibility, and country regimes evolve, so the result cannot be treated as a portable trading signal or current policy assessment.",
  },
  "The Macroeconomic Impact of Financial and Uncertainty Shocks": {
    question: "The article studies how financial-condition and uncertainty shocks interact and affect macroeconomic outcomes within an identified structural vector autoregression framework.",
    design: "It distinguishes shocks using a penalty-function approach in an SVAR, so variable definitions, identification restrictions, lag structure, sample period, and uncertainty proxy determine the impulse-response interpretation.",
    data: "Inputs require dated credit-spread and uncertainty measures, macroeconomic series, release vintages, transformations, policy and crisis context, sample frequency, and the complete identification and lag specification.",
    finding: "The source reports historically adverse effects under its identification design and highlights interaction between uncertainty and tighter financial conditions; it does not observe shocks directly or produce a current recession probability.",
    checks: "Preserve data vintages and release lags; state all transformations and units; predefine identification and sign or penalty restrictions; test alternative proxies; report confidence intervals; and separate crisis narratives from model output.",
    boundary: "Structural-shock estimates are model-dependent and cannot be converted into a real-time forecast, policy recommendation, or causal conclusion without repeating the full identification exercise.",
  },
  "Financial Intermediation and Credit Policy in Business Cycle Analysis": {
    question: "The handbook chapter explains how financial intermediaries and credit policy can be incorporated into business-cycle analysis through balance-sheet and credit-market mechanisms.",
    design: "It is a theoretical and survey-oriented framework rather than a single empirical estimator, so intermediary constraints, contract structure, policy rule, and equilibrium assumptions define each mechanism.",
    data: "An empirical application needs dated bank and intermediary balance sheets, lending and funding terms, credit spreads, policy actions, borrower characteristics, macro aggregates, regulatory regimes, and a stated mapping from concepts to observables.",
    finding: "The chapter organizes channels through which intermediary conditions and policy can matter for macro fluctuations; it does not identify a particular bank's risk, a live credit shock, or a policy prescription.",
    checks: "State the modeled intermediary friction; distinguish stock from flow measures; preserve regulatory and accounting regimes; align policy announcements and implementation dates; and keep model assumptions separate from observed correlations.",
    boundary: "A framework for financial intermediation is not evidence of a current causal channel, a credit recommendation, or a substitute for institution-specific supervisory analysis.",
  },
};

export const researchBatchFour200 = Object.fromEntries([
  guide({ title: "SSE Statistical Yearbook", url: "https://www.sse.com.cn/aboutus/publication/yearly/", source: "SSE Statistical Yearbook archive", question: "上交所统计年鉴是覆盖市场概况、指数、交易、上市公司、会员、投资者与大事记的官方年度参考资料。", design: "它是按卷编制的统计出版物，不是因果研究或实时数据流；所选卷次及其统计定义决定可比范围。", data: "应记录所选卷次、覆盖年度、表格定义、发布日期、计量单位、修订说明与市场分部，不能在没有口径对应表的情况下混合不同版本。", finding: "该资料提供交易所统计的结构化描述参照，不能据此判断单只证券、当前市场状态或某项制度变化的因果效果。", checks: "记录卷次和覆盖年度；保留表名、单位、分部与脚注；区分年度总量和日频数据；保留发布时间与访问日期。", boundary: "年度统计不能替代证券级、日内或实时记录，后续卷次也可能调整前一卷使用的定义或覆盖范围。" }),
  guide({ title: "Digesting Anomalies: An Investment Approach", url: "https://doi.org/10.1093/rfs/hhu068", source: "Review of Financial Studies · DOI record", question: "论文检验以市场、规模、投资和盈利因子构成的q因子模型，能否概括大量已报告收益异象的横截面表现。", design: "它在一组异象上比较多个因子模型，因子定义、组合构造、检验样本和基准模型均属于研究设计。", data: "需要时点一致的证券收益、市值、投资与盈利变量、退市处理、因子构造、断点规则、组合定义和样本资格日期。", finding: "公开摘要报告q因子模型可解释所考察集合中的许多但非全部异象；这不是所有异象消失或扣成本后可交易的证明。", checks: "冻结异象定义和文献集合；保留会计可得日期与退出证券；复现因子和断点规则；将基准、成本和多重检验选择分开报告。", boundary: "历史模型比较不是实时因子建议、预期收益保证，也不能用之后的会计重述值回填当时信息集。" }),
  guide({ title: "… and the Cross-Section of Expected Returns", url: "https://doi.org/10.1093/rfs/hhv059", source: "Review of Financial Studies · DOI record", question: "论文讨论在已有大量因子和重复检验的背景下，应如何提高关于预期收益横截面的统计证据门槛。", design: "研究整理历史因子文献并应用多重检验框架，文献清单、依赖假设与阈值构造都会影响结论。", data: "需要带日期的论文与因子清单、检验统计量、因子定义、发表时间，以及对依赖性和未公开尝试研究的明确假设。", finding: "论文为数据挖掘环境下提高证据门槛提供了理由，并未把某一个t统计量变成普遍接受或否定规则。", checks: "预先声明因子家族和假设数量；保留发现与验证的时间顺序；记录全部尝试设定；区分探索性证据和确认性证据。", boundary: "历史文献盘点与多重检验假设不能认证新信号、解决经济意义问题，或替代样本外与实施审查。" }),
  guide({ title: "Idiosyncratic Risk and the Cross-Section of Expected Stock Returns", url: "https://doi.org/10.1016/j.jfineco.2008.02.003", source: "Journal of Financial Economics · DOI record", question: "论文在区分条件波动率预测和简单已实现波动率代理后，检验预期收益是否与特质风险相关。", design: "它在资产定价框架中估计公司层面的波动率，并比较不同波动率度量下的收益关系，因此因子模型、预测设定和持有窗口都很关键。", data: "需要清洗后的日收益、无风险和因子序列、证券标识、退市、交易状态、波动率估计窗口以及带日期的样本范围。", finding: "来源研究的是特质风险度量选择如何改变横截面关系，并未说明原始波动率是普遍被定价的因子。", checks: "声明因子模型和波动率预测；保留停滞价格与低频交易；固定再平衡与收益期限；检验样本和微盘过滤的敏感性。", boundary: "模型依赖的波动率估计及其市场时期不能转化为当前风险评分、因果判断或另一市场的可交易预测。" }),
  guide({ title: "False Discoveries in Mutual Fund Performance: Measuring Luck in Estimated Alphas", url: "https://doi.org/10.1111/j.1540-6261.2009.01527.x", source: "The Journal of Finance · DOI record", question: "论文研究当同时检验大量基金时，如何区分由估计运气产生的显著alpha、技能、零alpha与非技能表现。", design: "它在允许基金alpha估计之间存在依赖的前提下应用错误发现控制，因此基金全集、基准模型和存续处理是核心。", data: "需要毛和净基金收益、费用、因子收益、基金标识、进入退出日期、份额类别处理、基准设定和完整的已清盘基金历史。", finding: "该方法改变了多基金样本中显著alpha的解释方式，并不在没有复现完整设计时识别某只在售基金经理为有技能。", checks: "纳入关闭和合并基金；声明费用处理和基准因子；保留设立与清盘日期；定义检验家族；将估计与后续验证分开。", boundary: "历史基金分类既不是产品推荐也不是未来表现预测，遗漏已清盘基金会实质改变推断。" }),
  guide({ title: "An Introduction to the Bootstrap", url: "https://doi.org/10.1201/9780429246593", source: "Chapman and Hall/CRC · DOI record", question: "该书介绍用于评估抽样变异、偏差、覆盖率和统计精度的自助法及相关重抽样方法。", design: "它是方法论参考：重抽样依照既定数据生成或抽样方案进行，不能代替对估计量和依赖结构的定义。", data: "需要原始观测、抽样单位、估计量、重抽样方案、随机种子、重抽样次数、依赖处理以及时间或聚类边界。", finding: "自助法输出描述的是重抽样假设下的不确定性，并不会验证模型、消除选择偏差或让相关金融观测独立。", checks: "声明抽样单位和估计目标；保留随机种子和次数；在需要时采用区块或聚类结构；保持训练、验证和测试期间隔离。", boundary: "重抽样不能恢复原始样本不存在的信息，也不能使超出既定抽样设计的因果或预测主张成立。" }),
  guide({ title: "Greedy Function Approximation: A Gradient Boosting Machine", url: "https://doi.org/10.1214/aos/1013203451", source: "The Annals of Statistics · DOI record", question: "论文将函数逼近表述为逐步优化，并在给定损失函数下发展用于回归和分类的梯度提升程序。", design: "它通过连续降低损失构建加性函数，弱学习器、损失函数、停止规则和验证方案共同定义模型，而不是“提升”一词本身。", data: "需要结果变量、预测时可得的特征、训练与留出观测、损失函数、弱学习器设置、正则或停止选择，以及时间序列数据的顺序切分。", finding: "论文提供优化与建模框架，并不说明柔性模型具有经济含义、稳定表现或金融应用中的可交易优势。", checks: "冻结目标时点和特征可得性；只用验证集调参；记录树、学习率和迭代设置；评估校准与漂移；保留所有候选设定。", boundary: "通用预测算法不能替代因果识别、时点数据控制或执行与风险评估。" }),
  guide({ title: "Autoencoder Asset Pricing Models", url: "https://doi.org/10.1016/j.jeconom.2020.07.009", source: "Journal of Econometrics · DOI record", question: "论文研究用自编码器在大规模资产收益与特征面板中刻画条件因子暴露和共同成分的框架。", design: "它结合非线性表征学习和资产定价结构，潜在维度、训练目标、样本切分、因子解释和条件信息都属于设计。", data: "需要时点一致的收益和特征面板、样本成员与退市、因子或测试资产定义、缺失处理、宏观条件变量以及按时间的验证区间。", finding: "来源提出估计潜在条件定价结构的方法，不会让潜在特征自动成为可观测经济因子或保证样本外收益。", checks: "保留特征版本和缩放；避免横截面与时间泄漏；最终测试前冻结架构和调参；报告缺失与存续偏差；比较已声明的基准。", boundary: "学习到的表征依赖模型和样本，不是实时信号、因果机制，也不能替代数据血缘和实施审查。" }),
  guide({ title: "Deep Learning in Asset Pricing", url: "https://doi.org/10.1287/mnsc.2023.4695", source: "Management Science · DOI record", question: "论文使用深度神经网络、条件信息、宏观状态和无套利准则估计个股资产定价模型。", design: "它以对抗式方法构造信息量高的测试资产并采用柔性条件函数，模型目标、架构、经济约束和时间评估需共同阅读。", data: "需要历史个股收益、时点一致的公司特征、含发布日期的宏观序列、样本成员、训练验证区间和基准模型定义。", finding: "来源在其评估设计下报告模型比较，不代表神经网络分数是可投资预测或普适有效的定价核。", checks: "锁定特征可得性和发布时滞；调参时不接触测试期；记录架构、种子、目标和基准；审计退市与缺失；报告制度变化敏感性。", boundary: "经济约束和历史拟合不能消除模型风险、数据泄漏、交易成本，亦不能替代独立复现。" }),
  guide({ title: "Characteristics Are Covariances: A Unified Model of Risk and Return", url: "https://doi.org/10.1016/j.jfineco.2019.05.001", source: "Journal of Financial Economics · DOI record", question: "论文提出用公司特征刻画时变因子暴露与条件协方差结构，从而统一风险和收益建模。", design: "它把特征面板与潜在因子结构连接，特征定义、标准化、因子维度、协方差估计和时间变化共同构成模型合同。", data: "需要时点一致的收益、带日期的公司特征、市场和因子数据、样本成员、退市历史、标准化规则和训练验证测试的时间顺序。", finding: "论文提供风险收益统一建模视角，并不说明单个观测特征具有独立因果溢价或可移植信号意义。", checks: "记录特征滞后与变换；保留缺失和退市规则；最终测试前固定因子维度；区分样本内拟合和验证；对比明确基准模型。", boundary: "某个模型和样本推断的条件协方差不是可观测真值，也不是当前投资建议。" }),
  guide({ title: "Realized Kernels in Practice: Trades and Quotes", url: "https://doi.org/10.1111/j.1368-423x.2008.00275.x", source: "The Econometrics Journal · DOI record", question: "论文说明在存在市场微观结构影响时，如何用高频成交或报价观测实施已实现核以估计个股日波动。", design: "它比较同一股票的成交和报价估计，并讨论局部价格趋势等挑战，因此观测类型、清洗、采样、核函数和交易时段规则都很关键。", data: "需要带时间戳的成交或报价、价格与报价字段、交易所日历、证券标识、采样同步规则、更正标记和明确的核函数选择。", finding: "来源展示已实现核如何在高频观测上实施，不能让任意五分钟K线成为逐笔成交或报价记录的等价替代。", checks: "区分成交与报价；保留交易所和接收时钟；定义交易时段与竞价处理；记录异常更正规则；结果前确定核与带宽；检查局部趋势。", boundary: "该方法估计的是既定数据和噪声假设下的历史变动，而不是可执行波动率预测或全部流动性与执行成本的度量。" }),
  guide({ title: "Microstructure Noise in the Continuous Case: The Pre-Averaging Approach", url: "https://doi.org/10.1016/j.spa.2008.11.004", source: "Stochastic Processes and their Applications · DOI record", question: "论文发展预平均方法，在高频观测受微观结构噪声影响时估计波动率相关量。", design: "它是连续时间统计框架，先对局部观测平均再估计；噪声假设、采样方案、窗口选择和渐近条件决定可用范围。", data: "需要有序高频价格、时间戳、交易时段、异常和更正标记、采样间隔、预平均窗口以及明确的噪声和跳跃假设。", finding: "来源在既定条件下提供噪声稳健估计思路，不会证明每个价格不规则现象都是噪声，或某个窗口对所有市场最优。", checks: "声明观测时钟和交易时间；保留原始与更正记录；记录窗口和采样选择；检查依赖与跳跃；将有限样本敏感性与渐近主张分开。", boundary: "连续时间假设和高频输入不能被粗粒度K线悄然替代，估计量也不是交易规则或实时风险保证。" }),
  guide({ title: "The Cost of Capital, Corporation Finance and the Theory of Investment", url: "https://www.jstor.org/stable/1809766", source: "The American Economic Review · JSTOR record", question: "论文在严格资本市场假设下提出关于融资结构、资本成本和投资的基准命题。", design: "它是理论基准分析，命题依赖税收、交易成本、信息、契约和资本市场完备性假设，而不是公司级预测样本。", data: "实证延展需要带日期的融资工具与条款、税收、发行和困境成本、所有权与信息摩擦、投资机会以及清晰反事实。", finding: "该框架说明在既定假设下可推出什么，并帮助识别后续摩擦为何重要；它不决定单个公司的最优资本结构或当前资本成本。", checks: "列出维持假设；定义现金流索取权和税收处理；区分账面与市值杠杆；保留公告时点；解释融资选择前先声明反事实。", boundary: "基准定理不是公司融资建议、估值输出，也不证明现实世界摩擦无关紧要。" }),
  guide({ title: "The Impact of Public Information on the Stock Market", url: "https://doi.org/10.1111/j.1540-6261.1994.tb00083.x", source: "The Journal of Finance · DOI record", question: "论文研究每日公开报道新闻数量与市场总体活动（包括成交量和收益）之间的关系。", design: "它把带日期的新闻计数与总体市场变量关联，并控制日历效应、新闻重要性代理、预定宏观公告及部分非信息型活动。", data: "需要原新闻来源范围与时间戳、文章分类、总体市场收益和成交量、交易日历、控制事件、发布时间，以及转载和重复故事的处理。", finding: "来源记录了有边界的相关关系，并强调将市场活动和波动与可观测信息关联的困难；它不说明原始新闻量衡量信息质量或造成可交易价格变动。", checks: "保留来源覆盖和首次可见时间；区分公司和市场新闻；去重转载；对齐发布和市场时钟；预定义控制事件；检验日历和选择敏感性。", boundary: "历史新闻库和总体市场环境不能验证当前情绪标签、再分发权利或实时交易规则。" }),
  guide({ title: "The Information Content of Forward-Looking Statements in Corporate Filings—A Naïve Bayesian Machine Learning Approach", url: "https://doi.org/10.1111/j.1475-679x.2010.00382.x", source: "Journal of Accounting Research · DOI record", question: "论文使用朴素贝叶斯方法分析10-K和10-Q中MD&A的前瞻性陈述，并将语调度量与后续基本面关联。", design: "它定义文本语料、分类程序、语调指标和会计结果；文本选择、标签构造、披露时间和控制变量均不可脱离。", data: "需要版本化披露文本、披露与修订时间、MD&A边界、句子或文档标签、公司标识、会计结果、使用时的收益，以及可审计的词典或分类器版本。", finding: "来源在论文定义的前瞻性语调度量中发现信息内容，不会验证通用词典、推断管理层意图或保证单份披露文件的前景。", checks: "使用分析时点可获得的披露；保留修订和文档分区；记录预处理和词典；隔离标签与训练；检验实体映射；明确会计结果时点。", boundary: "文本指标是受选择、语言和时点误差影响的代理变量，不是法律或投资建议，也不能替代阅读原始文件。" }),
  guide({ title: "Common Factors Affecting Bond Returns", url: "https://doi.org/10.3905/jfi.1991.692347", source: "The Journal of Fixed Income · DOI record", question: "论文研究收益率曲线变化中的共同成分，通常用水平、斜率和曲率模式描述利率的联动。", design: "它对不同期限利率变化进行因子分解，曲线构造、工具集合、期限映射、采样频率和因子提取惯例共同定义比较。", data: "需要带日期的不同期限收益率或价格、工具和报价惯例、曲线构造、日历、缺失报价处理、币种市场范围和因子标准化。", finding: "来源描述历史债券收益变化的共同成分，不会让某个因子标签成为预测、完整风险模型或当前收益率走势判断。", checks: "记录工具资格和期限桶；保留收益率惯例和币种；对齐观测时间；记录插值和缺失规则；固定因子符号和尺度；区分利率变化与总收益。", boundary: "历史因子分解不能替代证券级定价、信用分析、久期惯例或当前配置建议。" }),
  guide({ title: "Business Cycles in a Small Open Economy", url: "https://doi.org/10.1016/0014-2921(94)00105-9", source: "European Economic Review · DOI record", question: "论文建立小型开放经济动态模型，用以匹配宏观波动中的主要经验规律，包括贸易余额行为。", design: "它将模型含义与总体周期矩比较，偏好设定、外部环境、校准、会计恒等式和国家统计口径均属于分析内容。", data: "实证对应需要带日期的国民账户、产出、消费、投资、贸易余额、价格、世界利率、人口和季调惯例，并保留数据版本和修订记录。", finding: "论文对特定开放经济规律提供模型化解释，不会识别实时冲击、预测一国周期或证明某项政策效果。", checks: "保留国民账户版本和发布时间；声明国家与币种定义；记录去趋势和季调；列出校准参数；区分模型矩与观测因果估计。", boundary: "风格化小型开放经济模型不是当前宏观预测、政策处方或替代国别制度分析。" }),
  guide({ title: "The Forward Premium Puzzle: Different Tales from Developed and Emerging Economies", url: "https://doi.org/10.1016/s0022-1996(99)00039-2", source: "Journal of International Economics · DOI record", question: "论文在发达和新兴经济体分组下比较远期升贴水、汇率变化与利差之间的关系。", design: "它跨国估计外汇关系，币种集合、远期合约期限、报价惯例、样本窗口和国家分组均是核心设计选择。", data: "需要同步即期与远期汇率、利差、币种及报价方向、到期日、节假日日历、资本管制或制度资料和当时固定的国家分类。", finding: "来源记录历史跨国外汇环境中的差异，不会建立无套息平价的因果关系、套利策略或当前市场预期收益。", checks: "冻结币种和国家成员；说明买卖价或中间价惯例；匹配合约期限和日历；保留制度变化；考虑交易成本；不使用之后的分类。", boundary: "外汇市场结构、可兑换性和国家制度会变化，结果不能当作可移植交易信号或当前政策判断。" }),
  guide({ title: "The Macroeconomic Impact of Financial and Uncertainty Shocks", url: "https://doi.org/10.1016/j.euroecorev.2016.02.020", source: "European Economic Review · DOI record", question: "论文在识别的结构向量自回归框架中研究金融条件冲击和不确定性冲击如何互动并影响宏观结果。", design: "它以惩罚函数方法在SVAR中区分冲击，变量定义、识别限制、滞后结构、样本期和不确定性代理都会决定脉冲响应解释。", data: "需要带日期的信用利差和不确定性指标、宏观序列、发布版本、变换、政策与危机背景、样本频率以及完整的识别和滞后设定。", finding: "来源在既定识别设计下报告历史中的不利影响，并强调不确定性与金融条件收紧的交互；它不直接观测冲击，也不提供当前衰退概率。", checks: "保留数据版本和发布时滞；声明变换和单位；预定义识别及符号或惩罚限制；测试替代代理；报告置信区间；将危机叙事与模型输出分开。", boundary: "结构冲击估计依赖模型，不能在没有完整重复识别的情况下转成实时预测、政策建议或因果结论。" }),
  guide({ title: "Financial Intermediation and Credit Policy in Business Cycle Analysis", url: "https://doi.org/10.1016/b978-0-444-53238-1.00011-9", source: "Handbook of Monetary Economics · DOI record", question: "手册章节说明如何把金融中介和信贷政策经由资产负债表及信贷市场机制纳入商业周期分析。", design: "它是理论与综述框架而不是单一实证估计量；中介约束、契约结构、政策规则和均衡假设定义每个机制。", data: "实证应用需要带日期的银行和中介资产负债表、借贷与融资条款、信用利差、政策行动、借款人特征、宏观总量、监管制度及概念到观测值的映射。", finding: "章节组织中介条件和政策可能影响宏观波动的传导渠道，并不识别某家银行风险、实时信贷冲击或具体政策处方。", checks: "声明模型中的中介摩擦；区分存量和流量；保留监管与会计制度；对齐政策公告和实施日期；将模型假设与观测相关性分开。", boundary: "金融中介框架不是当前因果通道的证据、信贷建议或对机构监管分析的替代。" }),
]);
