// Authored reading guides. Evidence scope is internal, not a full-text-review claim.
import { researchEditorialExpansion } from "./researchEditorialExpansion.js";
const section = (zh, en, bodyZh, bodyEn) => ({ title: { zh, en }, body: { zh: bodyZh, en: bodyEn } });
const guide = (evidenceUrl, evidenceScope, sections, zh, en) => ({ reviewedAt: "2026-08-30", evidenceUrl, evidenceScope, sections, limits: { zh, en } });

export const researchEditorial = {
  ...researchEditorialExpansion,
  "Common risk factors in the returns on stocks and bonds": guide(
    "https://www.bauer.uh.edu/rsusmel/phd/Fama-French_JFE93.pdf", "Published paper, abstract and opening introduction (pp. 3–5); not a full-paper review.", [
      section("为什么把股票与债券放在一起？", "Why bring stocks and bonds together?", "这篇论文问的不是哪只股票会涨，而是不同资产的收益能否由少数共同变化解释。作者把股票、政府债券和公司债券放进同一框架：如果市场相互联系，解释股票的变量与解释债券的变量可能有交集。", "The question is whether a small set of shared movements helps explain returns across assets, not which security will rise. Fama and French study stocks alongside government and corporate bonds, asking whether connected markets also share sources of return variation."),
      section("从公司特征到共同因子", "From characteristics to common factors", "作者用月度时间序列回归，把资产超额收益与市场、规模、账面市值比，以及期限和违约相关的组合收益联系起来。公司规模是一个特征；对规模组合收益的敏感度是回归系数。阅读时应把两者分开。", "Time-series regressions relate monthly excess returns to the market, size, book-to-market, term and default-related portfolio returns. A firm's size is a characteristic; its loading on a size-related return series is a regression coefficient. Keeping those concepts separate is central to reading the paper."),
      section("解释共同波动，不等于解释全部收益", "Two different tests of explanation", "论文同时关注共同波动与平均收益：前者看因子能解释多少随时间的变化，后者看超额收益回归的截距是否仍明显偏离零。作者报告股票的三个因子与债券的两个因子具有解释力，但这不表示任何资产、任何时期都没有剩余差异。", "Shared variation and average returns are different tests. Loadings and fit describe co-movement; intercepts assess unexplained average excess returns. The authors report explanatory roles for three stock-market and two bond-market factors, without establishing universal coverage of every asset or period."),
      section("带着什么问题继续读？", "A useful reading question", "先读因子组合如何构造，再看回归截距，不要只看拟合优度。准备对应数据时，记录市场范围、无风险利率、财务信息可得日期和组合重建规则。1993年文中的五个跨资产因子，也不是后来加入盈利与投资的股票五因子模型。", "Read portfolio construction before interpreting intercepts or fit. For data preparation, record the market universe, risk-free benchmark, accounting availability and reconstitution rules. The five cross-asset factors here are not the later equity five-factor model that adds profitability and investment."),
    ], "历史美国样本中的解释力，不证明当前市场溢价或可交易收益；样本、交易成本和制度背景需要另行评估。", "Historical US explanatory power does not establish a current premium or executable return; sample construction, costs and institutions require separate assessment."),

  "Do Stock Prices Fully Reflect Information in Accruals and Cash Flows about Future Earnings?": guide(
    "https://www.cuhk.edu.hk/acy2/workshop/June2009Wasley/1996TAR).pdf", "Published paper, abstract, introduction and opening hypotheses (pp. 289–291).", [
      section("相同利润，为什么含义不同？", "The same earnings, different persistence", "利润包含现金流与应计成分。Sloan关注的是：相同的当期利润，如果来自不同成分，下一期能延续的程度是否相同？这把阅读起点从利润总额，移到利润形成过程。", "Earnings combine cash-flow and accrual components. Sloan asks whether identical current earnings imply the same persistence when their composition differs. The starting point is how earnings arise, rather than the headline total alone."),
      section("把持续性与价格反应分别检验", "Separate persistence from pricing", "论文先研究两个成分与未来盈利的关系，再检查股价是否充分反映这种差异。不能因为某种会计成分较不持续，就直接断言市场没有理解它；经济关系和市场定价需要分别提供证据。", "The analysis examines how the components relate to future earnings and then whether prices reflect that distinction. Lower persistence of an accounting component alone is not evidence of mispricing; the accounting relation and the pricing response require separate tests."),
      section("论文报告了什么？", "What does the paper report?", "在研究样本中，应计部分的盈利持续性低于现金流部分，股价表现与投资者没有充分区分两种成分的解释一致。作者还讨论未来盈利公告附近的价格反应。这里应保留“样本中”和“与解释一致”，而不是把应计一概当作造假。", "In the sample, accrual-related earnings are less persistent than cash-flow-related earnings. Price behavior is consistent with investors not fully distinguishing them, with subsequent earnings announcements playing a role. That interpretation does not make accruals synonymous with fraud."),
      section("数据准备从披露时间开始", "Start with disclosure timing", "本站建议先核对利润、现金流及应计定义，再按实际披露时间连接价格。报告期末不能替代可得时点，修订后的报表也不能无条件覆盖旧版本。可继续阅读应计估计误差论文，理解“应计的多少”与“应计的质量”不是同一个问题。", "For preparation, establish the earnings, cash-flow and accrual definitions, then join prices at disclosure availability. Period-end is not publication time, and revised statements must not overwrite earlier information sets. Read Dechow and Dichev next to distinguish accrual magnitude from accrual quality."),
    ], "这是一项历史样本研究；会计准则、行业、披露制度和成本会限制结论迁移。应计高低本身不能判定财务舞弊。", "Historical sample evidence may not transfer across accounting standards, industries, disclosure regimes or costs. Accrual magnitude alone does not establish misconduct."),

  "The Quality of Accruals and Earnings: The Role of Accrual Estimation Errors": guide(
    "https://papers.ssrn.com/sol3/papers.cfm?abstract_id=277231", "Author-deposited July 2001 working-paper abstract; final 2002 identity retained. Guide avoids unverified tables/sample estimates.", [
      section("应计不是现金流的反面", "Why accruals can be useful", "应计可以把不同时间收到或支付的现金，调整到更能表达经营活动的期间。Dechow与Dichev提出的问题是：这种时间匹配依赖估计，而估计错误会怎样影响盈利质量？因此，应计并不是天然有问题，关键在于估计是否与后来实现的现金流相符。", "Accruals can improve the timing match between cash flows and operating activity. Dechow and Dichev ask how errors in the estimates required for that matching affect earnings quality. Accrual accounting is not inherently defective; the quality of its estimates matters."),
      section("用现金流解释营运资本变化", "Relating working capital to cash flows", "作者提出把营运资本变化与过去、当期及未来的经营现金流联系起来，用不能被解释的部分刻画估计误差。这不是简单比较利润与现金流的大小，而是考察跨期匹配关系。", "The proposed measure relates working-capital changes to past, present and future operating cash flows. Unexplained variation is used to characterize estimation noise. This examines matching across periods, rather than merely comparing the level of earnings with cash flow."),
      section("“未来现金流”带来的关键边界", "The future-cash-flow boundary", "作者摘要报告应计质量与盈利持续性正相关。阅读中尤其要注意，衡量质量时用到了未来现金流。本期资料即使已经披露，也不代表这个完整质量指标在当时已经可以算出。", "The authors report a positive relation between accrual quality and earnings persistence. Crucially, the measure uses future cash-flow realizations. Availability of current statements does not mean that the complete quality measure was available at that same date."),
      section("如何放进时点一致研究？", "Using it in point-in-time work", "本站建议分别保存“事后研究标签”和“当时可用输入”。如果把指标放入按时间回看的研究，必须延迟到所有所需报表均已披露，或另行定义只使用历史信息的代理变量；后一种做法不能直接沿用原指标名称而不说明变化。", "Keep ex-post research labels separate from contemporaneously available inputs. A historical information-set analysis must wait until all required reports are available, or define a distinct historical-only proxy. Such a proxy should not silently inherit the original measure's name or interpretation."),
    ], "此导读依据作者工作论文摘要讨论核心方法；期刊版本的具体设定请以原文为准。残差也可能包含模型遗漏，不能被直接解释为舞弊。", "This guide explains the core method from the authors' working-paper abstract; consult the journal edition for exact specifications. Residuals may also reflect model omissions, not misconduct."),

  "Continuous Auctions and Insider Trading": guide(
    "https://www.econometricsociety.org/publications/econometrica/1985/11/01/continuous-auctions-and-insider-trading", "Publisher abstract; theoretical mechanism only, no unreviewed derivation or empirical claim.", [
      section("价格怎样逐步吸收私人信息？", "How does private information enter prices?", "Kyle研究一个知情交易者不会一次性暴露全部信息的市场。价格如何在连续交易中逐渐反映信息，取决于知情者的交易选择，以及做市者从订单流中能推断出多少。", "Kyle studies a market in which an informed trader need not reveal information all at once. Price discovery depends on the trader's order choices and on what market makers can infer from the resulting order flow."),
      section("三个角色构成一个机制", "Three roles, one mechanism", "模型包含单一风险中性的知情者、随机噪声交易者和竞争性的风险中性做市者。噪声交易让知情交易混入普通订单，做市者则根据观察到的交易更新价格。缺少这些角色和假设，就不能把任何成交量变化都叫作模型中的信息交易。", "The model contains one risk-neutral insider, random noise traders and competitive risk-neutral market makers. Noise trading conceals informed orders, while market makers update prices from observed flow. These roles and assumptions are not interchangeable with generic changes in trading volume."),
      section("均衡结果有条件", "Equilibrium results are conditional", "出版方摘要描述了连续交易极限下的结果：市场深度在模型中保持不变，私人信息到交易结束时进入价格。这些是特定模型下推导的性质，不是对现实每一个交易日的描述。", "The publisher's abstract describes constant market depth and incorporation of private information by the end of trading in the continuous-trading limit. These are properties derived under the model, not descriptions of every real trading session."),
      section("从模型走到数据，还缺什么？", "What is missing when moving to data?", "本站建议用它理解价格冲击与信息披露速度之间的联系，再单独核对实际数据能观察什么。分钟价格与总成交量并不直接提供交易方向、交易者身份或盘口深度；仅凭它们不能验证模型中的每一个机制。", "Use the model to organize questions about price impact and the speed of information revelation, then audit observability separately. Minute prices and aggregate volume do not directly reveal trade direction, trader identity or order-book depth, and cannot test every mechanism on their own."),
    ], "这是理论模型导读，不是内幕交易识别方法。单一知情者、风险中性等假设限制了向复杂现实市场的直接迁移。", "This is a guide to a theoretical model, not an insider-trading detector. Assumptions such as one informed trader and risk neutrality limit direct transfer to complex markets."),

  "Modeling and Forecasting Realized Volatility": guide(
    "https://users.ssc.wisc.edu/~behansen/718/Anderson2003.pdf", "Published paper, abstract and introduction (pp. 579–582).", [
      section("日内数据能告诉我们什么？", "What can intraday data add?", "只用每天一个收益观测，会丢掉日内价格如何波动的信息。作者把高频收益汇总成已实现波动度量，再用日频或更低频的时间序列方法研究其变化，将“测量波动”和“预测波动”连接起来。", "One return per day omits how prices move within that day. The authors aggregate intraday returns into realized-volatility measures and model their lower-frequency dynamics, connecting measurement with forecasting."),
      section("先测量，再建模", "Measure first, then model", "论文以连续时间价格与二次变差理论建立测量联系，并在外汇报价数据上研究已实现波动率的对数动态。它并不是简单宣称数据越密越好，而是要明确测量对象、采样方式以及测量误差如何进入模型。", "Quadratic-variation theory links the realized measure to continuous-time price variation. The empirical analysis models logarithmic realized volatilities from foreign-exchange quotations. The approach requires a defined measurement target, sampling scheme and treatment of measurement error, not simply more frequent data."),
      section("拟合与预测不是同一回事", "Fit is not forecast performance", "作者使用德国马克／美元、日元／美元报价，区分估计期和样本外预测期，并将波动及收益分布预测与其他方法比较。阅读价值在于这种测量、模型和样本外评价的连续关系，而不只是某个模型名称。", "The study uses Deutschemark/dollar and yen/dollar quotations, separates estimation from out-of-sample evaluation, and compares volatility and return-distribution forecasts. Its value lies in linking measurement, modeling and evaluation, not in a model name alone."),
      section("准备分钟数据时先检查什么？", "Before using minute observations", "本站建议先明确时区、交易日边界、隔夜区间、缺失报价和零收益的含义，再比较不同采样间隔。停牌不能机械补成零波动；外汇市场的连续交易背景，也不能直接套用到有午休和集合竞价的股票市场。", "First specify timezone, session boundaries, overnight intervals, missing quotations and the meaning of zero returns. Compare sampling intervals explicitly. A suspension should not be silently filled as zero volatility, and the FX setting should not be imposed on equity sessions with breaks and auctions."),
    ], "采样过密可能受到微观结构噪声影响；日内平方收益和与其平方根的单位不同。论文预测证据不等同于当前数据或模型的表现。", "Microstructure noise matters at fine sampling intervals; sums of squared returns and their square roots have different units. The paper's forecasting evidence is not a claim about current data or models."),

  "The Development of China's Stock Market and Stakes for the Global Economy": guide(
    "https://pages.stern.nyu.edu/~jcarpen0/pdfs/Carpenter%20Whitelaw%202017%20ARFE%20-%20The%20Development%20of%20China's%20Stock%20Market%20and%20Stakes%20for%20the%20Global%20Economy.pdf", "2017 published review, abstract and introduction (pp. 233–235).", [
      section("先理解市场为何如此形成", "Begin with how the market developed", "这是一篇2017年的文献综述，不是对今天行情的评论。Carpenter与Whitelaw把中国股票市场放在金融体系、国有企业改革、上市选择和国际市场联系中，帮助读者理解研究问题从何而来。", "This 2017 literature review is not commentary on today's market. Carpenter and Whitelaw place China's stock market within its financial system, state-enterprise reform, listing choices and international links, showing how institutional context shapes research questions."),
      section("两条线索：公司与价格", "Two threads: firms and prices", "公司层面的线索包括私有化、上市选择和发行定价；资产定价层面包括股份类别价差、价格的信息含量及收益横截面。把两条线分开阅读，有助于避免将公司制度问题误当作短期价格规律。", "The corporate thread covers privatization, listing selection and issuance. The pricing thread includes share-class premia, price informativeness and cross-sectional returns. Separating the threads prevents institutional questions about firms from being mistaken for short-term price patterns."),
      section("作者提醒避免套用现成框架", "Why institutional transfer matters", "作者强调中国金融制度的独特性，以及过度套用美国研究范式的风险。例如，评估国有企业改革时，如果只看单个企业价值，而忽略其社会、经济和战略目标，可能会把研究问题设得过窄。", "The authors caution against mechanically applying US research paradigms. For example, an evaluation of state-enterprise reform focused only on individual firm value may miss social, economic and strategic objectives relevant to that setting."),
      section("把综述读成研究地图", "Read the review as a research map", "本站建议为感兴趣的议题建立一张时间表：制度变化何时发生、哪些公司受影响、当时哪些股份可以交易、样本如何被选入。随后再沿原文参考文献追到具体研究。这样得到的是可核对的问题与样本边界，而不是一句泛化的中国市场结论。", "Build a timeline for the question you choose: when rules changed, which firms were affected, which shares were tradable and how the sample was selected. Then follow the review's references to individual studies. This produces testable questions and sample boundaries rather than a universal claim about China."),
    ], "文中制度、规模和开放程度属于2017年及以前的背景；用于当前研究时须重新核对，不能当作最新市场事实。", "Institutions, market size and openness describe the period up to 2017. Recheck them for current work rather than treating them as present-day facts."),

  "Giving Content to Investor Sentiment: The Role of Media in the Stock Market": guide(
    "https://www.columbia.edu/~pt2238/papers/Tetlock_Media_Sentiment_JF.pdf", "Author-hosted article, abstract and introduction; WSJ 1984–1999 design.", [
      section("媒体在反映市场，还是影响市场？", "Does media reflect or influence markets?", "Tetlock研究财经媒体的语气与市场活动之间的关系。问题不只是坏消息是否伴随下跌，还包括市场下跌是否反过来影响报道，以及这种关系能否与基本面信息区分。", "Tetlock examines how financial-media tone relates to market activity. The question includes whether pessimism precedes price changes, whether declines affect subsequent reporting, and how these relations differ from information about fundamentals."),
      section("把文字转成可观察的度量", "Turning text into a measure", "作者使用《华尔街日报》一个日常市场专栏，将词语分类并通过主成分方法构建悲观程度指标，再用时间序列方法观察它与收益、成交量的联系。这个度量依赖具体语料和词典，不是语言本身天然给出的分数。", "The study classifies words from a daily Wall Street Journal market column, uses principal components to construct a pessimism measure, and examines its temporal relations with returns and volume. The measure depends on a particular corpus and dictionary, not a universal language score."),
      section("双向关系与短期反应", "Feedback and short-run responses", "论文报告较高悲观程度与随后价格下行压力及回归相关，极端语气与较高成交量相关，市场下跌也会带来更多悲观报道。因此，单向写成“新闻决定股价”会丢失论文的重要部分。", "The paper reports downward price pressure followed by reversion after pessimistic media content, higher volume with extreme tone, and greater pessimism following low returns. Reducing this to 'news determines prices' omits important feedback in the evidence."),
      section("从旧报纸走向新语料", "Moving to a different corpus", "本站建议先固定媒体范围、版本与发布时间，再去除转载并检查实体识别。原样本是1984—1999年的美国报纸专栏；中文公告、社交媒体和大模型标签都需要自己的人工核对样本，不能直接继承这篇论文的测量有效性。", "Fix the publisher universe, text version and release timing before deduplicating and checking entity mapping. The sample is a US newspaper column from 1984–1999. Chinese filings, social media and model-generated labels need their own validation samples."),
    ], "时间序列预测关系不自动等于因果效应；语料选择、语言、词典与发布时间都会限制迁移。", "Predictive temporal relations do not automatically establish causation; corpus selection, language, dictionaries and release timing constrain transfer."),

  "When Is a Liability Not a Liability? Textual Analysis, Dictionaries, and 10-Ks": guide(
    "https://www.uts.edu.au/globalassets/sites/default/files/adg_cons2015_loughran-mcdonald-je-2011.pdf", "Published article, abstract and introduction (pp. 35–38).", [
      section("金融语言有自己的语境", "Financial language has its own context", "普通词典中的负面词，在财务报告里可能只是中性术语。Loughran与McDonald用这个问题提醒读者：先证明一个文本指标测量了你想测量的东西，再讨论它和金融变量的关系。", "A word classified as negative in a general dictionary may be neutral financial terminology. Loughran and McDonald put measurement first: establish what a text indicator captures before interpreting its relation to financial variables."),
      section("错分不只是增加噪声", "Misclassification is more than noise", "论文研究1994—2008年的10-K文件，指出通用词表中的一些高频词会把行业属性与负面语气混在一起。作者建立金融领域词表，并讨论词频加权；同样的词数，可能因计量方式不同而产生不同含义。", "Using 10-K filings from 1994–2008, the paper shows how frequent general-dictionary terms can confuse industry characteristics with negative tone. It develops financial word lists and discusses term weighting: identical word counts need not carry identical measurement meaning."),
      section("当期关联不等于未来可预测", "Association is not future predictability", "作者将词表与文件提交附近的收益、成交量、波动及其他变量联系起来，也明确报告没有发现这些竞争性语气指标能够预测未来收益的证据。阅读时不能只保留显著关联，省略这个限制。", "The study relates word lists to filing-period returns, volume, volatility and other outcomes. It also reports no evidence of future-return predictability from the competing tone measures. A reading that retains only significant associations loses this important boundary."),
      section("先检验词典，再扩大语料", "Validate before expanding", "本站建议抽样人工检查误判词，保留词典版本、清洗规则与文档范围，再比较不同权重方式。英文10-K词典不能直接翻译成中文词典后视为有效，也不能把整个文件和某个章节混成同一种输入。", "Sample and inspect misclassified terms, retain dictionary versions and cleaning rules, and compare weighting schemes. Translating an English 10-K lexicon does not validate a Chinese one. Whole filings and selected sections must also remain distinct input definitions."),
    ], "词表度量的是特定语境下的语言特征，不是公司质量、舞弊概率或交易指令。其他语言和文本类型需要重新验证。", "Word lists measure language features in context, not company quality, fraud probability or trading instructions. Other languages and document types require validation."),

  "Trading and Arbitrage in Cryptocurrency Markets": guide(
    "https://researchonline.lse.ac.uk/id/eprint/100409/1/Cryptocurrency_Markets_JFE_final_v4.pdf", "LSE accepted manuscript, abstract and introduction; retained journal DOI identifies final edition.", [
      section("同一种资产，为什么出现不同价格？", "Why can the same asset have different prices?", "Makarov与Schoar把不同交易所的比特币价格放在一起，研究价格偏离为何反复出现、为何没有立即消失。重点是市场之间的连接与资金约束，而不是单个交易所的价格趋势。", "Makarov and Schoar compare bitcoin prices across exchanges to study recurring deviations and why they persist. The focus is connections between markets and constraints on capital, rather than a price trend within one venue."),
      section("跨场所比较需要统一什么？", "What must a venue comparison align?", "研究使用多个国家、多个交易所的逐笔数据，比较境内与跨国价差，并区分共同和场所特有的带方向成交量变化。报价币种、时间同步与场所身份都是比较的前提，不能在聚合时消失。", "The analysis uses tick data across countries and exchanges, compares domestic with international deviations, and distinguishes common from venue-specific signed-volume components. Quote currencies, synchronized time and venue identity are prerequisites, not disposable metadata."),
      section("价格偏离揭示市场分割", "Deviations reveal segmentation", "作者报告跨国价格偏离通常比同国内更大，在比特币快速升值时期共同扩大，并讨论跨境资本流动约束的作用。这些证据说明看到价差并不等于资金能够无摩擦地跨场所移动。", "The paper reports larger deviations across countries than within them, common widening during rapid bitcoin appreciation, and a role for constraints on cross-border capital. Seeing a spread is not equivalent to being able to move capital frictionlessly between venues."),
      section("把价差记录成问题，而非收益承诺", "Treat a spread as a question", "本站建议同时记录价格、手续费、兑换与转移约束、缺失区间和数据时钟，再决定观察到的偏离是什么。本站单一Binance场所的数据只能作为局部材料，不能替代论文的跨交易所样本，更不能证明套利可执行。", "Record prices alongside fees, conversion and transfer constraints, missing periods and data clocks before interpreting a deviation. A single Binance venue is only partial material: it cannot replace this cross-exchange sample or establish executable arbitrage."),
    ], "接受稿与期刊定稿可能存在差异。历史价差不代表当前机会；转账、资本流动、场所风险和可成交数量均需另行评估。", "The accepted manuscript may differ from the journal edition. Historical deviations are not current opportunities; transfers, capital restrictions, venue risk and executable size require separate assessment."),

  "Tokenomics: Dynamic Adoption and Valuation": guide(
    "https://nengwang-economics.com/publications/papers/Cong_Li_Wang_RFS_2020_authorcopy.pdf", "Author copy, abstract and introduction (pp. 1–3); not a full-paper review.", [
      section("从平台使用理解代币价值", "Value through platform use", "作者讨论用于平台交易的代币，而不是把所有加密资产视为同一种资产。平台功能、用户交易需求和网络效应共同影响参与意愿，代币价值因此与平台经济活动相联系，而不是简单照搬股票现金流折现。", "The authors study tokens used for platform transactions, not every cryptoasset as one category. Platform productivity, transaction needs and network effects shape participation. Token value is linked to platform activity rather than mechanically importing an equity cash-flow valuation."),
      section("采用与价格是共同决定的", "Adoption and price are jointly determined", "模型中，用户先决定是否支付参与成本，再决定持有多少代币；代币市场通过需求与固定供给相等而出清。用户更多会增强网络效应，而预期价格变化又影响持有代币的机会成本，形成跨期反馈。", "Users first decide whether to incur participation costs and then choose token balances. Demand clears against fixed supply. More users strengthen network effects, while expected price changes alter the opportunity cost of holding tokens, producing intertemporal feedback."),
      section("S形采用不是价格预测曲线", "An adoption curve is not a price forecast", "论文描述模型中的采用过程由慢到快、再趋缓，并讨论代币如何影响用户规模对生产率冲击的反应。这些结论依赖模型设定，不能把一条S形曲线直接拟合到某代币价格上并声称完成估值。", "Adoption in the model follows an S-shaped path, and tokenization affects how the user base responds to productivity shocks. These conditional model results do not justify fitting an S-curve to a token price and calling it a valuation."),
      section("继续阅读时追踪三个对象", "Track three objects as you read", "本站建议始终分开平台生产率、真实用户活动与交易所价格。钱包地址不必然等于独立用户，交易量也不必然等于平台真实使用。先明确活动定义、供给制度和网络边界，才有可能判断模型讨论的机制是否相关。", "Keep platform productivity, real user activity and exchange prices separate. Wallet addresses need not be unique users, and trading volume need not represent platform use. Define activity, supply rules and network boundaries before judging whether the mechanism applies."),
    ], "固定供给、用户需求和平台功能等假设不能默认成立。这是理论机制导读，不是任何代币的估值、采用速度或价格预测。", "Fixed supply, user demand and platform-function assumptions cannot be presumed. This explains a theoretical mechanism, not a valuation or forecast for any token."),

  "Event Studies in Economics and Finance": guide(
    "https://storage.courtlistener.com/recap/gov.uscourts.txsd.1759270/gov.uscourts.txsd.1759270.250.1.pdf", "Published article reproduced as court exhibit; article pp. 13–16 inspected, not legal analysis.", [
      section("怎样区分事件与市场本身？", "Separating an event from the market", "MacKinlay介绍事件研究如何利用事件附近的证券价格考察经济影响。关键不是只看涨跌，而是先构造“没有这个事件时”的正常收益基准，再观察实际收益与基准的差异。", "MacKinlay reviews how security prices around an event can help study economic effects. The key is not the price move alone: define a normal-return benchmark without conditioning on the event, then compare actual performance with that benchmark."),
      section("事件窗口与估计窗口分开", "Separate event and estimation windows", "先定义事件和样本筛选条件，再确定事件窗口；正常收益模型通常用事件发生前、且不与事件窗口重叠的资料估计。盘后公告的影响可能进入次日，预先泄露或预期也可能体现在事件前，窗口选择因此属于研究设计的一部分。", "Define the event and sample selection before choosing its window. Normal-return models are commonly estimated on earlier, non-overlapping observations. After-hours announcements may affect the next session, while anticipation may appear earlier. Window selection is part of the design."),
      section("异常收益只是分析的起点", "Abnormal returns are a starting point", "计算异常收益后，还需要决定如何跨时间、跨公司汇总，以及如何进行统计推断。作者提醒样本偏差和少数观测的影响。某一天偏离市场，并不能单独证明事件造成了该变化。", "After computing abnormal returns, researchers must decide how to aggregate across time and firms and how to conduct inference. The review highlights selection bias and influential observations. A one-day departure from market performance alone does not prove causation."),
      section("从事件时间线开始准备", "Begin with an event timeline", "本站建议先完成带时区的发布时间、首次可见时间、修订关系和交易日映射，再考虑收益计算。没有这些时点，精细的统计检验也无法修复错位的样本。教程中的时间线示例只完成这一步，不自动输出事件研究结论。", "Prepare timezone-aware release times, first-seen times, revisions and session mapping before computing returns. Statistical sophistication cannot repair a misaligned sample. The accompanying timeline tutorial completes this preparation step without producing an event-study conclusion."),
    ], "并发事件、样本选择和跨公司相关性会影响解释与推断。事件窗口中的相关性不自动构成因果识别。", "Confounding events, selection and cross-firm dependence affect interpretation and inference. Correlation within an event window is not automatic causal identification."),

  "Forecasting the Term Structure of Government Bond Yields": guide(
    "https://elearning.unito.it/sme/pluginfile.php/546632/course/section/90489/DieboldLi_JoE06.pdf", "Published paper, abstract, introduction and methods 2.1–2.2.", [
      section("一条曲线，而不是一个利率", "A curve rather than one rate", "Diebold与Li研究不同期限的国债收益率如何共同变化。把每个期限完全分开，容易忽视曲线整体形状；论文用少数随时间变化的参数表达整条曲线。", "Diebold and Li study joint movements in government-bond yields across maturities. Modeling each maturity independently can miss the curve's overall shape. Their framework represents the curve using a small set of time-varying parameters."),
      section("水平、斜率与曲率", "Level, slope and curvature", "作者在Nelson–Siegel框架中解释三个动态因子，先逐期拟合曲线，再用因子的时间序列模型生成预测。拟合今天的曲线与预测未来的曲线，是两个不同的任务。", "The authors interpret three dynamic factors within the Nelson–Siegel framework, fit curves period by period, and forecast through time-series models of those factors. Fitting today's curve and predicting a future curve are distinct tasks."),
      section("为什么强调样本外比较？", "Why emphasize out-of-sample comparison?", "论文明确关注样本外预测，并报告较长期限预测相对若干基准的改善。阅读时应追问比较窗口、预测期和基准是什么，而不是把拟合误差小直接等同于预测能力强。", "The paper explicitly focuses on out-of-sample forecasting and reports improvements against several benchmarks at longer horizons. Ask which evaluation period, horizon and benchmark support the comparison; low fitting error does not establish forecast skill."),
      section("统一收益率口径后再连接", "Align yield conventions first", "本站建议区分零息收益率、票息债券到期收益率与远期利率，并保留期限单位、复利方式、币种和数据版本。原文讨论的曲线构造不能无说明地替换成任意供应商的一组利率字段。", "Distinguish zero-coupon yields, coupon-bond yields to maturity and forward rates. Preserve maturity units, compounding, currency and data vintage. An arbitrary vendor rate panel is not an undocumented substitute for the paper's curve construction."),
    ], "这套预测表示法不自动保证无套利，也不证明跨国家、制度时期或利率环境的预测表现。", "This forecasting representation does not automatically impose no-arbitrage or establish performance across countries, regimes or rate environments."),
};
