// Per-work preparation links for the original 43 guides. New guides may declare
// their own `related` value. Empty objects intentionally suppress topic defaults.
const recipes = (...ids) => ({ recipes: ids });
const datasets = (...ids) => ({ datasets: ids });
export const researchGuideMaterials = {
  "Common risk factors in the returns on stocks and bonds": recipes("pit-fundamentals-panel", "adjusted-price-series"),
  "Continuous Auctions and Insider Trading": {},
  "The Cross-Section of Expected Stock Returns": recipes("pit-fundamentals-panel"),
  "The Development of China's Stock Market and Stakes for the Global Economy": datasets("cn-equity-daily", "cn-company-master", "cn-market-reference"),
  "Modeling and Forecasting Realized Volatility": { datasets: ["cn-equity-minute"], recipes: ["minute-bar-gaps"] },
  "Intraday Information Efficiency on the Chinese Equity Market": { datasets: ["cn-equity-minute"], recipes: ["minute-bar-gaps"] },
  "Giving Content to Investor Sentiment: The Role of Media in the Stock Market": { datasets: ["cn-news-flashes"], recipes: ["document-version-ledger"] },
  "Trading and Arbitrage in Cryptocurrency Markets": datasets("crypto-binance-spot-5m"),
  "Portfolio Selection": recipes("adjusted-price-series"),
  "Capital Asset Prices: A Theory of Market Equilibrium under Conditions of Risk": recipes("adjusted-price-series"),
  "A Five-Factor Asset Pricing Model": recipes("pit-fundamentals-panel", "adjusted-price-series"),
  "Replicating Anomalies": recipes("pit-fundamentals-panel", "adjusted-price-series"),
  "The Other Side of Value: The Gross Profitability Premium": recipes("pit-fundamentals-panel"),
  "A Simple Implicit Measure of the Effective Bid-Ask Spread in an Efficient Market": {},
  "Measuring the Information Content of Stock Trades": {},
  "Illiquidity and Stock Returns: Cross-Section and Time-Series Effects": datasets("cn-equity-daily"),
  "The Price Impact of Order Book Events": {},
  "A Simple Way to Estimate Bid-Ask Spreads from Daily High and Low Prices": datasets("cn-equity-daily"),
  "A Simple, Positive Semi-Definite, Heteroskedasticity and Autocorrelation Consistent Covariance Matrix": {},
  "Estimating Standard Errors in Finance Panel Data Sets: Comparing Approaches": recipes("pit-fundamentals-panel"),
  "Event Studies in Economics and Finance": { datasets: ["cn-company-actions", "cn-announcements"], recipes: ["company-event-timeline", "adjusted-price-series"] },
  "Using Daily Stock Returns: The Case of Event Studies": { datasets: ["cn-company-actions"], recipes: ["company-event-timeline", "adjusted-price-series"] },
  "Bootstrap Methods: Another Look at the Jackknife": {},
  "Regression Shrinkage and Selection via the Lasso": {},
  "Do Stock Prices Fully Reflect Information in Accruals and Cash Flows about Future Earnings?": { datasets: ["cn-pit-fundamentals"], recipes: ["pit-fundamentals-panel"] },
  "Value Investing: The Use of Historical Financial Statement Information to Separate Winners from Losers": { datasets: ["cn-pit-fundamentals"], recipes: ["pit-fundamentals-panel"] },
  "Earnings, Book Values, and Dividends in Equity Valuation": { datasets: ["cn-pit-fundamentals", "cn-valuation-indicators"], recipes: ["pit-fundamentals-panel"] },
  "The Quality of Accruals and Earnings: The Role of Accrual Estimation Errors": recipes("pit-fundamentals-panel"),
  "Detecting Earnings Management": recipes("pit-fundamentals-panel"),
  "Financial Ratios, Discriminant Analysis and the Prediction of Corporate Bankruptcy": { datasets: ["cn-pit-fundamentals", "cn-valuation-indicators"], recipes: ["pit-fundamentals-panel"] },
  "In Search of Distress Risk": recipes("pit-fundamentals-panel", "adjusted-price-series"),
  "Corporate Governance and Equity Prices": {},
  "When Is a Liability Not a Liability? Textual Analysis, Dictionaries, and 10-Ks": recipes("document-version-ledger"),
  "Measuring Economic Policy Uncertainty": recipes("document-version-ledger"),
  "Investor Sentiment and the Cross-Section of Stock Returns": {},
  "Lazy Prices": recipes("document-version-ledger"),
  "Bond Risk Premia": datasets("cn-yield-curve"),
  "Parsimonious Modeling of Yield Curves": datasets("cn-yield-curve"),
  "Forecasting the Term Structure of Government Bond Yields": datasets("cn-yield-curve"),
  "The Real Value of China's Stock Market": datasets("cn-equity-daily", "cn-company-master", "cn-market-reference"),
  "Risks and Returns of Cryptocurrency": datasets("crypto-binance-spot-5m"),
  "Bitcoin: Economics, Technology, and Governance": {},
  "Tokenomics: Dynamic Adoption and Valuation": {},
};
