import { researchEditorial } from "./researchEditorial.js";

// Reviewed additions reuse the original four sections without mutating them.
// Evidence scope is internal; section references are reader-facing source aids.
const bi = (zh, en) => ({ zh, en });
const section = (zh, en, bodyZh, bodyEn, url, locatorZh, locatorEn) => ({
  title: bi(zh, en), body: bi(bodyZh, bodyEn),
  reference: { url, label: bi(locatorZh, locatorEn) },
});
const urls = {
  crossSection: "https://www.ivey.uwo.ca/media/3775518/the_cross-section_of_expected_stock_returns.pdf",
  factors: "https://www.bauer.uh.edu/rsusmel/phd/Fama-French_JFE93.pdf",
  spreadProgram: "https://sites.nd.edu/scorwin/files/2019/08/Sample-SAS-Program-Description.pdf",
  spreadAppendix: "https://sites.nd.edu/scorwin/files/2019/11/Internet-Appendix_FINAL.pdf",
  replication: "https://www.nber.org/system/files/working_papers/w23394/w23394.pdf",
  china: "https://www.sciencedirect.com/science/article/abs/pii/S0304405X20302403",
  intraday: "https://www.sciencedirect.com/science/article/abs/pii/S1043951X0900039X",
  filings: "https://www.nber.org/system/files/working_papers/w25084/w25084.pdf",
  bitcoin: "https://www.benedelman.org/publications/bitcoin-15jul2014.pdf",
  panels: "https://www.nber.org/system/files/working_papers/w11280/w11280.pdf",
  curve: "https://www.nber.org/system/files/working_papers/w1594/w1594.pdf",
  premia: "https://web.stanford.edu/~piazzesi/cp.pdf",
  kyle: "https://people.duke.edu/~qc2/BA532/1985%20EMA%20Kyle.pdf",
  media: "https://www.columbia.edu/~pt2238/papers/Tetlock_Media_Sentiment_JF.pdf",
  exchanges: "https://researchonline.lse.ac.uk/id/eprint/100409/1/Cryptocurrency_Markets_JFE_final_v4.pdf",
  events: "https://storage.courtlistener.com/recap/gov.uscourts.txsd.1759270/gov.uscourts.txsd.1759270.250.1.pdf",
};

const additions = {
  "Parsimonious Modeling of Yield Curves": {
    evidenceUrl: urls.curve,
    evidenceScope: "March 1985 NBER Working Paper 1594, Sections 2–3 and 5: conditional linear estimation and maturity extrapolation. Original scanned PDF pages 10, 13–14 and 22–23 visually inspected against extracted text. Final 1987 publication identity retained; no final-edition numerical findings or replication claim.",
    limits: bi("方法细节依据1985年NBER工作论文，书目信息保留1987年终刊。曲线拟合不保证跨期限外推可靠，也不等于无套利证明或未来预测能力。", "Method details use the 1985 NBER working paper; the citation identifies the 1987 journal publication. Curve fit does not establish reliable maturity extrapolation, no-arbitrage or future forecasting performance."),
    sections: [
      section("先固定衰减尺度，再估计系数", "Fix the decay scale before estimating coefficients",
        "1985年工作论文把估计分成两层：给定衰减参数后，其余三个系数可用线性最小二乘求得，再比较不同衰减参数下的拟合。该参数影响曲率集中在哪些期限；它不是无关紧要的设置。因此，“三个线性系数”不意味着整个估计问题只有三个待定量。",
        "The 1985 working paper separates estimation into two layers. Conditional on a decay parameter, three coefficients follow from linear least squares; fit is then compared across decay values. The decay scale affects where curvature can occur along maturity. Three linear coefficients therefore do not mean that only three quantities must be chosen.",
        urls.curve, "1985年工作论文第2–3节，正文第8、11–12页", "1985 working paper §§2–3, printed pp. 8, 11–12"),
      section("这里的样本外，是跨期限外推", "Out of sample here means extrapolating across maturities",
        "工作论文第5节用短期国库券拟合的曲线为长期债券定价，检验的是超出已有期限范围后的表现，不是未来日期的预测。文中说明，局部拟合相近的参数可能给出差别很大的长期贴现率。阅读这类检验时，要先分清留出的是期限还是时间，不能把二者当成同一种预测证据。",
        "Section 5 of the working paper prices a long bond using a curve fitted to short bills. Its extrapolation leaves the observed maturity range, not the observation date. Similar short-end fits can imply very different long-term discount rates. Distinguish a held-out maturity from a future date before interpreting either exercise as forecast evidence.",
        urls.curve, "1985年工作论文第5节，正文第20–21页", "1985 working paper §5, printed pp. 20–21"),
    ],
  },
  "The Cross-Section of Expected Stock Returns": {
    evidenceUrl: urls.crossSection,
    evidenceScope: "Original article introduction and Sections I.A–I.B, pp. 427–432: sample inclusion, accounting alignment, portfolio beta assignment and cross-sectional design. No numerical table audit or replication.",
    sections: [
      section("两个市值日期，各有用途", "Two capitalization dates serve different roles",
        "样本取CRSP与COMPUSTAT交集中的非金融企业。作者用上一年12月市值计算账面市值比等比率，用本年6月市值衡量规模，再对应7月起的收益。财务年度、比率分母日期和分组日期因此不是同一个时间；混用它们就改变了比较对象。",
        "The sample intersects CRSP and COMPUSTAT for nonfinancial firms. Prior-December capitalization enters accounting ratios; June capitalization measures size before returns beginning in July. Fiscal year, ratio denominator date and sorting date therefore play distinct roles. Collapsing them into one date changes the comparison.",
        urls.crossSection, "原文第I.A节：样本与日期对齐", "Original §I.A: sample and date alignment"),
      section("组合贝塔不是当时的个股预测", "Portfolio betas are not contemporaneous forecasts",
        "作者先按规模与预排序贝塔分组，再把组合的全样本后排序贝塔赋给组内股票，用于逐月横截面检验。这样做旨在提高测量精度，不是为每个历史时点生成可实时使用的输入。若改做时点一致分析，贝塔估计窗口也必须限制在当时已知的数据内。",
        "Stocks receive full-sample post-ranking betas from portfolios formed on size and pre-ranking beta. This improves measurement for monthly cross-sectional tests; it does not create real-time historical inputs. Editorial application: a point-in-time design must separately restrict beta estimation to observations already available at each date.",
        urls.crossSection, "原文第I.B.1节：贝塔估计与赋值", "Original §I.B.1: beta estimation and assignment"),
    ],
  },
  "Common risk factors in the returns on stocks and bonds": {
    evidenceUrl: urls.factors,
    evidenceScope: "Original introduction and Section 2.1: stock/bond factor roles, TERM/DEF definitions and size/book-to-market grouping. No factor reconstruction or numeric table audit.",
    sections: [
      section("债券因子是收益差，不是收益率差", "Bond factors are return differences, not yield spreads",
        "论文的TERM用长期国债月收益减去上月末已知的一月期国库券利率；DEF用长期公司债组合收益减去长期国债收益。这两个定义都依赖持有期回报，不能直接用两条到期收益率相减替代。债券价格、期限与回报口径需要先核对。",
        "TERM subtracts the previously observed one-month bill rate from the monthly long-government-bond return. DEF subtracts the long-government-bond return from the long-corporate-bond portfolio return. These are holding-period return constructions, not interchangeable with differences between quoted yields. Price, tenor and return conventions matter.",
        urls.factors, "原文第2.1.1节：债券市场因子", "Original §2.1.1: bond-market factors"),
      section("解释共同波动与解释平均水平", "Common variation and average returns are separate tests",
        "时间序列回归中的载荷与拟合度考察共同波动，截距则帮助检验平均超额收益是否仍未被解释。高拟合度并不自动意味着截距为零，也不证明唯一的经济机制。阅读时把这两类证据分别记录，才能理解论文为何同时讨论股票与债券。",
        "Loadings and fit in time-series regressions describe shared variation; intercepts test whether average excess returns remain unexplained. High fit does not automatically imply zero intercepts or establish a unique economic mechanism. Keeping these tests separate clarifies the paper's joint treatment of stocks and bonds.",
        urls.factors, "原文引言：时间序列检验的两个问题", "Original introduction: two questions for time-series tests"),
    ],
  },
  "A Simple Way to Estimate Bid-Ask Spreads from Daily High and Low Prices": {
    evidenceUrl: urls.spreadProgram,
    evidenceScope: "2012 author-issued sample-program description read completely; internet appendix contents and explanatory captions on data adjustments inspected. Publisher abstract retained for conceptual interpretation. Main-paper derivation and empirical tables not reviewed.",
    limits: bi("高低价法是依赖清洗约定的价差代理。本导读结合作者配套说明，不复现主文推导；它不能替代真实报价、订单簿或成交成本。", "The proxy depends on cleaning conventions. This guide uses the authors' companion instructions, not a replication of the derivation; it does not replace quotes, an order book or execution costs."),
    replacements: {
      2: { body: bi("论文比较低频价差估计与高频有效价差，作者配套材料还区分逐月横截面和逐股时间序列的比较。两类比较回答的问题不同；即使总体误差较小，单日、单股的估计仍不等于可成交成本，数量、冲击和费用也需另行考虑。", "The paper compares low-frequency estimates with high-frequency effective spreads. Its companion material separates monthly cross-sectional and stock-level time-series comparisons. Those answer different questions: aggregate accuracy does not make a daily estimate executable, and size, impact and fees remain separate.") },
    },
    sections: [
      section("实际输入不止最高与最低价", "Practical inputs extend beyond highs and lows",
        "作者示例程序要求证券身份、日期、月份及拆股调整后的最高、最低和收盘价，成交量可用于识别无交易日。程序先处理无效区间，再调整隔夜收益，最后计算价差。因此，把未经检查的日高低价直接代入一个公式，并不等于使用了完整方法。",
        "The authors' sample program requires security identity, date, month and split-adjusted high, low and closing prices; volume can identify nontrading days. Invalid ranges and overnight returns are handled before estimation. Feeding unchecked daily extremes into a formula therefore does not reproduce the documented procedure.",
        urls.spreadProgram, "作者程序说明：输入与步骤1–2", "Author program description: inputs and steps 1–2"),
      section("零值可能来自规则，而非无成本交易", "A zero can reflect a rule, not costless trading",
        "配套程序把负的日价差估计设为零，并要求一个月至少有12个观测；附录还说明了部分缺失高低价的替代处理。编辑建议：保留原始值与每次调整标记，区分缺失、替代和截断后的零。这个专用估计规则不能推广成所有行情缺口的自动填补规则。",
        "The companion program floors negative daily estimates at zero and requires at least 12 observations per month; the appendix also describes replacement of some missing extremes. Editorial application: retain raw values and adjustment flags. Missing, substituted and floored-zero values differ, and this estimator-specific convention is not a general gap-filling rule.",
        urls.spreadAppendix, "作者附录表IA.I说明与程序步骤3–4", "Author appendix Table IA.I notes; program steps 3–4"),
    ],
  },
  "Replicating Anomalies": {
    evidenceUrl: urls.replication,
    evidenceScope: "2017 NBER working paper introduction and Sections 3–3.1.1: sample construction, timing, breakpoints, weighting and delisting treatment. Final journal identity retained; no draft anomaly counts or effect magnitudes presented as final.",
    sections: [
      section("统一样本，也统一信息时钟", "Harmonize samples and information clocks",
        "2017年工作论文将CRSP月收益与COMPUSTAT财务资料连接。年度分组使用上一财年的资料；月度分组则区分已公告盈余与其他季度会计项目，后者采用四个月滞后。这个区分承认盈余新闻稿不一定同时披露资产负债表，不能把所有字段都视为同一天可得。",
        "The 2017 working paper joins CRSP monthly returns with COMPUSTAT accounts. Annual sorts use prior-fiscal-year data; monthly sorts distinguish announced earnings from other quarterly items, for which a four-month lag is imposed. Earnings releases need not contain balance sheets, so all accounting fields cannot share an assumed availability date.",
        urls.replication, "2017年工作论文第3–3.1节：信息滞后", "2017 working paper §§3–3.1: information lags"),
      section("退市处理也属于复现合同", "Delisting treatment belongs in the replication contract",
        "作者单独说明如何合并CRSP退市收益，以及缺失退市收益的处理。编辑建议：除记录断点和权重，还应列明退出样本的原因、退市回报来源与替代规则。只保留持续上市企业，或者把退市缺失值静默设为零，都会改变正在比较的实验。",
        "The authors document how CRSP delisting returns are combined with ordinary returns and how missing delisting observations are handled. Editorial application: record exit reasons, sources and substitution rules alongside breakpoints and weights. Keeping only surviving listings or silently replacing missing delisting returns with zero changes the experiment.",
        urls.replication, "2017年工作论文第3.1节：退市收益处理", "2017 working paper §3.1: delisting-return treatment"),
    ],
  },
  "The Real Value of China's Stock Market": {
    evidenceUrl: urls.china,
    evidenceScope: "Final publisher introduction and section previews read: 1995–2016 design, predicted variation, ownership comparisons and forecasting versus revelatory price efficiency. Full regression tables unavailable; no causal or replication claim.",
    sections: [
      section("信息含量不是指数与GDP的相关性", "Informativeness is not an index–GDP correlation",
        "作者依据未来企业盈利对既往价格的横截面回归，用预测部分的变动衡量价格信息含量。研究单位是企业及其后续经营结果，而不是全国指数与GDP两条曲线。即使都被称为“市场效率”，不同指标的分母、时间跨度和解释对象也可能完全不同。",
        "The study measures informativeness through predicted variation in cross-sectional regressions of future firm profits on earlier prices. Its unit is a firm and its subsequent operations, not an aggregate index–GDP comparison. Measures sharing the label 'market efficiency' can differ in scaling, horizon and the object being explained.",
        urls.china, "期刊版引言：信息含量的度量", "Journal-version introduction: informativeness measure"),
      section("价格知道信息，与经理从中学习", "Information in prices versus managers learning from prices",
        "论文进一步比较价格与未来盈利、价格与未来投资之间的联系。作者用后者讨论价格是否向经理提供新增信息，并强调价值最大化假设对民营企业更适用。观察到两个联系同步变化仍需结合模型解释，不能把它直接写成某项改革造成投资效率提升的因果证明。",
        "The paper compares price–future-profit and price–future-investment links to ask whether prices convey incremental information to managers. The value-maximization assumption is more appropriate for private firms in its framework. Comovement between these links still needs that model interpretation; it is not direct causal identification of a reform's effect.",
        urls.china, "期刊版引言：预测效率与信息启示效率", "Journal-version introduction: forecasting and revelatory efficiency"),
    ],
  },
  "Intraday Information Efficiency on the Chinese Equity Market": {
    evidenceUrl: urls.intraday,
    evidenceScope: "Final publisher abstract, introduction and previews of Market structure, Intraday trading costs and Unbiasedness regressions. No access to complete regression specification or numerical table audit.",
    sections: [
      section("历史交易阶段是样本的一部分", "Historical session phases are part of the sample",
        "原文市场结构段落区分早盘开盘集合竞价、上午连续交易、午间休市和下午交易。编辑建议：为2004—2005年样本保留当时的阶段标签，不把午休当作随机缺失，也不要直接套用今日制度。相同钟点在不同交易阶段，可能代表不同的信息环境。",
        "The market-structure passage separates the opening call auction, morning continuous trading, lunch closure and afternoon trading. Editorial application: retain historical phase labels for the 2004–2005 sample. Lunch is not a random gap, and present-day rules should not be assumed. Clock time alone does not identify the information environment.",
        urls.intraday, "期刊页面章节预览：Market structure", "Journal section preview: Market structure"),
      section("先分清价差问题与无偏性问题", "Spreads and unbiasedness ask different questions",
        "交易成本分析关心买卖价差，而无偏性回归考察日内价格与后续价格发现的关系。出版方预览说明后者使用收盘到收盘收益作为被解释对象。编辑建议：分别记录报价配对、收益基准和观测时点；价差较小不能单独证明价格已吸收全部信息。",
        "Trading-cost analysis concerns spreads, while unbiasedness regressions examine intraday prices relative to subsequent price discovery. The publisher preview identifies close-to-close returns as the dependent object. Editorial application: document quote matching, return benchmarks and observation times separately. A narrow spread alone does not establish complete information incorporation.",
        urls.intraday, "期刊页面章节预览：Unbiasedness regressions", "Journal section preview: Unbiasedness regressions"),
    ],
  },
  "Lazy Prices": {
    evidenceUrl: urls.filings,
    evidenceScope: "March 2019 NBER revision abstract and introduction, including illustrative disclosure timing and discussion of MD&A versus risk-factor changes. No similarity formula or numeric return claims; final publication identity kept distinct.",
    limits: bi("导读补充依据2019年3月工作论文；正式出版身份不变。文本变化不必然是坏消息，英文样本也不能直接验证中文指标或当前表现。", "Added reading detail uses the March 2019 working paper, separately from the final publication identity. Change is not automatically bad news; English-sample evidence does not validate Chinese measures or current performance."),
    sections: [
      section("报告所属年度不是读者看到的日期", "The reporting year is not the release date",
        "2019年工作论文考察1995—2014年的定期披露，并用Baxter案例说明：一份标为2009年度的报告实际在2010年公开，之后又出现相关新闻。编辑建议：同时保存报告期、提交时间和后续消息时间，不能将年度标签当作报告已可阅读的日期。",
        "The March 2019 working paper studies recurring disclosures from 1995–2014. Its Baxter illustration distinguishes a report for 2009 from its public filing in 2010 and subsequent news. Editorial application: preserve reporting period, filing time and later-news time separately; a fiscal-year label does not establish public availability.",
        urls.filings, "2019年3月工作论文引言：Baxter披露案例", "March 2019 working-paper introduction: Baxter disclosure example"),
      section("变化多的章节，不一定最有信息", "Frequent change need not be the most informative change",
        "作者在引言中区分变化集中出现的管理层讨论章节，与对后续结果更有信息的风险因素等内容。编辑建议：比较总文本变化之外，还要保留章节边界，并抽查新增、删除和修改的实际语句。一个整体相似度分数，无法独自说明变化属于经营风险还是例行编辑。",
        "The introduction distinguishes MD&A, where many changes occur, from sections such as risk factors that contain informative changes. Editorial application: preserve section boundaries and inspect additions, deletions and revisions alongside aggregate similarity. One whole-document score cannot by itself distinguish operating-risk disclosure from routine editing.",
        urls.filings, "2019年3月工作论文引言：章节差异", "March 2019 working-paper introduction: differences across sections"),
    ],
  },
  "Bitcoin: Economics, Technology, and Governance": {
    evidenceUrl: urls.bitcoin,
    evidenceScope: "Author-hosted July 15, 2014 draft: Enabling Technologies, The Role of Cryptography and Incentives for Participation. Final 2015 publisher abstract checked for identity/conceptual scope. Historical statistics, current security and current legal claims excluded.",
    limits: bi("导读结合2014年作者草稿与2015年综述摘要，仅解释历史设计思路，不提供当前协议、安全、监管或投资判断。", "The guide combines the 2014 author draft with the 2015 overview abstract to explain historical design ideas, not current protocol, security, regulatory or investment conditions."),
    sections: [
      section("签名解决授权，账本解决记录", "Signatures authorize; the ledger records",
        "作者草稿将两个问题分开：数字签名帮助验证支出的授权，分布式交易记录帮助追踪输入与此前输出的联系。签名并不负责隐藏整份交易历史，也不证明现实中的法律身份。理解这一区别，才能避免把“使用密码学”直接理解成所有交易内容都被加密保密。",
        "The author draft separates authorization through digital signatures from recording transactions whose inputs refer to earlier outputs. A signature does not conceal the entire transaction history or establish a real-world legal identity. Cryptographic verification and secrecy are therefore different properties, not interchangeable descriptions of the system.",
        urls.bitcoin, "2014年作者草稿：Enabling Technologies / The Role of Cryptography", "2014 author draft: Enabling Technologies / The Role of Cryptography"),
      section("激励机制同时带来资源成本", "Participation incentives also consume resources",
        "草稿把工作量证明与维护账本的激励联系起来：同一机制既提高伪造参与的成本，也奖励记录维护者，但计算活动消耗现实资源。阅读重点是激励、竞争与成本之间的关系；文中的历史奖励和能耗数字不能作为今天的参数，更不能只由交易价格判断网络运行状况。",
        "The draft links proof of work to incentives for maintaining the shared record: the mechanism makes fabricated participation costly and rewards record maintenance, while computation consumes resources. The useful reading is about incentives, competition and costs. Historical reward and energy figures are not current parameters, and exchange prices alone do not describe network operation.",
        urls.bitcoin, "2014年作者草稿：Incentives for Participation", "2014 author draft: Incentives for Participation"),
    ],
  },
  "Estimating Standard Errors in Finance Panel Data Sets: Comparing Approaches": {
    evidenceUrl: urls.panels,
    evidenceScope: "June 2006 NBER revision introduction and Section II.A assumptions; author final-publication page checked. Firm/time-effect comparison and fixed-effect caveat, not final-edition table magnitudes or universal prescriptions.",
    limits: bi("补充细节来自2006年工作论文，正式发表身份保留。依赖方向、分组数量与模型设定决定适用方法，没有一种标准误对所有数据都正确。", "Additional detail comes from the 2006 working paper, separately from its final publication identity. Dependence direction, cluster counts and specification matter; no standard-error method is universally correct."),
    sections: [
      section("分别构造公司效应与时间效应", "Separate firm effects from time effects",
        "工作论文先模拟同一公司跨期相关，再模拟同一时期跨公司相关，随后把两者组合。Fama–MacBeth与按公司聚类针对的依赖结构不同，因此不能因为两者都常见就互换。比较结果之前，先指出你的数据可能在哪个方向共享误差。",
        "The working paper first simulates within-firm dependence, then within-period dependence across firms, before combining them. Fama–MacBeth and firm-clustered inference address different dependence patterns; their popularity does not make them interchangeable. Identify which observations may share errors before comparing reported significance.",
        urls.panels, "2006年工作论文引言：第II–IV节的比较设计", "2006 working-paper introduction: design of Sections II–IV"),
      section("标准误修正不能修复解释变量内生性", "An uncertainty correction does not fix endogeneity",
        "第II.A节为说明标准误问题，明确假设模型设定正确，解释变量与误差独立。这使讨论聚焦于相关误差带来的不确定性。编辑建议：将这一前提单列；即使聚类方式合适，遗漏变量、反向因果或错误时间对齐仍可能影响系数，不能被一个“稳健”标签消除。",
        "Section II.A assumes a correctly specified model with regressors independent of errors to isolate the uncertainty problem. Editorial application: state that premise separately. Appropriate clustering does not remove coefficient problems arising from omitted variables, reverse causality or incorrect timing; the word 'robust' is not a general identification guarantee.",
        urls.panels, "2006年工作论文第II.A节：模型前提", "2006 working paper §II.A: model assumptions"),
    ],
  },
  "Bond Risk Premia": {
    evidenceUrl: urls.premia,
    evidenceScope: "Original introduction and Sections I.A–I.C: zero-coupon inputs, one-year excess-return definitions, restricted single-factor estimation and overlapping-horizon inference. No numerical table audit or current prediction claim.",
    sections: [
      section("持有一年后，债券期限也变短一年", "A year of holding also shortens maturity",
        "原文使用Fama–Bliss一至五年零息债券价格。买入一只n年债券，一年后卖出时它已是n−1年债券；持有期对数收益再减去期初一年期利率，才得到这里的超额收益。用同一期限收益率的年度变化代替，会漏掉滚动期限与价格转换。",
        "The paper uses Fama–Bliss zero-coupon prices for one- through five-year maturities. An n-year bond becomes an n−1-year bond when sold one year later; its log holding return is then reduced by the initial one-year rate. A change in a constant-maturity yield is not that return calculation.",
        urls.premia, "原文第I.A–I.B节：定义与零息价格", "Original §§I.A–I.B: definitions and zero-coupon prices"),
      section("月度观测的一年收益会重叠", "Monthly observations of annual returns overlap",
        "每个月向前看一年，相邻观测会共享大部分持有月份，因此样本行数不能当作独立年度实验次数。第I.C节专门比较重叠收益下的统计处理。作者也用滞后的远期利率检查共用价格测量误差；这与简单增加观测数量是不同的稳健性问题。",
        "Rolling a one-year horizon forward monthly makes adjacent observations share most holding months. Row count is therefore not a count of independent annual experiments. Section I.C examines overlapping-return inference, while lagged forward rates address shared-price measurement error. These are distinct checks, not benefits obtained merely by adding rows.",
        urls.premia, "原文第I.C节及引言：重叠窗口与测量误差", "Original §I.C and introduction: overlap and measurement error"),
    ],
  },
  "Continuous Auctions and Insider Trading": {
    evidenceUrl: urls.kyle,
    evidenceScope: "Original article Section 1, pp. 1315–1317: two-step auction, information sets, competitive pricing and continuous-limit interpretation. Formal proofs and empirical calibration not reviewed.",
    sections: [
      section("每次拍卖先提交数量，再确定价格", "Quantities precede pricing in each auction",
        "模型中知情者与噪声交易者先同时选择数量，做市者随后观察合并后的订单流并定价。做市者看不到两类交易的单独数量，知情者下单时也不知道当次噪声订单。把这些信息集合分清，才能理解噪声为何掩护私人信息，以及价格为何随订单流更新。",
        "The insider and noise traders choose quantities simultaneously; market makers then observe combined order flow and set a price. Makers cannot separate the two components, and the insider does not know the current noise order when choosing a quantity. These information sets explain both concealment and price updating.",
        urls.kyle, "原文第1节：两步拍卖与信息集合", "Original §1: two-step auction and information sets"),
      section("这里的深度不是盘口档位数量", "Model depth is not a count of order-book levels",
        "做市者按其信息条件下的资产清算价值期望定价，订单流因此与价格变化联系起来。连续交易极限中的恒定深度是这一均衡的性质，不是承诺现实盘口总有同样厚度。编辑建议：实证代理应写清交易方向、价格变化和采样间隔，不能用总成交量直接替代模型订单流。",
        "Competitive makers price at expected liquidation value conditional on their information, linking flow to price changes. Constant depth in the continuous limit is an equilibrium property, not a claim that displayed books always have equal thickness. Editorial application: specify trade direction, price changes and sampling; aggregate volume is not the model's signed flow.",
        urls.kyle, "原文第1节：竞争性定价与连续交易极限", "Original §1: competitive pricing and continuous limit"),
    ],
  },
  "Giving Content to Investor Sentiment: The Role of Media in the Stock Market": {
    evidenceUrl: urls.media,
    evidenceScope: "Author-hosted original introduction and Section II: Harvard IV-4 categories, weekday centering, annual PCA timing and factor interpretation. No VAR rerun, table audit or transfer of measurement validity to other corpora.",
    sections: [
      section("词典类别不是互斥标签", "Dictionary categories are not exclusive labels",
        "第II节说明General Inquirer词典类别既不互斥，也不覆盖所有词；一个词可能进入多个类别。作者还调整星期几对应的类别均值，避免专栏的规律性写作差异主导因子。编辑建议：保留词典版本、计数口径与日历处理，不把各类别计数直接加成独立词数。",
        "Section II states that General Inquirer categories overlap and do not cover every word. Category means are also centered by weekday to reduce systematic writing-pattern noise. Editorial application: preserve dictionary versions, counting conventions and calendar treatment; summing category counts does not yield a count of distinct classified words.",
        urls.media, "原文第II节：词语分类与星期效应", "Original §II: word categories and weekday effects"),
      section("先确定载荷，再计算下一年的文本指标", "Estimate loadings before scoring the next year",
        "作者用t−1年的文本估计主成分载荷，再用这些载荷计算t年的每日因子，避免把未来语料信息带入当期度量。这个因子从词语类别的共同变化中提取，不以股票收益作为拟合目标。若改用全样本一次性训练，就改变了原研究的信息边界。",
        "Loadings estimated from year t−1 score daily content in year t, keeping future corpus information out of contemporaneous measurement. The factor extracts variation among word categories rather than optimizing against stock returns. Training once on the complete historical corpus would change that information boundary.",
        urls.media, "原文第II节：逐年主成分估计", "Original §II: annual principal-component estimation"),
    ],
  },
  "Trading and Arbitrage in Cryptocurrency Markets": {
    evidenceUrl: urls.exchanges,
    evidenceScope: "LSE accepted manuscript introduction and Section 2: Kaiko venue coverage, Jan 2017–Feb 2018 window, transaction fields and capital-repatriation mechanism. Final publication identity retained; no current spread or executable-profit claim.",
    sections: [
      section("原始观测是带场所身份的成交", "The observations are venue-specific trades",
        "接受稿第2节说明主要资料来自Kaiko，覆盖17家大型交易所，分析窗口为2017年1月1日至2018年2月28日。记录包含成交时间、价格、数量和买卖发起方向。它不是把几家网站的日收盘价拼在一起；场所、报价币和时钟对齐共同决定比较是否有意义。",
        "Section 2 of the accepted manuscript describes Kaiko trades from 17 large exchanges, focusing on January 1, 2017–February 28, 2018. Fields include timestamps, prices, amounts and initiation direction. This is not a panel of website daily closes: venue identity, quote currency and synchronized clocks jointly define a meaningful comparison.",
        urls.exchanges, "接受稿第2节：数据描述", "Accepted manuscript §2: data description"),
      section("完成一次交易，不等于资金可以循环", "One completed trade is not a repeatable capital cycle",
        "作者用跨国交易说明，低价地区买入、高价地区卖出后，所得法币可能难以汇回最初地区，资金因而被困在交易的一端。这个机制把数字资产转移与法币回流分开。编辑建议：记录价差时也记录结算币种与转移限制，不把账面价格差当作可反复实现的收益。",
        "The authors distinguish moving crypto from repatriating fiat: after buying in a low-price region and selling in a high-price region, proceeds may be difficult to return to the starting market. Capital can become trapped. Editorial application: retain settlement currencies and transfer constraints rather than treating a quoted spread as repeatedly realizable profit.",
        urls.exchanges, "接受稿引言：法币回流与市场分割", "Accepted manuscript introduction: fiat repatriation and segmentation"),
    ],
  },
  "Event Studies in Economics and Finance": {
    evidenceUrl: urls.events,
    evidenceScope: "Original article reproduced as exhibit, Sections 2–4: study sequence, earnings-announcement example and statistical/economic normal-return models. Exhibit legal context excluded; no numerical table audit.",
    sections: [
      section("先定义意外消息，而不是先按涨跌分组", "Define the news surprise before grouping by returns",
        "原文用季度盈余公告举例，研究对象是1989—1993年道指30家公司的公告，并依据实际盈余与预期的差异区分消息。编辑建议：事件分类要来自事先定义的信息，不能看到股价上涨后再把公告标为好消息，否则分类本身已包含了要解释的结果。",
        "The illustrative study concerns quarterly earnings announcements for 30 Dow firms in 1989–1993, classifying news by actual earnings relative to expectations. Editorial application: define event categories from a prespecified information measure, not the observed price response. Labeling rising-price events as good news embeds the outcome in the classification.",
        urls.events, "原文第3节：盈余公告示例", "Original §3: earnings-announcement example"),
      section("经济模型也需要统计假设", "Economic models still require statistical assumptions",
        "第4节把正常收益模型区分为统计型与经济型：前者主要依赖收益过程假设，后者加入经济行为限制，但实际使用仍需要统计设定。选择更复杂的模型不是自动获得更强识别；应说明基准、估计期和残差性质为何适合这一类事件。",
        "Section 4 distinguishes statistical normal-return models from models imposing economic restrictions. Economic models still need statistical assumptions in practice. Complexity is not automatic identification strength: explain why the benchmark, estimation window and residual assumptions are appropriate for the event class being studied.",
        urls.events, "原文第4节：正常收益模型", "Original §4: models of normal performance"),
    ],
  },
};

export const researchGuideDepthExpansion = Object.fromEntries(
  Object.entries(additions).map(([title, addition]) => {
    const original = researchEditorial[title];
    const retained = original.sections.map((item, index) => ({ ...item, ...addition.replacements?.[index] }));
    return [title, {
      ...original,
      reviewedAt: "2026-08-30",
      evidenceUrl: addition.evidenceUrl,
      evidenceScope: addition.evidenceScope,
      ...(addition.limits ? { limits: addition.limits } : {}),
      sections: [retained[0], addition.sections[0], retained[1], retained[2], addition.sections[1], retained[3]],
    }];
  }),
);
