// Authored reading notes, not publisher abstracts. Metadata is resolved separately.
// title | Chinese reading title | first-author hint | year | topic | English orientation | Chinese orientation | English inputs | Chinese inputs
const rows = `
A Comprehensive Look at The Empirical Performance of Equity Premium Prediction|股权溢价预测的实证表现评估|Welch|2008|research-methods|Compares published predictors using a consistent out-of-sample evaluation framework.|用一致的样本外评估框架比较已发表的预测变量。|historical predictors; release dates; returns; expanding windows|历史预测变量；发布日期；收益；扩展窗口
Portfolio Selection|投资组合选择|Markowitz|1952|asset-pricing|Introduces the joint role of expected returns, variances, and covariances in portfolio analysis.|从预期收益、方差与协方差出发，理解组合分析为何需要联合分布。|asset returns; covariance matrix; sampling window|资产收益；协方差矩阵；采样窗口
Capital Asset Prices: A Theory of Market Equilibrium under Conditions of Risk|资本资产价格：风险条件下的市场均衡理论|Sharpe|1964|asset-pricing|Frames expected returns through systematic risk and an equilibrium market portfolio.|用系统性风险与市场组合界定预期收益的理论参照。|asset returns; market proxy; risk-free series|资产收益；市场代理；无风险序列
The Valuation of Risk Assets and the Selection of Risky Investments in Stock Portfolios and Capital Budgets|风险资产估值与风险投资选择|Lintner|1965|asset-pricing|Develops an equilibrium account of risk pricing and portfolio choice.|研究风险如何进入资产定价与组合选择的均衡框架。|asset returns; market weights; risk-free rate|资产收益；市场权重；无风险利率
An Intertemporal Capital Asset Pricing Model|跨期资本资产定价模型|Merton|1973|asset-pricing|Adds changing investment opportunities and hedging demands to asset-pricing analysis.|将投资机会变化与跨期对冲需求纳入资产定价分析。|returns; state variables; investment horizon|收益；状态变量；投资期限
The Arbitrage Theory of Capital Asset Pricing|资本资产定价的套利理论|Ross|1976|asset-pricing|Relates a factor structure in returns to restrictions implied by no-arbitrage.|考察收益因子结构与无套利条件对价格关系的约束。|return panel; factor exposures; residual covariance|收益面板；因子暴露；残差协方差
Risk, Return, and Equilibrium: Empirical Tests|风险、收益与均衡：实证检验|Fama|1973|asset-pricing|Introduces cross-sectional testing of the relation between estimated risk and average returns.|展示如何在横截面上检验风险估计与平均收益之间的关系。|security returns; portfolio formation dates; betas|证券收益；组合形成日期；贝塔估计
The Equity Premium: A Puzzle|股权溢价之谜|Mehra|1985|asset-pricing|Compares historical equity premia with a representative-agent consumption model.|将历史股权溢价与代表性投资者的消费模型进行比较。|equity returns; consumption; safe-asset returns|股票收益；消费；安全资产收益
Asset Prices in an Exchange Economy|交换经济中的资产价格|Lucas|1978|asset-pricing|Builds a consumption-based equilibrium model linking payouts and asset prices.|构建以消费为基础的均衡模型，连接资产支付与价格。|consumption; dividends; state transitions|消费；股息；状态转移
Habit Formation: A Resolution of the Equity Premium Puzzle|习惯形成与股权溢价之谜|Constantinides|1990|asset-pricing|Examines how consumption habits alter risk preferences in asset-pricing models.|研究消费习惯如何改变资产定价模型中的风险偏好。|consumption history; equity returns; model parameters|消费历史；股票收益；模型参数
By Force of Habit: A Consumption-Based Explanation of Aggregate Stock Market Behavior|习惯的力量：股票市场行为的消费解释|Campbell|1999|asset-pricing|Uses habit dynamics to connect consumption risk with aggregate market fluctuations.|利用习惯动态连接消费风险与整体市场波动。|consumption growth; market returns; valuation ratios|消费增长；市场收益；估值比率
Risks for the Long Run: A Potential Resolution of Asset Pricing Puzzles|长期风险与资产定价难题|Bansal|2004|asset-pricing|Studies persistent consumption growth and uncertainty as ingredients in asset pricing.|研究持续性消费增长与不确定性在资产定价中的作用。|consumption; dividends; volatility estimates|消费；股息；波动率估计
A Five-Factor Asset Pricing Model|五因子资产定价模型|Fama|2015|asset-pricing|Extends size and value comparisons with profitability and investment characteristics.|在规模与价值之外加入盈利能力和投资特征进行比较。|returns; book equity; operating profits; investment|收益；账面权益；营业利润；投资
Dissecting Anomalies with a Five-Factor Model|用五因子模型分析异象|Fama|2016|asset-pricing|Examines which return patterns remain after controlling for five common factors.|考察控制五个共同因子后，哪些收益模式仍有待解释。|factor returns; characteristic portfolios; sample definitions|因子收益；特征组合；样本定义
Digesting Anomalies: An Investment Approach|从投资视角理解异象|Hou|2015|asset-pricing|Organizes return comparisons around investment and profitability in a production-based framework.|在生产侧框架中围绕投资与盈利能力组织收益比较。|firm investment; profitability; market equity; returns|企业投资；盈利能力；市值；收益
Replicating Anomalies|复现异象|Hou|2020|research-methods|Shows why portfolio construction, microcap treatment, and significance thresholds matter in replication.|说明组合构造、微盘股处理与显著性门槛为何影响复现。|published signal definitions; security panel; delistings|已发表变量定义；证券面板；退市数据
… and the Cross-Section of Expected Returns|多重检验与预期收益横截面|Harvey|2016|research-methods|Examines the statistical burden created by testing many proposed return factors.|讨论大量候选收益因子检验带来的统计负担。|factor test inventory; test statistics; dependence|因子检验清单；检验统计量；依赖关系
The Other Side of Value: The Gross Profitability Premium|价值的另一面：毛利率研究|Novy-Marx|2013|corporate-fundamentals|Studies gross profitability alongside valuation when comparing firms.|在企业比较中将毛利能力与估值共同考察。|gross profits; total assets; book equity; returns|毛利；总资产；账面权益；收益
Value and Momentum Everywhere|跨资产的价值与动量|Asness|2013|asset-pricing|Compares value and momentum definitions across markets and asset classes.|比较不同市场与资产类别中的价值和动量定义。|multi-asset prices; value measures; currencies|多资产价格；价值指标；币种
Time Series Momentum|时间序列动量|Moskowitz|2012|quant-methods|Examines an asset's own past returns across futures markets.|以期货市场为样本，研究资产自身历史收益的统计关系。|futures returns; contract rolls; volatility; collateral|期货收益；换月；波动率；保证金现金
Betting Against Beta|贝塔约束与低风险资产研究|Frazzini|2014|asset-pricing|Studies leverage constraints and the pricing of assets with different market betas.|研究杠杆约束与不同市场贝塔资产的定价关系。|asset betas; financing rates; leverage constraints|资产贝塔；融资利率；杠杆约束
Idiosyncratic Risk and the Cross-Section of Expected Stock Returns|特质风险与预期股票收益横截面|Fu|2009|asset-pricing|Separates systematic volatility exposures from firm-specific return variation.|区分系统性波动暴露与企业特有的收益变化。|daily returns; factor model; volatility estimates|日收益；因子模型；波动率估计
Expected Stock Returns and Volatility|预期股票收益与波动率|French|1987|asset-pricing|Investigates the relationship between market volatility and expected stock returns.|考察市场波动率与预期股票收益的关系。|market returns; realized volatility; risk-free rates|市场收益；已实现波动率；无风险利率
The Cross-Section of Volatility and Expected Returns|波动率与预期收益的横截面|Ang|2006|asset-pricing|Examines how sensitivities to aggregate volatility relate to cross-sectional returns.|考察总体波动敏感度与横截面收益之间的关系。|equity returns; volatility innovations; factor exposures|股票收益；波动创新；因子暴露
Tests of Asset Pricing with Time-Varying Expected Risk Premiums and Market Betas|时变风险溢价与市场贝塔下的资产定价检验|Ferson|1987|asset-pricing|Uses changing business conditions to study time-varying expected returns.|利用经济环境变化研究时变预期收益。|returns; yield spreads; lagged conditioning variables|收益；收益率利差；滞后条件变量
The Dividend-Price Ratio and Expectations of Future Dividends and Discount Factors|股息价格比、未来股息与贴现因子|Campbell|1988|asset-pricing|Decomposes valuation ratios into expectations about dividends and discounting.|将估值比率分解为股息与贴现因素的预期。|prices; dividends; log returns; long time series|价格；股息；对数收益；长期序列
Do Stock Prices Move Too Much to be Justified by Subsequent Changes in Dividends?|股价波动能否由后续股息变化解释？|Shiller|1981|asset-pricing|Compares stock-price variability with a discounted-dividend benchmark.|将股价变化与贴现股息基准进行比较。|long-run prices; dividends; discount-rate assumptions|长期价格；股息；贴现率假设
Stock Prices, Earnings, and Expected Dividends|股价、盈利与预期股息|Campbell|1988|asset-pricing|Relates price and earnings histories to expectations of future dividend flows.|利用价格与盈利历史分析未来股息的预期。|earnings; dividends; price indices; inflation|盈利；股息；价格指数；通胀
On the Estimation of Beta-Pricing Models|贝塔定价模型的估计|Shanken|1992|asset-pricing|Examines inference when risk exposures used in pricing tests are themselves estimated.|研究定价检验中的风险暴露本身需要估计时的统计推断。|returns; estimated betas; sampling errors|收益；估计贝塔；采样误差
Presidential Address: Discount Rates|贴现率研究综述|Cochrane|2011|asset-pricing|Surveys variation in discount rates and its implications for interpreting asset prices.|综述贴现率变化及其对资产价格解释的影响。|valuation ratios; returns; macro state variables|估值比率；收益；宏观状态变量
Size and Value in China|中国市场的规模与价值|Liu|2019|a-share-market|Adapts size and value comparisons to Chinese market institutions and shell-value effects.|结合中国市场制度及壳价值问题，讨论规模和价值比较。|A-share returns; market equity; earnings; listing histories|A股收益；市值；盈利；上市历史
Bid, Ask and Transaction Prices in a Specialist Market with Heterogeneously Informed Traders|异质信息交易者下的买价、卖价与成交价|Glosten|1985|market-microstructure|Models how information asymmetry can generate a bid-ask spread.|解释信息不对称如何形成买卖价差。|bid and ask quotes; transaction prices; trade direction|买卖报价；成交价格；交易方向
A Simple Implicit Measure of the Effective Bid-Ask Spread in an Efficient Market|有效买卖价差的简便隐含度量|Roll|1984|market-microstructure|Derives a spread measure from the serial covariance of price changes.|利用价格变化的序列协方差推导价差度量。|transaction prices; price-change covariance; trading intervals|成交价格；价格变化协方差；交易间隔
Measuring the Information Content of Stock Trades|衡量股票交易的信息含量|Hasbrouck|1991|market-microstructure|Uses a dynamic system of trades and prices to study information in order flow.|用交易与价格的动态系统研究订单流的信息含量。|signed trades; quotes; timestamps; lag structure|带方向成交；报价；时间戳；滞后结构
One Security, Many Markets: Determining the Contributions to Price Discovery|一种证券、多个市场：价格发现贡献|Hasbrouck|1995|market-microstructure|Measures contributions to a common price from trading in multiple venues.|衡量多个交易场所对共同价格形成的贡献。|synchronized venue quotes; common securities; timestamps|同步场所报价；相同证券；时间戳
Illiquidity and Stock Returns: Cross-Section and Time-Series Effects|非流动性与股票收益|Amihud|2002|market-microstructure|Uses return-to-volume measures to examine liquidity across securities and time.|使用收益与成交金额的比值比较证券间和时间上的流动性。|daily returns; trading value; security histories|日收益；成交金额；证券历史
Asset Pricing and the Bid-Ask Spread|资产定价与买卖价差|Amihud|1986|market-microstructure|Connects transaction costs and expected holding periods to asset pricing.|将交易成本与预期持有期联系到资产定价。|quoted spreads; returns; holding-period assumptions|报价价差；收益；持有期假设
Liquidity Risk and Expected Stock Returns|流动性风险与预期股票收益|Pastor|2003|market-microstructure|Distinguishes marketwide liquidity shocks from an individual stock's liquidity level.|区分全市场流动性冲击与单只股票的流动性水平。|daily prices; volumes; aggregate liquidity innovations|日价格；成交量；总体流动性创新
Trading Volume and Serial Correlation in Stock Returns|成交量与股票收益的序列相关|Campbell|1993|market-microstructure|Studies how trading volume helps interpret serial dependence in returns.|考察成交量如何帮助解释收益的序列相关。|daily returns; turnover; lagged volumes|日收益；换手率；滞后成交量
Limit Order Book as a Market for Liquidity|限价订单簿作为流动性市场|Foucault|2005|market-microstructure|Models the choices of liquidity demanders and suppliers in a limit-order market.|建模分析限价订单市场中的流动性需求和供给决策。|order submissions; cancellations; queue positions|订单提交；撤单；队列位置
The Price Impact of Order Book Events|订单簿事件的价格冲击|Cont|2014|market-microstructure|Relates short-horizon price changes to imbalance in order-book events.|将短期价格变化与订单簿事件的不平衡联系起来。|order-book updates; trades; depth; event timestamps|订单簿更新；成交；深度；事件时间戳
Hawkes Processes in Finance|金融中的霍克斯过程|Bacry|2015|market-microstructure|Surveys self-exciting point processes for modeling clustered financial events.|综述用于建模金融事件聚集现象的自激点过程。|event timestamps; event types; intensity estimates|事件时间戳；事件类型；强度估计
The Long Memory of the Efficient Market|有效市场的长记忆|Lillo|2004|market-microstructure|Studies persistent order-flow patterns and their relationship to price efficiency.|研究持续的订单流模式及其与价格效率的关系。|signed order flow; transaction prices; long samples|带方向订单流；成交价格；长期样本
An Analysis of Changes in Specialist Inventories and Quotations|专家交易商库存与报价变化分析|Madhavan|1993|market-microstructure|Decomposes price formation into information and inventory-related components.|将价格形成分解为信息与库存相关成分。|dealer quotes; trades; inventory proxies; timestamps|交易商报价；成交；库存代理；时间戳
Why Do Security Prices Change? A Transaction-Level Analysis of NYSE Stocks|证券价格为何变化？逐笔交易分析|Madhavan|1997|market-microstructure|Examines information and trading frictions using transaction-level price dynamics.|借助逐笔价格动态研究信息与交易摩擦。|trade signs; transaction prices; quotes; intraday periods|交易方向；成交价格；报价；日内时段
High-Frequency Trading and Price Discovery|高频交易与价格发现|Brogaard|2014|market-microstructure|Studies the role of identified high-frequency traders in price formation.|研究可识别高频交易者在价格形成中的作用。|participant-classified trades; quotes; market timestamps|按参与者分类成交；报价；市场时间戳
Does Algorithmic Trading Improve Liquidity?|算法交易是否改善流动性？|Hendershott|2011|market-microstructure|Uses changes in market infrastructure to study algorithmic activity and liquidity.|利用市场基础设施变化研究算法交易活动与流动性。|message traffic; quotes; trades; infrastructure event dates|报文流量；报价；成交；基础设施事件日期
The High-Frequency Trading Arms Race: Frequent Batch Auctions as a Market Design Response|高频交易竞赛与频繁批量竞价|Budish|2015|market-microstructure|Examines continuous-time market design and the incentives for speed competition.|研究连续时间市场设计如何形成速度竞争的激励。|high-resolution quotes; cross-market synchronization; latency|高精度报价；跨市场同步；延迟
The Flash Crash: High-Frequency Trading in an Electronic Market|闪电崩盘：电子市场中的高频交易|Kirilenko|2017|market-microstructure|Analyzes participant-level trading around the May 2010 market disruption.|分析2010年5月市场异常前后的参与者级交易。|audit-trail trades; participant IDs; futures positions|审计级成交；参与者标识；期货持仓
High Frequency Trading and the New Market Makers|高频交易与新型做市商|Menkveld|2013|market-microstructure|Studies a large high-frequency market maker operating across venues.|研究跨交易场所活动的大型高频做市商。|identified dealer trades; venue quotes; inventory|可识别交易商成交；场所报价；库存
Market Microstructure: A Survey|市场微观结构综述|Madhavan|2000|market-microstructure|Organizes theories and evidence on how trading mechanisms affect observed prices.|梳理交易机制如何影响观测价格的理论与证据。|trade and quote data; trading rules; market design|成交与报价数据；交易规则；市场设计
Commonality in Liquidity|流动性的共同变化|Chordia|2000|market-microstructure|Studies whether liquidity measures co-move across individual securities.|考察不同证券的流动性度量是否共同变化。|quoted spreads; depth; volume; market aggregates|报价价差；深度；成交量；市场汇总
Market Liquidity and Trading Activity|市场流动性与交易活动|Chordia|2001|market-microstructure|Examines marketwide liquidity alongside trading activity and economic conditions.|结合交易活动和经济条件分析市场总体流动性。|market spreads; depth; turnover; calendar variables|市场价差；深度；换手率；日历变量
Order Imbalance and Individual Stock Returns: Theory and Evidence|订单不平衡与个股收益|Chordia|2004|market-microstructure|Relates order imbalance to short-horizon price changes and reversals.|将订单不平衡与短期价格变化及反转联系起来。|buyer/seller initiated trades; quotes; daily aggregation|买卖发起成交；报价；日频汇总
A New Estimate of Transaction Costs|交易成本的新估计方法|Lesmond|1999|market-microstructure|Infers trading costs from the occurrence of zero returns under a threshold model.|在阈值模型下从零收益的出现频率推断交易成本。|daily returns; market returns; nontrading indicators|日收益；市场收益；无交易标识
A Simple Way to Estimate Bid-Ask Spreads from Daily High and Low Prices|利用日高低价估计买卖价差|Corwin|2012|market-microstructure|Develops a high-low price estimator and distinguishes volatility from spread components.|利用最高最低价构造估计量，并区分波动与价差成分。|daily high/low prices; overnight adjustments; trading days|日最高最低价；隔夜调整；交易日
Autoregressive Conditional Heteroscedasticity with Estimates of the Variance of United Kingdom Inflation|自回归条件异方差模型|Engle|1982|research-methods|Introduces conditional variance modeling for time series with changing uncertainty.|为不确定性随时间变化的序列引入条件方差模型。|time series; residuals; lagged squared innovations|时间序列；残差；滞后平方创新
Generalized Autoregressive Conditional Heteroskedasticity|广义自回归条件异方差模型|Bollerslev|1986|research-methods|Extends conditional variance dynamics with lagged variances and shocks.|以滞后方差与冲击扩展条件方差动态。|returns; model residuals; lag specification|收益；模型残差；滞后设定
A Heteroskedasticity-Consistent Covariance Matrix Estimator and a Direct Test for Heteroskedasticity|异方差稳健协方差估计与检验|White|1980|research-methods|Explains robust covariance estimation when regression errors have unequal variances.|说明回归误差方差不同时如何进行稳健协方差估计。|regression design; residuals; sample size|回归设计；残差；样本量
A Simple, Positive Semi-Definite, Heteroskedasticity and Autocorrelation Consistent Covariance Matrix|异方差与自相关稳健协方差矩阵|Newey|1987|research-methods|Provides covariance estimation for dependent and heteroskedastic observations.|为存在依赖性与异方差的观测提供协方差估计。|ordered observations; regression residuals; bandwidth|有序观测；回归残差；带宽
Estimating Standard Errors in Finance Panel Data Sets: Comparing Approaches|金融面板数据标准误的比较|Petersen|2009|research-methods|Compares standard-error methods under firm and time dependence.|比较企业维度和时间维度依赖下的标准误方法。|firm-time panel; cluster identifiers; regression residuals|企业时间面板；聚类标识；回归残差
Robust Inference With Multiway Clustering|多维聚类下的稳健推断|Cameron|2011|research-methods|Develops inference with dependence along more than one clustering dimension.|研究多个聚类维度存在依赖时的统计推断。|panel observations; multiple cluster IDs; design matrix|面板观测；多个聚类标识；设计矩阵
Event Studies in Economics and Finance|经济与金融中的事件研究|MacKinlay|1997|research-methods|Sets out event-window construction, expected-return benchmarks, and testing issues.|梳理事件窗口、预期收益基准和检验问题。|event dates; returns; estimation and event windows|事件日期；收益；估计窗口与事件窗口
Using Daily Stock Returns: The Case of Event Studies|用日股票收益开展事件研究|Brown|1985|research-methods|Evaluates event-study methods using daily return observations.|利用日收益观测评估事件研究方法。|daily returns; event assignments; benchmark returns|日收益；事件分配；基准收益
The Adjustment of Stock Prices to New Information|股价对新信息的调整|Fama|1969|research-methods|Studies price behavior around stock splits to illustrate event-time analysis.|围绕股票拆分研究价格行为，展示事件时间分析。|split announcements; returns; dividends; market index|拆分公告；收益；股息；市场指数
A Reality Check for Data Snooping|数据窥探的现实检验|White|2000|research-methods|Accounts for choosing a model after evaluating many alternatives on the same data.|处理在同一数据上比较大量方案后再选择模型的问题。|candidate-model losses; time series; resampling blocks|候选模型损失；时间序列；重采样区块
A Test for Superior Predictive Ability|预测能力比较的统计检验|Hansen|2005|research-methods|Compares many forecasting procedures while accounting for data snooping.|在考虑数据窥探的前提下比较多种预测程序。|forecast errors; benchmark losses; bootstrap settings|预测误差；基准损失；自助法设定
Comparing Predictive Accuracy|比较预测准确性|Diebold|1995|research-methods|Tests differences in forecast losses while allowing serial dependence.|允许序列依赖并检验预测损失差异。|paired forecasts; realized values; loss differential|配对预测；真实值；损失差
The Probability of Backtest Overfitting|回测过拟合概率|Bailey|2017|research-methods|Examines selection bias when many configurations are evaluated on finite samples.|研究在有限样本上评估大量配置时的选择偏差。|configuration results; train/test splits; selection rules|配置结果；训练测试分割；选择规则
The Deflated Sharpe Ratio: Correcting for Selection Bias, Backtest Overfitting, and Non-Normality|修正夏普比率中的选择偏差与非正态性|Bailey|2014|research-methods|Explains how multiple trials and return distribution shape affect a performance statistic.|说明多次试验和收益分布形态如何影响绩效统计量。|return distribution; trial count; sample length|收益分布；试验次数；样本长度
False Discoveries in Mutual Fund Performance: Measuring Luck in Estimated Alphas|基金绩效中的错误发现|Barras|2010|research-methods|Uses false-discovery methods to distinguish estimation noise in a large fund sample.|利用错误发现方法识别大规模基金样本中的估计噪声。|fund returns; factor returns; test statistics; dead funds|基金收益；因子收益；检验统计量；退出基金
Controlling the False Discovery Rate: A Practical and Powerful Approach to Multiple Testing|控制错误发现率的多重检验方法|Benjamini|1995|research-methods|Introduces a procedure for controlling false discoveries across simultaneous tests.|介绍在同时进行多项检验时控制错误发现的方法。|hypothesis inventory; p-values; dependence assumptions|假设清单；p值；依赖假设
Bootstrap Methods: Another Look at the Jackknife|自助法与刀切法|Efron|1979|research-methods|Introduces resampling as a way to approximate estimator uncertainty.|通过重采样近似估计量的不确定性。|observations; estimator; resampling design|观测；估计量；重采样设计
The Stationary Bootstrap|平稳自助法|Politis|1994|research-methods|Resamples dependent time series using random-length blocks.|利用随机长度区块重采样有依赖的时间序列。|ordered series; block-length choice; stationarity checks|有序序列；区块长度；平稳性检查
An Introduction to the Bootstrap|自助法导论|Efron|1993|research-methods|Provides a general reference for resampling estimates, intervals, and model uncertainty.|系统介绍重采样估计、区间和模型不确定性。|sample observations; estimator definitions; resampling seed|样本观测；估计量定义；重采样种子
Regression Shrinkage and Selection via the Lasso|Lasso回归收缩与变量选择|Tibshirani|1996|research-methods|Studies coefficient shrinkage and variable selection through an absolute-value penalty.|利用绝对值惩罚研究系数收缩与变量选择。|predictor matrix; response; temporal validation splits|预测变量矩阵；响应；时间验证分割
Regularization and Variable Selection via the Elastic Net|弹性网正则化与变量选择|Zou|2005|research-methods|Combines penalties to handle correlated predictors and sparse model selection.|结合不同惩罚处理相关预测变量与稀疏选择。|standardized predictors; response; validation folds|标准化变量；响应；验证分组
Random Forests|随机森林|Breiman|2001|research-methods|Introduces an ensemble of randomized trees for prediction and variable comparison.|通过随机化树集成进行预测和变量比较。|feature matrix; labels; out-of-sample evaluation|特征矩阵；标签；样本外评估
Greedy Function Approximation: A Gradient Boosting Machine|梯度提升机|Friedman|2001|research-methods|Constructs flexible functions through sequential loss-reducing updates.|通过逐步降低损失来构造灵活函数。|features; target; loss function; held-out samples|特征；目标；损失函数；留出样本
Empirical Asset Pricing via Machine Learning|机器学习与实证资产定价|Gu|2020|research-methods|Compares nonlinear methods for organizing a large set of firm characteristics.|比较非线性方法如何组织大量企业特征。|firm characteristics; returns; temporal training splits|企业特征；收益；时间训练分割
Autoencoder Asset Pricing Models|自编码器资产定价模型|Gu|2021|research-methods|Uses latent representations to model conditional exposures and common components.|利用潜在表示建模条件暴露与共同成分。|characteristic panel; returns; model validation periods|特征面板；收益；模型验证期
Deep Learning in Asset Pricing|资产定价中的深度学习|Chen|2024|research-methods|Studies flexible representations of pricing kernels using economic restrictions.|结合经济约束研究定价核的灵活表示。|returns; firm characteristics; macro states; temporal splits|收益；企业特征；宏观状态；时间分割
Characteristics Are Covariances: A Unified Model of Risk and Return|特征即协方差：风险与收益的统一模型|Kelly|2019|research-methods|Uses characteristics to model changing factor exposures across firms and time.|利用特征描述企业与时间维度上变化的因子暴露。|firm characteristics; return panel; factor dimension|企业特征；收益面板；因子维度
A Simple Approximate Long-Memory Model of Realized Volatility|已实现波动率的简单近似长记忆模型|Corsi|2009|research-methods|Combines daily, weekly, and monthly volatility components in a parsimonious model.|用简约模型结合日、周、月尺度波动成分。|intraday returns; daily realized variance; calendar windows|日内收益；日已实现方差；日历窗口
Realized Kernels in Practice: Trades and Quotes|实践中的已实现核：成交与报价|Barndorff-Nielsen|2009|research-methods|Studies volatility estimation when high-frequency observations contain market noise.|研究高频观测含市场噪声时的波动率估计。|high-frequency trades; quotes; sampling and kernel choices|高频成交；报价；采样与核函数选择
Microstructure Noise in the Continuous Case: The Pre-Averaging Approach|连续情形下的微观结构噪声：预平均方法|Jacod|2009|research-methods|Uses local averaging to reduce noise in high-frequency variance estimation.|用局部平均减少高频方差估计中的噪声。|high-frequency prices; noise assumptions; window sizes|高频价格；噪声假设；窗口长度
Do Stock Prices Fully Reflect Information in Accruals and Cash Flows about Future Earnings?|股价是否反映应计项目与现金流信息？|Sloan|1996|corporate-fundamentals|Distinguishes accrual and cash-flow components when interpreting earnings persistence.|解释盈利持续性时区分应计与现金流成分。|income statements; cash flows; accruals; filing dates|利润表；现金流；应计项目；披露日期
Value Investing: The Use of Historical Financial Statement Information to Separate Winners from Losers|历史财务报表信息与企业比较|Piotroski|2000|corporate-fundamentals|Combines accounting indicators to study differences within high book-to-market firms.|结合会计指标研究高账面市值比企业内部的差异。|financial statements; book-to-market; announcement dates|财务报表；账面市值比；公告日期
Earnings, Book Values, and Dividends in Equity Valuation|股票估值中的盈利、账面价值与股息|Ohlson|1995|corporate-fundamentals|Links accounting quantities to equity valuation under a residual-income framework.|在剩余收益框架下连接会计量与股票估值。|book equity; earnings; dividends; accounting policies|账面权益；盈利；股息；会计政策
The Quality of Accruals and Earnings: The Role of Accrual Estimation Errors|应计项目与盈利质量|Dechow|2002|corporate-fundamentals|Examines the relation between accrual estimates and cash-flow realizations.|考察应计估计与实际现金流之间的关系。|working-capital accruals; operating cash flows; fiscal periods|营运资本应计；经营现金流；会计期间
Detecting Earnings Management|识别盈余管理|Dechow|1995|corporate-fundamentals|Compares models for separating discretionary from normal accrual variation.|比较区分可操纵与正常应计变化的模型。|accruals; revenue; assets; industry and event identifiers|应计项目；收入；资产；行业与事件标识
Earnings Management During Import Relief Investigations|进口救济调查期间的盈余管理|Jones|1991|corporate-fundamentals|Uses an institutional event to investigate accounting discretion.|利用制度事件研究会计裁量行为。|financial statements; investigation dates; industry controls|财务报表；调查日期；行业控制变量
The Detection of Earnings Manipulation|识别盈利操纵|Beneish|1999|corporate-fundamentals|Studies financial-statement indicators associated with reported manipulation cases.|研究与已识别操纵案例相关的财务报表指标。|statement ratios; labeled cases; comparable controls|报表比率；已标注案例；可比对照
Financial Ratios, Discriminant Analysis and the Prediction of Corporate Bankruptcy|财务比率与企业破产判别分析|Altman|1968|corporate-fundamentals|Illustrates multivariate financial-ratio analysis using bankruptcy outcomes.|以破产结果展示多变量财务比率分析。|balance sheets; income statements; bankruptcy outcomes|资产负债表；利润表；破产结果
Financial Ratios and the Probabilistic Prediction of Bankruptcy|财务比率与破产概率模型|Ohlson|1980|corporate-fundamentals|Uses probabilistic models to relate accounting information to distress outcomes.|用概率模型连接会计信息与财务困境结果。|financial ratios; firm size; distress labels; dates|财务比率；企业规模；困境标签；日期
In Search of Distress Risk|寻找财务困境风险|Campbell|2008|corporate-fundamentals|Combines market and accounting information in the analysis of corporate failure.|在企业失败分析中结合市场与会计信息。|market returns; leverage; cash; failure events|市场收益；杠杆；现金；失败事件
The Dark Side of Outside Directors: Do They Quit When They Are Most Needed?|外部董事离任与公司事件|Fahlenbrach|2017|corporate-fundamentals|Examines director departures around periods of heightened firm risk.|研究企业风险上升前后的董事离任事件。|director histories; departures; company events; filing times|董事任职历史；离任；公司事件；披露时点
Corporate Governance and Equity Prices|公司治理与股票价格|Gompers|2003|corporate-fundamentals|Links shareholder-rights measures with corporate characteristics and valuation.|将股东权利度量与企业特征和估值联系起来。|governance provisions; firm valuation; returns; ownership|治理条款；企业估值；收益；所有权
Investor Protection and Corporate Governance|投资者保护与公司治理|La Porta|2000|corporate-fundamentals|Compares legal protection and governance arrangements across countries.|比较各国法律保护与治理安排。|legal rules; ownership structures; country classifications|法律规则；所有权结构；国家分类
Law and Finance|法律与金融|La Porta|1998|corporate-fundamentals|Studies relationships between legal institutions and financial development.|研究法律制度与金融发展之间的关系。|legal origin; investor rights; financial development indicators|法律起源；投资者权利；金融发展指标
Corporate Ownership Around the World|全球公司所有权结构|La Porta|1999|corporate-fundamentals|Maps ownership and control across firms in different legal environments.|描绘不同法律环境下企业的所有权和控制权。|ultimate owners; control chains; voting rights|最终所有者；控制链；投票权
The Separation of Ownership and Control in East Asian Corporations|东亚企业所有权与控制权的分离|Claessens|2000|corporate-fundamentals|Examines pyramids, cross-holdings, and control rights in East Asian firms.|考察东亚企业中的金字塔、交叉持股和控制权。|ownership chains; share classes; voting and cash-flow rights|股权链；股份类别；投票权与现金流权
Agency Costs of Free Cash Flow, Corporate Finance, and Takeovers|自由现金流的代理成本|Jensen|1986|corporate-fundamentals|Frames conflicts over corporate cash deployment and control transactions.|讨论企业现金使用与控制权交易中的利益冲突。|cash flows; investment; payout; acquisition records|现金流；投资；分配；收购记录
The Capital Structure Puzzle|资本结构之谜|Myers|1984|corporate-fundamentals|Compares explanations for corporate debt and equity financing choices.|比较企业债务与股权融资选择的不同解释。|debt; equity issuance; profitability; financing events|债务；股权发行；盈利能力；融资事件
Corporate Financing and Investment Decisions When Firms Have Information That Investors Do Not Have|信息不对称下的融资与投资决策|Myers|1984|corporate-fundamentals|Studies how asymmetric information can shape financing and investment decisions.|研究信息不对称如何影响融资和投资决策。|financing events; investment; information environment|融资事件；投资；信息环境
Toward an Implied Cost of Capital|走向隐含资本成本估计|Gebhardt|2001|corporate-fundamentals|Examines assumptions used to infer required returns from accounting forecasts.|考察利用会计预测推断必要收益时的假设。|analyst forecasts; book equity; prices; valuation inputs|分析师预测；账面权益；价格；估值输入
PE Ratios, PEG Ratios, and Estimating the Implied Expected Rate of Return on Equity Capital|市盈率、PEG与隐含股权回报率估计|Easton|2004|corporate-fundamentals|Studies how earnings forecasts and growth assumptions enter implied capital costs.|研究盈利预测与增长假设如何进入隐含资本成本。|forecast earnings; prices; growth assumptions; fiscal dates|盈利预测；价格；增长假设；会计日期
Information Asymmetry, Corporate Disclosure, and the Capital Markets: A Review of the Empirical Disclosure Literature|信息不对称、公司披露与资本市场|Healy|2001|corporate-fundamentals|Reviews evidence on disclosure decisions, information asymmetry, and market outcomes.|综述披露决策、信息不对称与市场结果的证据。|disclosures; analyst coverage; ownership; market measures|披露；分析师覆盖；所有权；市场度量
Disclosure, Liquidity, and the Cost of Capital|披露、流动性与资本成本|Diamond|1991|corporate-fundamentals|Models connections among public disclosure, market liquidity, and financing costs.|建模分析公开披露、市场流动性与融资成本的联系。|disclosure timing; investor information; liquidity measures|披露时点；投资者信息；流动性度量
International Differences in the Cost of Equity Capital: Do Legal Institutions and Securities Regulation Matter?|股权资本成本的国际差异|Hail|2006|corporate-fundamentals|Examines cross-country capital-cost differences alongside institutions and regulation.|结合制度与监管研究跨国资本成本差异。|analyst forecasts; prices; country institutions; regulation|分析师预测；价格；国家制度；监管
The Cost of Capital, Corporation Finance and the Theory of Investment|资本成本、公司金融与投资理论|Modigliani|1958|corporate-fundamentals|Provides a benchmark for analyzing financing structure under restrictive assumptions.|在限定假设下提供分析融资结构的理论基准。|capital structure; cash-flow claims; financing assumptions|资本结构；现金流权利；融资假设
More Than Words: Quantifying Language to Measure Firms' Fundamentals|不止文字：量化语言与企业基本面|Tetlock|2008|alternative-data|Uses financial-news language to examine information about company fundamentals.|利用财经新闻语言研究企业基本面信息。|news text; firm mapping; publication time; accounting data|新闻文本；企业映射；发布时间；会计数据
When Is a Liability Not a Liability? Textual Analysis, Dictionaries, and 10-Ks|金融文本分析、词典与10-K报告|Loughran|2011|alternative-data|Shows why domain-specific language matters when measuring sentiment in filings.|说明衡量披露文本情绪时为何需要领域专用词典。|10-K documents; tokenization; financial dictionaries|10-K文件；分词；金融词典
Textual Analysis in Accounting and Finance: A Survey|会计与金融文本分析综述|Loughran|2016|alternative-data|Reviews textual measurement choices and validation challenges in financial research.|综述金融研究中的文本度量选择与验证难点。|documents; text features; labels; publication metadata|文档；文本特征；标签；发布元数据
Text as Data|文本作为数据|Gentzkow|2019|alternative-data|Explains how text is transformed into measurable variables and statistical evidence.|解释如何将文本转化为可测量变量与统计证据。|document corpus; preprocessing rules; labels; validation|文档语料；预处理规则；标签；验证
Measuring Economic Policy Uncertainty|衡量经济政策不确定性|Baker|2016|macro-finance|Constructs policy-uncertainty measures from news and other documentary inputs.|利用新闻及其他文档材料构建政策不确定性度量。|newspaper corpus; search rules; normalization; dates|报纸语料；检索规则；标准化；日期
Measuring Geopolitical Risk|衡量地缘政治风险|Caldara|2022|macro-finance|Builds text-based measures of geopolitical threats and realized events.|构建基于文本的地缘政治威胁与已发生事件度量。|news archives; dictionaries; event chronology|新闻档案；词典；事件时间线
The Price of Political Uncertainty: Theory and Evidence from the Option Market|政治不确定性的价格与期权市场证据|Kelly|2016|alternative-data|Uses election-related option observations to study uncertainty around political events.|利用选举相关期权观测研究政治事件前后的不确定性。|options; election dates; implied volatility; countries|期权；选举日期；隐含波动率；国家
In Search of Attention|寻找投资者关注|Da|2011|alternative-data|Uses search activity as a proxy for investor attention with careful entity matching.|在谨慎实体匹配的前提下，以搜索活动代理投资者关注。|search intensity; ticker mapping; dates; returns|搜索强度；代码映射；日期；收益
The Sum of All FEARS Investor Sentiment and Asset Prices|搜索行为、投资者情绪与资产价格|Da|2015|alternative-data|Aggregates search terms to study investor sentiment and market activity.|汇总搜索词以研究投资者情绪与市场活动。|search-term series; aggregation rules; returns; volumes|搜索词序列；汇总规则；收益；成交量
All That Glitters: The Effect of Attention and News on the Buying Behavior of Individual and Institutional Investors|关注与新闻对投资者买入行为的影响|Barber|2008|alternative-data|Compares investor buying behavior around attention-grabbing securities.|比较不同投资者在高关注证券上的买入行为。|investor-type trades; news; volume; extreme returns|投资者类型成交；新闻；成交量；极端收益
Peer Pressure: Social Interaction and the Disposition Effect|同伴压力、社会互动与处置效应|Heimer|2016|alternative-data|Studies social interaction and the disposition effect using investor-network and trading observations.|利用投资者网络与交易观测研究社会互动和处置效应。|social links; timestamped messages; account trades|社交关系；带时间戳消息；账户成交
Wisdom of Crowds: The Value of Stock Opinions Transmitted Through Social Media|社交媒体股票观点与群体信息|Chen|2014|alternative-data|Examines stock-related opinions and subsequent information in a social-media setting.|研究社交媒体股票观点与后续信息之间的联系。|authored posts; comment text; timestamps; earnings|署名帖子；评论文本；时间戳；盈利
Investor Sentiment and the Cross-Section of Stock Returns|投资者情绪与股票收益横截面|Baker|2006|alternative-data|Examines how sentiment measures relate to different types of companies.|考察情绪度量与不同类型企业之间的关系。|sentiment proxies; firm characteristics; returns|情绪代理；企业特征；收益
Investor Sentiment in the Stock Market|股票市场中的投资者情绪|Baker|2007|alternative-data|Reviews measurement approaches and economic interpretations of investor sentiment.|综述投资者情绪的度量方法与经济解释。|sentiment indicators; issuance; turnover; valuation|情绪指标；发行；换手率；估值
The Stock Market's Reaction to Unemployment News: Why Bad News Is Usually Good for Stocks|股票市场对失业消息的反应|Boyd|2005|macro-finance|Studies how business-cycle conditions change interpretation of labor-market releases.|研究经济周期状态如何改变劳动市场发布的含义。|release timestamps; unemployment surprises; market returns|发布时间戳；失业数据意外；市场收益
What Moves Stock Prices?|什么推动股价变化？|Cutler|1989|alternative-data|Compares large market movements with identified news and economic developments.|将大幅市场变化与可识别新闻和经济事件比较。|market returns; news chronology; macro announcements|市场收益；新闻时间线；宏观公告
The Impact of Public Information on the Stock Market|公开信息对股票市场的影响|Mitchell|1994|alternative-data|Studies daily public news releases and aggregate market activity.|研究每日公开新闻发布与市场总体活动之间的关系。|news counts; publication dates; returns; volume|新闻数量；发布日期；收益；成交量
Lazy Prices|迟滞的信息反应与披露文本变化|Cohen|2020|alternative-data|Uses changes in corporate disclosures to study how document revisions enter prices.|利用公司披露文本变化研究文档修订如何进入价格。|successive filings; text differences; filing dates; returns|连续披露文件；文本差异；披露日期；收益
The Information Content of Forward-Looking Statements in Corporate Filings—A Naïve Bayesian Machine Learning Approach|公司披露前瞻性陈述的信息含量|Li|2010|alternative-data|Classifies forward-looking disclosure language and relates it to subsequent fundamentals.|分类前瞻性披露语言，并与后续基本面关联。|filing sections; sentence labels; accounting outcomes|披露章节；句子标签；会计结果
Annual Report Readability, Current Earnings, and Earnings Persistence|年报可读性、当期盈利与盈利持续性|Li|2008|alternative-data|Studies document readability alongside earnings and their persistence.|结合盈利及其持续性研究文档可读性。|annual reports; readability measures; earnings; firm controls|年报；可读性指标；盈利；企业控制变量
Bond Risk Premia|债券风险溢价|Cochrane|2005|macro-finance|Examines information in forward rates for understanding bond excess returns.|研究远期利率包含的债券超额收益相关信息。|zero-coupon yields; forward rates; holding-period returns|零息收益率；远期利率；持有期收益
Common Factors Affecting Bond Returns|影响债券收益的共同因子|Litterman|1991|macro-finance|Studies level, slope, and curvature as common movements in interest rates.|研究利率共同变化中的水平、斜率与曲率。|yield curves; tenors; rate changes; factor loadings|收益率曲线；期限；利率变化；因子载荷
Parsimonious Modeling of Yield Curves|收益率曲线的简约建模|Nelson|1987|macro-finance|Provides a low-dimensional representation of term structures.|为期限结构提供低维表示。|bond yields; maturities; curve-fitting weights|债券收益率；到期时间；曲线拟合权重
Forecasting the Term Structure of Government Bond Yields|预测国债收益率期限结构|Diebold|2006|macro-finance|Models time variation in yield-curve factors using a dynamic representation.|用动态表示研究收益率曲线因子的时间变化。|yield curves; maturities; factor time series|收益率曲线；期限；因子时间序列
The Macroeconomy and the Yield Curve: A Dynamic Latent Factor Approach|宏观经济与收益率曲线|Diebold|2006|macro-finance|Connects latent yield-curve factors with macroeconomic observations.|将潜在收益率曲线因子与宏观观测连接。|yield curves; inflation; output; policy rates|收益率曲线；通胀；产出；政策利率
Business Cycles in a Small Open Economy|小型开放经济中的经济周期|Correia|1995|macro-finance|Studies macroeconomic fluctuations in an open-economy setting.|研究开放经济环境下的宏观波动。|output; consumption; trade balance; world interest rates|产出；消费；贸易余额；世界利率
The Forward Premium Puzzle: Different Tales from Developed and Emerging Economies|远期升水之谜与不同经济体|Bansal|2000|macro-finance|Compares exchange-rate and interest-rate relationships across country groups.|比较不同国家组的汇率与利率关系。|spot FX; forward FX; interest differentials; currencies|即期汇率；远期汇率；利差；币种
Common Risk Factors in Currency Markets|货币市场中的共同风险因子|Lustig|2011|macro-finance|Studies common risk components across currency portfolios.|研究货币组合之间的共同风险成分。|exchange rates; forward discounts; currency baskets|汇率；远期贴水；货币篮子
Carry|持有收益研究|Koijen|2018|macro-finance|Defines carry consistently across asset classes and distinguishes it from price changes.|跨资产统一定义持有收益，并与价格变化区分。|spot and forward prices; contract terms; financing rates|即期与远期价格；合约条款；融资利率
Discretion versus Policy Rules in Practice|相机抉择与政策规则|Taylor|1993|macro-finance|Offers a benchmark for relating policy rates to inflation and economic activity.|为政策利率与通胀及经济活动的关系提供基准。|policy rates; inflation; output gap; real-time vintages|政策利率；通胀；产出缺口；实时版本
Monetary Policy Shocks: What Have We Learned and to What End?|货币政策冲击的识别与解释|Christiano|1999|macro-finance|Reviews identification choices for measuring monetary policy shocks.|综述衡量货币政策冲击时的识别选择。|policy instruments; macro series; identification restrictions|政策工具；宏观序列；识别约束
Measuring the Effects of Monetary Policy: A Factor-Augmented Vector Autoregressive (FAVAR) Approach|货币政策效应的因子增强向量自回归分析|Bernanke|2005|macro-finance|Uses many macro indicators to enrich the information set in policy analysis.|利用大量宏观指标扩展政策分析的信息集。|macro panel; policy rates; factor estimates; vintages|宏观面板；政策利率；因子估计；数据版本
The Macroeconomic Impact of Financial and Uncertainty Shocks|金融与不确定性冲击的宏观影响|Caldara|2016|macro-finance|Studies identification of financial and uncertainty shocks and their separate macroeconomic effects.|研究金融冲击与不确定性冲击的识别及各自的宏观经济影响。|credit spreads; uncertainty measures; macro series|信用利差；不确定性指标；宏观序列
Credit Spreads and Business Cycle Fluctuations|信用利差与经济周期波动|Gilchrist|2012|macro-finance|Separates credit-spread components to examine economic fluctuations.|分离信用利差成分以研究经济波动。|bond prices; default risk; excess bond premium; output|债券价格；违约风险；超额债券溢价；产出
Financial Intermediation and Credit Policy in Business Cycle Analysis|经济周期分析中的金融中介与信用政策|Gertler|2010|macro-finance|Adds financial intermediaries to a framework for studying macroeconomic shocks.|将金融中介纳入宏观冲击研究框架。|bank balance sheets; credit spreads; macro aggregates|银行资产负债表；信用利差；宏观汇总
The Leverage Cycle|杠杆周期|Geanakoplos|2010|macro-finance|Explains how collateral requirements can amplify asset-price and credit cycles.|解释抵押要求如何放大资产价格与信贷周期。|collateral values; margins; leverage; funding conditions|抵押品价值；保证金；杠杆；融资条件
Liquidity and Leverage|流动性与杠杆|Adrian|2010|macro-finance|Studies balance-sheet adjustment and leverage over the financial cycle.|研究金融周期中的资产负债表调整与杠杆变化。|intermediary assets; debt; market values; funding|中介资产；债务；市值；融资
CoVaR|条件风险价值CoVaR|Adrian|2016|macro-finance|Measures dependence between institutional distress and systemwide tail outcomes.|衡量机构困境与系统尾部结果之间的依赖。|institution returns; system returns; state variables|机构收益；系统收益；状态变量
SRISK: A Conditional Capital Shortfall Measure of Systemic Risk|SRISK：系统性风险的条件资本缺口|Brownlees|2017|macro-finance|Connects leverage, size, and downside market exposure to capital shortfall.|将杠杆、规模与市场下行暴露连接到资本缺口。|equity prices; liabilities; capitalization; market returns|股价；负债；资本化；市场收益
Forecasting Using Principal Components From a Large Number of Predictors|大量预测变量的主成分方法|Stock|2002|macro-finance|Reduces a large information panel to factors for time-series analysis.|将大规模信息面板压缩为用于时间序列分析的因子。|macro panel; release lags; standardization; missing data|宏观面板；发布滞后；标准化；缺失数据
The Real Value of China's Stock Market|中国股票市场的实际价值|Carpenter|2021|a-share-market|Examines prices, future fundamentals, and corporate investment in China.|研究中国市场价格、未来基本面与企业投资之间的联系。|A-share prices; earnings; investment; institutional regimes|A股价格；盈利；投资；制度阶段
Law, Finance, and Economic Growth in China|中国的法律、金融与经济增长|Allen|2005|a-share-market|Studies formal and informal financing alongside economic development in China.|结合中国经济发展研究正式与非正式融资。|firm financing; ownership; regional institutions; growth|企业融资；所有权；区域制度；增长
The Chinese Warrants Bubble|中国权证泡沫|Xiong|2009|a-share-market|Uses the warrant market to examine disagreement and speculative trading.|利用权证市场研究分歧与投机交易。|warrant prices; underlying prices; turnover; expiry terms|权证价格；标的价格；换手率；到期条款
Short-Sales Constraints and Price Discovery: Evidence from the Hong Kong Market|卖空约束与价格发现：香港市场证据|Chang|2007|a-share-market|Uses changes in short-sale eligibility to study constraints and price discovery.|利用卖空资格变化研究交易约束与价格发现。|eligibility lists; effective dates; returns; volumes|资格名单；生效日期；收益；成交量
Differences of Opinion, Short-Sales Constraints, and Market Crashes|意见分歧、卖空约束与市场崩跌|Hong|2003|a-share-market|Models how disagreement and short-sale restrictions affect information in prices.|建模分析分歧与卖空限制如何影响价格中的信息。|turnover; return distributions; disagreement proxies|换手率；收益分布；分歧代理
Speculative Trading and Stock Prices: Evidence from Chinese A-B Share Premia|投机交易与中国A/B股溢价|Mei|2009|a-share-market|Studies price differences for related share classes under segmented participation.|研究参与者分割条件下相关股份类别的价格差异。|A/B paired shares; FX; turnover; ownership restrictions|A/B配对股份；汇率；换手率；持有约束
How Does Government Ownership Affect Firm Performance? Evidence from China’s Privatization Experience|政府所有权如何影响企业绩效？中国民营化证据|Sun|2002|a-share-market|Examines state ownership in relation to the characteristics of listed firms.|考察国家所有权与上市企业特征的关系。|state ownership; firm financials; listing and reform dates|国有持股；企业财务；上市与改革日期
Politically Connected CEOs, Corporate Governance, and Post-IPO Performance of China's Newly Partially Privatized Firms|政治关联、治理与中国部分私有化企业|Fan|2007|a-share-market|Studies executive backgrounds and governance around partial privatization IPOs.|研究部分私有化上市过程中的高管背景与公司治理。|CEO biographies; IPO dates; ownership; financial statements|高管履历；IPO日期；所有权；财务报表
The Effects of Political Connections and State Ownership on Corporate Litigation in China|政治关联、国有股权与中国企业诉讼|Firth|2011|a-share-market|Examines political connections and ownership in corporate litigation outcomes.|结合政治关联与所有权结构分析企业诉讼结果。|litigation records; ownership; political ties; firm controls|诉讼记录；所有权；政治关联；企业控制变量
Asset Growth and the Cross-Section of Stock Returns|资产增长与股票收益横截面|Cooper|2008|corporate-fundamentals|Studies differences in future returns across firms with different asset growth.|比较资产增长不同的企业之间的后续收益。|total assets; financial statement dates; returns|总资产；财报日期；收益
The Investment CAPM|投资资本资产定价模型|Zhang|2017|asset-pricing|Reviews a production-based perspective linking investment and expected returns.|综述连接企业投资与预期收益的生产侧定价视角。|investment; profitability; market equity; asset returns|投资；盈利能力；市值；资产收益
Stock Market Liberalization, Economic Reform, and Emerging Market Equity Prices|股市开放、经济改革与新兴市场股价|Henry|2000|a-share-market|Examines market liberalization events together with broader economic reforms.|结合更广泛经济改革研究市场开放事件。|liberalization dates; market indices; reform controls|开放日期；市场指数；改革控制变量
Does Financial Liberalization Spur Growth?|金融开放是否促进增长？|Bekaert|2005|a-share-market|Studies capital-market liberalization and growth using cross-country panels.|利用跨国面板研究资本市场开放与增长。|country panels; liberalization dates; macro controls|国家面板；开放日期；宏观控制变量
Retail and Institutional Investor Trading Behaviors: Evidence from China|中国散户与机构投资者交易行为|Tan|2024|a-share-market|Reviews heterogeneous investor behavior within China's institutional setting.|综述中国制度环境下不同投资者的行为差异。|investor classifications; trades; information and policy events|投资者分类；成交；信息与政策事件
The Economics of Cryptocurrencies—Bitcoin and Beyond|加密货币经济学：比特币及其他|Chiu|2019|crypto-markets|Models payment frictions and the economic design of cryptocurrency systems.|建模分析支付摩擦与加密货币系统的经济设计。|transaction fees; settlement delays; protocol parameters|交易费用；结算延迟；协议参数
Risks and Returns of Cryptocurrency|加密货币的风险与收益|Liu|2021|crypto-markets|Studies cryptocurrency return variation and compares it with traditional asset exposures.|研究加密货币收益变化，并与传统资产暴露比较。|crypto prices; network measures; attention; macro factors|加密价格；网络指标；关注度；宏观因子
Common Risk Factors in Cryptocurrency|加密货币中的共同风险因子|Liu|2022|crypto-markets|Organizes cross-sectional cryptocurrency returns using common characteristics.|利用共同特征组织加密资产收益横截面。|multi-token prices; capitalization; turnover; delistings|多代币价格；市值；换手率；退市记录
Is Bitcoin Really Un-Tethered?|比特币与稳定币发行关系研究|Griffin|2020|crypto-markets|Examines blockchain flows, stablecoin issuance, and exchange price movements.|研究链上流量、稳定币发行与交易所价格变化。|wallet flows; stablecoin issuance; exchange prices; timestamps|钱包流量；稳定币发行；场所价格；时间戳
Bitcoin: Economics, Technology, and Governance|比特币：经济、技术与治理|Bohme|2015|crypto-markets|Reviews Bitcoin's technical mechanisms and economic governance questions.|综述比特币技术机制与经济治理问题。|protocol rules; transaction records; mining incentives|协议规则；交易记录；挖矿激励
Some Simple Economics of the Blockchain|区块链的基本经济学|Catalini|2020|crypto-markets|Separates verification and networking costs in blockchain applications.|区分区块链应用中的验证成本与网络成本。|verification workflows; network structure; protocol costs|验证流程；网络结构；协议成本
Blockchain Economics|区块链经济学|Abadi|2022|crypto-markets|Models tradeoffs in distributed recordkeeping and incentive design.|建模分析分布式记账与激励设计的权衡。|consensus assumptions; transaction records; participation costs|共识假设；交易记录；参与成本
SoK: Research Perspectives and Challenges for Bitcoin and Cryptocurrencies|比特币与加密货币的研究视角和挑战|Bonneau|2015|crypto-markets|Systematizes cryptocurrency security, consensus, and privacy research challenges.|系统整理加密货币安全、共识与隐私的研究挑战。|protocol specifications; network observations; threat models|协议规范；网络观测；威胁模型
Decentralized Finance: On Blockchain- and Smart Contract-Based Financial Markets|去中心化金融与智能合约市场|Schar|2021|crypto-markets|Surveys DeFi building blocks and the risks of composable smart-contract services.|综述DeFi构件与可组合智能合约服务的风险。|protocol contracts; collateral; liquidity pools; governance|协议合约；抵押物；流动性池；治理
DeFi Risks and the Decentralisation Illusion|DeFi风险与去中心化假象|Aramonte|2021|crypto-markets|Examines concentration, governance, and financial fragilities in DeFi.|研究DeFi中的集中度、治理与金融脆弱性。|protocol governance; leverage; liquidity; token ownership|协议治理；杠杆；流动性；代币所有权
Taming Wildcat Stablecoins|稳定币制度与监管设计|Gorton|2022|crypto-markets|Compares stablecoin arrangements with historical private-money institutions.|将稳定币安排与历史私人货币制度比较。|reserve disclosures; redemption terms; issuance; prices|储备披露；赎回条款；发行；价格
An Empirical Study of DeFi Liquidations: Incentives, Risks, and Instabilities|DeFi清算的激励、风险与不稳定性|Qin|2021|crypto-markets|Studies liquidation mechanisms using on-chain lending observations.|利用链上借贷观测研究清算机制。|lending positions; collateral; oracle prices; liquidations|借贷头寸；抵押物；预言机价格；清算
Flash Boys 2.0: Frontrunning in Decentralized Exchanges, Miner Extractable Value, and Consensus Instability|去中心化交易所抢跑、MEV与共识稳定性|Daian|2020|crypto-markets|Documents ordering incentives and transaction extraction in decentralized exchanges.|研究去中心化交易所中的交易排序激励与价值提取。|mempool observations; transaction ordering; gas bids; blocks|内存池观测；交易排序；Gas竞价；区块
SoK: Decentralized Finance (DeFi)|去中心化金融知识体系综述|Werner|2022|crypto-markets|Organizes DeFi protocols, security assumptions, and economic risks into a taxonomy.|系统整理DeFi协议、安全假设与经济风险。|protocol taxonomy; smart contracts; attack and risk cases|协议分类；智能合约；攻击与风险案例
Cryptocurrency Pump-and-Dump Schemes|加密货币拉升出货事件研究|Li|2025|crypto-markets|Studies coordinated promotion episodes using messages and market observations.|结合消息与市场观测研究协同推广事件。|public messages; event timestamps; prices; volumes|公开消息；事件时间戳；价格；成交量
Tokenomics: Dynamic Adoption and Valuation|代币经济：动态采用与估值|Cong|2021|crypto-markets|Models interactions between platform adoption, token usage, and valuation.|建模分析平台采用、代币使用与估值之间的相互关系。|platform users; token supply; transaction demand; prices|平台用户；代币供给；交易需求；价格
`;

export const researchSeeds = rows.trim().split("\n").map((row) => {
  const [title, titleZh, authorHint, expectedYear, topic, summaryEn, summaryZh, data, dataZh] = row.split("|");
  return { title, titleZh, authorHint, expectedYear: Number(expectedYear), topic, summary: { en: summaryEn, zh: summaryZh }, data, dataZh };
});
