// Source editions and bounded inspection notes stay separate from public prose.
const guide = (url, edition, evidenceScope, limits, rows) => ({
  reviewedAt: "2026-08-30", evidenceUrl: url, evidenceScope, limits,
  sections: rows.map(([pages, zh, en, bodyZh, bodyEn]) => ({
    title: { zh, en }, body: { zh: bodyZh, en: bodyEn },
    reference: { url, label: { zh: `原文定位：${edition.zh}，第${pages}页`, en: `Source: ${edition.en}, pp. ${pages}` } },
  })),
});

export const researchMethodsMarketsGuides = {
  "Capital Asset Prices: A Theory of Market Equilibrium under Conditions of Risk": guide(
    "https://cdn.uw.edu/wp-content/uploads/sites/103/2022/07/12172209/Sharpe-1964-Capital-Asset-Prices-seminal-article.pdf",
    { zh: "1964年期刊版", en: "1964 journal article" },
    "1964 journal scan linked by the University of Washington: printed pp. 425–426, 431–434, 436–437 and 439–440 read in a matching journal scan, with pp. 433–434 and 439–440 checked against the UW copy and p. 433 visually checked. This is a conceptual guide, not empirical CAPM validation.",
    { zh: "这是带有共同预期、借贷条件等假设的均衡模型，不是历史拟合结果或收益预测保证。市场代理、估计窗口与实际融资约束仍需单独检验。", en: "This equilibrium model relies on shared expectations and borrowing assumptions. It is not empirical validation or a return guarantee; market proxies and actual financing constraints require separate scrutiny." },
    [
      ["425–426", "从组合选择走向价格均衡", "From portfolio choice to equilibrium prices",
        "Sharpe关心分散投资之后，哪种风险仍会进入资产价格。把单个资产看起来很波动，直接等同于它应获得更高收益，会忽略其与组合其他资产的共同变化。这也是理解理论为何从组合出发，而不是从单只股票排名出发的关键。",
        "Sharpe asks which risk remains priced after diversification. Standalone volatility misses an asset's interaction with the rest of a portfolio, motivating an equilibrium rather than a stock-ranking argument."],
      ["431–432", "相关性改变组合机会", "Correlation changes portfolio opportunities",
        "组合风险不仅取决于各项资产自身波动，也取决于它们如何一起变化。两个波动相近的资产，放入同一组合后的贡献可能不同。判断资产作用时需要整个协方差结构，不能只根据每只资产的单独风险大小进行排序。",
        "Portfolio opportunities depend on co-movement as well as individual volatility. Similar standalone risks can make different contributions to a combination; isolated risk rankings lose that distinction."],
      ["433–434", "共同预期是一项强假设", "Shared expectations are a strong assumption",
        "均衡推导假设投资者对预期收益、波动和相关性具有共同判断，并能按相同条件借贷。作者承认这些假设很强。现实中的观点分歧、融资成本和约束不因此消失；应用模型时，应把这些差异看作待检验的边界。",
        "Investors share forecasts and borrowing terms in the equilibrium construction. These restrictive assumptions do not erase real disagreements or financing constraints; application needs to confront those differences."],
      ["433", "风险组合与风险承担程度分开", "Separate the risky combination from risk tolerance",
        "在给定条件下，选择风险资产组合与决定借入或贷出多少资金可以分开考虑。共同组合不意味着所有投资者承担相同风险，其与无风险资产的配置仍会不同。若借贷条件改变，这种分离的适用性也要重新分析。",
        "Under the stated conditions, choosing the risky combination separates from borrowing or lending. Sharing that combination does not mean investors choose identical overall risk exposure."],
      ["436, 439–440", "系统风险与总风险不同", "Systematic exposure differs from total risk",
        "论文将资产对有效组合收益变化的敏感度与不能通过加入该组合消除的风险联系起来。这种敏感度不是资产的全部波动，也不是相关系数本身。模型讨论预期收益与这种暴露的关系，不能直接把资本市场线用于每个未分散资产。",
        "Sensitivity to an efficient combination identifies systematic exposure, distinct from total volatility or correlation alone. The capital-market relation for efficient portfolios is not a standalone-volatility rule for every asset."],
      ["439–440", "事前关系不等于事后每期兑现", "An expected relation is not a realized guarantee",
        "理论中的预期收益与风险暴露属于事前判断，而实际样本回报会受意外变化影响。历史回归可以帮助提出检验问题，却不是理论自动兑现的证明。选择哪个市场代理以及用什么窗口估计，都需要另行说明，不能从模型名称直接得到答案。",
        "The relation concerns expectations, not guaranteed realized returns. Historical estimates need explicit market proxies and windows; a model's name cannot supply those empirical choices or validate their results."],
    ]),
  "A Five-Factor Asset Pricing Model": guide(
    "https://tevgeniou.github.io/EquityRiskFactors/bibliography/FiveFactor.pdf",
    { zh: "2015年期刊版", en: "2015 journal article" },
    "Academic-course copy of the 2015 journal article: printed pp. 1–4 read for the valuation motivation, factor definitions, sorting and sample caveats; p. 3 visually checked. Later empirical tables and a replication were not independently verified.",
    { zh: "五因子解释力取决于样本与检验组合。某个样本中的价值因子冗余，不代表价值特征永久无用；模型也不是个股收益承诺。", en: "Explanatory power depends on the sample and test portfolios. Value-factor redundancy in one sample does not make value characteristics permanently irrelevant or turn the model into a return promise." },
    [
      ["1–3", "为什么再加入盈利与投资？", "Why add profitability and investment?",
        "作者从估值关系出发，说明账面市值比之外，预期盈利与投资也可能关联平均收益。五因子模型因此加入盈利和投资组合收益。这个动机解释了变量为何值得研究，却不单独证明某一种风险或错误定价机制是所有结果的唯一原因。",
        "Valuation relations motivate looking beyond book-to-market to expected profitability and investment. The model adds portfolio returns associated with those dimensions. This rationale explains why the variables deserve attention without uniquely identifying a risk mechanism or mispricing explanation for every empirical result."],
      ["3", "因子是组合收益，不是公司评分", "Factors are portfolio returns, not firm scores",
        "RMW比较盈利强与弱的分散组合收益，CMA比较投资保守与激进的组合收益，另有市场、规模和价值因子。公司盈利水平是排序特征，对RMW的回归载荷则是收益敏感度。两者有联系，但不能把会计比率直接当成因子收益或载荷。",
        "RMW contrasts diversified robust- and weak-profitability portfolios; CMA contrasts conservative and aggressive investment portfolios alongside market, size and value factors. A firm's profitability is a sorting characteristic, while its RMW loading measures return sensitivity. Neither the factor return nor its loading is simply an accounting ratio."],
      ["3", "这里的盈利分母是账面权益", "Operating profitability uses book equity",
        "文中的经营盈利以收入减去销售成本、销售及管理费用和利息费用，再除以账面权益。它不同于毛利润除以总资产，也不同于销售利润率。比较另一篇论文或数据字段时，要逐项核对费用范围、分母与财政年度，不能只看“盈利能力”这个名称。",
        "Operating profitability subtracts cost of goods sold, selling and administrative expenses, and interest expense from revenue, then divides by book equity. It differs from gross profit over assets and from a sales margin. Comparing papers or fields requires the expense scope, denominator and fiscal year, not just a shared profitability label."],
      ["3", "投资增长与排序时点相互配合", "Investment growth needs dated accounting inputs",
        "投资指标使用上一财政年度总资产的增量，除以前一年度总资产。组合每年六月末排序，采用此前财政年度会计资料与规定的市值时点。保留这些时点才能理解组合形成，不能把后来修订的财报当作历史排序日已经掌握的信息。",
        "Investment uses the prior fiscal year's increase in total assets divided by assets one year earlier. Portfolios are sorted at the end of June using preceding fiscal-year accounts and specified market-value dates. These conventions matter: a subsequently revised filing is not evidence of what was known on the historical sorting date."],
      ["3–4", "检验的对象是有意拉开差异的组合", "Test portfolios deliberately span characteristics",
        "研究通过规模与账面市值比、盈利或投资的排序构造组合，观察模型能否解释平均收益差异。若因子完整捕捉预期收益，超额收益回归截距应为零。组合拟合好与这一截距条件不是同一回事，多维排序还可能带来稀疏或分散不足的问题。",
        "Size sorts combined with book-to-market, profitability or investment create test portfolios with different average returns. Complete capture of expected returns implies zero excess-return regression intercepts. Good fit is a different criterion, and multidimensional sorting can also create sparse or poorly diversified cells."],
      ["1–4", "冗余结论有样本边界", "Redundancy is a sample-dependent finding",
        "论文的主要样本是1963年7月至2013年12月的美国股票。作者讨论加入新因子后的HML冗余，也指出低盈利且高投资的小股票带来的困难。理解这些结果要保留检验时期与组合选择，不能推导出价值永久失效或五因子普遍完备。",
        "The main US sample runs from July 1963 to December 2013. The paper discusses HML redundancy after adding the new factors and difficulties with small, weak-profitability, high-investment stocks. Neither finding establishes that value is permanently obsolete or that five factors universally complete an asset-pricing model."],
    ]),
  "Investor Sentiment and the Cross-Section of Stock Returns": guide(
    "https://pages.stern.nyu.edu/~jwurgler/papers/wurgler_baker_cross_section.pdf",
    { zh: "2006年期刊版", en: "2006 journal article" },
    "Author-hosted journal copy: printed pp. 1648–1651 and 1653–1657 read for conceptual channels, sample matching, six proxies and two-stage index construction; p. 1657 visually checked. Later return tables were not independently reproduced.",
    { zh: "综合情绪指数不是直接观察到的心理状态。共同周期、代理变量的时滞与套利限制都影响解释，历史美国样本的指数权重不是跨市场通用标准。", en: "The composite index is not a direct observation of psychology. Shared cycles, proxy timing and arbitrage constraints affect interpretation; historical US index weights are not a universal cross-market standard." },
    [
      ["1648–1650", "同一情绪为何影响不同股票？", "Why might sentiment affect stocks differently?",
        "论文把投机需求变化与套利限制放在一起考虑。估值更主观的公司可能更受乐观或悲观预期影响，难以对冲、卖空成本高的股票也更难被套利力量纠正。这两组特征常有重叠，所以研究并不能轻易把每个结果归给单一渠道。",
        "The argument combines changing speculative demand with limits to arbitrage. Subjective valuations may respond more to optimism or pessimism, while difficult hedging and costly short selling can impede correction. These characteristics overlap, making it difficult to assign each empirical pattern to only one channel."],
      ["1655–1656", "六个代理量，不是一份问卷", "Six proxies, not a sentiment questionnaire",
        "指数使用封闭式基金折价、纽约证交所换手率、IPO数量与首日收益、股票融资占比和股息溢价。它们分别来自市场价格、交易和融资活动。股息溢价比较派息与不派息公司的估值，不能替换为股息率；新闻情感分数也不是这篇论文的原始指标。",
        "The six inputs are closed-end fund discounts, NYSE turnover, IPO volume and first-day returns, the equity share in new issues, and the dividend premium. They describe prices, trading and financing. The dividend premium compares payer and nonpayer valuations; it is not a dividend yield or a text-based news sentiment score."],
      ["1656–1657", "共同成分也要考虑先后顺序", "Shared variation has a timing structure",
        "作者先对六个代理量及其滞后值提取第一主成分，再按与初步指数的相关性为各代理量选择时点，重新构造精简指数。最终组合同时含当期和滞后项，不能把所有观测统一移到同一年而声称保持了原方法。各输入还要先标准化。",
        "A first principal component is estimated from six proxies and their lags. Correlations with that preliminary index then select a timing for each proxy before a parsimonious index is constructed. The final mix uses current and lagged inputs, standardized first; moving every observation to the same year changes the method."],
      ["1657", "去除周期成分仍然是模型选择", "Removing business-cycle variation is conditional",
        "IPO与换手等变量也会随合理的经济变化波动，第一主成分不能自动把共同波动识别为情绪。作者另将各代理量对工业生产、消费增长和衰退指标回归，用残差构造第二指数。这个处理依赖选定的控制变量，不等于剔除了所有基本面信息。",
        "IPO activity and turnover can move for rational economic reasons; a principal component does not label shared variation as sentiment. A second index uses residuals after controlling for industrial production, consumption growth and recessions. Its interpretation remains conditional on those controls, not proof that all fundamental information has disappeared."],
      ["1653–1655", "公司特征需要历史匹配", "Firm characteristics require historical matching",
        "公司资料来自CRSP与Compustat的历史普通股样本，财政年度结束于t−1年的报表与t年7月至次年6月收益匹配。公司年龄按首次进入CRSP计算，并不等同于成立年限。数据覆盖改变会影响解释，跨市场迁移时不能省略这一身份与时间核对。",
        "The historical common-stock sample joins CRSP and Compustat, matching fiscal years ending in t−1 to returns from July t through June t+1. Age measures time since first appearance in CRSP, not time since incorporation. Coverage changes therefore matter when translating the firm's identity and timing conventions to another market."],
      ["1655, 1657", "不要给复杂特征贴单一标签", "Characteristics can carry several meanings",
        "高账面市值比既可能反映困境，也包含估值与预期收益信息；销售增长和融资又可能同时对应成长机会或经营压力。论文因此关注情绪与多种特征的关系，而不是把某一比率直接解释为非理性。指数与收益的关系仍需要结合样本和替代解释阅读。",
        "High book-to-market can reflect distress as well as valuation and expected returns; sales growth and financing can describe growth opportunities or operating pressure. The study examines sentiment across such multidimensional characteristics rather than equating one ratio with irrationality. Sample context and competing explanations remain important."],
    ]),
  "Risks and Returns of Cryptocurrency": guide(
    "https://www.nber.org/system/files/working_papers/w24877/w24877.pdf",
    { zh: "2018年8月工作论文", en: "August 2018 working paper" },
    "NBER working paper 24877, August 2018: printed pp. 2–5 read, including sample dates and attention/valuation proxies; p. 4 visually checked. This is the early three-asset draft, not a full-text review of the 2021 journal article or a replication of return tables.",
    { zh: "导读依据2018年工作论文，题录保留2021年期刊版。早期三种资产的结果不代表当前整个加密市场；历史注意力关联也不是可执行收益保证。", en: "This guide uses the 2018 working paper and retains the 2021 journal citation. Its early three-asset sample does not represent the entire current crypto market, and historical attention associations are not executable return guarantees." },
    [
      ["2–4", "先看这份早期版本研究了谁", "Start with the early draft's actual assets",
        "这份工作论文研究比特币、Ripple与以太坊，而不是今日所有代币。三条价格序列起点不同，分别始于2011、2013和2015年，均结束于2018年5月31日。不同长度会改变共同检验窗口，不能把三种资产的结果视为同一个完整市场面板。",
        "The draft studies Bitcoin, Ripple and Ethereum, not today's full token universe. Price histories begin in 2011, 2013 and 2015 respectively and end on May 31, 2018. Different lengths affect common testing windows, so the three series should not be treated as a balanced panel of the entire market."],
      ["2–3", "传统因子是比较基准，不是独立性证明", "Traditional factors are benchmarks, not proof of independence",
        "作者比较股票因子、货币、贵金属与宏观变量的解释力，并指出许多传统解释在该样本中较弱。但文中仍有个别资产与因子的关联，不能把总体讨论翻译成“加密资产与一切传统市场无关”。统计上未检出稳定关系，也不等于关系永远不存在。",
        "Equity factors, currencies, precious metals and macro variables serve as comparison benchmarks. Many conventional explanations are weak in this sample, but asset-specific associations remain. Failure to detect a stable pattern does not establish permanent independence from every traditional market or economic variable."],
      ["3–4", "关注度和情绪方向是两回事", "Attention is different from emotional tone",
        "Google搜索和包含Bitcoin的Twitter发帖数量被用作关注度代理，另有与黑客事件相关的搜索比率考察负面关注。搜索变多可能源于担忧或兴趣，所以不能直接解读为看多。关键词、分母、采样频率和时间对齐都会改变这个指标的含义。",
        "Google searches and Twitter post counts mentioning Bitcoin proxy for attention, while a hack-related search ratio examines negative attention. More searches can reflect concern or curiosity rather than optimism. Keywords, denominators, sampling frequency and time alignment are therefore part of the measure's meaning."],
      ["3–4", "钱包数量不是现金分红", "Wallet counts are not cash dividends",
        "草稿用价格相对于钱包用户数量的比值构造带引号的“价格股息比”。这里的钱包用户数量只是采用程度的代理，不是资产向持有人支付的现金流。论文在这份版本中未发现该指标的预测力，也不能据此推导出所有网络采用指标都无效。",
        "The draft's quoted price-to-dividend proxy divides price by wallet-user counts. Those counts proxy for adoption rather than cash distributions to holders. The reported lack of predictive power for this construction does not establish that every network-adoption measure is uninformative."],
      ["4–5", "比较资产时还要比较数据窗口", "Comparisons inherit different data windows",
        "加密价格来自CoinDesk，而股票、汇率、债券与其他比较序列来自不同资料库，其中一些更早结束。完整研究需要明确每项回归实际使用的交集窗口。某一个交易所的现货数据不能自动替代这些多来源序列，更不能补出没有观察到的历史。",
        "Crypto prices come from CoinDesk, whereas equities, currencies, bonds and other comparison series use different databases, some ending earlier. Each regression needs its actual overlapping window. A single venue's spot series cannot silently replace the multi-source inputs or create unobserved history."],
      ["2–4", "预测关联与交易结果之间仍有距离", "Predictive associations are not trading outcomes",
        "草稿讨论动量与注意力变量对后续收益的历史预测关系。这样的统计关联与扣除交易成本后、经过样本外检验的投资表现是不同问题。把论文用于新数据时，需要重新处理观察时点、样本变化与估计不确定性，不能直接沿用早期样本的结论。",
        "The draft discusses historical return predictability from momentum and attention. Such associations are distinct from out-of-sample investment performance after trading costs. Applying the questions to new data requires renewed timing, sample and estimation checks rather than carrying the early findings forward as current trading results."],
    ]),
  "The Real Value of China's Stock Market": guide(
    "https://pages.stern.nyu.edu/~jcarpen0/pdfs/Carpenter%20Lu%20Whitelaw%20-%20The%20Real%20Value%20of%20China%27s%20Stock%20Market.pdf",
    { zh: "2021年期刊版", en: "2021 journal article" },
    "Author-hosted 2021 journal article: printed pp. 680–682 read for the information/capital-allocation distinction, regressions, market-cap construction, ownership split and sample; p. 682 visually checked. Later tables and replication were not independently verified.",
    { zh: "研究覆盖1995至2016年，区分价格信息、投资配置与资本成本。历史实现收益不等于预期收益，制度变化同期发生也不单独证明改革的因果效应。", en: "The 1995–2016 study separates price information, capital allocation and capital costs. Realized historical returns need not equal expected returns, and coincident institutional reforms do not alone establish a causal reform effect." },
    [
      ["680–681", "真实价值不只体现在指数涨跌", "Real value is more than an index's return",
        "论文关心股票市场能否汇集有关企业未来盈利的信息，以及这些信息是否有助于投资配置。价格能预测未来盈利，与管理者从价格学到额外信息是两个问题。即使一个市场波动很大，也不能只据波动就判断它没有信息功能或资本配置作用。",
        "The paper asks whether prices aggregate information about future profits and whether that information helps allocate investment. Forecasting profits and revealing information beyond managers' private knowledge are distinct questions. High market volatility alone cannot establish the absence of either informational or allocative value."],
      ["681", "信息含量不是简单的市场相关性", "Informativeness is not simply market correlation",
        "作者按年做横截面回归，用当前估值和盈利等解释未来盈利，再结合估值分散度衡量预测变化。这个指标不同于股票对市场回归的拟合度。特质波动可能同时包含信息和噪声，所以不能把“与大盘走势不同”直接解释为价格包含更多可靠信息。",
        "Annual cross-sectional regressions relate future profits to current valuations and profitability, combining a coefficient with valuation dispersion to measure predicted variation. This differs from a stock's market-model fit. Idiosyncratic variation can contain news and noise, so moving differently from the market does not automatically imply more reliable information."],
      ["682", "市值并非仅用流通A股计算", "Market value is not just tradable A-share capitalization",
        "研究使用CSMAR的1995至2016年财务与行情资料，按年末A股价格乘以总股数构造市值，股数包括可交易A、B、H股及非流通股。这个特定口径不同于流通市值。若改用数据平台现成的市值字段，必须核对覆盖哪些股份类别。",
        "Using 1995–2016 CSMAR data, market value is year-end A-share price multiplied by total shares, including tradable A, B and H shares and nontradable shares. This is a specific convention, not free-float capitalization. A ready-made market-value field must be checked for which share classes it covers."],
      ["681–682", "价格、投资与盈利构成三组关系", "Prices, investment and profits form three tests",
        "论文分别研究价格对未来盈利、价格对未来投资，以及投资对未来盈利的预测关系，投资以资本开支衡量。三组结果之间的联系依赖管理者追求价值最大化并从价格学习等假设。它们共同提供解释线索，但不是同一个回归，也不能相互替代。",
        "Separate tests connect prices to future profits, prices to future investment, and investment to future profits, with capital expenditure measuring investment. Connections among them rely on assumptions about value-maximizing managers and learning from prices. They provide related evidence but are not interchangeable regressions."],
      ["682", "国有股权比例影响比较方式", "State ownership changes the comparison",
        "股权资料来自Wind，研究既允许系数随国有股权比例变化，也按40%的界限进行分组。国有企业可能承担盈利之外的目标，因而价值最大化假设的适用性不同。这个历史分组是论文的研究设计，不能当成所有场景通用的企业治理分类。",
        "Wind ownership data support coefficients varying with the state-owned equity fraction and a separate 40% split. State enterprises may pursue objectives beyond profit, changing the applicability of value-maximization assumptions. The historical grouping is a research design choice, not a universal corporate-governance classification."],
      ["680–682", "信息改善不等于未来回报保证", "Better information does not promise future returns",
        "作者还讨论资本成本，并提醒用历史实现回报估计必要回报会受到意外市场表现影响。价格信息含量改善也不意味着投资者可以轻易取得超额收益。阅读结论时应区分市场的信息作用、企业融资成本和投资者回报这三种含义。",
        "The capital-cost discussion warns that realized returns used to estimate required returns may reflect unexpected market performance. Improved price informativeness does not promise easily attainable excess returns. Keep the market's information function, firms' financing costs and investors' realized outcomes separate."],
    ]),
  "Measuring Economic Policy Uncertainty": guide(
    "https://users.ssc.wisc.edu/~mchinn/bakerbloomdavis_QJE2016.pdf",
    { zh: "2016年期刊版", en: "2016 journal article" },
    "University-hosted 2016 journal copy: printed pp. 1598–1600 and 1605–1606 read for newspaper measurement, normalization and historical/country differences; p. 1599 visually checked. This guide does not certify the audit corpus or reproduce macroeconomic response estimates.",
    { zh: "EPU是新闻覆盖频率构成的代理指标，不是政策发生概率或市场涨跌预测。报纸构成、关键词与标准化区间不同，会影响跨国和跨时期比较。", en: "EPU is a newspaper-frequency proxy, not a policy-event probability or market-direction forecast. Newspaper coverage, keyword sets and normalization windows affect comparisons across countries and periods." },
    [
      ["1598", "测量的是政策相关的不确定性", "The target is policy-related uncertainty",
        "作者希望捕捉谁制定政策、何时采取何种政策以及其经济影响等不确定性，也包含长期财政问题。它不是把所有政治报道加总，更不是一般经济波动的同义词。论文正式版聚焦报纸文本，早期草稿中的其他成分不能不加区别地混入。",
        "The target includes uncertainty about policymakers, policy actions, timing and economic consequences, including long-horizon fiscal questions. It is not a count of all political reporting or a synonym for economic volatility. The final article focuses on newspapers; components from earlier drafts should not be silently mixed into that definition."],
      ["1599", "同一篇报道必须满足三类词", "An article must meet three term categories",
        "美国月度指数在十家报纸中寻找同时包含不确定性、经济和政策三类词的文章，政策词包括国会、赤字、联储等及其变体。只出现政策关键词并不足够。跨语言扩展也需要重新设计词表与语境判断，不能把英文关键词逐字翻译就当作同一测量。",
        "The US monthly index searches ten newspapers for articles containing uncertainty, economy and policy terms together, including policy terms such as Congress, deficit and the Federal Reserve. A policy mention alone is insufficient. A new language requires reconsidering vocabulary and context rather than assuming literal translation preserves the measure."],
      ["1599", "先除以报道总量，再合成指数", "Normalize newspaper counts before combining them",
        "原始命中数先除以同一报纸同月全部文章数，再将各报纸序列按1985至2009年标准差缩放，按月平均后把基期均值设为100。100是尺度约定，不是100%的概率。新闻总量增加本身不应自动被解读为政策不确定性同比例上升。",
        "Matches are divided by each newspaper's total monthly article count, scaled using its 1985–2009 standard deviation, averaged across papers and normalized to a baseline mean of 100. That 100 is a scale convention, not a probability. More news volume alone should not imply proportionately greater uncertainty."],
      ["1600", "日度版不是月度版的简单拆分", "The daily series uses a different archive",
        "日度指数使用Newsbank更广泛的报纸集合，而不是把十家报纸的月度值拆到每天。报纸会进入或离开资料库，覆盖变化可能影响长期走势。因此频率转换之外，还要保留资料库构成与版本；两个指数相关性高也不表示定义完全相同。",
        "The daily index draws on a broader Newsbank archive rather than splitting the ten-paper monthly value into days. Papers enter and leave that archive, potentially affecting longer-run behavior. Archive composition and vintages matter alongside frequency conversion; high correlation does not make the two constructions identical."],
      ["1605–1606", "跨国与长历史需要调整词表", "Country and historical coverage need different choices",
        "长历史指数扩展了经济和政策相关词汇，以适应早期报纸用语；不同国家的报纸覆盖也并不一致。单报纸来源可能更嘈杂，媒体环境还会影响什么被报道。比较指数水平之前，应先检查当地来源、词表和基期，而不是只把曲线放在一起。",
        "Long-span indexes expand economic and policy vocabulary to reflect earlier usage, while country indexes differ in newspaper coverage. A single-paper source can be noisier, and media conditions affect what is reported. Check local sources, term sets and baselines before comparing index levels on a shared chart."],
      ["1598–1600", "政治事件不一定形成指数峰值", "Political turbulence need not produce an EPU spike",
        "论文指出一些政府停摆虽获大量报道，却很少同时出现经济与不确定性用语，因此未必带来明显峰值。这不是自动证明指数错误，而是提醒读者理解它的筛选目标。它衡量特定报道中的关注，不是给每次事件评定严重程度或因果影响。",
        "Some government shutdowns received extensive coverage without many articles simultaneously mentioning the economy and uncertainty. A missing spike is therefore not automatically a measurement failure. The index tracks a defined type of coverage, not the severity or causal economic impact of every political event."],
    ]),
  "A Simple, Positive Semi-Definite, Heteroskedasticity and Autocorrelation Consistent Covariance Matrix": guide(
    "https://www.nber.org/system/files/working_papers/t0055/t0055.pdf",
    { zh: "1986年2月修订工作论文", en: "February 1986 revised working paper" },
    "NBER technical working paper 55, revised February 1986: printed pp. 1–4 visually inspected because text extraction is empty. Scope covers moment conditions, covariance estimation, lag weights and the PSD property; it is not a review of every proof or of the final 1987 journal text.",
    { zh: "导读依据1986年修订工作论文，题录保留1987年期刊版。稳健协方差依赖矩条件与渐近假设，不能修复内生性，也不保证小样本推断准确。", en: "This guide uses the revised 1986 working paper and retains the 1987 journal citation. Robust covariance relies on moment conditions and asymptotic assumptions; it does not repair endogeneity or guarantee accurate small-sample inference." },
    [
      ["1", "首先问估计结果有多不确定", "Start with uncertainty around estimates",
        "论文讨论矩条件估计中的渐近协方差：参数估计不仅需要一个数值，还需要描述其不确定性，才能构造置信区间或检验。矩条件本身要求相应期望为零。如果这一识别前提错误，改用稳健协方差并不会自动使估计拥有正确的经济含义。",
        "The paper studies asymptotic covariance in moment-based estimation. A parameter estimate needs an uncertainty measure for confidence intervals and tests. The underlying moments must have zero expectation; changing the covariance estimator cannot automatically repair an invalid identifying condition."],
      ["1–2", "序列相关使不同时间共同影响方差", "Dependence links observations across time",
        "长期协方差不仅包含同一期矩向量的波动，还包含不同滞后之间的协方差。忽略这些项会遗漏时间依赖结构；异方差又意味着波动规模并不固定。这里处理的是用于推断的协方差对象，不能把它误读成预测未来价格波动的直接模型。",
        "Long-run covariance includes both contemporaneous variation in the moment vector and lagged covariances. Omitting lag terms discards temporal dependence, while heteroskedasticity allows changing variation. This is a covariance object for inference, not by itself a model that forecasts future price volatility."],
      ["2–3", "直接截断求和可能产生负方差问题", "Unweighted truncation can misbehave",
        "一种直观做法是把有限个滞后的样本协方差直接相加，但所得矩阵在有限样本中未必半正定。这样可能出现负的估计方差或难以解释的检验统计量。作者要解决的不只是能否算出结果，还包括协方差估计是否具有必要的数学性质。",
        "Simply summing sample covariances over finitely many lags need not produce a positive semidefinite matrix in a finite sample. Negative estimated variances or problematic test statistics may follow. The construction therefore addresses a mathematical property of covariance estimation, not just computational convenience."],
      ["3–4", "离得更远的滞后获得更小权重", "More distant lags receive smaller weights",
        "论文使用随滞后递减的权重：若截断参数为m，第j阶的权重是1−j/(m+1)，并把滞后协方差与其转置一起加入。同一期项另行保留。实现时需要同时核对索引、转置与权重，不能只保留“使用若干滞后”这个笼统描述。",
        "With truncation parameter m, lag j receives weight 1−j/(m+1); its covariance and transpose enter together alongside the contemporaneous term. Implementation requires consistent lag indexing, transposes and weights, not merely an instruction to include a few lagged observations."],
      ["3–4", "半正定不等于一定能求逆", "Positive semidefinite does not mean invertible",
        "该加权构造保证的半正定性质允许零特征值，并不等于矩阵必然严格正定或可逆。存在冗余矩条件、秩不足或数值问题时，后续计算仍需检查。不要把这项性质理解为每个检验都一定有效，或任何样本下都能直接完成矩阵求逆。",
        "The positive semidefinite property permits zero eigenvalues and does not guarantee invertibility. Redundant moments, rank deficiency or numerical problems still need scrutiny. This property is not a promise that every test is valid or that matrix inversion succeeds for every sample."],
      ["1–4", "滞后设置和样本仍影响推断", "Lag choices and sample size still matter",
        "一致性是随样本增长、在相应假设下成立的结论，不能直接等同于短样本的准确置信区间。截断参数决定保留多少依赖信息，也会影响估计噪声。阅读经验研究时，应记录滞后规则与样本频率，而不是只看到“Newey–West”名称就停止核对。",
        "Consistency is an asymptotic statement under assumptions, not a guarantee of accurate confidence intervals in short samples. Truncation governs retained dependence information and estimation noise. An empirical study should state its lag rule and observation frequency rather than relying on the Newey–West label alone."],
    ]),
  "Bootstrap Methods: Another Look at the Jackknife": guide(
    "https://sites.stat.washington.edu/courses/stat527/s13/readings/ann_stat1979.pdf",
    { zh: "1979年期刊版", en: "1979 journal article" },
    "University-course copy of Efron's 1979 paper: printed pp. 1–3 read for the sampling-distribution target, empirical distribution, replacement and jackknife relationship; p. 3 visually checked. Later examples and general-purpose confidence-interval validity were not independently verified.",
    { zh: "这里介绍原始单样本构造，不是对所有数据结构的自助法保证。有放回抽样不能自动保留时间、公司或群组依赖；增加重复次数也不会修复样本偏差。", en: "This guide describes the original one-sample construction, not universal bootstrap validity. Sampling with replacement does not automatically preserve time, firm or cluster dependence; more repetitions do not repair sample bias." },
    [
      ["1–2", "重采样要估计的是统计量的分布", "The target is a statistic's sampling distribution",
        "Efron提出的问题是：只观察到一个样本，如何近似某个统计量在重复抽样下的分布？研究对象可以是偏差、方差或更一般的统计量，而不只是样本均值。先明确要估计什么分布，才能判断重采样结果是否回答了原本的问题。",
        "Efron asks how one observed sample can approximate a statistic's distribution under repeated sampling. The target may concern bias, variance or a more general quantity rather than only a sample mean. Defining that target first determines whether a resampling result answers the intended question."],
      ["3", "用经验分布近似未知分布", "Replace the unknown distribution with an empirical one",
        "基本构造把每个已观察值赋予1/n的概率质量，形成经验分布，再把未知总体分布替换为它。这是从样本出发的近似，并没有创造新的总体信息。原样本若遗漏某类对象，重复抽取现有观测也不会自动恢复那些没有出现的对象。",
        "The basic construction assigns probability mass 1/n to each observed value and substitutes that empirical distribution for the unknown population. This is an approximation based on available data, not new population information. Resampling cannot automatically restore groups absent from the original observations."],
      ["3", "有放回抽取与打乱顺序不同", "Sampling with replacement is not permutation",
        "每次从经验分布中有放回抽取n个观测，因此某些原始值可能重复出现，另一些则不出现。它不是简单打乱原样本的顺序。置换检验与这种自助法具有不同随机机制，不能因为都生成很多样本，就把它们的假设与解释混为一谈。",
        "Each bootstrap sample draws n observations with replacement, so some original values repeat and others are absent. This is not merely a permutation of the data. Permutation tests and this bootstrap construction use different random mechanisms, even though both can generate many simulated samples."],
      ["2–3", "每次重新计算同一个目标", "Recompute a consistently defined target",
        "在每个重采样数据上重新计算目标统计量，同时使用经验分布对应的参照量，便形成自助分布。目标如何中心化或标准化会影响近似表现。只汇总重采样后的原始数据分布，而没有重新计算所关心的估计量，通常不是同一个任务。",
        "The target is recalculated on each resample using the corresponding empirical-distribution reference, producing a bootstrap distribution. Centering and scaling can affect approximation quality. Summarizing the resampled raw observations without recomputing the estimator of interest generally answers a different question."],
      ["1–3", "刀切法是相关方法，不是同一个过程", "The jackknife is related but not identical",
        "普通刀切法通过逐个删去观测重新估计，自助法则从经验分布有放回抽样。论文用线性近似理解二者的联系，并以样本中位数等例子说明适用表现可能不同。不能据此宣称任何统计量都能可靠地刀切，或自助法对所有问题都优于其他方法。",
        "The ordinary jackknife recomputes estimates after leaving out individual observations, whereas the bootstrap resamples with replacement. The paper relates them through linear approximation and discusses differing behavior for statistics such as the median. Neither connection establishes universal reliability or superiority for every statistic."],
      ["2–3", "抽样单位决定保留什么依赖", "The sampling unit determines retained dependence",
        "原始单样本说明从同一未知分布抽取观测。若把有时间相关的日收益或同一公司多期资料当作独立行抽取，就改变了原有依赖。应用到金融面板前，需要另行说明适合该结构的抽样单位与方法；重复次数更多并不能代替这个设计判断。",
        "The introductory one-sample construction draws observations from one unknown distribution. Treating dependent daily returns or repeated firm records as independent rows changes their dependence. Financial panels need a separately justified sampling unit and method; increasing repetitions cannot substitute for that design decision."],
    ]),
  "Regression Shrinkage and Selection via the Lasso": guide(
    "https://sites.stat.washington.edu/courses/stat527/s13/readings/j_royal_stat_soc_b1996.pdf",
    { zh: "1996年期刊版", en: "1996 journal article" },
    "University-course journal copy: printed pp. 267–269 and 273–275 read for the constraint, standardization, illustrative model and tuning uncertainty; p. 268 visually checked. Simulations and finance-specific predictive performance were not independently reproduced.",
    { zh: "Lasso的变量选择依赖缩放、样本和调参目标，不证明被选变量具有因果作用。原文的独立观测设定与示例不能直接替代金融时间序列的验证设计。", en: "Lasso selection depends on scaling, samples and tuning objectives; selected variables are not thereby causal. The paper's independent-observation setup and example do not replace validation designed for financial time series." },
    [
      ["267", "在偏差、方差与简洁性之间取舍", "Trade bias against variance and complexity",
        "普通最小二乘可能具有较大估计方差，完整模型也可能难以解释。Lasso通过收缩系数并让部分系数为零，在预测与简洁性之间寻求取舍。增加偏差有时能降低预测误差，但这不是任何数据都必然改善，更不等于找到了唯一真实模型。",
        "Ordinary least squares can have substantial variance and a full model may be hard to interpret. Lasso shrinks coefficients and sets some to zero, balancing prediction and simplicity. Added bias can sometimes reduce prediction error, but improvement is not universal and the selected model need not be uniquely true."],
      ["268", "约束上限越小，收缩越强", "A smaller bound means more shrinkage",
        "原文最小化残差平方和，同时限制系数绝对值之和不超过t。较小的约束上限通常意味着更强收缩；这与常见惩罚形式中参数越大、惩罚越强的方向不同。比较软件参数时，先确认使用的是约束上限还是惩罚权重，不能只比较数值大小。",
        "The original formulation minimizes residual sum of squares subject to an absolute-coefficient sum bounded by t. A smaller constraint bound means more shrinkage, unlike a penalty-weight formulation where a larger weight penalizes more. Software parameters must be identified by formulation before their numerical sizes are compared."],
      ["268", "变量尺度会改变惩罚含义", "Predictor scale changes the penalty's meaning",
        "论文先将解释变量中心化并缩放到统一尺度。若一个字段以元计、另一个以百万元计，同样大小的系数惩罚并不代表同样的变量影响。用于新数据时应保留缩放规则，并在训练资料上确定变换，不能用后来观察到的信息改善历史预测。",
        "Predictors are centered and standardized before fitting. A coefficient penalty has a different meaning when one input is measured in units and another in millions. For new predictive applications, preserve scaling rules and estimate transformations from training data rather than using later observations to improve historical predictions."],
      ["269", "零系数来自收缩，不是显著性裁决", "A zero coefficient is not a significance verdict",
        "在正交设计的说明中，Lasso表现为软阈值收缩：较小的系数被压至零，较大的也会缩小。这个例子帮助理解它与岭回归和子集选择的差异，但实际相关解释变量的情形更复杂。零系数不是证明某变量在经济上永远没有作用。",
        "In the orthonormal illustration, soft thresholding sets smaller coefficients to zero and shrinks larger ones. It clarifies differences from ridge regression and subset selection, but correlated predictors are more complicated. A zero fitted coefficient does not prove that a variable is economically irrelevant in every setting."],
      ["273–275", "调参目标是预测误差", "Tuning targets predictive error",
        "论文讨论交叉验证、广义交叉验证等选择收缩程度的方法，并以非金融资料展示模型。验证方式决定参数选择回答什么问题。对有时间先后关系的金融数据，不能直接把独立观测示例中的分折程序当成已经处理了时间泄漏或市场制度变化。",
        "Cross-validation and generalized cross-validation help select shrinkage, illustrated with nonfinancial data. The validation design determines the question answered by tuning. For ordered financial observations, the independent-data example does not establish protection against temporal leakage or changing market regimes."],
      ["274–275", "固定参数与重新调参的不确定性不同", "Retuning introduces another source of uncertainty",
        "论文比较自助样本中固定收缩参数与每次重新选择参数的标准误，后者加入额外的选择变化。报告一个固定模型的系数波动，不能自动概括完整建模流程的不确定性。解释结果时应说明是否重新调参，以及哪些步骤在重复样本中被固定。",
        "The example compares bootstrap standard errors with shrinkage held fixed and reselected in each sample; retuning adds selection variation. Variation around one fixed model does not automatically describe uncertainty in the full modeling procedure. State whether tuning is repeated and which steps remain fixed across samples."],
    ]),
};
