// Source locators are public reading aids; review scope remains internal.
const bi = (zh, en) => ({ zh, en });
const section = (zh, en, bodyZh, bodyEn, url, locatorZh, locatorEn) => ({
  title: bi(zh, en), body: bi(bodyZh, bodyEn),
  ...(url ? { reference: { url, label: bi(locatorZh, locatorEn) } } : {}),
});
const urls = {
  portfolio: "https://www2.stat.duke.edu/courses/Fall07/sta103/markowitz.pdf",
  volatility: "https://users.ssc.wisc.edu/~behansen/718/Anderson2003.pdf",
  accruals: "https://www.cuhk.edu.hk/acy2/workshop/June2009Wasley/1996TAR).pdf",
  china: "https://pages.stern.nyu.edu/~jcarpen0/pdfs/Carpenter%20Whitelaw%202017%20ARFE%20-%20The%20Development%20of%20China's%20Stock%20Market%20and%20Stakes%20for%20the%20Global%20Economy.pdf",
  text: "https://www.uts.edu.au/globalassets/sites/default/files/adg_cons2015_loughran-mcdonald-je-2011.pdf",
  tokens: "https://nengwang-economics.com/publications/papers/Cong_Li_Wang_RFS_2020_authorcopy.pdf",
  events: "https://bandi.feb.uns.ac.id/wp-content/uploads/2010/03/brown-warner-1985-1.pdf",
  yields: "https://elearning.unito.it/sme/pluginfile.php/546632/course/section/90489/DieboldLi_JoE06.pdf",
};
const guide = (key, scope, sections, zh, en) => ({ reviewedAt: "2026-08-30", evidenceUrl: urls[key], evidenceScope: scope, sections, limits: bi(zh, en) });

export const researchDeepReads = {
  "Portfolio Selection": guide("portfolio", "Original paper excerpt: opening argument, portfolio moment equations and efficient-set discussion. No empirical replication; not a full-paper review.", [
    section("为什么单看收益不够", "Why expected return is not enough", "Markowitz把选择过程分成形成未来判断与据此配置资产两步，本文研究后一步。若只追求最高预期收益，很难解释为何要分散持有；文章因此把预期收益与收益方差一起纳入选择。这里讨论的是给定判断后的取舍，不是如何预测股票。", "Markowitz separates forming beliefs from choosing a portfolio given those beliefs. The paper addresses the second task. Maximizing expected return alone cannot explain a preference for diversification, so variance enters alongside expected return. It is a framework for choices conditional on beliefs, not a stock-forecasting procedure."),
    section("材料是模型，不是回测样本", "A model, not a backtest sample", "输入是各证券的预期收益、方差和两两协方差，以及由投资者确定的权重。本文所展示的推导排除负权重，且权重之和为1。它没有给出某一市场或某段历史的优胜组合；历史收益只是后来估计这些输入的一种可能材料。", "Inputs are expected returns, variances, pairwise covariances and investor-chosen weights. The displayed analysis excludes negative weights and requires weights to sum to one. It does not report a winning historical portfolio. Using past returns to estimate its inputs is an additional empirical choice.", urls.portfolio, "原文：组合收益与方差定义", "Original: portfolio return and variance definitions"),
    section("关键一步：把共同变动算进去", "The key step: include co-movement", "组合期望收益是个别期望收益的加权和；组合方差还包含证券之间的协方差。因此，给两只各自波动很大的证券配权，结果取决于它们是否一起涨跌。只比较单只证券的风险，或者只数持仓个数，都会漏掉组合层面的关系。", "Portfolio mean is a weighted sum of individual means; portfolio variance also includes cross-security covariance terms. Combining two volatile securities therefore depends on their co-movement. Ranking securities by stand-alone volatility, or counting holdings, misses this portfolio-level relationship."),
    section("有效集合说明了什么", "What the efficient set tells us", "文章用几何方式描述可达到的收益—方差组合。在预期收益相同或更高时方差最低，或者方差相同或更低时期望收益最高的组合，构成有效选择的边界。这不是唯一答案：投资者仍需在边界上选择自己愿意接受的风险与收益组合。", "The geometric argument describes attainable mean–variance combinations and their efficient boundary. Efficiency means that another feasible portfolio cannot improve the relevant mean–variance trade-off. It does not identify one universally best allocation: the investor must still choose a preferred point on that boundary.", urls.portfolio, "原文：有效集合与几何说明", "Original: efficient-set and geometric discussion"),
    section("阅读时先分清三个对象", "Keep three objects separate", "建议依次区分个别证券的随机收益、事先固定的持仓权重，以及由两者组合得到的收益分布。读协方差式子时，检查非对角项如何改变结果；读有效边界时，再问哪些权重被允许。更换约束或预期判断，就已经在研究另一个可行集合。", "Track random security returns, fixed allocation weights and the resulting portfolio distribution separately. In the variance expression, inspect the off-diagonal terms; in the efficient-set argument, inspect the allowed weights. Different constraints or beliefs define a different feasible problem."),
    section("把模型带入数据前", "Before bringing data to the model", "编辑建议：先冻结收益定义、证券范围、观察窗口和缺失处理，再讨论估计。协方差矩阵所用的日期必须对齐，不能让不同证券在不同样本上悄悄计算。估计误差、交易成本与现实约束需另行处理；一条画出来的边界不能证明未来表现。", "Editorial application: freeze return definitions, the universe, observation windows and missingness rules before estimation. Align covariance inputs to a defensible common sample. Estimation error, trading costs and real constraints need separate treatment; a plotted frontier does not validate future performance."),
  ], "本文建立的是给定预期与协方差后的选择框架；样本估计、偏好和现实约束改变时，结果也会改变。", "This is a conditional choice framework. Estimated inputs, preferences and real-world constraints can change the result."),

  "Modeling and Forecasting Realized Volatility": guide("volatility", "Original Sections 1–2, 3.1–3.2 and introduction's findings; sample and construction passages checked. No re-estimation or numerical forecast-table audit.", [
    section("从日内变化到每日波动", "From intraday movement to daily volatility", "Andersen等人研究如何把日内信息用于日频及更低频的波动测量与预测。重点不是预测价格方向，而是把波动从潜在变量转为可以由高频收益近似测量的对象，再研究这个对象随时间如何变化。", "Andersen and coauthors use intraday information to measure and forecast daily and lower-frequency volatility. Their target is not price direction. They construct an observable proxy for variation from high-frequency returns, then model its dynamics."),
    section("原始样本与时间切分", "Original observations and time split", "原始材料是1986年12月至1999年6月Reuters屏幕上的马克/美元与日元/美元银行间买卖报价。它们是指示性报价，不是必然可成交的价格。作者剔除周末及部分低活跃假日后，保留3,045天，并将其分为2,449天估计期与596天样本外预测期。", "The raw material is indicative interbank DM/USD and JPY/USD bid/ask quotes on Reuters, December 1986–June 1999—not binding transaction prices. After weekend and selected holiday exclusions, 3,045 days remain: 2,449 for estimation and 596 for out-of-sample evaluation.", urls.volatility, "原文第3.1节：报价、清理与样本切分", "Original §3.1: quotes, cleaning and sample split"),
    section("30分钟采样是取舍", "Thirty-minute sampling is a trade-off", "作者从相邻报价插值得到等间隔价格，再计算30分钟对数收益；按日累加收益平方及交叉乘积，构造波动与协变动。选择30分钟，是为了平衡更密集采样的信息收益与微观结构噪声，并非证明这个间隔对所有市场最优。", "They interpolate prices from neighboring quotes, calculate half-hour log returns and aggregate squared returns and cross-products. Thirty-minute sampling balances information against microstructure contamination in this setting. It is not a universally optimal interval.", urls.volatility, "原文第3.1–3.2节：收益与已实现波动构造", "Original §§3.1–3.2: returns and realized-volatility construction"),
    section("论文报告的发现", "What the paper reports", "作者利用对数已实现波动的近似高斯分布与长记忆特征建立简单的多变量模型，并报告其波动预测通常优于比较模型。结合条件收益分布后，还检验密度与分位数预测。阅读时要分开点预测好坏和整个预测分布是否校准，不能用其中一个替代另一个。", "The authors exploit approximately Gaussian log realized volatility and long-memory dynamics in a simple multivariate model. They report generally strong volatility forecasts and assess return-density and quantile calibration. Point-forecast accuracy and distributional calibration are distinct evaluations."),
    section("建议怎样读", "A useful reading order", "先读第3节，明确每日样本究竟怎样生成；再回第2节理解二次变差与实际测量之间的关系；最后读第5–6节的模型与预测比较。尤其注意：已实现波动是事后测量，预测必须只使用预测时点之前的信息，二者不能混成同一个指标。", "Start with Section 3's construction, return to Section 2's quadratic-variation foundation, then read Sections 5–6 on modeling and forecast comparisons. Keep ex-post realized variation distinct from a forecast formed using information available beforehand."),
    section("迁移到股票分钟线的缺口", "What changes with equity bars", "编辑建议：股票有午间休市、集合竞价、停牌和隔夜区间，不能照搬全球外汇的24小时日界。分钟收盘价也不是原文的买卖报价中点。应先标明缺口与时间网格，单独处理隔夜变化，再讨论频率敏感性，不能将补零后的完整表格当作完整观测。", "Editorial application: equities introduce lunch breaks, auctions, suspensions and overnight intervals, unlike the global FX day. Minute closes are not quote midpoints. Mark gaps, define session boundaries and separate overnight movement before testing sampling sensitivity; zero-filled rows are not observations."),
  ], "历史外汇结果不能直接证明股票或加密市场的预测效果；缺失、报价口径与采样噪声都需要重新检查。", "Historical FX results do not establish forecasting performance for equities or crypto. Missingness, quote conventions and sampling noise require fresh checks."),

  "Do Stock Prices Fully Reflect Information in Accruals and Cash Flows about Future Earnings?": guide("accruals", "Original introduction and Sections II–III (hypotheses, 1962–1991 sample, balance-sheet accrual measurement). Findings summarized from introduction; no portfolio replication.", [
    section("同样的利润，能否同样持续", "Can equal earnings persist differently?", "Sloan把当期利润拆成应计与现金流部分，研究它们对未来利润的含义是否不同，以及价格是否充分区分这种差别。问题不是简单地把应计项目判成坏消息，而是考察会计组成与持续性之间的联系。", "Sloan separates earnings into accrual and cash-flow components, asking whether their persistence differs and whether prices reflect that difference. Accruals are not simply classified as bad news; the question concerns the information in earnings composition."),
    section("30年的美国公司数据", "Thirty years of US company data", "论文将1993版Compustat与CRSP文件连接，使用1962—1991年财务资料，最终有40,679个公司年度观察。样本筛选要求必要财务项目、股票收益和后续利润可得；银行与保险等缺少所需应计资料的公司不在这一测量范围内。这不是全市场无条件样本。", "The study joins the 1993 Compustat and CRSP files, using financial statements for 1962–1991 and 40,679 firm-years. Required accounting items, returns and subsequent earnings determine inclusion. Banks and insurers lack the necessary accrual data in this setup, so the sample is not unconditional market coverage.", urls.accruals, "原文第III节：样本形成", "Original §III: sample formation"),
    section("应计口径不是随手相减", "Accrual measurement is specific", "由于现金流量表规则只覆盖样本末期，作者用资产负债表与利润表项目构造经营应计：流动资产变动扣现金，减去调整短期债务和应付税后的流动负债变动，再扣折旧摊销。利润采用折旧后的经营利润，现金部分由利润减应计得到，不能直接替换成任意净利润与现金流字段。", "Because cash-flow-statement reporting covers only the sample's final years, operating accruals are reconstructed from balance-sheet changes and depreciation. Earnings use operating income after depreciation; the cash component is the residual after accruals. Arbitrary net-income and cash-flow fields are not interchangeable with these definitions.", urls.accruals, "原文第III节：变量定义", "Original §III: variable measurement"),
    section("分别检验持续性与定价", "Test persistence and pricing separately", "论文先研究两个组成部分对未来利润的持续性，再检验价格中隐含的预期是否充分区分它们。进一步观察后续异常收益及其是否集中在未来业绩公告附近。这样能把会计关系、价格解释与信息揭示时间联系起来，但每一层都有各自的模型假设。", "The tests separate earnings persistence from expectations embedded in prices, then examine subsequent abnormal returns and their concentration around later earnings announcements. Accounting relations, pricing interpretation and information timing are connected, but each layer retains its own assumptions."),
    section("发现应怎样理解", "How to interpret the finding", "作者报告应计部分的持续性低于现金部分，价格表现与投资者未充分区分这两者相一致。原文中的历史异常收益是支持这一解释的证据，不是今天可获得同样收益的保证；异常收益也依赖基准模型，不能直接叫作无风险利润。", "The paper reports lower persistence for the accrual component and price behavior consistent with incomplete differentiation. Historical abnormal returns support that interpretation; they do not promise a current payoff. Abnormal performance also depends on the benchmark and is not risk-free profit."),
    section("读完后先准备版本面板", "Prepare a versioned panel first", "编辑建议：从原文第III节逐项映射会计定义，保留单位、合并范围与报告版本。财年末不等于信息可得日，最新重述值也不能倒填历史。若历史版本或发布日期不足，先把缺口列清，再用时点一致教程验证选择规则，不要先做组合再补解释。", "Editorial application: map each Section III definition, preserving units, consolidation scope and filing versions. Fiscal year-end is not availability; latest restatements cannot be backfilled as historical knowledge. Expose missing vintage or release evidence before moving beyond the point-in-time preparation exercise."),
  ], "会计准则、行业范围、存活筛选与披露时间都会影响迁移；应计高低本身不是公司质量定论。", "Accounting rules, industry coverage, survival filters and disclosure timing affect transferability. Accrual magnitude alone is not a verdict on company quality."),

  "The Development of China's Stock Market and Stakes for the Global Economy": guide("china", "2017 published review: abstract, introduction and Section 2 incl. 2.1; synthesis is attributed to review, not independent re-estimation of cited papers or claims beyond the abstract and inspected sections.", [
    section("先理解制度，再套用模型", "Institutions before imported models", "Carpenter与Whitelaw解释为何研究中国股市不能只移植美国市场的常见假设。股票市场同时涉及国企改革、上市选择与资本配置，企业目标和投资者约束未必与已有模型一致。文章的价值是提出研究问题的背景，而不是给市场打一个效率总分。", "Carpenter and Whitelaw explain why familiar US-market assumptions may not transfer to China. SOE reform, listing selection and capital allocation interact with different objectives and constraints. The review frames research questions rather than assigning the market a single efficiency score."),
    section("这是2017年的文献综述", "A review published in 2017", "文章梳理公司金融与资产定价文献，并以当时的制度演进组织讨论，没有一个可以概括全文的统一回归样本。引言中的规模与制度描述对应其写作时期；阅读时应将其视为历史背景，不能把2017年的规则表述直接当成今天的规则。", "This review organizes corporate-finance and asset-pricing studies around institutional development; there is no single pooled regression sample for the article. Market sizes and rules in its introduction belong to its historical setting, not automatically to the present.", urls.china, "原文摘要与第1节：综述范围", "Original abstract and §1: review scope"),
    section("公司侧：上市与所有权选择", "Corporate side: listing and ownership", "第2节从部分私有化、IPO和上市选择展开。文章比较不同研究对产权变化与企业表现的发现，并提醒国企还可能承担就业、社会与战略目标。因此，上市公司不一定代表全部企业，单个利润指标也未必覆盖改革的全部目标。", "Section 2 examines partial privatization, IPOs and listing choice. It contrasts findings on ownership and performance and notes SOEs' employment, social and strategic roles. Listed firms need not represent all firms, and a single profitability measure need not capture every reform objective.", urls.china, "原文第2节，尤其第2.1节", "Original §2, especially §2.1"),
    section("价格侧：分割与信息含量", "Pricing side: segmentation and information", "引言归纳了A股与境外股份价差、公司特定信息进入价格，以及收益横截面等研究线索。价格差异可能同时涉及信息、可投资范围与市场分割，不能看到价差就认定存在可执行套利；价格波动大也不等于没有公司信息。", "The introduction maps work on A-share versus foreign-share premiums, firm-specific price information and the return cross-section. Information and investment constraints can coexist with segmentation. A price gap is not proof of executable arbitrage, and volatility alone is not proof of absent information."),
    section("如何使用这篇综述", "How to use this review", "建议先选一个问题，例如股权改革如何改变企业行为，再沿第2节追到被引用的原始研究。分别记录每篇的政策时期、处理对象、对照样本与结果变量。综述适合建立地图；若要引用具体效果大小或因果结论，仍需回到对应论文核对。", "Choose a question—such as how ownership reform changes firm behavior—then follow the review to original studies. Record policy periods, treated units, comparison groups and outcomes. A review supplies a map; effect sizes and causal claims still require checking the cited originals."),
    section("数据准备从历史身份开始", "Start with historical identities", "编辑建议：证券代码之外，还需保留上市板块、股份类别、所有权和资格规则的生效时间。用今天的公司主表回填过去，会抹去改革和样本选择。若研究涉及跨市场比较，还要明确币种、交易日历与可交易限制，不能仅按同名公司连接两列价格。", "Editorial application: preserve dated board membership, share class, ownership and eligibility alongside identifiers. Today's company master can erase historical selection and reform changes. Cross-market comparisons additionally need currency, calendars and trading constraints, not just matching company names."),
  ], "这是一张历史研究地图；当前制度、原始论文的识别假设和可获得数据需分别核对。", "This is a historical research map. Current institutions, original studies' identification assumptions and available data require separate checks."),

  "When Is a Liability Not a Liability? Textual Analysis, Dictionaries, and 10-Ks": guide("text", "Original introduction and Section II A–D: 1994–2008 sample, parsing and event definitions; findings from introduction. No independent dictionary or return reconstruction.", [
    section("负面词不一定是负面消息", "A negative word is not always bad news", "Loughran与McDonald指出，通用词典中的负面词在财务文件里可能只是术语。例如负债、税或成本经常是在描述会计项目。研究问题是词典是否测到了财务语气，还是不经意测到了行业与文件写法。", "Loughran and McDonald question whether general-purpose negative-word lists measure financial tone. Terms for liabilities, taxes or costs may simply describe accounting items. A dictionary can inadvertently capture industry or document conventions instead of adverse information."),
    section("样本经过多层筛选", "The sample is filtered", "原文使用1994—2008年的EDGAR年度10-K及10-K405文件，排除修订文件，并连接CRSP与Compustat。满足标识、价格、收益、财务信息和文本长度等条件后，留下50,115个公司年度、8,341家公司。管理层讨论部分另有识别与长度筛选，不能把子样本直接当成全样本。", "The study uses 1994–2008 EDGAR 10-K/10-K405 filings, excluding amendments, matched to CRSP and Compustat. Identity, price, returns, accounting and document-length requirements leave 50,115 firm-years from 8,341 firms. MD&A analyses apply additional extraction and length filters.", urls.text, "原文第II.A节：10-K样本", "Original §II.A: the 10-K sample"),
    section("先解析，再计数", "Parsing comes before counting", "作者采用词袋表示，但计数前先排除表格与附件，减少模板语言的干扰。文中还比较词频比例与词项加权，避免高频词压过真正有信息的词。因而“全文分析”在这里不是把下载文件每个字符直接分词：解析范围本身就是方法的一部分。", "The bag-of-words pipeline excludes tables and exhibits to reduce boilerplate contamination. Proportional counts are compared with term weighting, which reduces domination by frequent words. Here, full-document analysis has a defined parsing boundary; it is not indiscriminate tokenization of every downloaded character.", urls.text, "原文第II.B与II.E节：解析与加权", "Original §§II.B and II.E: parsing and weighting"),
    section("发现不是一条交易信号", "The finding is not a trading signal", "作者发现通用词典存在显著语境误分类，财务负面词表及加权方案能改变与文件披露反应的关系。但引言也明确指出，比较的语气指标没有显示出其检验中的未来收益可预测性。能描述同期市场反应，不等于能提前获利。", "The authors report substantial contextual misclassification and show that financial dictionaries and term weighting change relations with filing reactions. They also report no future-return predictability from the competing tone measures in their tests. Describing an announcement response is not the same as forecasting profits."),
    section("读方法时追踪事件窗口", "Track the event window", "第II.D节把披露反应定义为提交日及随后三日的持有期超额收益，并说明基准与控制变量。建议把文本范围、词表版本、分母和事件时间一起记录：即使词典相同，换成新闻标题、中文公告或另一种事件窗口，也不是同一项测量。", "Section II.D defines a filing-date response over days 0–3 and specifies the benchmark and controls. Track text boundaries, dictionary version, denominator and event timing together. The same dictionary applied to headlines, Chinese announcements or another window defines a different measurement."),
    section("中文材料需要另行验证", "Chinese documents need separate validation", "编辑建议：中文文本的分词、否定、歧义与财务术语要在人工标注样本上验证，不能逐词翻译英语词典后宣称等效。保留文件哈希与修订关系，才能区分语气变化、解析器变化和重复转载；不要把数据清理差异解释成公司行为变化。", "Editorial application: validate Chinese segmentation, negation and domain terms against labeled material; translating an English dictionary does not establish equivalence. Preserve document hashes and revisions to distinguish tone changes from parser changes or syndicated copies."),
  ], "词典是有版本、有语境的测量工具，不是对事实真伪或投资价值的自动判断。", "A dictionary is a versioned, context-dependent measurement tool, not an automatic judgment of truth or investment value."),

  "Tokenomics: Dynamic Adoption and Valuation": guide("tokens", "Author copy dated 2020: introduction and Section 1 model setup, with findings attributed to introductory overview. Catalogue retains 2021 publication identity. No token calibration.", [
    section("代币价格与用户采用互相影响", "Token value and adoption interact", "Cong、Li与Wang研究作为平台支付媒介的代币：更多用户可能提高平台交易价值，而预期代币升值又可能改变用户现在是否加入。它把采用决策与代币价格放在同一个动态模型里，不把用户数量简单当作外生估值倍数。", "Cong, Li and Wang model tokens used as platform payment media. More users can raise transaction utility, while expected token appreciation can affect today's participation. Adoption and valuation are jointly determined rather than treating user count as an external valuation multiple."),
    section("理论对象，不是币价样本", "A theoretical economy, not a price sample", "模型中的用户有不同交易需求，平台生产率随机变化，代币供给在基准设定中固定。用户决定是否承担参与成本，以及持有多少支付余额。文中提到具体平台是帮助解释机制，不是对这些币做出的样本回归或价格目标。", "Users differ in transaction needs, platform productivity is stochastic and baseline token supply is fixed. Agents choose participation and payment balances. Named platforms illustrate the mechanism; they are not an empirical price-regression sample or valuation targets.", urls.tokens, "作者版本第1节：平台经济模型", "Author copy §1: platform-economy model"),
    section("持有成本是关键连接", "Carrying cost connects the decisions", "持有支付媒介意味着放弃其他资产的回报。在模型中，预期代币升值可以抵消部分机会成本，鼓励更早采用；用户增长又增加代币需求。这个反馈需要平台交易效用、网络效应与预期共同成立，不是仅靠限制发行数量就能推出价格上涨。", "Payment balances forgo returns on other assets. Expected token appreciation can offset part of that opportunity cost and encourage earlier adoption, while user growth increases demand. The feedback depends on transaction utility, network effects and expectations—not scarcity alone."),
    section("模型给出的条件性结论", "Conditional model implications", "作者描述了S形采用路径，以及在相同生产率过程下，代币平台相较无代币平台更快、更稳定的采用。网络效应也可能放大生产率冲击对价格的影响。因此，“采用更稳定”与“价格更稳定”不能混为一谈，更不能据此断言现实项目必然成功。", "The model produces S-shaped adoption and, relative to a tokenless platform with the same productivity process, accelerated and more stable participation. Network effects can also amplify price responses to productivity shocks. Stable adoption and stable prices are different claims."),
    section("阅读时对照两种平台", "Compare like-for-like platforms", "建议先读第1节，列出用户效用、参与成本、供给与贴现假设；随后比较有代币与使用普通计价商品的平台。尤其注意代币的权利：本文交易媒介并不等同于代表发行人现金流的证券型代币。用不同权利的资产替代，会改变模型问题。", "Start with utility, participation cost, supply and discounting assumptions in Section 1, then compare token and numeraire-settled platforms. Rights matter: transaction tokens here are distinct from claims on issuer cash flows. Substituting a different asset changes the model's question.", urls.tokens, "作者版本引言：代币范围与比较思路", "Author-copy introduction: token scope and comparison"),
    section("怎样准备后续观察材料", "Preparing subsequent observations", "编辑建议：如果要研究现实平台，应分别定义真实用户、交易用途、代币余额和供给变更，并检查激励活动或机器人是否扭曲计数。交易所价格与成交量只能描述交易活动，不能替代平台采用和效用；本导读不输出估值、收益预测或买卖建议。", "Editorial application: define users, transaction uses, balances and supply changes separately, checking incentive-driven or automated activity. Exchange prices and volumes cannot substitute for platform adoption or utility. This guide produces no valuation, return forecast or trading recommendation."),
  ], "导读依据2020年作者版本；书目保留2021年正式发表身份。理论比较不等于对现实代币的实证验证。", "The guide uses the 2020 author copy while retaining the 2021 publication identity. Theoretical comparisons are not empirical validation of live tokens."),

  "Using Daily Stock Returns: The Case of Event Studies": guide("events", "Original introduction, Sections 2–3 and opening findings; sample/window definitions checked in prose, no simulation rerun or numeric table audit.", [
    section("检验方法会不会自己制造事件", "Can the test manufacture an event?", "Brown与Warner研究日收益的厚尾、非同步交易与方差变化，是否会破坏事件研究中的统计检验。问题是方法在没有异常表现时会不会误报，以及存在给定异常表现时能不能发现，而不是证明某一类公司公告必然影响价格。", "Brown and Warner ask how daily-return properties affect event-study tests. They examine false rejection when abnormal performance is absent and detection when a known effect is introduced. They do not establish the impact of one particular announcement category."),
    section("真实收益配上虚构事件日", "Actual returns, artificial event dates", "作者从CRSP随机有放回抽取证券与事件日期，构造250组、每组50只证券，日期范围为1962年7月至1979年12月。收益来自历史市场，但事件是随机指定的。因此这是一项方法模拟，不能把样本理解成250次真实公告。", "The experiment constructs 250 samples of 50 securities, drawing securities and event dates with replacement from CRSP, July 1962–December 1979. Returns are historical, but events are assigned randomly. These are methodological simulations, not 250 observed announcement episodes.", urls.events, "原文第3.1节：实验样本", "Original §3.1: experimental samples"),
    section("先估计正常表现，再看事件窗口", "Estimate normal performance first", "每只证券最多使用事件前244日至后5日的250个日收益；前239日为估计期，最后11日为事件期。作者比较均值调整、市场调整和OLS市场模型。不同基准给出不同的异常收益定义，估计窗口与事件窗口不能互相污染。", "Up to 250 returns span days −244 through +5: 239 estimation days and an 11-day event period. Mean-adjusted, market-adjusted and OLS market-model measures are compared. Each benchmark defines abnormal performance differently, and estimation and event windows must remain separate.", urls.events, "原文第3.1–3.2节：窗口与超额收益", "Original §§3.1–3.2: windows and excess returns"),
    section("误报率和检验能力是两件事", "Size and power are different", "没有人为加入异常收益时，观察拒绝原假设的频率；随后向事件日收益加入已知幅度，观察方法能否检出。前者考察误报，后者考察检验能力。仅展示一次显著结果，既不能证明方法校准，也不能说明未显著时确实没有经济效应。", "With no added abnormal return, rejection frequency measures test size. Adding a known event-day effect probes power. One significant result establishes neither calibration nor the ability to detect plausible effects; an insignificant result is not automatically evidence of no economic effect."),
    section("结果不是忽略相关性的通行证", "The findings are not a dependence waiver", "论文报告标准日频方法在不少模拟情形下表现良好，同时指出超额收益自相关和事件引起的方差变化有时值得调整。某些设定中更复杂的相关性处理未必更有检验力，但不能据此忽略真实样本中的集中事件、共同冲击或重叠窗口。", "Standard daily procedures perform well in many simulations, while serial dependence and event-induced variance changes sometimes warrant adjustment. More elaborate dependence correction need not always improve power, but that is not permission to ignore clustered events, common shocks or overlapping windows."),
    section("从事件定义开始落地", "Begin with an event definition", "编辑建议：先确定事件身份、可得时间与交易日映射，再定义估计窗口、基准和样本单位。对集中发生的事件单独检查依赖结构，并保留未对齐记录。本板块的事件时间线教程只完成这些准备，不替代异常收益估计或因果识别。", "Editorial application: define event identity, availability and session mapping before choosing windows, benchmarks and sampling units. Inspect dependence for clustered events and retain unresolved records. The event-timeline tutorial handles preparation only, not abnormal-return estimation or causal identification."),
  ], "随机事件模拟的良好表现不自动适用于集中公告、选择性事件或另一市场的交易制度。", "Performance under random-event simulation does not automatically transfer to clustered announcements, selected events or another market's trading institutions."),

  "Forecasting the Term Structure of Government Bond Yields": guide("yields", "Original Sections 2.1–2.2, 3.1 and 4: yield conventions, factor interpretation, sample and qualitative forecast conclusion. No numerical forecast-table replication.", [
    section("拟合今天与预测未来不同", "Fitting today is not forecasting tomorrow", "Diebold与Li把Nelson–Siegel曲线重新解释为水平、斜率与曲率三个动态因子，再预测因子来重建未来曲线。核心问题不只是当前各期限能否拟合得很漂亮，而是这种简约结构是否有助于样本外预测。", "Diebold and Li reinterpret Nelson–Siegel coefficients as dynamic level, slope and curvature factors. Forecasting the factors reconstructs a future curve. The question is whether a parsimonious structure helps out-of-sample prediction, not merely whether today's curve fits closely."),
    section("输入是构造后的零息收益率", "Inputs are constructed zero yields", "样本为1985年1月至2000年12月的美国国债月末买卖报价均值，来自CRSP。作者由过滤后的债券报价构造Fama–Bliss零息收益率，再将相邻期限插值到固定期限。这不是把债券票息或任意到期收益率直接拼成一条曲线。", "The sample uses end-of-month US Treasury bid/ask averages from CRSP, January 1985–December 2000. Filtered bond prices yield Fama–Bliss zero rates, interpolated to fixed maturities. Coupon rates or arbitrary coupon-bond yields cannot simply be substituted.", urls.yields, "原文第2.1与3.1节：收益率口径和数据", "Original §§2.1 and 3.1: yield conventions and data"),
    section("三个因子怎样作用于期限", "How the factors load on maturity", "水平因子的载荷在所有期限相同；斜率因子更多作用于短端；曲率因子主要作用于中段。作者固定衰减参数，让每期因子可以用较简单的估计方法得到。要注意斜率的符号约定：因子系数不应未经转换就等同于长端减短端的利差。", "The level loading is constant, the slope loading concentrates at the short end and curvature loads most strongly in the middle. Fixing the decay parameter simplifies factor estimation. Sign conventions matter: a slope coefficient is not automatically the long-minus-short yield spread.", urls.yields, "原文第2.2节：因子解释", "Original §2.2: factor interpretation"),
    section("优势依赖预测期限", "The advantage depends on horizon", "结论部分报告，一月期预测未优于随机游走等主要对照，而一年期表现明显更好。这提醒读者不要只说“模型胜出”，而应写明预测期限、评价样本与基准。当前曲线拟合更灵活，也不保证样本外预测更准。", "The conclusion distinguishes horizons: one-month forecasts do not outperform the leading benchmarks, while one-year forecasts are substantially stronger. A model comparison must specify horizon, evaluation sample and benchmark. A more flexible in-sample fit does not guarantee better forecasts.", urls.yields, "原文第4节：预测结论与限制", "Original §4: forecasting conclusions and limits"),
    section("先读单位，再读预测比较", "Read units before comparisons", "建议先核对零息、连续复利、期限单位和报价日期，再读第2.2节的载荷，最后看预测比较。模型中的期限用月表示；如果改成年而不一致地调整参数，曲线形状就会被改变。不同国家或数据商的曲线也要先统一口径。", "Check zero-coupon status, compounding, maturity units and observation dates before reading the loadings and forecast comparisons. Maturity is measured in months; changing units without adjusting parameters changes the shape. Curves from different countries or vendors need convention alignment first."),
    section("预测模型不是定价保证", "A forecast model is not a pricing guarantee", "作者明确讨论其模型并非无套利模型。编辑建议：若目标是预测，先保留时间切分与基准；若目标转为衍生品定价，则需要另行处理无套利与动态一致性。宏观解释也应独立检验，不能把水平、斜率和曲率的名称直接当成经济因果。", "The authors explicitly note that their model is not arbitrage-free. Editorial application: preserve chronological evaluation for forecasting; derivative pricing needs additional no-arbitrage and dynamic-consistency treatment. Factor labels also do not establish macroeconomic causality."),
  ], "美国历史月度样本的预测比较不是跨市场保证；零息口径、期限单位与预测目标必须保持明确。", "Historical US monthly forecast comparisons are not a cross-market guarantee. Keep zero-yield conventions, maturity units and forecasting targets explicit."),
};
