// Bibliographic identities remain fixed; these are bounded, original reading guides.
const bi = (zh, en) => ({ zh, en });
const guide = (url, edition, evidenceScope, limits, rows) => ({
  reviewedAt: "2026-08-31", evidenceUrl: url, evidenceScope, limits, related: {},
  sections: rows.map(([location, zh, en, bodyZh, bodyEn]) => ({
    title: bi(zh, en), body: bi(bodyZh, bodyEn),
    reference: { url, label: bi(`${edition.zh} · ${location}`, `${edition.en} · ${location}`) },
  })),
});

export const researchEightyGuides = {
  "Time Series Momentum": guide(
    "https://w4.stern.nyu.edu/facdir/lpederse/papers/TimeSeriesMomentum.pdf", bi("2012年期刊版", "2012 journal article"),
    "Author-hosted final article p. 228 and pp. 231–233 inspected for own-return versus cross-sectional comparison, return construction, volatility scaling, CFTC classifications and panel inference. Strategy sections, performance claims and trading implementation not reproduced.",
    bi("这里讨论历史研究的测量与推断，不提供交易信号或组合。期货超额收益、现货价格和合约拼接不是同一对象；历史统计关系不保证未来表现。", "This guide concerns measurement and inference, not signals or portfolios. Futures excess returns, spot prices and contract stitching are different objects; historical associations do not guarantee future performance."), [
      ["§1", "比较自己的过去，而不是同伴排名", "Compare an asset with its own past, not its peers",
        "时间序列动量关注同一资产过去与未来收益的关系，横截面动量则比较资产相对同伴的表现。即使两者都使用过去收益，它们的基准与问题不同。市场中所有资产同时上涨时，一个资产仍可能在自身历史意义上上涨、却在横截面落后。",
        "Time-series momentum relates an asset's own past and future returns; cross-sectional momentum compares its performance with peers. Their benchmarks differ even when both use past returns. An asset can rise in absolute terms while lagging a broadly rising market."],
      ["§2.1 · p. 231", "研究输入是合约收益，不是拼接价格图", "The input is contract returns, not a stitched price chart",
        "论文逐日计算流动性较高合约的超额收益，再将收益复合为可比较的序列。换月时的两个价格可能因为交割日期不同而有价差；直接连接价格并求涨跌，会把合约差异误认为持有收益。收益定义应先于任何历史比较。",
        "The article compounds daily excess returns from liquid contracts into comparable series. Contracts with different delivery dates can have different prices at a roll. Joining their prices and taking changes can mistake a contract difference for a holding-period return."],
      ["§2.4", "不同资产先处理波动尺度", "Reconcile volatility scales across assets",
        "不同合约的波动大小差异很大，未经处理的汇总可能被少数高波动资产主导。作者用事先估计的波动率将收益放在相近尺度上。这个变换改变比较的权重，不等于提高了原始收益，也不保证每个资产未来风险完全相同。",
        "Volatility differs substantially across contracts, so unscaled aggregation can be dominated by a few volatile instruments. The paper uses ex ante volatility to put returns on comparable scales. This changes comparison weights; it does not improve raw returns or equalize future risk perfectly."],
      ["§2.4 · equation (1)", "风险估计必须早于所评价的收益", "The risk estimate must precede the evaluated return",
        "波动率估计使用滞后平方收益，并在评价当期收益时采用上一时点的估计。这个时间顺序避免把当前结果反馈进事前风险尺度。用整个样本统一标准化虽然方便，却会与原文事先可得信息的含义不同，必须明确区分。",
        "Volatility is estimated from lagged squared returns, using the prior estimate for the current return. That ordering avoids feeding the evaluated outcome into its ex ante scale. Full-sample normalization would have a different information meaning and must be distinguished."],
      ["§2.2", "商业与非商业分类不是动机的直接观测", "Trader classifications do not directly observe motives",
        "研究使用CFTC的商业与非商业交易者分类讨论持仓，但原文承认商业交易者也可能进行投机，分类覆盖也并非所有合约一致。这些标签是申报口径，不能直接证明每个账户的真实目的；周度持仓也不是逐笔成交记录。",
        "CFTC commercial and non-commercial categories support the position analysis, but commercial traders can also speculate and coverage differs across contracts. These reporting labels do not prove individual motives. Weekly positions are not transaction-by-transaction trading records."],
      ["§3.1", "多资产面板仍共享同一时间冲击", "A multi-asset panel still shares shocks across time",
        "回归将不同合约与日期组合起来，同时按月份聚类计算推断，以考虑同月资产间的相关。合约数量增加不等于增加同等数量的独立历史。对历史持续性的解释，还应与样本选择、预测期限和未使用样本中的表现分开讨论。",
        "The pooled regressions account for common monthly dependence through time clustering. More contracts do not supply an equal number of independent histories. Interpretation of persistence must remain separate from sample selection, forecast horizons and evidence from untouched observations."],
    ]),
  "Law, Finance, and Economic Growth in China": guide(
    "https://ocw.mit.edu/courses/11-946-planning-in-transition-economies-for-growth-and-equity-spring-2004/9257eee0807f159387f0a70050eb3359_feb_17.pdf", bi("2004年2月3日修订稿", "February 3, 2004 revision"),
    "MIT-hosted manuscript cover and printed pp. 1–5 read for the three sector definitions, cross-country comparison, listed-company evidence and 17-interview regional evidence. This early draft is not the 2005 journal version; later sample sizes and historical projections are not adopted.",
    bi("导读依据2004年工作稿，不能当作当前中国制度或融资结构的说明。稿中的Private Sector包括部分地方政府相关所有制，访谈证据也不代表全国随机样本。", "The 2004 draft is not a description of current Chinese institutions or financing. Its Private Sector includes some local-government-related ownership, and its interviews are not a national random sample."), [
      ["§I · pp. 1–2", "用中国经验追问跨国规律的边界", "Use China to question the boundaries of cross-country regularities",
        "Allen、Qian与Qian将中国当时的增长经验与法律、金融和增长文献对照，提醒跨国平均关系可能遗漏大型经济体内部的差异。问题不是简单选边支持或反对法律保护，而是现有解释能否覆盖不同部门的融资与治理方式。",
        "Allen, Qian and Qian compare China's historical growth with law-and-finance research, questioning whether country averages obscure internal differences. The issue is not a simple vote for or against legal protection, but whether existing explanations cover different financing and governance arrangements."],
      ["§I · p. 2; footnote 6", "先按论文定义理解三个部门", "Read the three sectors using the paper's definitions",
        "工作稿分别讨论国有、上市及其定义下的Private Sector。最后一类包含其他私人和部分地方政府相关所有制，不能直接翻译成今天统计口径下的纯民营企业。部门比较之前，应保留作者的分类，避免把不同年代的名称当作完全一致。",
        "The draft discusses state, listed and its defined Private Sector, the last including private and some local-government-related ownership. It is not identical to a present-day purely private-firm category. Preserve the authors' definitions before comparing sectors across periods."],
      ["§I · pp. 3–4", "上市公司不能代表全部企业融资", "Listed companies do not represent all corporate finance",
        "作者把上市公司样本与其他部门分开，指出公开证券市场只是企业融资的一部分。对上市公司分红、估值或股权集中度的观察，不能自动说明非上市企业怎样取得资金。只用股票数据库研究整体经济，会遗漏另一种重要的样本选择。",
        "The article separates listed-company evidence from other sectors because public securities are only one financing channel. Listed-company dividends, valuations and ownership do not explain how all unlisted firms obtain funds. A stock database introduces a consequential selection boundary."],
      ["§I · p. 4", "访谈提供机制线索，不是全国估计", "Interviews provide mechanism evidence, not national estimates",
        "这一早期稿的私人部门证据主要来自浙江与江苏17位创业者和管理者的访谈，地区本身也较发达。它能帮助理解亲友、金融机构和关系网络的作用，但不能据此计算全国企业使用某融资渠道的精确比例，更不能混用后续版本样本。",
        "This early draft relies mainly on interviews with 17 entrepreneurs and executives in Zhejiang and Jiangsu. These developed regions offer mechanism evidence about family, institutions and relationships, not a precise national financing share. Later-version samples must not be substituted silently."],
      ["§I · pp. 4–5", "声誉与重复合作可以影响履约", "Reputation and repeated relationships can affect enforcement",
        "工作稿讨论声誉、关系、竞争和共享未来收益如何约束参与者行为。这些机制依赖持续合作的价值与具体环境，并不是无成本、无风险的正式制度替代物。看到某些企业通过关系融资成功，也不能推断所有企业都能获得同样机会。",
        "The draft discusses reputation, relationships, competition and shared future gains as constraints on behavior. These mechanisms depend on continued cooperation and context; they are not costless substitutes for formal institutions. Success among some firms does not imply equal access for all."],
      ["§I", "比较解释，不把历史研究变成今日制度结论", "Compare explanations without turning history into a current institutional claim",
        "这篇研究提供的是特定转型时期的部门比较与机制讨论。与投资者保护文献并读时，应区分外部公开融资、关系型融资和企业增长这几个结果。历史上存在替代渠道，不等于正式保护不重要，也不证明今天的法律和融资条件仍与当时相同。",
        "This is a sector comparison from a particular transition period. Read it alongside investor-protection research while separating public external finance, relationship finance and growth. Alternative channels do not make formal protection irrelevant or establish that today's institutions match the historical setting."],
    ]),
  "The Capital Structure Puzzle": guide(
    "https://dspace.mit.edu/server/api/core/bitstreams/000e2308-1252-40ad-9a5f-81a8a01a95ae/content", bi("1984年MIT工作稿", "1984 MIT working paper"),
    "MIT working paper 1548-84, printed pp. 1–6, 9–10 and 14 inspected for tradeoff versus pecking order, adjustment costs, internal/external equity and information-related investment costs. Journal identity retained; tax-model derivations and all empirical claims not reviewed.",
    bi("本文比较融资行为的解释，不给出企业的最佳负债率。观察到的杠杆同时受融资历史、投资机会和调整成本影响，不能直接当作最优目标。", "This compares explanations of financing behavior, not a firm's optimal debt ratio. Observed leverage reflects financing history, investment opportunities and adjustment costs, not necessarily an optimal target."), [
      ["pp. 1–2", "解释实际选择，先于给出最优建议", "Explain observed choices before prescribing an optimum",
        "Myers从对企业实际融资行为了解不足出发，比较两类常见解释。他强调一个理论能描述最佳结构，并不表示已经解释管理者为什么选择债务、股权或混合证券。对现实数据的判断，需要先明确理论预测的是目标、选择过程还是公告反应。",
        "Myers starts from limited understanding of actual financing choices and compares two explanations. A theory describing an optimum need not explain why managers issue debt, equity or hybrids. Identify whether a prediction concerns targets, decision processes or announcement responses."],
      ["pp. 4–6", "权衡理论围绕目标负债率展开", "Tradeoff reasoning centers on a target debt ratio",
        "静态权衡把借款收益与财务困境成本放在一起，讨论给定资产和投资计划下的目标负债率。不同企业可能有不同目标，因此高杠杆与低杠杆的价值差异不能只归因于融资方式。资产风险和其他决定目标的因素也必须纳入解释。",
        "Static tradeoff reasoning balances borrowing benefits against financial-distress costs, conditional on assets and investment plans. Firms may have different targets. Valuation differences between high- and low-leverage firms therefore cannot be attributed to financing alone without considering risk and other determinants."],
      ["p. 5", "偏离目标与目标不同是两回事", "Different targets differ from deviations from a target",
        "存在调整成本时，实际杠杆可能暂时偏离目标；但横截面差异也可能来自各公司的目标本来不同。作者提醒实证研究不要混淆这两种解释。仅观察某家公司负债率上升，既不能断言其远离最优，也不能断言它正在回归目标。",
        "Adjustment costs can keep leverage away from a target, while cross-sectional differences can also reflect different targets. Myers warns against mixing these explanations. An observed increase in leverage alone establishes neither departure from an optimum nor movement back toward it."],
      ["pp. 9–10", "融资顺序不需要唯一目标比例", "A financing hierarchy need not imply one target ratio",
        "融资顺序解释优先使用内部资金，必要时再考虑外部融资，并先使用信息敏感度较低的证券。纯粹的顺序模型没有明确的目标债股比，实际杠杆反映累计融资需求。它与权衡理论的差异，不只是哪个模型认为债务比较便宜。",
        "Pecking-order reasoning favors internal funds, then external claims that are less information-sensitive. Its pure form has no well-defined target debt-equity mix; observed leverage reflects cumulative financing needs. The distinction from tradeoff theory goes beyond which model calls debt cheaper."],
      ["pp. 9–10", "内部权益与外部发股不能合并看待", "Internal equity and a new share issue are not interchangeable",
        "留存收益和新发行股权在资产负债表上都与权益有关，但融资顺序把它们放在很不同的位置。稳定分红与波动的投资需求会造成资金余缺，使外部需求随时间变化。只看期末权益比例，会隐藏企业实际上采用过哪些融资方式。",
        "Retained earnings and newly issued equity both relate to equity financing, but occupy different positions in the hierarchy. Sticky dividends and varying investment needs create funding gaps over time. An end-of-period equity ratio hides the financing path that produced it."],
      ["p. 14", "信息成本也可能表现为放弃投资", "Information costs can appear as forgone investment",
        "当外部投资者无法了解管理层掌握的信息时，融资成本不只是承销费。文中讨论了为保护原股东而放弃正净现值项目的可能性，因此内部资金的价值与投资机会有关。这个机制依赖模型假设，不意味着任何拒绝发股都一定合理。",
        "With asymmetric information, financing costs can exceed underwriting fees: the firm may forgo a positive-value project to protect existing shareholders. Internal funds can therefore matter through investment opportunities. This model mechanism does not make every refusal to issue equity optimal."],
    ]),
  "Investor Protection and Corporate Governance": guide(
    "https://www.nber.org/system/files/working_papers/w7428/w7428.pdf", bi("1999年NBER工作稿", "1999 NBER working paper"),
    "NBER 7428, titled Investor Protection: Origins, Consequences, Reform, is linked to the 2000 article by the Harvard repository. Printed pp. 1–4, 6, 15 and 20 inspected for insider diversion, legal enforcement, cash-flow/control rights and ownership. Not a current legal review.",
    bi("导读采用与期刊论文相连的1999年工作稿。跨国历史研究不能替代当前法律判断；现金流权、控制权和实际执行效果需要分别识别。", "This guide uses the associated 1999 working paper. Historical cross-country research does not establish current law; cash-flow rights, control rights and enforcement must be distinguished."), [
      ["§1 · pp. 1–2", "外部投资者为何能拿回收益", "Why can outside investors receive the cash flows?",
        "论文不把企业创造现金流与投资者实际获得现金流视为同一件事。管理者或控制股东可能通过关联交易、资产转移或其他安排取得私人收益。公司治理因此不仅是经理效率问题，也涉及外部股东和债权人如何限制内部人的攫取。",
        "Creating cash flows and returning them to investors are different matters. Managers or controlling shareholders can divert value through related transactions or other arrangements. Governance therefore concerns not just managerial efficiency but how outside shareholders and creditors constrain insiders."],
      ["§1 · p. 3", "现金流权与控制权不能混作持股比例", "Cash-flow rights and control rights are different",
        "作者从现金流索取权进一步讨论改变董事、阻止有害项目或要求清算等权力。获得多少经济收益与能够左右多少决策未必一致。分析股权结构时，只列直接持股比例可能遗漏控制链条，不能据此完整判断外部投资者受到怎样的保护。",
        "The paper moves from cash-flow claims to powers such as changing directors, blocking harmful projects or pursuing liquidation. Economic ownership and decision power need not coincide. Direct share percentages alone can miss control chains and do not fully describe investor protection."],
      ["§2 · p. 6", "规则内容与执行效果一起看", "Read legal rules together with enforcement",
        "研究把法律、监管、交易所规则和实际执行共同纳入投资者保护。纸面上存在某项权利，并不说明行使成本低或执行可靠。这个区分也意味着不能只靠一张法规清单比较治理质量，更不能用历史法律分类推断当前个案的法律结果。",
        "Investor protection includes laws, regulations, exchange rules and their enforcement. A formal right does not establish inexpensive or reliable exercise. A rule checklist alone cannot compare governance quality, and historical legal classifications do not determine the outcome of a current case."],
      ["§2 · p. 6", "股东与债权人的保护对象不同", "Shareholder and creditor protections address different claims",
        "股东权利可能涉及投票、同等分红或新股认购，债权人权利则更多涉及抵押物、优先顺序与重组。两者都属于外部投资者保护，但不应合成一个没有解释的总标签。融资方式变化，也可能改变各方权力与激励的分配。",
        "Shareholder protections can concern voting, proportional payouts and issue participation; creditor protections concern collateral, priority and reorganization. Both protect outsiders but should not be collapsed into an unexplained label. Financing choices can change the distribution of power and incentives."],
      ["§3 · p. 15", "集中持有既有约束作用，也有控制问题", "Concentrated ownership can constrain and create control problems",
        "较高现金流持有可能让内部人与外部投资者利益更一致，但集中控制也使少数股东面临被侵占的风险。论文将所有权结构与投资者保护联系起来，不把集中或分散简单划为好坏。现金流持有与控制集中必须分别解释。",
        "Greater insider cash-flow ownership can align incentives, while concentrated control can expose minority investors to diversion. The paper connects ownership patterns with protection rather than labeling concentration uniformly good or bad. Economic ownership and control concentration require separate interpretation."],
      ["§1; §3–4", "制度比较不是单一企业的因果证明", "Institutional comparison is not firm-level causal proof",
        "这篇综述把不同国家的融资、所有权和保护机制放在同一框架下。编辑解读：跨国规律不能独自解释某家公司的价值变化，也不能替代对关系融资等其他机制的研究。与中国部门研究并读时，尤其要区分公开资本市场与非上市企业。",
        "The review relates financing, ownership and protection across countries. Editorial interpretation: those regularities do not alone explain one firm's valuation change or replace study of relationship finance. Comparisons with China's sector evidence should distinguish public markets from unlisted firms."],
    ]),
  "Information Asymmetry, Corporate Disclosure, and the Capital Markets: A Review of the Empirical Disclosure Literature": guide(
    "https://fenix.iseg.ulisboa.pt/downloadFile/1126033050841610/Healy%20and%20Palepu%202001%20(JAE).pdf", bi("2001年期刊版", "2001 journal article"),
    "Original JAE article printed pp. 407–410, 420 and 426 inspected for information/agency problems, intermediaries, voluntary-disclosure incentives and proxy/endogeneity limitations. This is a bounded reading of the review, not verification of every cited empirical study.",
    bi("披露数量、披露可信度与信息不对称不是同一个变量。研究综述强调内生性和测量误差，观察到披露与融资成本相关不等于已经识别因果。", "Disclosure quantity, credibility and information asymmetry are different variables. The review emphasizes endogeneity and measurement error; association with financing costs is not causal identification."), [
      ["§2.1", "融资前的信息问题", "The information problem before financing",
        "Healy与Palepu先讨论企业比投资者更了解项目质量的情形。外部投资者无法区分好坏项目时，会调整愿意支付的价格，优质项目也可能因此受损。披露在这里的作用是帮助区分质量，不只是增加报告篇幅或提高新闻曝光。",
        "The review begins with entrepreneurs knowing more than investors about project quality. When outsiders cannot distinguish projects, pricing can penalize good ones. Disclosure can help separate quality; that role is not equivalent to longer reports or greater media visibility."],
      ["§2.2", "融资后的激励问题", "The incentive problem after financing",
        "资金投入之后，管理者的决策可能偏离外部投资者利益，形成代理问题。披露可支持监督合同履行和资源使用，但仍需要治理与执行机制。即使所有人知道同样的信息，也不意味着利益已经一致，信息问题与激励问题不能合并。",
        "After funding, managers may act against outside investors' interests. Disclosure supports monitoring of contracts and resources but still depends on governance and enforcement. Equal information does not guarantee aligned incentives, so information and agency problems remain distinct."],
      ["§2 · Figure 1", "资金中介与信息中介各有角色", "Financial and information intermediaries have distinct roles",
        "文中区分将储蓄转为企业资金的金融中介，以及分析、验证和传播企业信息的信息中介。分析师、审计和评级机制可以提高可信度，但它们也可能有自己的激励冲突。报告经过中介处理，并不自动成为没有偏差的信息。",
        "The framework distinguishes intermediaries channeling savings from those producing or validating information. Analysts, auditors and rating mechanisms can improve credibility, yet have their own incentive conflicts. Intermediation does not automatically turn a disclosure into unbiased information."],
      ["§5.2.1", "自愿披露本身就是一种选择", "Voluntary disclosure is itself a choice",
        "管理者可能因融资交易、控制权、薪酬、诉讼或专有信息成本而改变披露。披露更积极的企业，往往也在其他方面不同。因此研究披露后结果时，不能把主动披露与随机分配的信息处理视为同一种研究设计。",
        "Financing transactions, control contests, compensation, litigation and proprietary costs can affect disclosure choices. Firms disclosing more may differ along many other dimensions. Studying subsequent outcomes is therefore not equivalent to randomly assigning an information treatment."],
      ["§5.2.3 · p. 426", "管理层预测只是披露的一种代理", "Management forecasts proxy only part of disclosure",
        "盈利预测的时间和数字通常较清楚，后来也容易与实际结果对照，这给研究带来优势。但客户满意度、人力资本等披露不一定具有同样可验证性。以盈利预测得到的结论，不能直接推广为所有企业文本或所有披露方式的效果。",
        "Management forecasts often have clear timing and numerical outcomes that can later be checked. Other disclosures, such as customer satisfaction or human capital, may be harder to verify. Evidence from earnings forecasts cannot automatically generalize to every corporate text or disclosure channel."],
      ["p. 407; §5.2.3", "读披露研究，要同时读测量与识别", "Read measurement and identification alongside disclosure findings",
        "综述明确指出许多研究存在内生性和测量误差。编辑解读：文本长度、词频或评级得分究竟代理什么，需要先说清；随后再判断披露是原因、结果还是共同变化。更多文字可能是更多信息，也可能是更复杂业务或更高披露负担。",
        "The review explicitly highlights endogeneity and measurement error. Editorial reading: establish what length, word counts or ratings proxy before deciding whether disclosure is a cause, consequence or correlate. More text can reflect information, business complexity or a heavier reporting burden."],
    ]),
  "All That Glitters: The Effect of Attention and News on the Buying Behavior of Individual and Institutional Investors": guide(
    "https://faculty.haas.berkeley.edu/odean/Papers%20current%20versions/AllThatGlitters_RFS_2008.pdf", bi("2008年期刊版", "2008 journal article"),
    "Author-hosted RFS final article printed pp. 785–788 inspected for choice-set reasoning, purchase/sale asymmetry, three attention proxies, investor samples and the net-buying hypothesis. Later regressions and trading results were not independently reproduced.",
    bi("关注度不是看多情绪，也不是收益预测。文中的注意力代理和投资者交易样本各有边界；总体买卖必然对应，不能把某组净买入说成全市场净买入。", "Attention is not bullish sentiment or a return forecast. Attention proxies and investor samples are bounded; one group's net buying is not net buying by the entire market."), [
      ["pp. 785–786", "先进入选择集合，再谈偏好", "Attention shapes the choice set before preferences act",
        "Barber与Odean把选择分成先注意到哪些股票、再在其中选择两个环节。研究的机制是有限注意力改变候选集合，而不是所有人看到同一消息都会买同一只股票。关注度解释为什么进入视野，偏好仍决定后续选择。",
        "The paper separates noticing stocks from choosing among them. Limited attention changes the consideration set; it does not imply that everyone buys the same stock after seeing news. Attention helps explain entry into consideration, while preferences still determine choices."],
      ["p. 786", "买入与卖出的搜索空间不对称", "Buying and selling involve different search spaces",
        "个人投资者买入时可以面对大量股票，卖出时往往只考虑已有的少量持仓，且很少卖空。作者用这种不对称解释注意力为何更影响买入。这个前提与样本交易习惯有关，不能无条件套到持仓广泛或经常卖空的参与者。",
        "Individuals can choose among many stocks when buying but usually sell from a small existing portfolio and rarely short. This asymmetry motivates a stronger attention effect on buying. It need not apply unchanged to participants with broad holdings or frequent short selling."],
      ["p. 787", "三种代理都不是直接读出注意力", "None of the three proxies directly observes attention",
        "研究通过新闻、异常成交量和极端收益间接观察可能引起关注的事件。新闻记录不告诉作者到底多少人阅读，成交放大也可能来自少数大额交易。多个代理帮助从不同角度检验解释，但不能把代理值本身写成人群注意力的精确计量。",
        "News, unusual volume and extreme returns indirectly indicate attention-grabbing events. News archives do not count readers, and large trades can raise volume without widespread attention. Multiple proxies provide complementary evidence, not exact measurements of the population's attention."],
      ["p. 788", "要检验的是净买入，不只是交易增多", "The hypothesis concerns net buying, not merely more trading",
        "若把成交量本身作为注意力代理，再发现成交活跃，几乎只是重复定义。作者真正比较的是特定投资者群体在高关注日更倾向买入还是卖出。买卖方向、投资者分类和交易数量必须分开，只有总成交量无法回答这个问题。",
        "Using volume as an attention proxy and then finding active trading would be close to circular. The hypothesis instead concerns whether a specified investor group buys more than it sells. Direction, group classification and trading intensity must be distinguished."],
      ["pp. 787–788", "机构的选择条件可能不同", "Institutions can face different choice conditions",
        "机构可能持有更多股票、具有不同卖空条件，也投入更多资源筛选对象，因此不能假设个人与机构面对完全相同的注意力约束。研究按不同投资者样本比较，而不是把全部交易压成一个平均账户；这种分类也不代表每家机构行为相同。",
        "Institutions can hold more stocks, face different short-selling conditions and devote more resources to selection. The study compares investor samples rather than one average account. These categories do not imply identical behavior within every institution or individual group."],
      ["p. 788 · footnote 4", "价格变化也可能由买入引起", "Buying can cause price changes as well as follow them",
        "作者使用前一日收益作为一个注意力代理，以减轻同日买入本身造成价格变化的内生性。这个处理体现研究设计的重要性，但不能消除所有共同原因。关注被激活与未来回报可靠，是不同命题；本研究不提供追逐热点的依据。",
        "Prior-day returns help reduce the endogeneity of same-day buying causing price moves. That timing choice does not remove every common cause. Evidence that attention is activated differs from reliable future-return evidence; it is not a basis for chasing prominent stocks."],
    ]),
  "In Search of Attention": guide(
    "https://www.ou.edu/dam/price/Finance/files/Paul%20Gao%20Paper.pdf", bi("2010年6月3日作者稿", "June 3, 2010 manuscript"),
    "University-hosted manuscript printed pp. 5–6 and 8–9 inspected for search-term choice, historical membership, low-volume zeros, sampled downloads and comparisons with other attention proxies. Final 2011 article identity retained; return and IPO tests not reproduced.",
    bi("导读使用2010年稿中的历史Google搜索数据说明测量。搜索热度不是投资者身份、情绪方向或实际交易；历史下载口径不应被当作当前平台接口规范。", "The 2010 draft illustrates measurement with historical Google search data. Search intensity does not identify investors, sentiment or trades, and its download conventions are not current API specifications."), [
      ["§2 · p. 5", "搜索体现主动关注，但不说明看多或看空", "Searching signals active interest, not its direction",
        "Da、Engelberg与Gao使用搜索频率研究注意力，与只观察新闻曝光相比，搜索更接近主动寻求信息的行为。但搜索某只股票并不告诉我们搜索者准备买入、卖出还是核查坏消息，也不能证明搜索者一定持有该股票。",
        "Search frequency is closer to active information seeking than media exposure alone. Yet searching a stock does not reveal whether someone intends to buy, sell or investigate bad news. Nor does it prove ownership of the security being searched."],
      ["§2 · pp. 5–6", "公司名与股票代码测到不同人群", "Company names and tickers can reach different audiences",
        "公司名称可能被用于购物、求职或寻找门店，股票代码通常更接近金融信息需求，因此稿中主要用代码搜索。但某些代码本身也是常用词，会引入无关流量。实体匹配与歧义处理属于指标定义，不是可忽略的数据清洗细节。",
        "Company names can attract shopping, job or store-location searches, while tickers more closely target financial interest. Some tickers are ordinary words, however. Entity matching and ambiguity handling therefore define the measure rather than being negligible cleaning details."],
      ["§2 · p. 5", "历史成分集合降低一种存续偏差", "Historical membership addresses one survivorship problem",
        "作者使用研究期间曾进入Russell 3000的公司集合，而不是只拿期末仍在指数中的公司回看历史。这避免遗漏部分后来退出的证券，但仍有指数覆盖范围和价格筛选限制。样本曾经入选，也不等于整个时期都属于同一个指数。",
        "The draft includes firms that belonged to the Russell 3000 at any time during the study, rather than only end-period survivors. Index coverage and price filters still restrict the sample. Ever-membership does not imply continuous membership throughout the period."],
      ["§2 · p. 6", "低搜索量的零值不应直接等同于无人关注", "Low-volume zeros do not establish zero attention",
        "稿中说明部分低搜索频率的查询返回零，只有一部分公司周观测具有有效非零数据。这会改变哪些公司可被分析。缺少可发布搜索统计、真实零搜索和缺失下载不能随意合并，尤其不能把它们都当成精确的零注意力。",
        "Some rarely searched tickers return zero in the historical service, leaving only part of the firm-week sample with valid nonzero data. Unreportable low volume, true zero activity and a missing download should not be collapsed into an exact zero-attention observation."],
      ["§2 · footnote 3", "同一历史查询也可能有下载差异", "Repeated historical downloads can differ",
        "作者记录当时平台使用抽样搜索数据，重复下载同一查询可能略有差异。这提醒读者，网页指标也有版本与抽样误差。保存查询条件、下载日期和原始返回有助于解释差别，但历史服务的描述不能作为今天平台实现方式的证明。",
        "The draft notes that the historical service sampled searches, so repeated downloads could differ. Web-based indicators have versions and sampling error too. Query settings, download dates and raw responses help explain discrepancies, without establishing how today's platform operates."],
      ["§3 · pp. 8–9", "与其他代理相关，不等于同一个变量", "Correlation with other proxies does not make them identical",
        "文中将搜索指标与异常收益、换手、新闻及文本情绪比较。它们可能相关，但新闻供给、价格结果与主动信息需求不是同一概念。与注意力买卖行为研究并读时，应先比较测量对象，而不是把所有热度指标合成一个未经解释的分数。",
        "Search is compared with abnormal returns, turnover, news and textual sentiment. These may correlate while representing different objects: information supply, market outcomes and active demand. Read attention studies by comparing what is measured, not by merging all prominence measures into an unexplained score."],
    ]),
  "Measuring the Effects of Monetary Policy: A Factor-Augmented Vector Autoregressive (FAVAR) Approach": guide(
    "https://www.nber.org/system/files/working_papers/w10220/w10220.pdf", bi("2004年NBER工作稿", "2004 NBER working paper"),
    "NBER 10220 printed pp. 1–9 inspected for omitted-information motivation, policy innovations versus rules, observation/transition equations, two-step and Bayesian estimation and generated-regressor uncertainty. Application identification and impulse-response tables not independently reproduced.",
    bi("因子扩大信息集，不自动识别外生政策冲击。导读使用2004年工作稿；政策意外变化、系统性反应与政策规则比较是不同问题。", "Factors broaden the information set but do not automatically identify exogenous policy shocks. This guide uses the 2004 working paper and distinguishes innovations, systematic responses and comparisons of policy rules."), [
      ["§1 · pp. 1–2", "小型VAR可能遗漏决策者已知的信息", "A small VAR can omit information known to policymakers",
        "Bernanke、Boivin与Eliasz指出，央行和市场可能观察很多指标，而研究者的VAR只放入少数变量。模型看起来意外的利率变化，可能只是对遗漏信息的系统反应。增加信息集的目的，是减少这种混淆，而不是让模型变量越多越好。",
        "Central banks and markets can observe many indicators while a small VAR contains only a few. An apparently unexpected rate movement may respond systematically to omitted information. A richer information set seeks to reduce this confusion, not maximize variable count for its own sake."],
      ["§1 · pp. 2–3", "价格之谜提示的是识别问题", "The price puzzle points to an identification problem",
        "如果央行因预见通胀而收紧政策，但模型遗漏了这些通胀信号，收紧后价格仍上涨就可能被误读为政策造成通胀。文章以此说明信息不足会污染整个冲击解释。观察到反常响应，不应立即把它当成普遍的经济机制。",
        "If a central bank tightens in anticipation of inflation absent from the model, subsequent price rises can be misread as effects of tightening. The example illustrates contamination of shock interpretation. An unexpected response pattern should not immediately become a universal economic mechanism."],
      ["§2 · equations (2.1)–(2.2)", "观测方程与动态方程分工不同", "Measurement and dynamics have different jobs",
        "一个方程把大量指标与少数潜在因子、可观测变量联系起来，另一个方程描述这些因子和变量怎样随时间演化。提取共同变化与解释动态响应是两个环节。主成分有较强解释力，不会自动赋予某个创新明确的政策含义。",
        "One equation connects many indicators to latent factors and observed variables; another models their joint dynamics. Summarizing co-movement and interpreting responses are separate steps. Strong principal-component explanatory power does not automatically make an innovation a policy shock."],
      ["§2 · pp. 7–9", "两步估计与联合估计不是同一实现", "Two-step and joint estimation are different approaches",
        "论文讨论先提取主成分再估计VAR的两步法，也讨论基于贝叶斯抽样的联合估计。它们在计算、误差假设与不确定性处理上不同。阅读复现时，需要先确认采用哪种方法，而不能仅因都叫FAVAR就认定参数和区间应完全一致。",
        "The paper considers principal components followed by a VAR, and joint Bayesian estimation. Computation, error assumptions and uncertainty treatment differ. Identify the approach in a replication before expecting parameters and intervals to match merely because both are called FAVAR."],
      ["§2 · p. 8", "估计出来的因子也带有不确定性", "Estimated factors carry uncertainty too",
        "两步法第二步使用第一步估计的因子，属于生成的回归变量。作者为脉冲响应区间采用考虑因子估计不确定性的bootstrap处理。把因子当作无误差的已知序列可能低估某些不确定性，因子数量和样本条件也影响近似是否合适。",
        "The second step uses generated regressors from the first. The paper's bootstrap intervals account for uncertainty in factor estimation. Treating factors as perfectly observed can misstate uncertainty; sample dimensions and factor choices affect the suitability of the approximation."],
      ["§1 · pp. 1–2", "政策冲击不是政策规则本身", "A policy shock is not the policy rule itself",
        "作者明确区分未预期的政策变化与系统性政策反应，VAR冲击分析主要处理前者。它不能直接回答更换整套规则或长期目标会怎样。与Taylor规则等文献对照时，应先分清是在研究反应函数、意外冲击，还是制度选择。",
        "The introduction distinguishes unanticipated policy changes from systematic responses. Shock analysis mainly addresses the former, not replacing an entire rule or long-run objective. Reading it alongside Taylor-rule work requires separating reaction functions, innovations and institutional choices."],
    ]),
  "Credit Spreads and Business Cycle Fluctuations": guide(
    "https://www.nber.org/system/files/working_papers/w17021/w17021.pdf", bi("2011年NBER工作稿", "2011 NBER working paper"),
    "NBER 17021 printed pp. 3–4, 11–12 and 18 inspected for bond sample, cash-flow-matched Treasury comparison, log-spread model, retransformation, default distance and option adjustment. Final AER identity retained; causal VAR and forecast coefficients not independently reproduced.",
    bi("超额债券溢价是模型分解的残差，不是可直接观测的纯情绪，也不是已实现超额收益。现金流匹配、违约风险模型与期权调整都会影响结果。", "The excess bond premium is a model-based residual, not directly observed pure sentiment or realized excess return. Cash-flow matching, the default model and option adjustments affect it."), [
      ["§2.1", "从单只债券构造利差", "Build spreads from individual bonds",
        "Gilchrist与Zakrajšek使用企业债券二级市场价格，而不是只比较两个现成评级指数。样本限制在固定息票的高级无抵押债券，并设定期限和极端利差筛选。这个细粒度构造有助于比较，但也明确排除了不少其他债务工具。",
        "The study constructs spreads from secondary-market corporate bond prices rather than only comparing rating indexes. Fixed-coupon senior unsecured issues, maturity filters and spread exclusions define the sample. Granularity aids comparison while excluding many other debt instruments."],
      ["§2.1 · pp. 3–4", "同到期日不等于同现金流", "Equal maturity does not mean equal cash flows",
        "作者用国债零息曲线给企业债相同的息票和本金现金流定价，得到可比的假想无风险收益率。简单减去相同到期日国债收益，可能仍留下久期和现金流结构差异。利差的基准构造因此属于研究核心，而不是无关的计算细节。",
        "Treasury zero-coupon yields price a synthetic security matching the corporate bond's coupon and principal cash flows. Subtracting a same-maturity Treasury yield can leave duration and cash-flow differences. Benchmark construction is central to the spread measure, not a minor calculation detail."],
      ["§4 · equation (3)", "总利差分成模型解释部分与残差", "Separate model-explained spreads from the residual",
        "论文用企业违约风险与债券特征解释对数利差，再将预测部分与实际聚合利差比较，差额称为超额债券溢价。这里的“超额”不是持有债券赚到的收益。它依赖模型所包含的信息，未被解释的部分也可能含遗漏因素或测量误差。",
        "Default risk and bond characteristics explain log spreads; the gap between aggregated actual and predicted spreads is the excess bond premium. Excess does not mean a realized holding return. The residual depends on included information and can contain omitted factors or measurement error."],
      ["§4 · p. 11", "从对数回到水平需要额外处理", "Returning from logs to levels needs care",
        "在正态误差假设下，稿中对预测对数利差加上误差方差的一半，再指数化形成水平预测。直接对拟合值取指数并不是相同操作。这一步会影响预测利差及其残差，因此比较不同实现时，必须核对回转假设和聚合顺序。",
        "Under normal disturbances, the draft adds half the error variance before exponentiating predicted log spreads. Simply exponentiating fitted values is different. This retransformation changes predicted spreads and the residual, making distribution assumptions and aggregation order important across implementations."],
      ["§4.1", "违约距离是模型推断，不是直接概率读数", "Distance to default is inferred, not directly observed",
        "作者利用股权价值、股权波动和资本结构，在结构模型假设下推断资产价值与风险，进而刻画违约风险。潜在资产价值并不可直接观测，模型还简化了债务结构。不能把违约距离这个统计对象直接当作实际发生违约的确定概率。",
        "Equity values, equity volatility and capital structure inform latent asset value and risk under a structural model. Asset value is unobserved and debt structure is simplified. Distance to default is therefore a model-based quantity, not a directly observed probability of actual default."],
      ["§4.2 · p. 18", "可赎回条款也会影响利差", "Call options can change spreads too",
        "利率水平、期限结构与波动会影响嵌入赎回权的价值，稿中对这类债券进行相应调整。若把所有利差变化都视为违约恶化或风险偏好变化，就可能把合同期权的影响混入解释。宏观预测证据也应与这种测量分解保持区分。",
        "Rates, the term structure and volatility affect embedded call options, which the draft adjusts for. Treating every spread movement as worsening default risk or changing appetite can mix contractual-option effects into the interpretation. Macro forecasting evidence remains separate from this measurement decomposition."],
    ]),
  "Some Simple Economics of the Blockchain": guide(
    "https://www.nber.org/system/files/working_papers/w22952/w22952.pdf", bi("2019年6月修订稿", "June 2019 revision"),
    "NBER 22952 revised June 2019, printed pp. 3–4, 6, 12–13 and 23 inspected for verification/networking costs, offline links, intermediary roles and adoption conditions. No protocol security audit, legal analysis or token valuation performed.",
    bi("这是关于验证和网络组织成本的经济框架，不是代币估值或协议安全证明。链上记录一致不保证链外事实真实；去中心化的收益与成本取决于具体场景。", "This is an economic framework for verification and network organization, not token valuation or a security proof. Consistent records do not guarantee truthful offline facts; costs and benefits depend on context."), [
      ["§2", "验证成本：交易属性能否被可信确认", "Verification costs concern establishing transaction attributes",
        "Catalini与Gans从交易双方需要确认的属性出发，例如所有权、资金是否存在以及交易是否履行。可信验证可能依赖中介，也可能依赖共享记录。框架关心的是这种验证成本如何变化，不是简单比较账本写入速度或交易手续费。",
        "The framework starts with attributes parties must verify, such as ownership, available funds and performance. Verification may rely on intermediaries or shared records. The economic question concerns changing verification costs, not merely ledger throughput or transaction fees."],
      ["§3", "网络成本：怎样建立并维持共同基础设施", "Networking costs concern building and sustaining shared infrastructure",
        "第二类成本涉及如何启动和维持一个网络，而不仅是连接电脑。协议规则与经济激励可以协调为基础设施贡献资源的参与者。能验证一笔记录，并不自动解决参与者为何加入、谁承担运行成本或网络怎样持续获得维护这些问题。",
        "Networking concerns bootstrapping and operating a marketplace, not just connecting computers. Rules and incentives coordinate contributors to shared infrastructure. Verifying a record does not itself explain why participants join, who pays operating costs or how maintenance continues."],
      ["§2 · p. 12", "原生数字状态与线下资产映射不同", "Native digital state differs from representations of offline assets",
        "原生链上资产的状态可以由系统规则直接检验，但一件线下商品是否存在、品质如何，仍需可信输入。把商品编号写到链上，只保存了关于商品的声明。后续记录难以篡改，不会追溯性地让最初错误或虚假的输入变成真实。",
        "A native digital asset's state can be checked within system rules, while an offline product's existence or quality needs trustworthy input. Recording an identifier preserves a claim about the product. Making later alteration difficult does not make an initially false claim true."],
      ["§1; §2 · pp. 4, 12–13", "中介的工作可能改变，而不是全部消失", "Intermediaries may change roles rather than disappear",
        "论文认为技术更可能改变中介如何创造价值和拥有市场力量，而非消除所有中介。身份、争议处理与链外事件仍可能需要其他机构。评估一个应用时，应列出哪些信任被协议替代、哪些仍由参与者或外部服务承担。",
        "The paper argues that technology can change intermediaries' value creation and market power rather than remove them all. Identity, disputes and offline events may still require institutions. Evaluate which trust relationships the protocol replaces and which remain elsewhere."],
      ["§2 · pp. 12–13", "分散验证不保证每笔交易更便宜", "Decentralized verification need not be cheaper per transaction",
        "作者明确区分单笔处理效率与竞争、控制权、隐私和单点故障等潜在收益。即使去中心化处理比集中处理消耗更多资源，也可能在其他维度提供价值；反过来，不能只因贴上去中心化标签，就推断所有成本都下降。",
        "The paper separates per-transaction efficiency from potential benefits in competition, control, privacy and single points of failure. Decentralized processing can consume more resources while offering other value. The decentralized label alone does not establish that every cost falls."],
      ["§4 · p. 23", "先找适用条件，再讨论采用价值", "Identify suitable conditions before claiming adoption value",
        "结论把链外连接难度、网络利益分配、新数字权利和隐私需求列为判断条件。若这些条件不成立，传统中介与关系合同可能仍然合适。技术能协调一套规则，不等于某个项目已经解决治理、欺诈或用户采用问题，也不是购买代币的理由。",
        "The conclusion emphasizes offline-link frictions, allocation of network benefits, digital rights and privacy needs. Traditional intermediaries can remain suitable when those conditions fail. Coordinating rules does not establish that a project has solved governance, fraud or adoption, nor justify purchasing its token."],
    ]),
};
