// Editorial reading links for the twenty guides completed in the 200-guide release.
// They describe a reason to compare scopes; they are not citation, agreement, or ranking claims.
const pair = (left, right, zh, en) => ({ left, right, reason: { zh, en } });

export const researchComparisons200 = [
  pair("SSE Statistical Yearbook", "CSI 300 Index Methodology", "交易所年度统计与指数编制规则都依赖版本、覆盖范围和定义；年报汇总不能替代某一指数的历史成分或日频序列。", "Exchange annual statistics and index methodology both depend on edition, coverage, and definitions. An annual aggregate cannot replace historical index membership or a daily series."),
  pair("Digesting Anomalies: An Investment Approach", "Replicating Anomalies", "一个从因子模型归纳已发表异象，另一个检验复现中定义与样本选择的影响；模型残差和复现结果应分别阅读。", "One organizes published anomalies through a factor model; the other examines definitions and sample choices in replication. Read model residuals and replication results separately."),
  pair("… and the Cross-Section of Expected Returns", "Controlling the False Discovery Rate: A Practical and Powerful Approach to Multiple Testing", "前者将多重检验置于因子发现史中，后者给出错误发现控制程序；历史研究数量和具体检验家族不能混为一谈。", "One puts multiplicity in the history of factor discovery; the other gives a false-discovery procedure. A research inventory is not the same as a specified testing family."),
  pair("Idiosyncratic Risk and the Cross-Section of Expected Stock Returns", "The Cross-Section of Expected Stock Returns", "特质波动率如何估计与横截面收益如何排序是相连但不同的问题；先统一因子模型、窗口和可得时点。", "Estimating idiosyncratic volatility and sorting cross-sectional returns are connected but distinct tasks. Align factor model, window, and availability timing first."),
  pair("False Discoveries in Mutual Fund Performance: Measuring Luck in Estimated Alphas", "Controlling the False Discovery Rate: A Practical and Powerful Approach to Multiple Testing", "基金 alpha 的错误发现应用依赖基准、存续与横截面依赖；通用程序本身不替代这些基金样本选择。", "False-discovery analysis of fund alphas depends on benchmarks, survival treatment, and cross-sectional dependence. The general procedure does not replace those fund-sample choices."),
  pair("An Introduction to the Bootstrap", "Bootstrap Methods: Another Look at the Jackknife", "两者都讨论重采样，但使用的估计量、抽样单位和依赖结构仍须逐项声明；同名方法不是自动可比的设置。", "Both discuss resampling, but estimator, sampling unit, and dependence structure still need to be stated. A shared label does not make settings automatically comparable."),
  pair("Greedy Function Approximation: A Gradient Boosting Machine", "Random Forests", "两种树模型都可用于预测，却通过不同的集成和调参路径控制复杂度；比较时应固定时间切分和目标定义。", "Both tree methods can predict, but they control complexity through different ensembles and tuning paths. Hold time splits and target definition fixed when comparing them."),
  pair("Autoencoder Asset Pricing Models", "Deep Learning in Asset Pricing", "两篇都把非线性表示带入资产定价，但目标函数、约束与测试资产构造不同；相似网络术语不代表相同经济对象。", "Both bring nonlinear representation learning to asset pricing, but objectives, restrictions, and test-asset construction differ. Similar neural-network language does not imply the same economic object."),
  pair("Characteristics Are Covariances: A Unified Model of Risk and Return", "Digesting Anomalies: An Investment Approach", "前者以特征刻画条件协方差，后者以因子模型概括异象；特征、因子和可投资组合构造是不同层级的选择。", "One uses characteristics to model conditional covariances; the other summarizes anomalies with factors. Characteristics, factors, and investable portfolio construction are different layers of choice."),
  pair("Realized Kernels in Practice: Trades and Quotes", "Microstructure Noise in the Continuous Case: The Pre-Averaging Approach", "两者都处理高频噪声，但一个强调成交与报价实施，另一个给出预平均框架；原始观测类型与窗口规则不能省略。", "Both address high-frequency noise, but one emphasizes trade/quote implementation and the other a pre-averaging framework. Raw observation type and window rules remain essential."),
  pair("The Cost of Capital, Corporation Finance and the Theory of Investment", "The Capital Structure Puzzle", "一个给出摩擦被排除时的理论基准，另一个组织现实融资选择的解释；先列出被放松的假设，再讨论公司行为。", "One gives a theoretical benchmark with frictions removed; the other organizes explanations for real financing choices. List the relaxed assumptions before discussing firm behavior."),
  pair("The Impact of Public Information on the Stock Market", "The Information Content of Forward-Looking Statements in Corporate Filings—A Naïve Bayesian Machine Learning Approach", "前者统计公开新闻数量与总体活动，后者定义披露文本中的前瞻语气；数量、内容分类和信息时点不是同一度量。", "One counts public news and aggregate activity; the other defines forward-looking tone in filings. Volume, content classification, and information timing are not the same measure."),
  pair("Common Factors Affecting Bond Returns", "Bond Risk Premia", "收益率曲线共同变动与债券超额收益的预测关系不同；期限、回报定义与持有期必须分开核对。", "Common yield-curve movements differ from predicting bond excess returns. Check maturities, return definitions, and holding periods separately."),
  pair("Business Cycles in a Small Open Economy", "Financial Intermediation and Credit Policy in Business Cycle Analysis", "开放经济周期模型与金融中介框架都描述宏观传导，但外部部门、资产负债表摩擦和政策规则并非同一机制。", "A small-open-economy cycle model and an intermediation framework both describe macro transmission, but external-sector structure, balance-sheet frictions, and policy rules are not the same mechanism."),
  pair("The Forward Premium Puzzle: Different Tales from Developed and Emerging Economies", "Common Risk Factors in Currency Markets", "前者按国家组比较远期升水关系，后者组织货币组合的共同风险；国家分组与组合因子解释需要分别验证。", "One compares forward-premium relations by country group; the other organizes common risk in currency portfolios. Country grouping and portfolio-factor explanations require separate validation."),
  pair("The Macroeconomic Impact of Financial and Uncertainty Shocks", "Credit Spreads and Business Cycle Fluctuations", "一个通过结构识别区分金融与不确定性冲击，另一个分解信用利差与周期关系；冲击标签与利差成分不是可互换的变量。", "One distinguishes financial and uncertainty shocks through structural identification; the other decomposes credit spreads and cycles. Shock labels and spread components are not interchangeable variables."),
];
