// Bounded, bilingual orientations for existing catalog identities. The cited
// primary-source descriptions were reviewed; this is not full-text replication.
import { researchSummaryMaterials } from "./researchSummaryMaterials.js";

const bi = (zh, en) => ({ zh, en });
const guide = ({ title, url, source, question, design, data, finding, checks, boundary }) => [title, {
  reviewedAt: "2026-09-01",
  evidenceUrl: url,
  evidenceScope: "The cited primary source's public description and registered bibliographic record were read. This orientation guide remains within those materials; it does not infer numerical results, table-level evidence, a causal conclusion, or an implementation beyond the stated source description.",
  limits: bi(`本文只整理“${title}”所公开说明的研究问题与设计边界，不构成收益预测、交易规则或全文复现。${boundary}`, `This guide only organizes the publicly described question and design of “${title}”. It is not a return forecast, trading rule, or full-text replication. The source's stated scope remains controlling.`),
  related: researchSummaryMaterials[title] ?? {},
  sections: [
    ["研究问题", "Research question", `${question} 阅读时先把它理解为一个被界定的问题，而不是可以脱离样本、时间和制度环境的结论。`, `“${title}” frames a bounded research question. Read the stated question together with the named sample, dates, and institutional setting rather than treating it as a conclusion that automatically travels to another market or period.`],
    ["研究设计", "Research design", `${design} 这说明比较对象、观察窗口和对照关系是研究合同的一部分；改变其中任何一项，都可能改变所检验的命题。`, `For “${title}”, the source describes a deliberate comparison, observation window, and control relation. Those choices are part of its research contract: changing one can change the proposition being tested, even when the method label remains the same.`],
    ["数据与时点", "Data and timing", `${data} 数据字段、可得时点和样本筛选需要与原始研究分开记录，不能仅凭同名变量或最终修订数据就视为可比。`, `For “${title}”, keep the fields, their availability timing, and the sample filters separate from the original study. A same-named variable, later-revised database, or matching end-of-period date is not automatically a comparable input.`],
    ["如何理解结果", "How to read the result", `${finding} 它支持的是该来源所描述的经验或理论关系；它本身不把相关性、模型拟合或历史表现升级为因果、可执行性或未来保证。`, `For “${title}”, the source supports only the empirical or theoretical relation it describes. It does not turn association, model fit, or historical performance into causality, a directly executable procedure, or a guarantee about subsequent outcomes.`],
    ["复核清单", "Replication checks", `${checks} 在做后续分析前，应把这些选择写入版本化的研究记录，并保留原始来源链接与访问日期。`, `Before extending “${title}”, record its sample, timing, construction choices, and source edition in a versioned note. Keep the primary-source link and access date so a later reader can distinguish a changed definition from a changed result.`],
    ["适用边界", "Scope boundary", `该条导读引用 ${source}。${boundary} 若需要量化结论、参数、表格或稳健性检验，请回到原文并单独核对版本、附录与样本定义。`, `This guide cites ${source} for “${title}”. Its public description defines the boundary. For numerical conclusions, parameters, tables, or robustness tests, return to the original and separately verify the edition, appendices, and sample definitions.`],
  ].map(([zhTitle, enTitle, zhBody, enBody]) => ({
    title: bi(zhTitle, enTitle), body: bi(zhBody, enBody), reference: { url, label: bi(`${source} · 来源说明`, `${source} · source description`) },
  })),
}];

export const researchBatchTwo160 = Object.fromEntries([
  guide({ title: "Trading Volume and Serial Correlation in Stock Returns", url: "https://doi.org/10.2307/2118454", source: "The Quarterly Journal of Economics (1993)", question: "论文考察市场成交量与日收益一阶序列相关之间的关系，以及流动性交易压力如何参与解释该关系。", design: "来源同时讨论股票指数和大型个股，并把高低成交活跃度下的收益特征放在做市商承接非信息交易压力的模型中理解。", data: "需要区分日收益、成交量口径、指数或个股样本、交易日历和定义成交活跃度的时间窗口。", finding: "公开摘要把成交量视为解释收益序列依赖的条件信息，而不是把较高成交量本身变成方向性信号。", checks: "冻结收益调整规则与成交量定义，区分停牌和零成交，并分别记录指数构造、样本存续与非同步交易处理。", boundary: "该研究的做市和流动性交易机制不能由分钟 OHLCV 单独观察，更不能直接转写成跨市场的交易规则。" }),
  guide({ title: "An Analysis of Changes in Specialist Inventories and Quotations", url: "https://doi.org/10.1111/j.1540-6261.1993.tb05122.x", source: "The Journal of Finance (1993)", question: "论文研究交易商库存、报价修订与订单失衡所传递信息之间的动态关系。", design: "来源以包含库存与信息效应的动态做市模型为起点，并用纽约证券交易所一名 specialist 的库存资料检验。", data: "关键输入包括交易商库存、交易、报价修订、订单失衡代理及它们一致的日内时间戳。", finding: "摘要讨论库存向目标水平回归，以及报价修订与交易和订单失衡信息之间的关系，并非所有电子市场的通用描述。", checks: "记录交易商角色和制度、库存数据可见范围、报价更新顺序及交易方向识别规则，避免把库存代理当作真实账户头寸。", boundary: "特定 specialist 制度和单一库存样本不能替代现代订单簿、参与者身份或其他市场的做市行为证据。" }),
  guide({ title: "Why Do Security Prices Change? A Transaction-Level Analysis of NYSE Stocks", url: "https://doi.org/10.1093/rfs/10.4.1035", source: "Review of Financial Studies (1997)", question: "论文用逐笔层面的价格形成框架，询问信息冲击和微观结构摩擦如何共同影响日内价格变化。", design: "来源构建并检验结构模型，分析日内买卖价差、波动、交易成本以及成交和报价自相关的模式。", data: "需要逐笔成交、同步报价、交易方向、交易成本定义、日内分段和交易场所制度资料。", finding: "摘要描述其用于理解价格发现与有效交易成本的度量；这些度量依赖交易与报价数据，而不是只依赖收盘价。", checks: "统一成交与报价时钟，明确有效价差和报价价差的定义，处理撤单、更正及开收盘竞价，并保存市场状态标签。", boundary: "该结构模型和原始 NYSE 制度不能被分钟蜡烛图复现，也不能自动给出另一场所的价格发现结论。" }),
  guide({ title: "The Flash Crash: High-Frequency Trading in an Electronic Market", url: "https://doi.org/10.1111/jofi.12498", source: "The Journal of Finance (2017)", question: "论文研究2010年5月6日电子市场遭遇大规模、短暂卖压时，日内中介活动如何表现。", design: "来源使用该事件日和此前三日 E-mini 的审计轨迹逐笔数据，并以活跃的非指定日内中介者为分类对象。", data: "必须保留审计轨迹成交、参与者分类、合约身份、事件时钟、前后比较窗口和市场状态。", finding: "摘要只描述特定事件和分类下的中介交易模式；它不把高频交易当成单一行为类型，也不对所有极端波动作因果归因。", checks: "确认事件时间轴、品种和参与者分类版本，区分订单、成交和头寸字段，并保存用于比较的前期窗口。", boundary: "单一压力事件、单一期货合约和受限审计数据不能由公开分钟行情替代，也不能推出一般性市场质量判断。" }),
  guide({ title: "High Frequency Trading and the New Market Makers", url: "https://doi.org/10.1016/j.finmar.2013.06.006", source: "Journal of Financial Markets (2013)", question: "论文考察大型高频做市商跨交易场所活动时的中介与库存特征。", design: "研究围绕可识别做市商的跨场所交易、报价和库存资料组织，而不是仅比较普通交易量。", data: "所需对象包括可识别交易商成交、场所级报价、库存或头寸代理、费用规则和跨场所同步时钟。", finding: "该论文把新型做市商放入特定市场结构中讨论；它不证明所有算法化交易者都具有相同行为或作用。", checks: "冻结交易场所名单、交易商分类、路由和费用制度，明确跨场所匹配规则，并记录数据是否包含暗池或内部化交易。", boundary: "缺少参与者身份、订单簿和场所级时钟时，不能将公开聚合行情解释为该论文意义上的做市活动。" }),
  guide({ title: "Commonality in Liquidity", url: "https://doi.org/10.1016/s0304-405x(99)00057-4", source: "Journal of Financial Economics (2000)", question: "论文检验个券的流动性度量是否随共同市场条件而变化。", design: "来源把个券与市场汇总的价差、深度和交易活跃度放在同一横截面与时间序列框架中比较。", data: "需要可比较的报价价差、深度、成交量、个券权重、市场汇总规则及交易日时间对齐。", finding: "研究关注流动性共同变化，而不是声称任一单一指标即可完整代表交易成本或市场承压。", checks: "统一报价、深度和成交字段口径，保留样本成员变动与停牌，明确市场汇总权重及异常行情处理。", boundary: "不同交易制度下的价差和深度不必可比；日频代理也不能取代原文所需的报价和订单簿观察。" }),
  guide({ title: "Earnings Management During Import Relief Investigations", url: "https://doi.org/10.2307/2491047", source: "Journal of Accounting Research (1991)", question: "论文研究企业在进口救济调查背景下是否会出现与报告激励相关的应计项目行为。", design: "来源围绕一类受制度约束的调查事件，比较公司报告变量与调查时点之间的关系。", data: "需要财务报表项目、应计项目构造、调查事件日期、公司身份、会计期间与公告可得时点。", finding: "该研究讨论特定制度激励下的报告选择，不能把应计项目变化本身直接等同于故意操纵。", checks: "保存原始申报及修订版本，区分财报期末与可得日期，明确事件样本纳入规则和行业或公司对照。", boundary: "特定贸易调查环境和历史会计准则限制外推；该导读不提供舞弊识别、合规判断或公司评价。" }),
  guide({ title: "The Detection of Earnings Manipulation", url: "https://doi.org/10.2469/faj.v55.n5.2296", source: "Financial Analysts Journal (1999)", question: "论文讨论利用财务报表变量组织对盈余操纵风险的分析框架。", design: "公开说明以多个财务指标的组合和历史比较为基础，而不是以单一比率作决定性判别。", data: "输入包括经版本控制的财务报表、会计科目定义、公司行动、报告期和实际披露日期。", finding: "研究提供风险筛查与解释框架，不能把任何分数或比率直接视为操纵事实或法律结论。", checks: "保留单位、币种、合并范围和重述，按当时可得信息构造指标，并记录缺失值与行业口径处理。", boundary: "会计模型的历史样本和定义并不替代审计证据；该导读不作公司评价、执法判断或投资建议。" }),
  guide({ title: "Financial Ratios and the Probabilistic Prediction of Bankruptcy", url: "https://doi.org/10.2307/2490395", source: "Journal of Accounting Research (1980)", question: "论文以概率模型连接财务比率、企业规模等会计信息与困境结果。", design: "来源将多个报告变量放进概率预测框架，并围绕明确的困境标签和样本定义讨论结果。", data: "必须保留财务比率的原始分子分母、公司规模、困境定义、财年、披露时间和证券映射。", finding: "模型说明会计变量可被用于研究困境结果的条件关联，但不把估计概率视为某家公司必然的未来状态。", checks: "以披露时点而非财年末对齐输入，记录重述、合并范围和标签期限，并检查类别不平衡与样本外定义。", boundary: "破产制度、会计准则和公司样本随时间与国家变化；历史概率模型不构成当前信用判断或融资建议。" }),
  guide({ title: "Law and Finance", url: "https://doi.org/10.1086/250042", source: "Journal of Political Economy (1998)", question: "论文研究法律制度、投资者权利与金融发展指标之间的跨国关系。", design: "来源使用国家层面的法律起源、权利和金融发展指标进行比较，制度分类是研究设计的一部分。", data: "需要国家口径、法律与权利变量版本、金融发展指标、观察年份及原始编码规则。", finding: "论文描述跨国制度与金融结果的关系；相关性和制度分类不应被改写为单一公司的治理结论。", checks: "保留法律编码版本和国家样本，区分法律文本、执行强度和市场发展指标，并记录历史边界和缺失处理。", boundary: "国家层级的历史比较不能替代任何司法辖区当前的法律意见、监管状态或公司层面的因果判断。" }),
  guide({ title: "Corporate Ownership Around the World", url: "https://doi.org/10.1111/0022-1082.00115", source: "The Journal of Finance (1999)", question: "论文描绘不同法律环境下大公司最终所有权和控制权的结构。", design: "研究根据控制链、投票权和最终所有者识别规则比较跨国公司样本。", data: "需要公司实体、股权与投票权、控制链、披露版本、国家制度口径和观察日期。", finding: "其价值在于说明所有权与控制权不能仅凭直接持股读出；它不对任何公司当前控制人或治理质量作断言。", checks: "冻结公司范围和控制阈值，保存股权结构披露版本，处理交叉持股与多层实体，并按披露可得时间连接。", boundary: "所有权网络会变化，跨国披露口径也不同；历史映射不能被当作实时受益所有人或治理评分。" }),
  guide({ title: "Agency Costs of Free Cash Flow, Corporate Finance, and Takeovers", url: "https://www.jstor.org/stable/1818789", source: "The American Economic Review (1986)", question: "论文提出自由现金流、公司融资和控制权交易中的代理冲突问题。", design: "来源以公司控制、现金流配置和管理者激励的理论讨论组织，而不是一套直接可运行的评分模型。", data: "若进行经验延伸，需要现金流、投资、分配、收购记录、治理结构与各项信息的披露时点。", finding: "概念框架帮助区分现金流配置与控制权激励，但不将高现金或某类交易自动标记为低效。", checks: "明确自由现金流定义、企业生命周期、资本支出和分配口径，保留治理与交易文件版本，并区分公告与完成日期。", boundary: "理论机制不能独自裁定某项收购或资本配置的质量，也不构成估值、公司行动或投资建议。" }),
  guide({ title: "The Adjustment of Stock Prices to New Information", url: "https://doi.org/10.2307/2525569", source: "International Economic Review (1969)", question: "论文围绕股票拆分信息研究价格如何在事件时间内调整，展示早期事件研究的组织方式。", design: "来源把事件、收益和市场比较放入事件窗口，重点是信息时点与正常回报基准的定义。", data: "需要原始公告时间、拆分与股息资料、复权价格、市场指数、交易日历和事件样本筛选规则。", finding: "该研究说明事件时间分析依赖准确的事件和基准构造，而不是说明每一条新闻都会产生同一种价格反应。", checks: "区分公告、传闻、实施和交易所生效日期，处理事件重叠和停牌，并保存使用的复权及基准版本。", boundary: "历史股票拆分样本和市场制度不等于当前事件的因果模板；该导读不输出异常收益或交易信号。" }),
  guide({ title: "The Stationary Bootstrap", url: "https://doi.org/10.1080/01621459.1994.10476870", source: "Journal of the American Statistical Association (1994)", question: "论文提出保留时间序列依赖结构的 stationary bootstrap 重采样方法。", design: "方法通过随机区块长度和连续观测片段构造重采样序列，设计选择决定其保留的依赖特征。", data: "输入是按固定时钟排序的完整时间序列、缺失处理规则、抽样区块设置和统计量定义。", finding: "它提供对时间依赖数据进行不确定性评估的一种工具，而不是使任何小样本或非平稳数据自动可靠。", checks: "记录频率、缺失段和区块长度设定，检验重采样是否尊重交易时段和结构断点，并保存随机种子。", boundary: "重采样假设无法替代对非平稳、制度变化或样本选择的诊断，更不证明预测或策略有效。" }),
  guide({ title: "Empirical Asset Pricing via Machine Learning", url: "https://doi.org/10.1093/rfs/hhaa009", source: "Review of Financial Studies (2020)", question: "论文研究机器学习方法如何用于资产定价中的条件预期收益与特征关系建模。", design: "来源把多个机器学习模型置于统一的资产定价训练、验证和评估安排中，而不是只展示一个模型的拟合值。", data: "需要带日期的特征、收益、证券样本、退市处理、训练验证测试划分、调参记录和可得性时钟。", finding: "研究讨论模型在历史样本和评估设计中的表现；复杂模型的拟合或变量重要性并不自动给出经济因果解释。", checks: "严格隔离训练与测试，保存全部候选模型和调参过程，按当时可得信息处理特征，并纳入退市与样本成员变化。", boundary: "该论文不提供实时预测服务或可执行组合；历史机器学习结果不能替代成本、容量和分布变化评估。" }),
  guide({ title: "Textual Analysis in Accounting and Finance: A Survey", url: "https://doi.org/10.1111/1475-679x.12123", source: "Journal of Accounting Research (2016)", question: "综述讨论会计与金融研究中如何把文档转换为文本度量，以及这些选择的验证困难。", design: "来源比较词典、语调、可读性和其他文本特征的构造与验证问题，强调文本对象和测量规则不可分离。", data: "应保存文档原件或允许访问的版本、来源与权限、首次可见时间、实体映射、特征字典和人工验证样本。", finding: "文本变量是经过选择与处理的度量，不是天然无偏的事实；公开可见也不等同于可再分发或可用于训练。", checks: "记录抓取和版本来源，去除转载重复，区分文本发布日期与财报期，并让标签验证与模型训练保持隔离。", boundary: "该综述不证明任何词典或模型在所有语言、行业和时期有效，也不授予文本或新闻的使用权。" }),
  guide({ title: "Dissecting Anomalies with a Five-Factor Model", url: "https://doi.org/10.1093/rfs/hhv043", source: "Review of Financial Studies (2016)", question: "论文考察加入盈利能力和投资因子的五因子框架如何组织若干平均收益异象。", design: "来源将特征组合回报与五因子暴露放在同一模型中，比较不同异象在该规格下的解释情况。", data: "需要因子定义、特征组合、复权收益、形成规则、样本成员和会计信息的可得时点。", finding: "摘要讨论若干异象与因子暴露的共同解释，而不是宣称五因子模型消除了所有异象或保证未来溢价。", checks: "冻结因子构造、再平衡和断点，纳入退市证券，按披露可得性对齐会计变量，并记录市场和时期。", boundary: "历史因子拟合不等于当前可获得回报；融资、卖空、交易成本和市场制度仍须单独评估。" }),
  guide({ title: "Common Risk Factors in Currency Markets", url: "https://doi.org/10.1093/rfs/hhr068", source: "Review of Financial Studies (2011)", question: "论文研究高低利率货币之间的横截面超额回报差异及其共同风险因子。", design: "来源以货币组合、利率或远期贴水和共同冲击为核心，检验一个 slope factor 对横截面差异的解释。", data: "需要即期与远期汇率、利率口径、货币篮子组成、再平衡日期、时区和各国可得数据版本。", finding: "摘要描述特定货币组合中的共同风险暴露；它不将借低息、持高息货币变成无条件的未来收益承诺。", checks: "统一币种、期限、报价方向和日历，保留资本管制或交易限制，区分样本可得信息与后续修订宏观数据。", boundary: "货币制度、融资约束和危机时期影响很大；历史因子关系不能直接用于任何市场或执行决策。" }),
  guide({ title: "Is Bitcoin Really Un-Tethered?", url: "https://doi.org/10.1111/jofi.12903", source: "The Journal of Finance (2020)", question: "论文研究2017年繁荣期稳定币发行、链上流动和交易所比特币价格之间的关系。", design: "来源使用链上流动识别和交易所价格时间序列，对不同关于稳定币流动的解释进行比较。", data: "需要钱包或地址映射、发行事件、链上转移、场所级价格、时间戳、交易所身份和原始数据覆盖说明。", finding: "摘要报告与供给驱动假说一致的模式；它不把观察到的时间关系升级为对当前储备、全部稳定币或整个加密市场的证明。", checks: "冻结链上标签和场所范围，审计时间同步与地址归属假设，区分授权、发行和转移，并保留缺失及修订记录。", boundary: "单一历史周期和受限场所数据不能代表所有加密资产，也不构成关于储备、操纵或价格走向的当前判断。" }),
  guide({ title: "Cryptocurrency Pump-and-Dump Schemes", url: "https://doi.org/10.1017/s0022109025000201", source: "Journal of Financial and Quantitative Analysis (2025)", question: "论文记录加密货币拉升出货事件的价格、成交量、波动和参与者相关模式。", design: "来源将事件识别、市场观测和钱包级资料结合，并利用平台政策变化讨论相关市场后果。", data: "需要事件时间戳、公开消息或识别规则、代币和场所身份、价格成交量、钱包数据及政策变更时点。", finding: "摘要描述短期剧烈变动和快速反转等历史事件特征；它不提供实时事件识别器，也不把所有异常成交归为操纵。", checks: "记录事件定义和所有纳入排除规则，冻结场所与代币范围，核对消息时钟和市场时钟，并区分钱包标签与已验证身份。", boundary: "加密市场的覆盖、洗售和消息可见性限制很强；该导读不作执法结论、风险评级或交易建议。" }),
]);
