// Source editions and review scope are editorial evidence, not reader-facing status.
const guide = (url, edition, evidenceScope, limits, rows) => ({
  reviewedAt: "2026-08-30", evidenceUrl: url, evidenceScope, limits,
  sections: rows.map(([pages, zh, en, bodyZh, bodyEn]) => ({
    title: { zh, en }, body: { zh: bodyZh, en: bodyEn },
    reference: { url, label: { zh: `原文定位：${edition.zh}，第${pages}页`, en: `Source: ${edition.en}, pp. ${pages}` } },
  })),
});

export const researchFundamentalsMicrostructureGuides = {
  "Value Investing: The Use of Historical Financial Statement Information to Separate Winners from Losers": guide(
    "https://www.ivey.uwo.ca/media/3775523/value_investing_the_use_of_historical_financial_statement_information.pdf",
    { zh: "2000年论文", en: "2000 paper" },
    "Ivey-hosted paper: opening argument and printed pp. 5–12 read for the nine signals, sample selection, timing and delisting convention; printed p. 7 visually checked. Return tables and full replication were not independently verified.",
    { zh: "原研究针对历史高账面市值比股票。九项二元信号不是通用质量评级或买卖建议；样本时滞和退市处理会影响结果，迁移时需重新核对。", en: "The historical study concerns high book-to-market stocks. Nine binary signals are not a universal quality rating or a trading recommendation; availability lags and delisting treatment require renewed scrutiny in another sample." },
    [
      ["2, 5–7", "先限定问题：便宜的股票并不相同", "Cheap stocks are not interchangeable",
        "Piotroski从高账面市值比股票出发，研究财务报表能否区分其中经营状况较强与较弱的企业。这里的财务信号服务于一个已经限定的价值股样本，并不是先给全市场公司打分，再声称同一阈值适合所有行业、规模和市场。",
        "Piotroski starts with high book-to-market stocks and asks whether financial statements distinguish stronger from weaker firms within that group. The accounting signals address a bounded value-stock sample. They do not establish that a single score threshold applies to every industry, company size or market."],
      ["7–8", "盈利与现金流要一起看", "Read profitability alongside cash flow",
        "盈利组包含四项信号：资产收益为正、经营现金流为正、资产收益改善，以及现金流高于会计利润。利润和现金流使用期初资产缩放；最后一项关注应计成分。只保留净利润是否增长，会丢失现金支持程度与资产规模这两层信息。",
        "Four profitability signals cover positive return on assets, positive operating cash flow, improving return on assets and cash flow exceeding accounting earnings. Earnings and cash flow are scaled by beginning assets; their comparison captures accruals. Earnings growth alone loses both cash support and the asset base underlying profitability."],
      ["8–10", "融资状态与经营效率是另外两组", "Financing and operations supply five more signals",
        "另五项分别观察长期杠杆下降、流动比率改善、没有发行普通股，以及毛利率和资产周转率改善。毛利率的分母是销售额，周转率则连接销售与资产。它们描述不同变化，不能用一个名称宽泛的“盈利能力”字段替代。",
        "Five further signals track lower long-term leverage, improving current ratio, no common-equity issuance, improving gross margin and improving asset turnover. Gross margin uses sales as its denominator, whereas turnover links sales to assets. These are distinct changes, not interchangeable versions of a generic profitability field."],
      ["7–10", "九个判断，不是精确的经营刻度", "Nine binary judgements, not a continuous scale",
        "每项条件满足得一分，合计形成0至9的分数。这样的等权二元表达便于比较，却不保留改善幅度：略有改善与大幅改善可能同得一分。阅读时应保留原始财务值、比较期间和信号方向，避免把一分差异解释成固定的经济距离。",
        "Each satisfied condition contributes one point to a score from zero to nine. Equal-weight binary coding is easy to compare but discards magnitude: slight and substantial improvements can receive the same point. Preserve the underlying financial values, comparison periods and signal directions rather than treating each point as a fixed economic distance."],
      ["11–12", "报告期末不是信息可用时点", "Respect the gap between fiscal year and use",
        "研究样本覆盖1976至1996年，并在每个财政年度结束后的第五个月开始计算持有期收益。高账面市值比的样本筛选也需要财务资料齐备。这个历史时滞不证明其他市场的披露已经完成；实际应用仍要保留公告日期和修订版本。",
        "The sample covers 1976–1996, with holding-period returns beginning in the fifth month after fiscal year-end. High book-to-market selection also requires sufficient accounting data. This historical lag is not proof that disclosure is complete elsewhere; actual publication dates and revised filing versions remain essential for a new dataset."],
      ["11–12", "结果也受样本退出规则影响", "Exits and exclusions affect interpretation",
        "论文比较强弱财务组及整个高账面市值比样本，并使用不同统计检验。它在此处采用退市收益为零的假设，这会影响退出样本的处理。重读结果时，应把样本剔除、退市回报和缺失值规则一起考虑，不能只沿用评分而忽略收益序列如何形成。",
        "The paper compares financially stronger and weaker groups with the wider high book-to-market sample using multiple statistical tests. Its stated convention assumes a zero delisting return. Interpretation therefore needs exclusions, delisting treatment and missing-data rules alongside the score, rather than borrowing the signals while ignoring construction of the return series."],
    ]),
  "Corporate Governance and Equity Prices": guide(
    "https://www.nber.org/papers/w8449.pdf",
    { zh: "2001年8月NBER工作论文", en: "August 2001 NBER working paper" },
    "NBER Working Paper 8449, August 2001: printed pp. 1–8 visually read because the PDF text encoding is unreliable. Review covers index direction, IRRC editions, sample construction and causal caveats; later tables and the final 2003 article were not fully reviewed.",
    { zh: "导读依据2001年工作论文，题录保留2003年期刊版。历史美国治理条款不能直接视为当前法律或跨市场治理标准；相关关系不等于治理改革的因果效果。", en: "This guide uses the 2001 working paper while retaining the 2003 journal citation. Historical US provisions are not current law or a cross-market governance standard; associations do not identify the causal effect of governance reform." },
    [
      ["1–3, 7–8", "分数越高，股东权利越弱", "Check the direction before reading the score",
        "论文汇总24项治理条款，形成衡量股东权利的指数。数值较高代表对股东权利的限制更多，而不是“治理更好”。这也不是环境、社会与治理的综合评分。解释任何分组或图表之前，先确认计分方向及条款到底衡量谁的权利。",
        "The index combines 24 governance provisions: a higher score indicates weaker shareholder rights, not better governance. It is also not a combined environmental, social and governance rating. Before interpreting a group comparison or chart, establish the coding direction and whose rights the underlying provisions describe."],
      ["2, 7–8", "覆盖范围决定结论的边界", "Coverage defines the comparison",
        "工作论文使用约1500家大型公司的治理资料，研究时期为1990至1999年，并排除双重股权结构公司。资料覆盖在后期发生扩展。因此样本不是所有上市公司的固定全集，跨期比较需要区分治理变化与被纳入资料库的公司变化。",
        "The working paper uses governance information for roughly 1,500 large companies over 1990–1999 and excludes dual-class firms. Coverage expands later in the period. This is not a fixed census of all listed companies; a time comparison must distinguish changing provisions from changes in which firms enter the source database."],
      ["7–8", "条款来自文件，不来自行情", "Governance coding starts with documents",
        "资料来源包括公司章程、内部细则、代理投票材料及年度或季度文件。将条款编码为指数，需要保留原始文件、规则解释和观察日期。价格、财务比率或公司名称本身不能证明某项反收购安排存在，也不能替代具体条款的核对。",
        "The source material includes charters, bylaws, proxy documents and annual or quarterly filings. Coding provisions requires their documentary basis, interpretation and observation date. Prices, financial ratios or company names cannot establish the existence of a particular takeover defense or replace inspection of the relevant provision."],
      ["7–8", "资料版本不是实时状态", "A publication vintage is not a live state",
        "治理资料来自1990、1993、1995和1998年的多个版本，并非每次都会更新所有公司的全部条款。相邻版本数值相同，不足以证明期间没有变化。与行情连接时还要校验公司标识和样本匹配，不能把最新一版指数直接回填到过去。",
        "Governance observations come from the 1990, 1993, 1995 and 1998 publications, without a complete refresh of every company at each edition. An unchanged value does not prove that nothing changed between observations. Matching market data requires validated firm identities and dated vintages, not backfilling history with the latest index."],
      ["3–5", "多个经营结果提供不同线索", "Outcomes ask different economic questions",
        "论文把治理指数与公司估值、盈利、销售增长、资本支出和收购活动联系起来。这些结果变量不是同一概念：估值包含市场预期，投入可能反映扩张，盈利则受会计口径影响。理解论证需要分别看它们，不能把所有关系压缩成单一“优质公司”标签。",
        "The paper relates the index to valuation, profitability, sales growth, capital spending and acquisitions. These outcomes are not equivalent: valuation incorporates expectations, spending may reflect expansion and earnings depend on accounting conventions. Read their separate roles rather than compressing every association into a single label of company quality."],
      ["4–6", "相关性留下了因果问题", "Association leaves causality unresolved",
        "作者明确不把这些关系当作因果方向已经确定的证明。治理条款可能影响经营，也可能在公司预期表现恶化时被采用，或者只是其他问题的伴随特征。若想评价一次治理改革，需要额外识别设计，而不是把历史组间差异直接解释为改革收益。",
        "The authors explicitly refrain from claiming a settled direction of causality. Provisions might affect operations, be adopted in anticipation of poor performance or indicate other underlying problems. Evaluating a governance reform requires an additional identification design; a historical difference between groups is not itself the return to implementing that reform."],
    ]),
  "In Search of Distress Risk": guide(
    "https://dash.harvard.edu/server/api/core/bitstreams/7312037c-5bf6-6bd4-e053-0100007fdf3b/content",
    { zh: "2005年6月27日作者稿", en: "June 27, 2005 author draft" },
    "Harvard DASH manuscript dated June 27, 2005: printed pp. 1–8 read; printed p. 6 visually checked for predictor scaling and accounting lag. The repository wrapper cites 2008, but the linked manuscript is an earlier draft; final-version tables and prediction replication not verified.",
    { zh: "导读依据2005年作者稿，题录为2008年期刊版，最终设定需回到期刊原文。企业失败的标签、会计时滞与市场制度有样本依赖性，不能直接生成当前公司的违约概率。", en: "This guide uses the 2005 author draft, not the definitive specifications of the 2008 journal article. Failure labels, reporting lags and market institutions are sample-dependent; the guide does not generate current company default probabilities." },
    [
      ["1, 4–5", "先定义什么叫企业失败", "Define the outcome before the predictors",
        "研究区分破产申请与更宽的企业失败标签；后者还纳入特定退市和信用评级降至D等事件。两种标签的覆盖时期也不同。因此，破产、违约和退市不能随意互换，更不能把所有退市都视作同一种财务失败。",
        "The study distinguishes bankruptcy filings from broader failure events, including specified delistings and a D credit rating. The labels also have different historical coverage. Bankruptcy, default and delisting are not interchangeable outcomes; in particular, every delisting must not automatically be treated as the same kind of financial failure."],
      ["4–6", "观察单位是公司与月份", "Think in firm-month observations",
        "作者用动态面板逻辑模型研究失败概率，每家公司可以贡献多个按月排列的观察值。问题是已知当时信息时，在指定未来期限内是否发生失败，而不是给每家公司永久贴一个标签。样本退出、时间顺序及预测期限都是模型定义的一部分。",
        "A dynamic panel logit model organizes observations by firm and month. The question is whether failure occurs over a specified future horizon given information available then, not whether a company deserves a permanent label. Exits, observation order and forecast horizon therefore belong to the definition of the model."],
      ["5–7", "市场口径改变了财务比率", "The denominator changes the financial signal",
        "作者稿比较以账面资产缩放的盈利和负债，与使用“权益市值加账面负债”缩放的版本。后者会随股价变化，并不是把账面资产简单改名。准备变量时应分别保存分子、分母和价格日期，避免把同名的杠杆或盈利指标混在一起。",
        "The draft compares profitability and leverage scaled by book assets with versions scaled by market equity plus book liabilities. The latter changes with equity prices; it is not book assets under another name. Keep numerators, denominators and price dates separately so similarly named leverage or profitability fields are not mixed."],
      ["6–7", "会计数据与市场数据有不同的时钟", "Accounting and market inputs run on different clocks",
        "解释变量结合季度财务、月度收益和日度价格波动。此作者稿对会计数据施加两个月的时滞，同时使用过去市场信息构造收益和波动变量。拼接时要保留各自的可用日期；固定时滞本身不能证明一份延迟披露的报表当时已可获得。",
        "Predictors combine quarterly accounts, monthly returns and daily price variability. This draft lags accounting information by two months while constructing market measures from past observations. Preserve availability dates for each input: a fixed lag does not establish that a delayed financial filing was actually accessible at that time."],
      ["2–3, 7–8", "近期风险与远期风险不是同一道题", "Near and distant horizons need separate evaluation",
        "盈利、杠杆、超额收益、波动、规模和现金等特征共同进入比较，但它们对不同期限的失败预测可能有不同作用。检验应写清未来窗口、样本基准和预测信息集。一个期限下的拟合结果不能自动成为另一期限下经过校准的概率。",
        "Profitability, leverage, excess returns, volatility, size and cash enter the comparison, but their relevance can change with the failure horizon. Evaluation needs an explicit future window, baseline and information set. A fit at one horizon does not automatically yield calibrated probabilities at another."],
      ["1–3", "失败概率与股票回报需要分开解释", "Failure risk is not a promised return premium",
        "论文进一步研究财务困境与股票收益的关系，但预测企业是否失败和解释股东收益是两个不同任务。企业困境更深，并不意味着股东必然获得更高补偿；历史关系也不能转化为个股交易结论。阅读时应把失败标签与收益样本分别核对。",
        "The paper also studies stock returns, but predicting company failure and explaining shareholder payoffs are separate tasks. Greater distress need not deliver a higher reward to equity holders. Historical associations do not establish an individual-stock trade; the failure outcome and the return sample must be examined independently."],
    ]),
  "A Simple Implicit Measure of the Effective Bid-Ask Spread in an Efficient Market": guide(
    "https://www.bauer.uh.edu/rsusmel/phd/roll1984.pdf",
    { zh: "1984年期刊版", en: "1984 journal article" },
    "University-hosted journal scan: printed pp. 1128–1131 and 1134–1135 read for spread derivation, units and sampling-frequency evidence, with p. 1129 visually checked. Full empirical tables were not replicated; handling of invalid sample covariance is an editorial measurement caveat.",
    { zh: "Roll指标依赖有效价格与交易过程假设，是隐含价差估计，不是完整执行成本。样本协方差、采样频率和价格单位会改变可解释性，不能把公式失效静默改写成零成本。", en: "The Roll measure depends on assumptions about efficient prices and trading. It estimates an implicit spread, not total execution costs; sample covariance, frequency and price units constrain interpretation, and an invalid calculation is not evidence of zero cost." },
    [
      ["1128–1129", "成交价会在买卖报价之间跳动", "Bid–ask bounce can create serial dependence",
        "即使有效价格没有可预测变化，成交也可能交替发生在买价和卖价附近，造成相邻价格变化的负相关结构。Roll利用这个交易摩擦留下的统计痕迹估计价差。它不是把所有短期反转都认定为可获利的价格错误。",
        "Even without predictable movements in efficient value, transactions can alternate near bid and ask prices, leaving negative serial dependence in price changes. Roll uses this statistical footprint of trading friction to infer a spread. The argument does not classify every short-run reversal as a profitable pricing error."],
      ["1129", "公式使用协方差，不是相关系数", "Covariance is not correlation",
        "在论文假设下，有效价差等于相邻价格变化协方差取负号后的平方根，再乘以二。这里是协方差而非相关系数：后者已经除去尺度，不能直接代入得到价格单位的价差。计算前应明确变化量、滞后方向和配对观察值。",
        "Under the model, the spread is twice the square root of minus the covariance between adjacent price changes. This is covariance, not correlation: a scale-free correlation cannot be inserted to obtain a spread in price units. Specify the changes, lag direction and paired observations before calculation."],
      ["1129–1131", "价格变化与收益变化有不同单位", "Price changes and returns have different units",
        "用价格差计算时，估计结果具有价格单位；使用收益的近似形式时，结果更接近比例口径。跨币种、复权方案或股票价格水平比较前，需要说明输入与缩放。隐含有效价差也不同于屏幕上的报价差，更不包含全部手续费与市场冲击。",
        "Using price differences produces a spread in price units; a return-based approximation instead has a proportional interpretation. Comparisons across currencies, adjustment schemes or price levels need explicit inputs and scaling. An inferred effective spread also differs from a displayed quoted spread and does not include every fee or market-impact cost."],
      ["1128–1130", "无法估计也是有信息的结果", "An unavailable estimate is a diagnostic",
        "这个平方根表达式在样本协方差为负时给出正的价差。协方差为正时，实数范围内无法按原式得到价差，可能涉及样本噪声或假设不适用。此时应报告无法估计及其原因；擅自取绝对值或填零会改变方法，不应仍称为未经修改的原始估计。",
        "The square-root expression gives a positive spread for negative sample covariance. A positive covariance does not yield a real-valued spread under that expression and can reflect sampling noise or unsuitable assumptions. Report the estimation failure; silently taking an absolute value or filling zero changes the method rather than preserving the original estimator."],
      ["1134–1135", "换一个频率，结果为何会变？", "Sampling frequency tests the assumptions",
        "论文比较日频和周频估计，发现明显差异，而理论中的简化假设并不预期这种差异。作者讨论了价格有效性与非平稳等解释。频率敏感性因此值得作为诊断保留，不能任意挑选数值较低的窗口来声称某只股票交易成本更小。",
        "Daily and weekly estimates differ materially in the paper, despite the simplified theory's sampling-interval implication. The author discusses efficiency and nonstationarity as possible explanations. Retain frequency sensitivity as a diagnostic instead of choosing whichever window produces the lowest number and declaring a stock cheaper to trade."],
      ["1128–1131, 1134–1135", "先保留序列，再解释估计", "Preserve the sequence behind the estimate",
        "准备数据时应核对成交价定义、复权、交易时段和缺失观察，并明确相邻记录是否真的是相邻交易或相邻时间窗。补零、跨停牌拼接或混合不同频率，都可能改变协方差。保留这些处理记录，才有条件区分交易摩擦与数据加工带来的反转。",
        "For new data, check transaction-price definitions, adjustments, sessions and missing observations. State whether adjacent records represent adjacent trades or time windows. Zero filling, joining across suspensions and mixing frequencies can alter covariance; documented treatment helps distinguish trading friction from reversals introduced during data preparation."],
    ]),
  "Measuring the Information Content of Stock Trades": guide(
    "https://www.acsu.buffalo.edu/~keechung/MGF743/Readings/K2.pdf",
    { zh: "1991年期刊版", en: "1991 journal article" },
    "Image-only university-hosted journal scan: printed pp. 179–183 and 190–192 visually read, including trade innovations, quote revisions, transaction-time indexing and data filters. Subsequent coefficient tables and full VAR estimation were not independently reviewed or reproduced.",
    { zh: "交易的信息含量依赖报价、成交方向、事件排序与模型设定。历史样本中的长期报价响应不能直接解释为每笔交易的私人信息，更不能只靠分钟行情复现。", en: "Information content depends on quotes, trade signs, event ordering and model specification. A persistent quote response in this historical design does not identify private information in every trade, and minute bars alone cannot reproduce it." },
    [
      ["179–181", "信息含量关注持久影响", "Information content concerns the persistent response",
        "Hasbrouck研究交易之后报价的长期调整，而不是只看成交后的即时价格跳动。短期反应可能包含库存管理和交易摩擦；持久部分更接近论文想识别的信息作用。把两者区分开，才能理解为什么一次成交价变化并不等于信息被完整揭示。",
        "Hasbrouck studies the eventual quote adjustment following a trade rather than only its immediate price movement. Short-run responses can include inventory management and trading frictions. Separating these from the persistent component explains why a single transaction-price change does not measure the complete revelation of information."],
      ["180–183", "关键是未被预期的交易部分", "Focus on the unexpected component of trading",
        "交易本身可能延续此前的成交与报价信息。论文关注在给定过去信息后仍无法预期的交易创新，并分析它随后引起的报价响应。直接把全部买入成交量与价格变化相连，会混合可预测订单流和新增信息，回答的已不是同一个问题。",
        "Trades can be predictable from earlier trades and quote changes. The paper focuses on the trading innovation left after conditioning on past information and traces the subsequent quote response. Relating all buyer-initiated volume directly to price changes mixes predictable order flow with new information and answers a different question."],
      ["181–183", "滞后关系组成一个动态系统", "Lags form a dynamic system",
        "向量自回归把交易与报价修订放进同一滞后系统，允许信息在多个事件后逐步体现。由此得到的长期响应依赖变量选择、滞后长度和交易过程假设。它不是把一条回归的当期系数简单命名为永久冲击，模型设定也需要随结果保留。",
        "A vector autoregression places trades and quote revisions in a joint lagged system, allowing adjustment over several events. Its long-run response depends on variables, lag structure and assumptions about trading. It is not merely a contemporaneous regression coefficient renamed as permanent impact; the specification must accompany the result."],
      ["181–182, 191–192", "报价中点与成交价各有角色", "Quotes and transaction prices play different roles",
        "论文以报价中点描述价格修订，并给成交赋予买方或卖方发起的方向。中点处的成交方向可能无法明确识别。只保存成交价和成交量会失去当时报价背景；方向判定规则也应单独记录，不能把推断方向当成交易所直接提供的事实。",
        "Quote midpoints describe price revisions, while trades receive buyer- or seller-initiated signs. Trades at the midpoint can be indeterminate. Keeping only transaction prices and volume loses the quote context; retain the signing rule separately rather than treating an inferred direction as an exchange-observed fact."],
      ["190–192", "事件时间不等于钟表时间", "Transaction time is not clock time",
        "样本使用1989年第一季度的交易和报价记录，并按规模组选取公司。模型的事件索引会在交易或报价出现时推进；报价与成交还经过时间匹配处理。因此一个滞后不是固定的一分钟，不能用规则时间柱机械替代原研究的事件序列。",
        "The sample uses first-quarter 1989 trades and quotes from companies selected across size groups. The transaction time index advances with trade or quote events, with additional quote–trade timing alignment. A lag is therefore not a fixed minute; regular time bars cannot mechanically substitute for the original event sequence."],
      ["180–183, 191–192", "持久响应不自动证明私人信息", "Persistence alone does not prove private information",
        "公开新闻、报价调整方式和交易摩擦都可能影响所估计的响应。论文讨论的识别依赖其结构和信息假设；数据匹配误差也可能改变交易与报价的先后关系。评价结果时需要同时阅读模型限制和清洗方法，而不是把每次持久变动归因于知情交易者。",
        "Public news, quote adjustment and trading frictions can influence the estimated response. Identification depends on the model's structural and information assumptions, while matching errors can alter the order of trades and quotes. Read these limits alongside preprocessing rather than assigning every persistent movement to an informed trader."],
    ]),
  "The Price Impact of Order Book Events": guide(
    "https://arxiv.org/pdf/1011.6402v3",
    { zh: "2011年3月作者稿v3", en: "March 2011 author draft v3" },
    "Frozen arXiv 1011.6402v3: introduction and sections 1–2.3 read, printed pp. 8–11 and appendix p. 26 checked for regressions and filters; p. 4 visually checked against the OFI equation. The 2014 journal identity is retained; full final-version tables and execution simulations not verified.",
    { zh: "导读采用2011年作者稿v3，题录保留2014年期刊版。最优报价处的同期关系不是未来价格预测，也不代表完整订单簿或真实执行成本；分钟成交量不足以替代所需输入。", en: "This guide uses the 2011 author draft v3 while retaining the 2014 journal citation. Best-quote contemporaneous relationships are not forecasts, a complete order book or execution costs; minute-level traded volume cannot replace the required inputs." },
    [
      ["1–4", "订单簿事件不只是成交", "Order book events extend beyond trades",
        "论文从最优买卖报价及其挂单数量出发，把市价成交、限价单新增和撤单共同纳入供需变化。成交量只记录已经撮合的部分，无法描述尚未成交的流动性变化。因此只有价格柱和成交量时，不能直接声称重建了论文的订单流不平衡。",
        "The paper starts from best bid and ask prices and displayed sizes, combining market trades, limit-order additions and cancellations. Traded volume records only matched activity, not all changes in available liquidity. Price bars and volume alone therefore cannot establish that the paper's order flow imbalance has been reconstructed."],
      ["4–5", "OFI是按事件累计的净变化", "OFI aggregates signed event contributions",
        "订单流不平衡按最优报价及队列变化，为每个事件赋予带方向的贡献，再在时间窗内累计。买方队列增加与卖方队列增加的方向不同，最优价格改变时也要按定义处理。它不是简单用买入成交量减去卖出成交量，更不是整本订单簿的静态买卖数量差。",
        "Order flow imbalance aggregates signed contributions from changes in best prices and queues over an interval. Added bid and ask size contribute in opposite directions, and best-price changes need their own treatment. OFI is neither simply buyer volume minus seller volume nor a static difference across the entire order book."],
      ["5–8", "相同不平衡在不同深度下含义不同", "Depth changes the response to imbalance",
        "作者把时间窗内以最小价格变动单位计量的中点变化，与同窗OFI联系起来，并讨论斜率随市场深度下降而增大的关系。价格单位、挂单数量单位和深度定义必须同时明确；这个简化关系并不保证任意市场、任意规模的订单都有相同线性影响。",
        "The model relates midpoint changes measured in ticks to OFI over the same interval and links a larger slope to lower market depth. Price units, size units and the depth definition must travel together. This simplified relation does not guarantee linear impact for every order size or market."],
      ["8–11", "时间窗是研究设定的一部分", "The observation window is part of the design",
        "作者稿使用2010年4月随机选取的50只标普500股票，基准观察网格为10秒，并在半小时区间估计关系。论文还考察其他时间尺度。更换股票范围、市场时段或聚合窗口会改变样本与参数，不能把原文的短窗结论直接移到日频数据。",
        "The draft studies 50 randomly selected S&P 500 stocks in April 2010, using a ten-second baseline grid and estimating relations within half-hour periods. Other timescales are also examined. Changing the universe, session or aggregation window changes the sample and parameters; short-window findings cannot simply be transferred to daily data."],
      ["8–11", "同期解释不是下一刻的预测", "Contemporaneous fit is not a forecast",
        "核心比较使用同一窗口里的价格变化和订单流不平衡，是同期解释关系，而不是提前知道下一窗口的价格。部分事件还同时改变最优报价，存在机械联系需要检查。若研究预测能力，必须另设信息截止点与未来目标，不能把同期拟合优度当成预测成绩。",
        "The core comparison is contemporaneous: price changes and OFI come from the same interval, not a forecast of the next interval. Some events also change best prices, requiring checks for mechanical association. Predictive evaluation needs a separate information cutoff and future target rather than reusing contemporaneous fit as a forecasting score."],
      ["4, 26", "保留报价事件与清洗依据", "Retain event records and filtering choices",
        "附录说明了报价、成交记录的筛选、交易时段和最优报价整理。准备新数据时，应保留事件时间、买卖价格与数量、记录类型和过滤原因，并核对是否具备合并最优报价所需信息。只有这些边界清楚，才能判断指标缺口来自市场行为还是数据覆盖。",
        "The appendix describes quote and trade filtering, sessions and construction of best quotes. For new data, retain event times, bid and ask prices and sizes, record types and exclusion reasons, checking whether consolidated best-quote information is available. These boundaries distinguish economic variation from gaps in data coverage."],
    ]),
};
