// Original bilingual editorial writing; review scopes are retained internally.
const section = (zh, en, bodyZh, bodyEn) => ({ title: { zh, en }, body: { zh: bodyZh, en: bodyEn } });
const guide = (evidenceUrl, evidenceScope, sections, zh, en) => ({ reviewedAt: "2026-08-30", evidenceUrl, evidenceScope, sections, limits: { zh, en } });

export const researchEditorialExpansion = {
  "Portfolio Selection": guide(
    "https://www2.stat.duke.edu/courses/Fall07/sta103/markowitz.pdf", "Published article extract: opening argument and portfolio mean/variance exposition, pp. 77, 81–82; not a complete review.", [
      section("先问资产之间怎样共同变化", "Begin with co-movement", "Markowitz把组合选择与预期形成分开：论文从给定的收益预期和协方差出发，讨论如何组合资产。它没有解决怎样准确预测这些输入。这个区分能帮助读者理解，优化程序的精确不等于输入可靠。", "Markowitz separates portfolio choice from forming beliefs. The paper takes expected returns and covariances as inputs; it does not solve their prediction. A precisely solved optimization can still rest on unreliable inputs."),
      section("分散化不只是增加数量", "Diversification is not a count", "组合的预期收益是加权平均，而方差还取决于资产两两之间的协方差。因此，持有更多资产不必然带来同等程度的风险分散；资产之间的共同变化才是关键。原文的几何讨论还限定了权重非负。", "Expected portfolio return is a weighted average, but variance also depends on pairwise covariances. More holdings need not deliver proportionate diversification. The geometric exposition assumes nonnegative weights."),
      section("有效集合回答一个条件问题", "Efficiency is conditional", "在给定输入和约束下，有效组合是在相同预期收益下方差更低，或相同方差下预期收益更高的选择。这个集合不是唯一答案，还需要说明对风险与收益的偏好。方差也不是所有损失风险的完整描述。", "The efficient set compares variance at a given expected return, or return at a given variance. It does not select one universally best portfolio. Preferences still matter, and variance is not a complete description of losses."),
      section("从组合语言走向定价检验", "From portfolios to pricing tests", "准备输入时，本站建议统一收益频率、复权方法和共同样本窗口，保留缺失与退市记录。继续读Fama与French，可以比较“给定预期如何组合”和“哪些变量解释平均收益”这两个不同问题。", "Align return frequency, adjustment conventions and common observation windows; retain missing and delisted records. Fama and French then shift the question from combining given expectations to explaining average returns."),
    ], "输入估计、约束和样本时期改变时，有效集合也会改变；本文不是现成的配置方案或收益保证。", "Estimated inputs, constraints and sample periods change the efficient set; this is not a ready-made allocation or return guarantee."),

  "The Cross-Section of Expected Stock Returns": guide(
    "https://www.ivey.uwo.ca/media/3775518/the_cross-section_of_expected_stock_returns.pdf", "Published article abstract, introduction and opening data description, pp. 427–429.", [
      section("比较公司，不是预测下一天", "Compare firms, not tomorrow", "Fama与French研究公司之间平均收益的差异，比较市场贝塔、规模、账面市值比、杠杆和盈利价格比。横截面问题与预测某只股票下一天的价格不同，也不等于解释每一次日内波动。", "Fama and French compare average returns across firms using beta, size, book-to-market, leverage and earnings-price ratios. This cross-sectional question differs from forecasting tomorrow's price or explaining every intraday move."),
      section("把相互重叠的解释放在一起", "Test overlapping explanations", "这些变量往往共享价格或公司规模信息。分别显著不意味着各自提供独立解释；作者把它们联合考察，并区分与规模相关及无关的贝塔变化。理解这种比较，比记住某一个系数更重要。", "Several variables share price or size information. Separate significance does not establish independent explanatory content. Joint tests and beta variation distinct from size help disentangle their roles."),
      section("样本结论与经济解释分开", "Separate finding from mechanism", "在1963—1990年的美国样本中，规模与账面市值比刻画了多项变量所关联的平均收益差异；市场贝塔的关系较弱。作者讨论风险与非理性定价两类解释，不能把统计关联直接定性为某一种机制。", "In the 1963–1990 US sample, size and book-to-market capture return differences associated with several variables, while beta's relation is weak. Risk and mispricing remain competing interpretations of those associations."),
      section("与1993年论文对照阅读", "Read alongside the 1993 paper", "这篇以公司特征和横截面为中心，1993年论文进一步研究因子组合收益的时间序列解释力。本站建议记录财务数据披露时点与市值日期，避免用后来修订的账面值去解释当时可得的信息。", "This paper centers on characteristics and cross-sections; the 1993 study examines factor-return time series. Preserve accounting availability and capitalization dates so later revisions do not silently enter historical information sets."),
    ], "历史关联既不识别唯一原因，也不保证其他市场或未来时期的表现；公司特征不等同于因子载荷。", "Historical associations neither identify one cause nor establish transfer to other markets or periods; characteristics are not factor loadings."),

  "A Simple Way to Estimate Bid-Ask Spreads from Daily High and Low Prices": guide(
    "https://onlinelibrary.wiley.com/doi/10.1111/j.1540-6261.2012.01729.x", "Publisher abstract; explanatory guide only, no uninspected estimator formula or implementation claim.", [
      section("只有日行情，还能研究价差吗？", "What can daily prices reveal?", "Corwin与Schultz研究在缺少逐笔报价时，能否用每日最高价与最低价估计买卖价差。这是用容易取得的数据构造代理量，而不是从日行情恢复真实订单簿。", "Corwin and Schultz ask whether daily highs and lows can estimate spreads when detailed quotes are unavailable. The aim is a low-frequency proxy, not reconstruction of an order book."),
      section("价格区间包含两种变化", "A range mixes two components", "作者的思路是：最高与最低成交价之间的差异，既包含价格波动，也包含买卖价差。两种成分随观测区间扩展的方式不同，因而可以结合一天与两天的高低价比进行识别。", "High-low ranges combine price variation and spread effects. Their different behavior as the observation interval expands motivates combining one-day and two-day high-low ratios."),
      section("估计价差与观测价差不同", "Estimated is not observed", "论文摘要报告该方法相对其他低频估计量的表现。阅读时应追问比较基准、场所与样本，而不是把每个估计值当作当时可以成交的成本。执行成本还涉及数量、冲击和费用，日价格区间没有包含这些全部信息。", "The abstract reports comparative performance against other low-frequency estimators. Ask about benchmarks, venues and samples. An estimated spread is not an executable cost, which also depends on size, impact and fees."),
      section("与波动率论文一起读", "Read with volatility measurement", "已实现波动率研究讨论高频收益如何聚合；这里则尝试从低频区间分离波动与价差。准备数据时先核对高低价口径、交易时段和停牌情况；具体计算还需结合原文公式、适用条件与异常处理。", "Realized volatility aggregates high-frequency returns; this paper separates components of low-frequency ranges. Check price conventions, sessions and suspensions. Consult the full specification and exception handling before implementing the estimator."),
    ], "本篇为基于摘要的方法概览。低频代理不能替代真实报价、订单簿或成交成本；具体估计步骤请见原文。", "This abstract-based overview is not an implementation. A low-frequency proxy cannot replace quotes, order books or execution costs; consult the paper for estimation steps."),

  "Replicating Anomalies": guide(
    "https://www.nber.org/system/files/working_papers/w23394/w23394.pdf", "2017 NBER working-paper abstract and supplied opening excerpts; final publication identity retained, no transfer of draft numerical counts.", [
      section("同一个名称是否代表同一个实验？", "Does a name identify an experiment?", "Hou、Xue与Zhang把大量已发表的异象放进统一复现框架。核心问题不只是是否再次得到显著结果，还包括变量定义、股票范围、分组方式与权重改变后，原有解释是否仍成立。", "Hou, Xue and Zhang bring reported anomalies into a common replication framework. The question includes variable definitions, universes, grouping and weighting, not merely whether significance reappears."),
      section("微型股为什么影响比较", "Why microcaps matter", "作者通过纽约证券交易所断点和市值加权，降低微型股对比较的主导作用。等权与市值加权回答的对象不同，因此不能只比较结果名称，而不比较样本中哪些公司实际上贡献最大。", "NYSE breakpoints and value weighting reduce microcap influence. Equal- and value-weighted results describe different objects, so comparing labels without checking which firms dominate can mislead."),
      section("显著性之外还有复现口径", "Replication is more than significance", "论文报告许多结果在统一标准下减弱或不再显著，并讨论多重检验。不能由此推导所有异象都不存在；相反，需要说明什么定义、样本和统计标准产生了什么证据。工作论文与定稿的统计数量也不可混用。", "Many results weaken under harmonized standards, with multiple testing adding another hurdle. This does not prove every anomaly absent. Definitions, samples and inference standards must accompany findings; draft and final counts are not interchangeable."),
      section("回到应计研究重新提问", "Return to accrual studies", "读完Sloan和Dechow–Dichev后，可以用这篇重新检查财务变量怎样构建。本站建议保留原始字段、版本、筛选记录和每一步样本数量，把无法复现的环节当作明确缺口，而不是用相近指标补齐后继续沿用原结论。", "After Sloan and Dechow–Dichev, revisit accounting-variable construction. Keep raw fields, versions, exclusions and sample counts. A substituted proxy should be named as a change, not quietly presented as replication."),
    ], "导读依据2017年工作论文讨论复现原则；具体清单与检验以期刊定稿为准。未显著不等于证明效应为零。", "The guide uses the 2017 working paper for replication principles; consult the journal edition for its final inventory and tests. Insignificance is not proof of zero effect."),

  "The Real Value of China's Stock Market": guide(
    "https://www.sciencedirect.com/science/article/abs/pii/S0304405X20302403", "Final 2021 publisher abstract and introductory excerpt; 1995–2016 sample, not the earlier NBER draft.", [
      section("市场的价值不只看指数涨跌", "More than index performance", "Carpenter、Lu与Whitelaw研究股价是否包含未来企业盈利的信息，以及这些信息如何与企业投资相联系。问题关注股票市场的信息与资本配置功能，不是把指数走势当作经济增长的简单镜像。", "Carpenter, Lu and Whitelaw study whether prices contain information about future profits and how that relates to investment. The focus is information and capital allocation, not an index as a simple mirror of GDP."),
      section("把价格与后来的经营结果连接", "Connect prices to later operations", "期刊版本考察1995—2016年资料，以未来盈利对既往价格的横截面关系度量信息含量，并区分所有权。未来盈利在这里是用来事后检验信息的结果变量，不是当时可以输入的已知事实。", "The journal version studies 1995–2016, linking subsequent profits to earlier prices and distinguishing ownership. Future profits are ex-post outcomes for evaluating information, not inputs known contemporaneously."),
      section("所有权差异不能被平均数掩盖", "Ownership changes the interpretation", "作者报告价格信息含量的改善，并发现民营企业的信息含量与投资效率变化相关。国有企业在金融危机后呈现不同模式。把所有企业合并成一句“中国市场有效”，会丢掉论文的重要条件和差异。", "The authors report improved informativeness and an association with investment efficiency among private firms. State-owned firms show a different postcrisis pattern. An unconditional statement that the market is efficient loses that distinction."),
      section("从制度综述走到可检验对象", "From institutions to measurement", "与中国股市发展综述相连，这篇给制度讨论引入可度量对象。本站建议保留公司身份、所有权变更、财务版本与研究窗口。继续读日内效率论文时，也要注意“预测未来盈利的信息”与“日内价格发现”不是同一种效率。", "This extends institutional context into measurable objects. Preserve firm identities, ownership changes, filing versions and windows. The next intraday study uses a different meaning of efficiency: price discovery within a session."),
    ], "关联不自动识别改革的因果效应；历史所有权分组和样本结论不代表当前全部A股企业。", "Associations do not by themselves identify reform effects; historical ownership groups and findings do not represent every present-day A-share firm."),

  "Intraday Information Efficiency on the Chinese Equity Market": guide(
    "https://www.sciencedirect.com/science/article/abs/pii/S1043951X0900039X", "Final publisher abstract and introduction; sample description and reported intraday patterns only.", [
      section("一天中的信息吸收是否相同？", "Does information arrive evenly?", "Chen、Cai与Ho关注价格发现如何在交易日内变化。开盘、连续交易与收盘拥有不同的信息环境；把它们平均成一天，可能掩盖市场机制的重要差别。", "Chen, Cai and Ho examine how price discovery changes within a trading day. Opening, continuous trading and closing have different information environments that daily aggregation can hide."),
      section("研究依赖逐笔交易与报价", "Trades and quotes are distinct inputs", "作者使用2004年6月至2005年5月上海证券交易所180只成分股的报价与成交资料，考察报价价差、有效价差及价格无偏性。只拥有五分钟行情或日收盘价，不能重建原研究的全部观测。", "The sample contains trades and quotes for 180 Shanghai stocks from June 2004 through May 2005. Quoted spreads, effective spreads and price unbiasedness require information that daily closes or five-minute bars cannot fully recover."),
      section("读模式，也读适用条件", "Read patterns with their conditions", "摘要报告价差在开盘较高、随后下降、收盘略有回升，并发现更高流动性股票的日内价格更接近所检验的有效与无偏特征。不同交易规模在不同时段的作用也不同，不能概括为“大单总是更有信息”。", "Reported spreads are high at the open, decline and rise slightly at the close. More liquid stocks appear more efficient under the tests. Trade-size roles vary by session; large trades are not uniformly more informative."),
      section("在不同尺度之间保持概念清楚", "Keep time scales distinct", "长期盈利信息与日内价格发现相互关联，但度量和样本要求不同。本站建议保留交易所时钟、报价与成交类型、交易阶段和缺失记录，再决定能回答什么问题，不用数据频率高低替代质量判断。", "Long-horizon profit information and intraday discovery are related but require different measures. Preserve exchange clocks, quote/trade identity, session phase and gaps before deciding which question the data can answer."),
    ], "样本仅覆盖特定时期与成分股；市场制度已可能变化。导读不是当前日内效率诊断，低频行情也不是原样本替代品。", "The sample is period- and constituent-specific. This is not a current efficiency diagnosis, and low-frequency bars are not equivalent to its original observations."),

  "Lazy Prices": guide(
    "https://onlinelibrary.wiley.com/doi/10.1111/jofi.12885", "Final publisher abstract; checked against March 2019 NBER opening excerpt at https://www.nber.org/system/files/working_papers/w25084/w25084.pdf. No uninspected formula claims.", [
      section("读变化，而不只读语气", "Read changes, not just tone", "Cohen、Malloy与Nguyen比较企业定期披露文本在不同版本之间的变化。与计算一份文件有多少负面词不同，这里的研究对象是同一公司报告语言和结构怎样改变。", "Cohen, Malloy and Nguyen compare changes in recurring corporate disclosures. Unlike counting negative words in one document, the object is how a firm's reporting language and construction change over time."),
      section("需要一对可比文件", "Start with a comparable pair", "研究使用美国公司的季度与年度文件。本站建议先明确比较的报告类型、期间和版本，再处理格式。把年报与季报、首次披露与后续修订混在一起，可能把文档管理差异误认为信息变化。", "The study uses US quarterly and annual filings. Match form, period and version before cleaning. Mixing annual with quarterly reports, or originals with amendments, can confuse document management with information change."),
      section("没有即时反应不等于没有信息", "No immediate response is not no information", "作者报告文本变化与后续经营结果相关，但未观察到典型的公告时点反应，因而讨论投资者注意力。这个发现提示应区分信息发布、信息被处理与后续结果显现，而不是只看披露当天。", "The authors associate changes with later operating outcomes despite lacking a typical announcement response. Their attention interpretation separates information release, processing and subsequent realization rather than looking only at filing day."),
      section("与金融词典互补，而非替代", "Complement dictionaries", "金融词典强调特定语境下的词义，这篇强调同一企业的文本变化，两者测量对象不同。本站建议保留文本版本、清洗规则和人工核对样本；版式调整、模板变更和会计制度变化都值得单独检查。", "Financial dictionaries target contextual meaning; this study targets document change. Preserve versions, cleaning rules and manual checks. Formatting, templates and reporting-rule changes deserve separate inspection."),
    ], "变化不是负面消息的同义词，也不自动证明注意力是唯一机制；英文披露样本不能直接验证中文文本或当前表现。", "Change is not synonymous with bad news or proof of a unique attention mechanism; English filings do not validate Chinese text measures or current performance."),

  "Bitcoin: Economics, Technology, and Governance": guide(
    "https://www.aeaweb.org/articles?id=10.1257/jep.29.2.213", "Publisher abstract of the 2015 overview; scope is conceptual orientation, not current protocol or regulatory advice.", [
      section("先区分协议与价格", "Separate protocol from price", "Böhme、Christin、Edelman与Moore面向非技术读者介绍比特币的设计、经济机制与治理。文章把支付协议、分布式记录和现实金融系统的连接放在一起，而不是从价格曲线出发给资产估值。", "Böhme, Christin, Edelman and Moore introduce Bitcoin's design, economics and governance to nontechnical readers. They connect a payment protocol and distributed records to the conventional financial system rather than deriving value from a price chart."),
      section("机制不能脱离参与者", "Mechanisms depend on participants", "综述讨论交易记录、参与激励、发行路径和权力集中等问题。即使规则在协议中写明，仍然需要理解谁运行系统、谁提供中介服务，以及参与者怎样响应激励，不能把技术描述当作完整经济解释。", "The overview discusses transaction records, participation incentives, issuance and concentration. Protocol rules alone do not fully explain who operates the system, provides intermediation or responds to incentives."),
      section("隐私与去中心化都有边界", "Privacy and decentralization have limits", "作者强调灵活性、隐私和监管相关特征并非没有限制。本站建议把链上可见信息与链下身份、交易所账户和托管关系分开，避免把公开记录解释成匿名保证，或把协议特征套用到所有服务商。", "The authors emphasize limits to flexibility, privacy and regulatory claims. Distinguish on-chain records from off-chain identity, exchange accounts and custody. Public records do not establish anonymity or identical intermediary behavior."),
      section("再分别阅读采用模型与市场数据", "Then study adoption and markets", "这篇提供概念背景；Tokenomics讨论平台采用与价值的模型，跨交易所研究讨论交易场所分割。三个对象相关但不能互换：交易量不是用户数，交易所价格也不是协议全部经济活动。", "This is conceptual background. Tokenomics models platform adoption, while cross-exchange research studies venue segmentation. Trading volume, users and protocol activity are related but not interchangeable objects."),
    ], "这是2015年的历史性综述导读，不是当前协议、安全性、监管或投资判断；也不代表所有加密资产。", "This guide covers a 2015 overview, not current protocol, security, regulatory or investment advice, and does not represent every cryptoasset."),

  "Using Daily Stock Returns: The Case of Event Studies": guide(
    "https://bandi.feb.uns.ac.id/wp-content/uploads/2010/03/brown-warner-1985-1.pdf", "Published article abstract and sections 1–3 opening, pp. 3–6; not all simulation tables reviewed.", [
      section("方法本身也需要实验", "Test the method itself", "Brown与Warner研究日收益的统计特性如何影响事件研究。与围绕真实公告报告一个结果不同，作者用真实收益序列搭配随机分配的事件日，检查方法会不会在没有平均异常表现时仍频繁报警。", "Brown and Warner test event-study methods using observed returns with randomly assigned event dates. They ask whether procedures reject too often when no average abnormal performance should be present."),
      section("误报与检出能力分别衡量", "False positives and power differ", "作者既检查原假设为真时的拒绝率，也检查识别给定异常表现的能力。一个方法看起来保守，不代表它更有用；一个方法更容易显著，也不代表它更可靠。两种性质需要一起看。", "The analysis considers rejection under the null and power against specified effects. Conservatism alone is not usefulness, and more significant results are not automatically more reliable."),
      section("日频数据带来的具体问题", "Daily data bring specific problems", "论文讨论非正态、非同步交易、序列相关及事件附近方差变化。作者发现标准方法在多种情形下表现良好，但某些修正仍可能有帮助；不能从这项结果推出任何事件样本都可以忽略依赖结构。", "The paper examines nonnormality, nonsynchronous trading, serial dependence and event-related variance changes. Standard procedures often perform well, while corrections can help in some settings. This is not permission to ignore dependence in every sample."),
      section("从窗口设计走向推断设计", "From windows to inference", "MacKinlay帮助定义事件与窗口，这篇检查方法运行时的误差。继续阅读Petersen，可进一步理解跨公司、跨时间依赖。本站建议保留事件重复、交易日映射与样本剔除记录，再讨论标准误。", "MacKinlay organizes event and window design; this paper evaluates method behavior. Petersen extends the discussion to dependence across firms and time. Retain duplicate-event, session-mapping and exclusion records before choosing inference."),
    ], "模拟设计和历史股票样本限定了结论；集中发生的事件、短窗口或特殊市场仍需独立诊断。", "Simulation design and historical samples bound the conclusions; clustered events, short windows and different markets require their own diagnostics."),

  "Estimating Standard Errors in Finance Panel Data Sets: Comparing Approaches": guide(
    "https://www.kellogg.northwestern.edu/faculty/petersen/htm/papers/standarderror.html", "Author's final-publication abstract and companion-method page; NBER June 2006 introduction checked for dependency intuition, not final table estimates.", [
      section("更多行不一定是更多独立信息", "Rows are not independent evidence", "Petersen研究公司金融与资产定价中常见的面板数据：同一家公司跨年度的残差可能相关，同一年不同公司的残差也可能相关。忽略这些联系，会让不确定性的估计失真。", "Petersen studies panels where residuals may correlate within firms over time or across firms in a year. Ignoring these links can distort uncertainty, even with many rows."),
      section("先描述依赖，再选择标准误", "Describe dependence first", "论文比较文献中常见的处理方法，并解释它们何时一致、何时不同。本站建议先写清观测单位、公司与时间维度、可能共同的冲击，再选择方法，不按哪一种给出的显著性更高来挑选。", "The paper compares common approaches and explains when they agree or diverge. Define the observation unit, firm/time dimensions and common shocks before choosing a method, not after comparing significance."),
      section("控制平均差异不等于处理全部相关", "Mean controls and dependence differ", "把公司或年度差异放入模型，与正确估计剩余误差的相关结构，是两个相关但不同的任务。固定效应不能被当作自动解决一切标准误问题的标签；具体设定仍要回到原文与数据结构。", "Controlling average firm or year differences is distinct from estimating remaining residual dependence. Fixed effects are not a label that automatically resolves every standard-error problem; specifications must match the data structure."),
      section("把阅读路线落到数据组织", "Make the panel structure explicit", "从事件研究继续到这篇，重点转向多个公司与多个时点的共同变化。本站建议保存稳定实体ID、期间、版本和分组键，检查重复观测；若基础表就把修订当成独立样本，后续统计修正不能恢复正确的信息集合。", "Following event studies, focus on common variation across firms and dates. Keep stable IDs, periods, versions and grouping keys; audit duplicates. Statistical corrections cannot repair amendments mistakenly counted as independent observations."),
    ], "本导读解释依赖结构，不指定适用于所有数据的标准误。分组数量、样本长度及模型设定仍须专门检查。", "This guide explains dependence, not a universal standard-error choice. Cluster counts, time span and model assumptions still require checking."),

  "Parsimonious Modeling of Yield Curves": guide(
    "https://doi.org/10.1086/296409", "Publisher-registered abstract retrieved through DOI; full text unavailable in this pass. No unreviewed formula claims.", [
      section("用少数参数描述很多期限", "Few parameters, many maturities", "Nelson与Siegel提出简约收益率曲线模型，目标是在较少参数下表达常见曲线形状。简约意味着在灵活度和可解释性之间做选择，不意味着所有期限都能毫无误差地拟合。", "Nelson and Siegel seek a small-parameter representation of common yield-curve shapes. Parsimony trades flexibility against interpretability; it does not promise exact fit at every maturity."),
      section("曲线不必总是向上", "Curves need not simply rise", "摘要说明模型能够表达单调、驼峰与S形曲线。阅读时应把观察到的形状与赋予形状的经济解释分开：同一种外形可能来自不同市场环境，不能只凭曲线形状识别唯一原因。", "The abstract describes monotonic, humped and S-shaped curves. An observed shape and its economic interpretation are different; a shape alone cannot identify one underlying cause."),
      section("拟合证据有样本范围", "Fit has a sample boundary", "原研究用1981—1983年的国库券收益率考察不同期限的拟合，并讨论参数随时间的变化。这是特定资料上的曲线表示证据，不应写成任何时期、任何国家的利率预测能力。", "The study examines Treasury-bill yields in 1981–1983 and movements in fitted parameters. Evidence about representation in that sample is not universal forecasting performance across countries and regimes."),
      section("下一步：让曲线随时间变化", "Next: model curves over time", "Diebold与Li在相关框架中进一步研究动态表示与样本外预测。本站建议先确认输入是零息收益率还是到期收益率，统一期限与复利单位；曲线拟合、跨期预测和债券持有期收益是三种不同任务。", "Diebold and Li extend the discussion to dynamics and out-of-sample forecasts. First align yield definitions, maturity units and compounding. Curve fitting, forecasting and holding-period returns are distinct tasks."),
    ], "本导读依据摘要解释目标和样本；模型公式、估计约束及具体拟合过程请以原文为准，不能据此宣称无套利或预测有效。", "This abstract-based guide covers purpose and sample. Consult the paper for formulas and estimation constraints; it establishes neither no-arbitrage nor forecast validity."),

  "Bond Risk Premia": guide(
    "https://web.stanford.edu/~piazzesi/cp.pdf", "Published author-hosted article abstract and introduction, pp. 138–139.", [
      section("收益率曲线与持有期收益不同", "Yields are not holding-period returns", "Cochrane与Piazzesi研究债券预期超额收益如何随时间变化。研究对象是未来一年持有债券的超额收益，而不是今天的到期收益率或一年后的短期利率；三者不能互相替代。", "Cochrane and Piazzesi study time variation in expected excess bond returns. Their target is a one-year holding-period excess return, not today's yield or next year's short rate."),
      section("从期初远期利率提取信息", "Use information available initially", "作者将一年超额收益与期初一组远期利率联系起来，发现一个帐篷形线性组合能概括多个期限的预测关系。这里的组合是统计表示，不是本站提供的交易信号，也不是任意挑选几个期限即可重建。", "Regressions relate one-year excess returns to initial forward rates. A tent-shaped combination summarizes relationships across maturities. It is a statistical representation, not a site-provided trading signal or an arbitrary choice of tenors."),
      section("拟合曲线的因子未必保留全部信息", "Curve factors may omit information", "论文强调，预测收益的信息有一部分不同于描述收益率曲线主要变化的水平、斜率和曲率。一个模型很好地拟合了收益率，不代表它自动保留了另一个目标所需要的全部信息。", "Some return-forecasting information differs from level, slope and curvature movements explaining most yield variation. A good fit for yields need not preserve everything relevant to a different target."),
      section("与前两篇形成三个层次", "Three questions in one sequence", "Nelson–Siegel关注曲线形状，Diebold–Li关注曲线动态，这篇关注持有期超额收益。本站建议分别保存价格、收益率、远期利率和期限约定；不要把供应商同名字段当作论文定义，也不要把样本内关系写成当前可用预测。", "Nelson–Siegel addresses shape, Diebold–Li dynamics, and this paper holding-period excess returns. Preserve prices, yields, forwards and tenor conventions separately; vendor labels alone do not establish equivalence to the paper's inputs."),
    ], "美国国债历史样本的统计关系不保证当前或跨市场预测；持有期重叠、利率测量和样本外检验仍影响解释。", "Historical US Treasury relationships do not guarantee current or cross-market forecasts; overlapping horizons, rate measurement and out-of-sample tests matter."),
};
