// Bounded bilingual orientations for existing catalog identities. Primary-source
// descriptions and registered bibliographic records were checked; these are not replications.
import { researchSummaryMaterials } from "./researchSummaryMaterials.js";

const bi = (zh, en) => ({ zh, en });
const guide = ({ title, url, source, question, design, data, finding, checks, boundary, english = researchBatchThree180English[title] }) => [title, {
  reviewedAt: "2026-09-01",
  evidenceUrl: url,
  evidenceScope: "The cited primary source's public description and registered bibliographic record were reviewed. This orientation remains within those materials; it does not infer numerical estimates, table-level results, causality, or an implementation beyond the stated source description.",
  limits: bi(`本文只整理“${title}”公开说明的研究对象与设计边界，不构成收益预测、交易规则或全文复现。${boundary}`, `This guide only organizes the publicly described question and design of “${title}”. It is not a return forecast, trading rule, or full-text replication. The source's stated scope remains controlling.`),
  related: researchSummaryMaterials[title] ?? {},
  sections: [
    ["研究问题", "Research question", `${question} 阅读时应把它理解为受样本、时点和制度限定的问题，而不是可以脱离条件的结论。`, `${english.question} Read it as a bounded question, not as a conclusion that automatically travels beyond its sample, dates, or institutional setting.`],
    ["研究设计", "Research design", `${design} 比较对象、观察窗口和对照关系共同构成研究合同；改变其中一项，可能改变所检验的命题。`, `${english.design} The comparison, observation window, and control relation are part of the research contract; changing one can change the proposition being tested.`],
    ["数据与时点", "Data and timing", `${data} 字段定义、可得时点和样本筛选需要与原研究分别记录，不能仅因变量同名或使用最新修订值就视为可比。`, `${english.data} Keep fields, availability timing, and sample filters separate from the original study: a same-named variable or later-revised database is not automatically comparable.`],
    ["如何理解结果", "How to read the result", `${finding} 它只支持来源所描述的经验或理论关系，不能把相关性、模型拟合或历史表现升级为因果、可执行性或未来保证。`, `${english.finding} This remains the empirical or theoretical relation described by the source; it does not turn association, fit, or historical performance into causality, an executable procedure, or a future guarantee.`],
    ["复核清单", "Replication checks", `${checks} 开展后续分析前，应将这些选择写入版本化研究记录，并保留原始来源链接与访问日期。`, `${english.checks} Before extending the analysis, record these choices in a versioned note and retain the primary-source link and access date.`],
    ["适用边界", "Scope boundary", `该条导读引用 ${source}。${boundary} 如需数值结论、参数、表格或稳健性检验，请回到原文并单独核对版本、附录与样本定义。`, `This guide cites ${source}. ${english.boundary} For numerical conclusions, parameters, tables, or robustness tests, return to the original and separately verify the edition, appendices, and sample definitions.`],
  ].map(([zhTitle, enTitle, zhBody, enBody]) => ({ title: bi(zhTitle, enTitle), body: bi(zhBody, enBody), reference: { url, label: bi(`${source} · 来源说明`, `${source} · source description`) } })),
}];

export const researchBatchThree180English = {
  "Market Microstructure: A Survey": {
    question: "This survey organizes the economic questions raised by how markets are structured and how that structure affects trading and price formation.",
    design: "It is a survey of market-microstructure research rather than a single-estimator test; institutions and modeling assumptions determine the comparisons it brings together.",
    data: "A reader extending a cited result needs the specific venue rules, order and quote fields, participant definitions, clock precision, and source-period selection used by that underlying study.",
    finding: "The survey provides a map of mechanisms and evidence categories, not one universal measure of liquidity, information, or execution quality.",
    checks: "Identify the cited underlying study before reproducing any claim; preserve venue regime, order type, tick size, trade classification, and the distinction between quotes, trades, and positions.",
    boundary: "A survey cannot make public OHLCV equivalent to order-book or participant data, and its framework is not a trading recommendation or a current market-quality assessment.",
  },
  "Market Liquidity and Trading Activity": {
    question: "The article studies aggregate U.S. equity-market spreads, depth, and trading activity over an extended sample, including their variation with market and macro conditions.",
    design: "It aggregates daily market measures and relates their changes to market direction, volatility, calendar effects, rates, and scheduled macroeconomic announcements.",
    data: "Required inputs are daily quoted spreads, depth, activity measures, security composition and aggregation weights, a trading calendar, rate series, and dated announcement events.",
    finding: "Its abstract reports time variation and joint movement in market liquidity and activity; it does not say that any one daily proxy exhausts trading cost or stress.",
    checks: "Freeze the universe and aggregation rule; align quotes and trades to the same session; keep halts, membership changes, outliers, rate conventions, and event clocks explicit.",
    boundary: "The U.S. aggregate sample and its institutional period do not establish a real-time liquidity signal or a portable causal effect for another venue.",
  },
  "Order Imbalance and Individual Stock Returns: Theory and Evidence": {
    question: "The article asks how order imbalance relates to individual-stock returns, using a theoretical and empirical framing of trading pressure and return behavior.",
    design: "It combines a model of imbalance-related price effects with evidence at the individual-security level, so the direction rule and measurement window are part of the design.",
    data: "A comparable study needs trade direction or the paper's imbalance proxy, individual-security returns, quote context, security universe, timestamp convention, and treatment of nontrading.",
    finding: "The title and public record support a bounded investigation of imbalance and individual returns, not the claim that signed volume alone is a universal directional signal.",
    checks: "Document trade-signing method, sampling interval, quote lag, corporate-action adjustments, zero-return treatment, and whether imbalance is shares, dollars, or counts.",
    boundary: "Different trading protocols and unavailable order information can change imbalance measurement, so minute bars cannot silently substitute for the study's underlying observations.",
  },
  "A New Estimate of Transaction Costs": {
    question: "The article develops an estimate of effective transaction costs when direct cost data are unavailable, using the incidence of zero daily returns.",
    design: "Its model places zero returns inside a return-generating process to produce firm-, exchange-, and period-level average round-trip cost estimates from daily return histories.",
    data: "Inputs are a clean daily return series, zero-return definition, security and exchange identities, sample dates, corporate-action adjustments, and filters for stale or missing prices.",
    finding: "The public abstract presents a return-based cost estimator and comparisons with commonly used estimators; it does not equate a zero return with a known execution cost for every asset.",
    checks: "Retain unrounded and adjusted price rules; distinguish suspended, stale, and missing observations; record sample eligibility, return frequency, and any benchmark-cost comparison.",
    boundary: "A daily-return proxy is not an observed bid-ask spread, fee schedule, or executable all-in cost, especially across different assets and market structures.",
  },
  "The Dark Side of Outside Directors: Do They Quit When They Are Most Needed?": {
    question: "The working paper examines whether outside directors have incentives to resign when they anticipate poor firm performance or adverse disclosure.",
    design: "It studies surprise director departures and compares affected firms' subsequent stock, operating, restatement, and litigation-related outcomes described in the paper's abstract.",
    data: "A faithful extension needs dated board membership and departure classifications, firm identifiers, price and operating measures, restatement and lawsuit records, and the paper's event definitions.",
    finding: "The source reports associations after surprise departures; a departure is not by itself evidence of misconduct, foreknowledge, or a firm-specific governance verdict.",
    checks: "Separate anticipated from surprise exits; preserve announcement versus effective dates; verify director identity and board role; define all outcome windows before inspecting results.",
    boundary: "The paper's historical sample and event classification do not support a current legal, compliance, or investment conclusion about any director or company.",
  },
  "The Separation of Ownership and Control in East Asian Corporations": {
    question: "The article maps the separation of ownership and control in East Asian corporations through ultimate ownership and control relationships.",
    design: "It uses control chains, voting rights, and ownership rules across company and economy samples, making the control threshold and entity mapping central design choices.",
    data: "Inputs include historical company entities, direct and ultimate ownership, voting and cash-flow rights, pyramids or cross-holdings, disclosure versions, countries, and observation dates.",
    finding: "It shows why direct equity stakes alone may not describe control; it does not establish a current controller, beneficial owner, or governance-quality score.",
    checks: "Freeze company scope and control thresholds; retain each ownership disclosure version; document treatment of indirect holdings, nominee accounts, multilayer entities, and missing links.",
    boundary: "Ownership networks and disclosure regimes evolve, so this historical regional mapping cannot be treated as a real-time ownership register.",
  },
  "Corporate Financing and Investment Decisions When Firms Have Information That Investors Do Not Have": {
    question: "The article develops how financing and investment decisions can be affected when firms possess information that outside investors do not have.",
    design: "It is a theoretical analysis of adverse-selection and financing choices, not a ready-made empirical scoring or prediction system.",
    data: "An empirical application would need dated financing announcements, investment opportunities, security issuance terms, firm information proxies, investor information sets, and institutional rules.",
    finding: "The framework explains a possible information-asymmetry mechanism; it does not diagnose private information or the quality of a particular financing decision.",
    checks: "State the model assumptions, financing instruments, announcement clock, counterfactual, and how investment opportunities and information asymmetry are measured.",
    boundary: "A theoretical mechanism cannot by itself classify an issuer, price a security, or provide a capital-structure recommendation.",
  },
  "Toward an Implied Cost of Capital": {
    question: "The article develops an implied cost-of-capital approach using market prices and accounting-based expectations rather than observing investors' required return directly.",
    design: "It connects valuation inputs and expected future accounting performance in an implied-return framework, so forecast construction and timing are integral to the estimate.",
    data: "Inputs include point-in-time price, book value, earnings or forecasts, payout assumptions, fiscal dates, security identity, analyst-information availability, and valuation horizon.",
    finding: "An implied estimate is conditional on the model and forecast inputs; it is not an observed financing rate or a guarantee of realized return.",
    checks: "Use information available at the estimation date; preserve forecast vintages, split adjustments, currency, accounting standards, missing-data rules, and the exact valuation specification.",
    boundary: "Different forecast sources and valuation assumptions can materially change an implied estimate, so it is not a current investment recommendation or a universal discount rate.",
  },
  "PE Ratios, PEG Ratios, and Estimating the Implied Expected Rate of Return on Equity Capital": {
    question: "The article considers how PE and PEG ratios can be used in estimating an implied expected rate of return on equity capital.",
    design: "It works through valuation relationships that connect price, earnings, growth expectations, and an implied expected return, rather than treating a ratio as self-interpreting.",
    data: "Comparable inputs need point-in-time prices, earnings definitions, growth assumptions or forecasts, dilution and share-count treatment, fiscal dates, and the original sample filters.",
    finding: "The title supports a model-dependent implied expected-return exercise; it does not make a low or high PE or PEG a stand-alone valuation or return conclusion.",
    checks: "Specify trailing versus forward earnings, forecast vintage, negative or near-zero earnings treatment, currency, corporate actions, and the equation and horizon used.",
    boundary: "Ratios are sensitive to accounting and expectation inputs, so this framework is not a live signal, target price, or assurance of equity cost of capital.",
  },
  "Disclosure, Liquidity, and the Cost of Capital": {
    question: "The article analyzes a theoretical connection among corporate disclosure, market liquidity, and the cost of capital.",
    design: "It develops an information-and-liquidity model in which disclosure choices and investor trading conditions are linked through stated assumptions.",
    data: "An empirical extension requires dated disclosure content and availability, investor or market-maker information measures, liquidity definitions, price data, and institutional disclosure rules.",
    finding: "The paper supplies a mechanism for how disclosure can affect liquidity and capital costs under its assumptions; it does not certify any issuer's disclosure quality or financing cost.",
    checks: "Separate disclosure event time from reporting period; define voluntary versus mandatory disclosure; preserve liquidity measure, investor set, and the model's information assumptions.",
    boundary: "The theoretical setting cannot substitute for audit, legal, or regulatory evaluation and does not establish a causal effect for every market or disclosure.",
  },
  "International Differences in the Cost of Equity Capital: Do Legal Institutions and Securities Regulation Matter?": {
    question: "The article studies whether country legal institutions and securities regulation relate to international differences in the cost of equity capital.",
    design: "It compares firms and countries using legal and regulatory classifications alongside implied cost-of-equity measures, making country coding and estimation model part of the design.",
    data: "Inputs include historical country classifications, legal and regulatory variables, firm financials, point-in-time market data, forecast or valuation inputs, and country-year coverage.",
    finding: "The study concerns cross-country empirical differences; it does not rate current legal systems, determine a single firm's compliance status, or prove one institutional cause.",
    checks: "Freeze legal-code versions and country sample; separate law on the books from enforcement; reproduce the implied-cost model and account for currency, listings, and missing markets.",
    boundary: "Historical country comparisons are not legal advice, a live regulatory assessment, or a current company-level cost-of-capital quotation.",
  },
  "Short-Sales Constraints and Price Discovery: Evidence from the Hong Kong Market": {
    question: "The article examines short-sales constraints and price discovery using evidence from the Hong Kong market.",
    design: "It compares securities or periods under the market's short-sale eligibility and constraint rules, making the regime definition and policy timing essential.",
    data: "Required inputs include dated short-sale eligibility, borrowing or constraint proxies, stock and market prices, trading data, listing status, shares or classes, and policy-event dates.",
    finding: "The study is about price discovery under a specific Hong Kong institutional setting; it does not make short-selling universally stabilizing or destabilizing.",
    checks: "Preserve historical eligibility and rule versions; distinguish short interest, borrowing availability, and executed short sales; align policy dates with market sessions and suspensions.",
    boundary: "Hong Kong's rules, market design, and sample period limit extrapolation to other exchanges, assets, or current regulatory decisions.",
  },
  "How Does Government Ownership Affect Firm Performance? Evidence from China’s Privatization Experience": {
    question: "The article investigates how government ownership relates to firm performance in the setting of China's privatization experience.",
    design: "It uses a historically bounded ownership and privatization setting, requiring the ownership measure, firm sample, and performance comparison to be read together.",
    data: "A comparable analysis needs dated ownership stakes and control, privatization and listing events, firm financials, operating-performance definitions, share classes, and disclosure availability.",
    finding: "The paper studies performance in a particular institutional transition; it does not label state ownership or privatization as uniformly good or bad for every firm.",
    checks: "Retain ownership and control versions, event dates, accounting standards, consolidation scope, industry and selection rules, and distinguish fiscal period-end from public availability.",
    boundary: "China's historical privatization context does not establish present ownership effects, a governance score, or an investment conclusion for a named company.",
  },
  "The Effects of Political Connections and State Ownership on Corporate Litigation in China": {
    question: "The article studies how political connections and state ownership relate to corporate litigation outcomes in China.",
    design: "It compares litigation observations using political-connection and state-control classifications, with case definitions and appeal outcomes forming part of the empirical design.",
    data: "Inputs need litigation-case records, plaintiff and defendant identities, filing and outcome dates, return or firm measures, political-connection coding, state-control status, and court-stage labels.",
    finding: "The source reports associations in a historical litigation sample; it does not determine the merits of any case or establish current judicial, political, or corporate conduct.",
    checks: "Freeze legal-event coding and outcome stage; distinguish announcement from ruling dates; document connection and ownership classification rules; retain case inclusion, appeals, and missing records.",
    boundary: "This empirical setting is not legal advice or a current litigation-risk rating, and historical associations cannot be applied to an individual dispute without its full facts.",
  },
  "Media Coverage and the Cross-section of Stock Returns": {
    question: "The article studies media coverage and the cross-section of stock returns, requiring attention to which firms and news sources enter the coverage measure.",
    design: "It relates a coverage measure to cross-sectional return outcomes, so source selection, entity matching, publication timing, and portfolio formation are core design choices.",
    data: "Inputs include original media items or a licensed coverage archive, first-publication timestamps, firm identifiers, return and delisting data, coverage aggregation, and sample membership.",
    finding: "The paper examines a historical coverage-return relation; public visibility of news does not turn coverage into a universal, causal, or tradable signal.",
    checks: "Keep source permissions and versions; deduplicate syndication; map entities before aggregation; separate first-seen time from later edits; use point-in-time security universes.",
    boundary: "Different news ecosystems, languages, access rules, and publication lags can change the measure, so this is not a redistribution right or a current return forecast.",
  },
  "The Price of Political Uncertainty: Theory and Evidence from the Option Market": {
    question: "The article analyzes political uncertainty in the option market, using variation around national elections and global summits guided by a policy-choice model.",
    design: "It links option prices to event-spanning exposure and compares political-event timing across settings, so event definition, contract life, and economic conditions are part of the test.",
    data: "Required inputs include option quotes and contract terms, underlying prices, expiry and event clocks, election or summit dates, country identifiers, volatility measures, and market-quality filters.",
    finding: "Its abstract reports that political-event-spanning options are more expensive in the studied setting; it does not give a universal hedge instruction or a forecast of any election outcome.",
    checks: "Align option and event time zones; preserve strike, maturity, liquidity, and quote filters; distinguish scheduled events from news shocks; record cross-country matching choices.",
    boundary: "Option prices are model- and market-dependent, and historical political-event evidence is not political advice, a trading rule, or a guarantee of tail protection.",
  },
  "Peer Pressure: Social Interaction and the Disposition Effect": {
    question: "The article examines whether social interaction contributes to traders' disposition effect using a social network linked to individual trading records.",
    design: "It exploits staggered brokerage partnerships with a social trading platform and compares activity before and after exposure to estimate peer effects.",
    data: "Inputs include consented or lawfully accessible account-level trades, network exposure and entry timing, realization labels, brokerage and platform identities, and a comparable pre-period.",
    finding: "The paper's abstract reports an association and a stated identification design in its setting; social activity is not proof of any individual's bias or future trading behavior.",
    checks: "Preserve exposure definition and staggered timing; define realized gains and losses before analysis; protect privacy; account for selection, account activity, and brokerage-policy changes.",
    boundary: "Restricted individual records and one platform setting cannot be replaced by public social posts or used to profile a person, recommend trades, or infer intent.",
  },
  "Wisdom of Crowds: The Value of Stock Opinions Transmitted Through Social Media": {
    question: "The article investigates whether investor opinions in social-media articles and their reader commentaries predict future stock returns and earnings surprises.",
    design: "It applies textual analysis to a U.S. investor social-media platform and separately considers author articles and response commentaries.",
    data: "Inputs include permitted, versioned article and comment text, author and firm mappings, first-visible timestamps, text-processing rules, returns, earnings-surprise definitions, and coverage filters.",
    finding: "The abstract reports predictive patterns in its platform sample; it does not validate every post, imply that crowd opinion is true, or provide a live forecasting service.",
    checks: "Record collection rights and version history; deduplicate edited or reposted content; separate publication from ingestion time; keep labels and validation samples out of training.",
    boundary: "Platform composition, moderation, survivorship, language, and selection can alter results, so this guide grants neither data rights nor a trading recommendation.",
  },
  "Asset Growth and the Cross-Section of Stock Returns": {
    question: "The article tests the cross-sectional relation between firm asset growth and subsequent stock returns in a U.S. sample.",
    design: "It compares annual firm asset-growth rates with other documented return determinants, making accounting construction, portfolio timing, and benchmark-return definition central.",
    data: "Inputs include point-in-time total assets and financial statements, fiscal and filing dates, security returns and delistings, firm universe, accounting adjustments, and formation dates.",
    finding: "The abstract reports historical predictive ability of annual asset growth in its sample; it does not turn any balance-sheet expansion into a certain abnormal return.",
    checks: "Use publication availability rather than latest restated data; define asset growth, mergers, currency, and consolidation; retain delistings and freeze portfolios before holding periods.",
    boundary: "Accounting regimes, financing conditions, and trading costs vary, so this historical cross-section is not a current ranking, valuation judgment, or executable portfolio.",
  },
  "The Investment CAPM": {
    question: "The article presents an investment-based class of capital-asset-pricing models that arises from firms' real investment decisions.",
    design: "It is a conceptual asset-pricing synthesis linking investment policies, costs of capital, and empirical return patterns, not a single observed market-factor calculation.",
    data: "An empirical implementation needs point-in-time investment, profitability and asset data, return series, factor or model specification, firm universe, dates, and treatment of exits.",
    finding: "The abstract frames investment CAPM as a paradigm for organizing anomalies and investment behavior; it does not establish that a model is uniquely causal or universally dominant.",
    checks: "State the model equations and assumptions; preserve investment and accounting definitions, information timing, factor construction, sample selection, and all competing specifications.",
    boundary: "A theoretical paradigm is not a live factor feed, valuation engine, or guarantee that historical anomaly patterns will persist after costs and market changes.",
  },
};

export const researchBatchThree180 = Object.fromEntries([
  guide({ title: "Market Microstructure: A Survey", url: "https://doi.org/10.1016/s1386-4181(00)00007-0", source: "Journal of Financial Markets (2000)", question: "综述梳理市场如何组织，以及制度结构如何影响交易与价格形成这一组经济问题。", design: "它汇集市场微观结构研究，不是单一估计器的实证检验；交易制度和模型假设决定其组织的比较。", data: "若延伸其中被引用的结论，应回到对应研究所使用的交易场所规则、订单与报价字段、参与者定义、时钟精度及样本时期。", finding: "该综述提供机制和证据类别的地图，而非某个放之四海而皆准的流动性、信息或执行质量指标。", checks: "先定位被复现的原始研究；保留场所制度、订单类型、最小报价单位、成交分类，并区分报价、成交和持仓。", boundary: "综述不能把公开 OHLCV 变成订单簿或参与者数据，其框架也不构成交易建议或当前市场质量评价。" }),
  guide({ title: "Market Liquidity and Trading Activity", url: "https://doi.org/10.1111/0022-1082.00335", source: "The Journal of Finance (2001)", question: "论文研究较长样本中的美国股票市场整体价差、深度和交易活动，以及它们随市场与宏观条件的变化。", design: "它聚合日度市场指标，并把其变化与市场涨跌、波动、日历效应、利率和已安排宏观公告关联。", data: "需要日度报价价差、深度、活动度量、证券构成与聚合权重、交易日历、利率序列和带时点的公告事件。", finding: "摘要报告流动性与活动的时间变化和共同变动，而不是认为单一日度代理变量穷尽交易成本或压力。", checks: "冻结样本与聚合规则；让报价和成交落在同一交易时段；明确停牌、成员变化、异常值、利率口径和事件时钟。", boundary: "美国整体样本及其制度时期不等于实时流动性信号，也不自动证明对其他场所的可迁移因果效应。" }),
  guide({ title: "Order Imbalance and Individual Stock Returns: Theory and Evidence", url: "https://doi.org/10.1016/s0304-405x(03)00175-2", source: "Journal of Financial Economics (2004)", question: "论文在交易压力与收益行为的理论和实证框架中研究订单不平衡与个股收益的关系。", design: "它把不平衡相关价格效应模型与个股层面的证据结合，方向规则和测量窗口均属于设计的一部分。", data: "可比研究需要成交方向或原文的订单不平衡代理、个股收益、报价语境、证券样本、时间戳口径和不交易处理。", finding: "标题和公开记录支持对订单不平衡与个股收益的有限研究，不支持把带符号成交量当成普适方向信号。", checks: "记录成交方向识别、采样间隔、报价滞后、公司行动调整、零收益处理，以及不平衡按股数、金额还是笔数计算。", boundary: "不同交易协议和缺失订单信息会改变不平衡测量，分钟K线不能无声替代原研究所需观测。" }),
  guide({ title: "A New Estimate of Transaction Costs", url: "https://doi.org/10.1093/rfs/12.5.1113", source: "Review of Financial Studies (1999)", question: "论文在直接成本数据不可得时，利用日收益为零的发生情况估计有效交易成本。", design: "模型把零收益纳入收益生成过程，仅由日收益历史产生公司、交易所和时期层面的平均往返成本估计。", data: "输入包括清洗后的日收益序列、零收益定义、证券与交易所身份、样本日期、公司行动调整，以及陈旧或缺失价格过滤。", finding: "摘要提出基于收益的成本估计器及其与常用估计器的比较，并不把每一个零收益等同于已知执行成本。", checks: "保留未四舍五入和复权价格规则；区分停牌、陈旧和缺失观测；记录样本资格、收益频率和成本基准比较。", boundary: "日收益代理并非观察到的买卖价差、费率表或可执行全成本，特别是在不同资产和市场结构间。" }),
  guide({ title: "The Dark Side of Outside Directors: Do They Quit When They Are Most Needed?", url: "https://doi.org/10.3386/w15917", source: "National Bureau of Economic Research Working Paper 15917 (2010)", question: "工作论文考察外部董事是否会在预期公司表现不佳或出现负面披露时辞职。", design: "它研究意外董事离任，并比较受影响公司之后的股价、经营、重述和诉讼相关结果。", data: "忠实延伸需要带日期的董事会成员和离任分类、公司身份、价格与经营指标、重述及诉讼记录和原文事件定义。", finding: "来源报告意外离任后的相关性；一次离任本身不是不当行为、预知信息或公司治理结论的证据。", checks: "区分预期和意外离任；保留公告与生效日期；核对董事身份和角色；在观察结果前预先定义所有窗口。", boundary: "历史样本和事件分类不支持对任何董事或公司作出当前法律、合规或投资结论。" }),
  guide({ title: "The Separation of Ownership and Control in East Asian Corporations", url: "https://doi.org/10.1016/s0304-405x(00)00067-2", source: "Journal of Financial Economics (2000)", question: "论文通过最终所有权和控制关系描绘东亚公司的所有权与控制权分离。", design: "它在公司和经济体样本中使用控制链、投票权和所有权规则，控制阈值和实体映射是核心设计选择。", data: "输入包括历史公司实体、直接与最终所有权、投票与现金流权、金字塔或交叉持股、披露版本、国家和观测日期。", finding: "研究说明直接持股未必描述控制权，但不确认当前控制人、受益所有人或治理质量评分。", checks: "冻结公司范围和控制阈值；保留每个所有权披露版本；记录间接持股、代持、多层实体和缺失链路处理。", boundary: "所有权网络和披露制度会变化，历史区域映射不能作为实时所有权登记簿。" }),
  guide({ title: "Corporate Financing and Investment Decisions When Firms Have Information That Investors Do Not Have", url: "https://doi.org/10.1016/0304-405x(84)90023-0", source: "Journal of Financial Economics (1984)", question: "论文讨论在公司掌握而外部投资者不掌握信息时，融资与投资决策会如何受到影响。", design: "它是关于逆向选择与融资选择的理论分析，不是一套可直接运行的实证评分或预测系统。", data: "经验应用需要带日期的融资公告、投资机会、发行条款、公司信息代理、投资者信息集和制度规则。", finding: "框架解释一种信息不对称机制，而不诊断私有信息或某项融资决策的质量。", checks: "明确模型假设、融资工具、公告时钟、反事实以及投资机会和信息不对称的测量方式。", boundary: "理论机制不能独自为发行人分类、给证券定价或提供资本结构建议。" }),
  guide({ title: "Toward an Implied Cost of Capital", url: "https://doi.org/10.1111/1475-679x.00007", source: "Journal of Accounting Research (2001)", question: "论文使用市场价格和基于会计的预期，构造隐含资本成本，而不是直接观察投资者要求回报。", design: "它把估值输入与预期会计表现放入隐含回报框架，预测构造和时点是估计的一部分。", data: "输入包括时点价格、账面价值、收益或预测、分配假设、财年日期、证券身份、分析师信息可得性和估值期限。", finding: "隐含估计依赖模型与预测输入，不是观察到的融资利率或实现回报保证。", checks: "只使用估计日可得信息；保留预测版本、拆股调整、货币、会计准则、缺失规则和精确估值设定。", boundary: "不同预测来源和估值假设会显著改变隐含估计，它不构成当前投资建议或普适贴现率。" }),
  guide({ title: "PE Ratios, PEG Ratios, and Estimating the Implied Expected Rate of Return on Equity Capital", url: "https://doi.org/10.2308/accr.2004.79.1.73", source: "The Accounting Review (2004)", question: "论文讨论如何利用 PE 和 PEG 比率估计权益资本的隐含预期回报率。", design: "它通过价格、收益、增长预期和隐含预期回报的估值关系展开，而不把比率当作自解释指标。", data: "可比输入需要时点价格、收益定义、增长假设或预测、稀释与股数处理、财年日期和原始样本过滤。", finding: "标题支持依赖模型的隐含预期回报练习，不意味着高低 PE 或 PEG 单独给出估值或收益结论。", checks: "明确历史或前瞻收益、预测版本、负或接近零收益处理、货币、公司行动，以及所用方程和期限。", boundary: "比率对会计和预期输入敏感，不能作为实时信号、目标价或权益资本成本保证。" }),
  guide({ title: "Disclosure, Liquidity, and the Cost of Capital", url: "https://doi.org/10.1111/j.1540-6261.1991.tb04620.x", source: "The Journal of Finance (1991)", question: "论文分析公司披露、市场流动性和资本成本之间的理论联系。", design: "它构建信息与流动性模型，将披露选择和投资者交易条件在明确假设下连接。", data: "经验延伸需带日期的披露内容与可得性、投资者或做市商信息指标、流动性定义、价格数据和披露制度规则。", finding: "论文给出披露如何在其假设下影响流动性和资本成本的机制，并不认证某发行人的披露质量或融资成本。", checks: "区分披露事件时点和报告期；定义自愿与强制披露；保留流动性度量、投资者集合和模型的信息假设。", boundary: "理论设定不能替代审计、法律或监管评估，也不证明每个市场或披露的因果效应。" }),
  guide({ title: "International Differences in the Cost of Equity Capital: Do Legal Institutions and Securities Regulation Matter?", url: "https://doi.org/10.1111/j.1475-679x.2006.00209.x", source: "Journal of Accounting Research (2006)", question: "论文研究国家法律制度与证券监管是否关联跨国权益资本成本差异。", design: "它以法律和监管分类及隐含权益成本度量比较公司和国家，国家编码和估计模型均属于设计。", data: "输入包括历史国家分类、法律和监管变量、公司财务、时点市场数据、预测或估值输入及国家年份覆盖。", finding: "研究讨论跨国经验差异，不给当前法律制度评级、不确定单一公司合规状态，也不证明单一制度原因。", checks: "冻结法律编码版本和国家样本；区分成文法与执法；复现隐含成本模型并处理货币、上市和缺失市场。", boundary: "历史国家比较并非法律意见、实时监管评估或当前公司层面的资本成本报价。" }),
  guide({ title: "Short-Sales Constraints and Price Discovery: Evidence from the Hong Kong Market", url: "https://doi.org/10.1111/j.1540-6261.2007.01270.x", source: "The Journal of Finance (2007)", question: "论文以香港市场证据考察卖空约束与价格发现，并以当地证券制度作为研究解释的前提。", design: "它比较卖空资格与约束规则下的证券或时期，制度定义和政策时点至关重要。", data: "需要带日期的卖空资格、借券或约束代理、股票和市场价格、交易数据、上市状态、股份类别和政策事件日期。", finding: "研究针对特定香港制度下的价格发现，不意味着卖空在所有情况下稳定或扰乱市场。", checks: "保留历史资格和规则版本；区分卖空余额、借券可得性和已执行卖空；对齐政策日期与交易时段和停牌。", boundary: "香港规则、市场设计和样本时期限制其向其他交易所、资产或当前监管决策的外推。" }),
  guide({ title: "How Does Government Ownership Affect Firm Performance? Evidence from China’s Privatization Experience", url: "https://doi.org/10.1111/1468-5957.00422", source: "Journal of Business Finance & Accounting (2002)", question: "论文在中国私有化经历的背景下研究政府所有权与公司表现的关系。", design: "它使用有历史边界的所有权与私有化环境，所有权度量、公司样本和表现比较必须一并理解。", data: "可比分析需要带日期的所有权和控制、私有化与上市事件、公司财务、经营表现定义、股份类别和披露可得性。", finding: "论文研究特定制度转型下的表现，不把国有或私有化对每家公司的影响标记为一致好坏。", checks: "保留所有权和控制版本、事件日期、会计准则、合并范围、行业和选择规则，并区分期末与公开可得时点。", boundary: "中国历史私有化环境不证明当前所有权效应、治理评分或对某公司投资的结论。" }),
  guide({ title: "The Effects of Political Connections and State Ownership on Corporate Litigation in China", url: "https://doi.org/10.1086/659261", source: "The Journal of Law and Economics (2011)", question: "论文研究政治关联和国有控制如何与中国公司诉讼结果相关。", design: "它使用政治关联和国有控制分类比较诉讼观测，案件定义和上诉结果是实证设计的一部分。", data: "输入需要诉讼记录、原被告身份、立案与结果日期、收益或公司指标、政治关联编码、国有控制状态和法院阶段标签。", finding: "来源报告历史诉讼样本中的相关性，不裁定个案的是非，也不证明当前司法、政治或公司行为。", checks: "冻结法律事件编码和结果阶段；区分公告与裁判日期；记录关联和所有权分类规则；保留案件纳入、上诉和缺失记录。", boundary: "该环境不是法律意见或实时诉讼风险评级，历史相关性不能脱离完整事实套用于单个争议。" }),
  guide({ title: "Media Coverage and the Cross-section of Stock Returns", url: "https://doi.org/10.1111/j.1540-6261.2009.01493.x", source: "The Journal of Finance (2009)", question: "论文研究媒体覆盖与股票收益横截面，关键在于哪些公司和新闻来源被纳入覆盖度量。", design: "它将覆盖度量与横截面收益结果关联，来源选择、实体匹配、发布时间和组合形成均是核心设计选择。", data: "输入包括原始媒体内容或合法覆盖档案、首次发布时间、公司身份、收益与退市数据、覆盖聚合和样本成员。", finding: "论文研究历史覆盖—收益关系；新闻公开可见并不使覆盖成为普适、因果或可交易信号。", checks: "保留来源权限与版本；去除转载；汇总前映射实体；区分首次可见与后续编辑；使用时点证券样本。", boundary: "新闻生态、语言、访问规则和发布时间滞后不同会改变度量；这不是再分发权或当前收益预测。" }),
  guide({ title: "The Price of Political Uncertainty: Theory and Evidence from the Option Market", url: "https://doi.org/10.1111/jofi.12406", source: "The Journal of Finance (2016)", question: "论文在政策选择模型指引下，利用国家选举和全球峰会前后的变化研究期权市场中的政治不确定性。", design: "它把期权价格与跨越政治事件的暴露相连并进行比较，事件定义、合约存续期和经济条件均是检验的一部分。", data: "需要期权报价和合约条款、标的价格、到期和事件时钟、选举或峰会日期、国家身份、波动率指标和市场质量过滤。", finding: "摘要报告样本中跨政治事件期权价格更高，不提供普适套保指令或任何选举结果预测。", checks: "对齐期权和事件时区；保留行权价、期限、流动性和报价过滤；区分预定事件与新闻冲击；记录跨国匹配选择。", boundary: "期权价格依赖模型和市场，历史政治事件证据不是政治建议、交易规则或尾部保护保证。" }),
  guide({ title: "Peer Pressure: Social Interaction and the Disposition Effect", url: "https://doi.org/10.1093/rfs/hhw063", source: "Review of Financial Studies (2016)", question: "论文利用与个人交易记录相连的社交网络，研究社交互动是否会影响交易者的处置效应。", design: "它利用零售经纪商分阶段与社交交易平台合作的暴露，并比较暴露前后活动以估计同伴效应。", data: "输入包括获得许可的账户交易、网络暴露和进入时点、实现损益标签、经纪商与平台身份，以及可比暴露前时期。", finding: "摘要报告特定环境中的关联和识别设计；社交活动并不证明任何个体存在偏误或可预测其未来交易。", checks: "保留暴露定义和分阶段时点；分析前定义实现盈亏；保护隐私；处理选择、账户活动和经纪政策变化。", boundary: "受限个人记录和单一平台环境不能用公开社交帖子替代，也不得用于画像个人、荐股或推测意图。" }),
  guide({ title: "Wisdom of Crowds: The Value of Stock Opinions Transmitted Through Social Media", url: "https://doi.org/10.1093/rfs/hhu001", source: "Review of Financial Studies (2014)", question: "论文考察社交媒体文章和读者评论中的投资者观点，是否预测未来股票收益和盈余意外。", design: "它对美国投资者社交媒体平台进行文本分析，并分别考察作者文章和回应评论。", data: "输入包括获许可且版本化的文章和评论文本、作者与公司映射、首次可见时点、文本处理规则、收益、盈余意外定义和覆盖过滤。", finding: "摘要报告平台样本中的预测模式，不验证每条帖子、不表示群体观点为真，也不提供实时预测服务。", checks: "记录采集权利和版本历史；去重编辑或转载内容；区分发布与采集时点；将标签和验证样本排除在训练外。", boundary: "平台构成、审核、幸存、语言和选择性会改变结果；该导读不授予数据权利或交易建议。" }),
  guide({ title: "Asset Growth and the Cross-Section of Stock Returns", url: "https://doi.org/10.1111/j.1540-6261.2008.01370.x", source: "The Journal of Finance (2008)", question: "论文在美国样本中检验公司资产增长与后续股票收益的横截面关系。", design: "它将年度资产增长与其他已记录收益决定因素比较，会计构造、组合时点和基准收益定义均至关重要。", data: "输入包括时点总资产与财务报表、财年与申报日期、证券收益和退市、公司样本、会计调整和形成日期。", finding: "摘要报告年度资产增长在样本中的历史预测能力，不把任何资产负债表扩张变成确定的异常收益。", checks: "使用披露可得性而非最新重述数据；定义资产增长、并购、货币和合并口径；纳入退市并在持有期前冻结组合。", boundary: "会计制度、融资条件和交易成本不同，历史横截面不构成当前排序、估值判断或可执行组合。" }),
  guide({ title: "The Investment CAPM", url: "https://doi.org/10.1111/eufm.12129", source: "European Financial Management (2017)", question: "论文提出源于公司实体投资决策的一类投资型资本资产定价模型。", design: "它是连接投资政策、资本成本和经验收益模式的概念性资产定价综合，而非单一可观察的市场因子计算。", data: "经验实现需要时点投资、盈利和资产数据、收益序列、因子或模型设定、公司样本、日期和退出处理。", finding: "摘要将投资 CAPM 作为组织异象和投资行为的范式，并不证明某模型唯一具有因果性或普遍占优。", checks: "明确模型方程和假设；保留投资与会计定义、信息时点、因子构造、样本选择和全部竞争设定。", boundary: "理论范式不是实时因子源、估值引擎，也不保证历史异象在成本和市场变化后继续存在。" }),
]);
